#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &UbuntuSansMono_Medium6pt7b, 6, "UbuntuSansMono_Medium6pt7b" },
  { &UbuntuSansMono_Medium7pt7b, 7, "UbuntuSansMono_Medium7pt7b" },
  { &UbuntuSansMono_Medium8pt7b, 8, "UbuntuSansMono_Medium8pt7b" },
  { &UbuntuSansMono_Medium9pt7b, 9, "UbuntuSansMono_Medium9pt7b" },
  { &UbuntuSansMono_Medium10pt7b, 10, "UbuntuSansMono_Medium10pt7b" },
  { &UbuntuSansMono_Medium11pt7b, 11, "UbuntuSansMono_Medium11pt7b" },
  { &UbuntuSansMono_Medium12pt7b, 12, "UbuntuSansMono_Medium12pt7b" },
  { &UbuntuSansMono_Medium13pt7b, 13, "UbuntuSansMono_Medium13pt7b" },
  { &UbuntuSansMono_Medium14pt7b, 14, "UbuntuSansMono_Medium14pt7b" },
  { &UbuntuSansMono_Medium15pt7b, 15, "UbuntuSansMono_Medium15pt7b" },
  { &UbuntuSansMono_Medium16pt7b, 16, "UbuntuSansMono_Medium16pt7b" },
  { &UbuntuSansMono_Medium17pt7b, 17, "UbuntuSansMono_Medium17pt7b" },
  { &UbuntuSansMono_Medium18pt7b, 18, "UbuntuSansMono_Medium18pt7b" },
  { &UbuntuSansMono_Medium19pt7b, 19, "UbuntuSansMono_Medium19pt7b" },
  { &UbuntuSansMono_Medium20pt7b, 20, "UbuntuSansMono_Medium20pt7b" },
  { &UbuntuSansMono_Medium21pt7b, 21, "UbuntuSansMono_Medium21pt7b" },
  { &UbuntuSansMono_Medium22pt7b, 22, "UbuntuSansMono_Medium22pt7b" },
  { &UbuntuSansMono_Medium23pt7b, 23, "UbuntuSansMono_Medium23pt7b" },
  { &UbuntuSansMono_Medium24pt7b, 24, "UbuntuSansMono_Medium24pt7b" },
  { &UbuntuSansMono_Medium25pt7b, 25, "UbuntuSansMono_Medium25pt7b" },
  { &UbuntuSansMono_Medium26pt7b, 26, "UbuntuSansMono_Medium26pt7b" },
  { &UbuntuSansMono_Medium27pt7b, 27, "UbuntuSansMono_Medium27pt7b" },
  { &UbuntuSansMono_Medium28pt7b, 28, "UbuntuSansMono_Medium28pt7b" },
  { &UbuntuSansMono_Medium29pt7b, 29, "UbuntuSansMono_Medium29pt7b" },
  { &UbuntuSansMono_Medium30pt7b, 30, "UbuntuSansMono_Medium30pt7b" },
  { &UbuntuSansMono_Medium31pt7b, 31, "UbuntuSansMono_Medium31pt7b" },
  { &UbuntuSansMono_Medium32pt7b, 32, "UbuntuSansMono_Medium32pt7b" },
  { &UbuntuSansMono_Medium33pt7b, 33, "UbuntuSansMono_Medium33pt7b" },
  { &UbuntuSansMono_Medium34pt7b, 34, "UbuntuSansMono_Medium34pt7b" },
  { &UbuntuSansMono_Medium35pt7b, 35, "UbuntuSansMono_Medium35pt7b" },
  { &UbuntuSansMono_Medium36pt7b, 36, "UbuntuSansMono_Medium36pt7b" },
  { &UbuntuSansMono_Medium37pt7b, 37, "UbuntuSansMono_Medium37pt7b" },
  { &UbuntuSansMono_Medium38pt7b, 38, "UbuntuSansMono_Medium38pt7b" },
  { &UbuntuSansMono_Medium39pt7b, 39, "UbuntuSansMono_Medium39pt7b" },
  { &UbuntuSansMono_Medium40pt7b, 40, "UbuntuSansMono_Medium40pt7b" },
  { &UbuntuSansMono_Medium41pt7b, 41, "UbuntuSansMono_Medium41pt7b" },
  { &UbuntuSansMono_Medium42pt7b, 42, "UbuntuSansMono_Medium42pt7b" },
  { &UbuntuSansMono_Medium43pt7b, 43, "UbuntuSansMono_Medium43pt7b" },
  { &UbuntuSansMono_Medium44pt7b, 44, "UbuntuSansMono_Medium44pt7b" },
  { &UbuntuSansMono_Medium45pt7b, 45, "UbuntuSansMono_Medium45pt7b" },
  { &UbuntuSansMono_Medium46pt7b, 46, "UbuntuSansMono_Medium46pt7b" },
  { &UbuntuSansMono_Medium47pt7b, 47, "UbuntuSansMono_Medium47pt7b" },
  { &UbuntuSansMono_Medium48pt7b, 48, "UbuntuSansMono_Medium48pt7b" },
  { &UbuntuSansMono_Medium49pt7b, 49, "UbuntuSansMono_Medium49pt7b" },
  { &UbuntuSansMono_Medium50pt7b, 50, "UbuntuSansMono_Medium50pt7b" },
  { &UbuntuSansMono_Medium51pt7b, 51, "UbuntuSansMono_Medium51pt7b" },
  { &UbuntuSansMono_Medium52pt7b, 52, "UbuntuSansMono_Medium52pt7b" },
  { &UbuntuSansMono_Medium53pt7b, 53, "UbuntuSansMono_Medium53pt7b" },
  { &UbuntuSansMono_Medium54pt7b, 54, "UbuntuSansMono_Medium54pt7b" },
  { &UbuntuSansMono_Medium55pt7b, 55, "UbuntuSansMono_Medium55pt7b" },
  { &UbuntuSansMono_Medium56pt7b, 56, "UbuntuSansMono_Medium56pt7b" },
  { &UbuntuSansMono_Medium57pt7b, 57, "UbuntuSansMono_Medium57pt7b" },
  { &UbuntuSansMono_Medium58pt7b, 58, "UbuntuSansMono_Medium58pt7b" },
  { &UbuntuSansMono_Medium59pt7b, 59, "UbuntuSansMono_Medium59pt7b" },
  { &UbuntuSansMono_Medium60pt7b, 60, "UbuntuSansMono_Medium60pt7b" },
  { &UbuntuSansMono_Medium61pt7b, 61, "UbuntuSansMono_Medium61pt7b" },
  { &UbuntuSansMono_Medium62pt7b, 62, "UbuntuSansMono_Medium62pt7b" },
  { &UbuntuSansMono_Medium63pt7b, 63, "UbuntuSansMono_Medium63pt7b" },
  { &UbuntuSansMono_Medium64pt7b, 64, "UbuntuSansMono_Medium64pt7b" },
  { &UbuntuSansMono_Medium65pt7b, 65, "UbuntuSansMono_Medium65pt7b" },
  { &UbuntuSansMono_Medium66pt7b, 66, "UbuntuSansMono_Medium66pt7b" },
  { &UbuntuSansMono_Medium67pt7b, 67, "UbuntuSansMono_Medium67pt7b" },
  { &UbuntuSansMono_Medium68pt7b, 68, "UbuntuSansMono_Medium68pt7b" },
  { &UbuntuSansMono_Medium69pt7b, 69, "UbuntuSansMono_Medium69pt7b" },
  { &UbuntuSansMono_Medium70pt7b, 70, "UbuntuSansMono_Medium70pt7b" },
  { &UbuntuSansMono_Medium71pt7b, 71, "UbuntuSansMono_Medium71pt7b" },
  { &UbuntuSansMono_Medium72pt7b, 72, "UbuntuSansMono_Medium72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
