#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &JetBrainsMono_Bold6pt7b, 6, "JetBrainsMono_Bold6pt7b" },
  { &JetBrainsMono_Bold7pt7b, 7, "JetBrainsMono_Bold7pt7b" },
  { &JetBrainsMono_Bold8pt7b, 8, "JetBrainsMono_Bold8pt7b" },
  { &JetBrainsMono_Bold9pt7b, 9, "JetBrainsMono_Bold9pt7b" },
  { &JetBrainsMono_Bold10pt7b, 10, "JetBrainsMono_Bold10pt7b" },
  { &JetBrainsMono_Bold11pt7b, 11, "JetBrainsMono_Bold11pt7b" },
  { &JetBrainsMono_Bold12pt7b, 12, "JetBrainsMono_Bold12pt7b" },
  { &JetBrainsMono_Bold13pt7b, 13, "JetBrainsMono_Bold13pt7b" },
  { &JetBrainsMono_Bold14pt7b, 14, "JetBrainsMono_Bold14pt7b" },
  { &JetBrainsMono_Bold15pt7b, 15, "JetBrainsMono_Bold15pt7b" },
  { &JetBrainsMono_Bold16pt7b, 16, "JetBrainsMono_Bold16pt7b" },
  { &JetBrainsMono_Bold17pt7b, 17, "JetBrainsMono_Bold17pt7b" },
  { &JetBrainsMono_Bold18pt7b, 18, "JetBrainsMono_Bold18pt7b" },
  { &JetBrainsMono_Bold19pt7b, 19, "JetBrainsMono_Bold19pt7b" },
  { &JetBrainsMono_Bold20pt7b, 20, "JetBrainsMono_Bold20pt7b" },
  { &JetBrainsMono_Bold21pt7b, 21, "JetBrainsMono_Bold21pt7b" },
  { &JetBrainsMono_Bold22pt7b, 22, "JetBrainsMono_Bold22pt7b" },
  { &JetBrainsMono_Bold23pt7b, 23, "JetBrainsMono_Bold23pt7b" },
  { &JetBrainsMono_Bold24pt7b, 24, "JetBrainsMono_Bold24pt7b" },
  { &JetBrainsMono_Bold25pt7b, 25, "JetBrainsMono_Bold25pt7b" },
  { &JetBrainsMono_Bold26pt7b, 26, "JetBrainsMono_Bold26pt7b" },
  { &JetBrainsMono_Bold27pt7b, 27, "JetBrainsMono_Bold27pt7b" },
  { &JetBrainsMono_Bold28pt7b, 28, "JetBrainsMono_Bold28pt7b" },
  { &JetBrainsMono_Bold29pt7b, 29, "JetBrainsMono_Bold29pt7b" },
  { &JetBrainsMono_Bold30pt7b, 30, "JetBrainsMono_Bold30pt7b" },
  { &JetBrainsMono_Bold31pt7b, 31, "JetBrainsMono_Bold31pt7b" },
  { &JetBrainsMono_Bold32pt7b, 32, "JetBrainsMono_Bold32pt7b" },
  { &JetBrainsMono_Bold33pt7b, 33, "JetBrainsMono_Bold33pt7b" },
  { &JetBrainsMono_Bold34pt7b, 34, "JetBrainsMono_Bold34pt7b" },
  { &JetBrainsMono_Bold35pt7b, 35, "JetBrainsMono_Bold35pt7b" },
  { &JetBrainsMono_Bold36pt7b, 36, "JetBrainsMono_Bold36pt7b" },
  { &JetBrainsMono_Bold37pt7b, 37, "JetBrainsMono_Bold37pt7b" },
  { &JetBrainsMono_Bold38pt7b, 38, "JetBrainsMono_Bold38pt7b" },
  { &JetBrainsMono_Bold39pt7b, 39, "JetBrainsMono_Bold39pt7b" },
  { &JetBrainsMono_Bold40pt7b, 40, "JetBrainsMono_Bold40pt7b" },
  { &JetBrainsMono_Bold41pt7b, 41, "JetBrainsMono_Bold41pt7b" },
  { &JetBrainsMono_Bold42pt7b, 42, "JetBrainsMono_Bold42pt7b" },
  { &JetBrainsMono_Bold43pt7b, 43, "JetBrainsMono_Bold43pt7b" },
  { &JetBrainsMono_Bold44pt7b, 44, "JetBrainsMono_Bold44pt7b" },
  { &JetBrainsMono_Bold45pt7b, 45, "JetBrainsMono_Bold45pt7b" },
  { &JetBrainsMono_Bold46pt7b, 46, "JetBrainsMono_Bold46pt7b" },
  { &JetBrainsMono_Bold47pt7b, 47, "JetBrainsMono_Bold47pt7b" },
  { &JetBrainsMono_Bold48pt7b, 48, "JetBrainsMono_Bold48pt7b" },
  { &JetBrainsMono_Bold49pt7b, 49, "JetBrainsMono_Bold49pt7b" },
  { &JetBrainsMono_Bold50pt7b, 50, "JetBrainsMono_Bold50pt7b" },
  { &JetBrainsMono_Bold51pt7b, 51, "JetBrainsMono_Bold51pt7b" },
  { &JetBrainsMono_Bold52pt7b, 52, "JetBrainsMono_Bold52pt7b" },
  { &JetBrainsMono_Bold53pt7b, 53, "JetBrainsMono_Bold53pt7b" },
  { &JetBrainsMono_Bold54pt7b, 54, "JetBrainsMono_Bold54pt7b" },
  { &JetBrainsMono_Bold55pt7b, 55, "JetBrainsMono_Bold55pt7b" },
  { &JetBrainsMono_Bold56pt7b, 56, "JetBrainsMono_Bold56pt7b" },
  { &JetBrainsMono_Bold57pt7b, 57, "JetBrainsMono_Bold57pt7b" },
  { &JetBrainsMono_Bold58pt7b, 58, "JetBrainsMono_Bold58pt7b" },
  { &JetBrainsMono_Bold59pt7b, 59, "JetBrainsMono_Bold59pt7b" },
  { &JetBrainsMono_Bold60pt7b, 60, "JetBrainsMono_Bold60pt7b" },
  { &JetBrainsMono_Bold61pt7b, 61, "JetBrainsMono_Bold61pt7b" },
  { &JetBrainsMono_Bold62pt7b, 62, "JetBrainsMono_Bold62pt7b" },
  { &JetBrainsMono_Bold63pt7b, 63, "JetBrainsMono_Bold63pt7b" },
  { &JetBrainsMono_Bold64pt7b, 64, "JetBrainsMono_Bold64pt7b" },
  { &JetBrainsMono_Bold65pt7b, 65, "JetBrainsMono_Bold65pt7b" },
  { &JetBrainsMono_Bold66pt7b, 66, "JetBrainsMono_Bold66pt7b" },
  { &JetBrainsMono_Bold67pt7b, 67, "JetBrainsMono_Bold67pt7b" },
  { &JetBrainsMono_Bold68pt7b, 68, "JetBrainsMono_Bold68pt7b" },
  { &JetBrainsMono_Bold69pt7b, 69, "JetBrainsMono_Bold69pt7b" },
  { &JetBrainsMono_Bold70pt7b, 70, "JetBrainsMono_Bold70pt7b" },
  { &JetBrainsMono_Bold71pt7b, 71, "JetBrainsMono_Bold71pt7b" },
  { &JetBrainsMono_Bold72pt7b, 72, "JetBrainsMono_Bold72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
