#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_SemiBoldItalic6pt7b, 6, "NotoSans_SemiBoldItalic6pt7b" },
  { &NotoSans_SemiBoldItalic7pt7b, 7, "NotoSans_SemiBoldItalic7pt7b" },
  { &NotoSans_SemiBoldItalic8pt7b, 8, "NotoSans_SemiBoldItalic8pt7b" },
  { &NotoSans_SemiBoldItalic9pt7b, 9, "NotoSans_SemiBoldItalic9pt7b" },
  { &NotoSans_SemiBoldItalic10pt7b, 10, "NotoSans_SemiBoldItalic10pt7b" },
  { &NotoSans_SemiBoldItalic11pt7b, 11, "NotoSans_SemiBoldItalic11pt7b" },
  { &NotoSans_SemiBoldItalic12pt7b, 12, "NotoSans_SemiBoldItalic12pt7b" },
  { &NotoSans_SemiBoldItalic13pt7b, 13, "NotoSans_SemiBoldItalic13pt7b" },
  { &NotoSans_SemiBoldItalic14pt7b, 14, "NotoSans_SemiBoldItalic14pt7b" },
  { &NotoSans_SemiBoldItalic15pt7b, 15, "NotoSans_SemiBoldItalic15pt7b" },
  { &NotoSans_SemiBoldItalic16pt7b, 16, "NotoSans_SemiBoldItalic16pt7b" },
  { &NotoSans_SemiBoldItalic17pt7b, 17, "NotoSans_SemiBoldItalic17pt7b" },
  { &NotoSans_SemiBoldItalic18pt7b, 18, "NotoSans_SemiBoldItalic18pt7b" },
  { &NotoSans_SemiBoldItalic19pt7b, 19, "NotoSans_SemiBoldItalic19pt7b" },
  { &NotoSans_SemiBoldItalic20pt7b, 20, "NotoSans_SemiBoldItalic20pt7b" },
  { &NotoSans_SemiBoldItalic21pt7b, 21, "NotoSans_SemiBoldItalic21pt7b" },
  { &NotoSans_SemiBoldItalic22pt7b, 22, "NotoSans_SemiBoldItalic22pt7b" },
  { &NotoSans_SemiBoldItalic23pt7b, 23, "NotoSans_SemiBoldItalic23pt7b" },
  { &NotoSans_SemiBoldItalic24pt7b, 24, "NotoSans_SemiBoldItalic24pt7b" },
  { &NotoSans_SemiBoldItalic25pt7b, 25, "NotoSans_SemiBoldItalic25pt7b" },
  { &NotoSans_SemiBoldItalic26pt7b, 26, "NotoSans_SemiBoldItalic26pt7b" },
  { &NotoSans_SemiBoldItalic27pt7b, 27, "NotoSans_SemiBoldItalic27pt7b" },
  { &NotoSans_SemiBoldItalic28pt7b, 28, "NotoSans_SemiBoldItalic28pt7b" },
  { &NotoSans_SemiBoldItalic29pt7b, 29, "NotoSans_SemiBoldItalic29pt7b" },
  { &NotoSans_SemiBoldItalic30pt7b, 30, "NotoSans_SemiBoldItalic30pt7b" },
  { &NotoSans_SemiBoldItalic31pt7b, 31, "NotoSans_SemiBoldItalic31pt7b" },
  { &NotoSans_SemiBoldItalic32pt7b, 32, "NotoSans_SemiBoldItalic32pt7b" },
  { &NotoSans_SemiBoldItalic33pt7b, 33, "NotoSans_SemiBoldItalic33pt7b" },
  { &NotoSans_SemiBoldItalic34pt7b, 34, "NotoSans_SemiBoldItalic34pt7b" },
  { &NotoSans_SemiBoldItalic35pt7b, 35, "NotoSans_SemiBoldItalic35pt7b" },
  { &NotoSans_SemiBoldItalic36pt7b, 36, "NotoSans_SemiBoldItalic36pt7b" },
  { &NotoSans_SemiBoldItalic37pt7b, 37, "NotoSans_SemiBoldItalic37pt7b" },
  { &NotoSans_SemiBoldItalic38pt7b, 38, "NotoSans_SemiBoldItalic38pt7b" },
  { &NotoSans_SemiBoldItalic39pt7b, 39, "NotoSans_SemiBoldItalic39pt7b" },
  { &NotoSans_SemiBoldItalic40pt7b, 40, "NotoSans_SemiBoldItalic40pt7b" },
  { &NotoSans_SemiBoldItalic41pt7b, 41, "NotoSans_SemiBoldItalic41pt7b" },
  { &NotoSans_SemiBoldItalic42pt7b, 42, "NotoSans_SemiBoldItalic42pt7b" },
  { &NotoSans_SemiBoldItalic43pt7b, 43, "NotoSans_SemiBoldItalic43pt7b" },
  { &NotoSans_SemiBoldItalic44pt7b, 44, "NotoSans_SemiBoldItalic44pt7b" },
  { &NotoSans_SemiBoldItalic45pt7b, 45, "NotoSans_SemiBoldItalic45pt7b" },
  { &NotoSans_SemiBoldItalic46pt7b, 46, "NotoSans_SemiBoldItalic46pt7b" },
  { &NotoSans_SemiBoldItalic47pt7b, 47, "NotoSans_SemiBoldItalic47pt7b" },
  { &NotoSans_SemiBoldItalic48pt7b, 48, "NotoSans_SemiBoldItalic48pt7b" },
  { &NotoSans_SemiBoldItalic49pt7b, 49, "NotoSans_SemiBoldItalic49pt7b" },
  { &NotoSans_SemiBoldItalic50pt7b, 50, "NotoSans_SemiBoldItalic50pt7b" },
  { &NotoSans_SemiBoldItalic51pt7b, 51, "NotoSans_SemiBoldItalic51pt7b" },
  { &NotoSans_SemiBoldItalic52pt7b, 52, "NotoSans_SemiBoldItalic52pt7b" },
  { &NotoSans_SemiBoldItalic53pt7b, 53, "NotoSans_SemiBoldItalic53pt7b" },
  { &NotoSans_SemiBoldItalic54pt7b, 54, "NotoSans_SemiBoldItalic54pt7b" },
  { &NotoSans_SemiBoldItalic55pt7b, 55, "NotoSans_SemiBoldItalic55pt7b" },
  { &NotoSans_SemiBoldItalic56pt7b, 56, "NotoSans_SemiBoldItalic56pt7b" },
  { &NotoSans_SemiBoldItalic57pt7b, 57, "NotoSans_SemiBoldItalic57pt7b" },
  { &NotoSans_SemiBoldItalic58pt7b, 58, "NotoSans_SemiBoldItalic58pt7b" },
  { &NotoSans_SemiBoldItalic59pt7b, 59, "NotoSans_SemiBoldItalic59pt7b" },
  { &NotoSans_SemiBoldItalic60pt7b, 60, "NotoSans_SemiBoldItalic60pt7b" },
  { &NotoSans_SemiBoldItalic61pt7b, 61, "NotoSans_SemiBoldItalic61pt7b" },
  { &NotoSans_SemiBoldItalic62pt7b, 62, "NotoSans_SemiBoldItalic62pt7b" },
  { &NotoSans_SemiBoldItalic63pt7b, 63, "NotoSans_SemiBoldItalic63pt7b" },
  { &NotoSans_SemiBoldItalic64pt7b, 64, "NotoSans_SemiBoldItalic64pt7b" },
  { &NotoSans_SemiBoldItalic65pt7b, 65, "NotoSans_SemiBoldItalic65pt7b" },
  { &NotoSans_SemiBoldItalic66pt7b, 66, "NotoSans_SemiBoldItalic66pt7b" },
  { &NotoSans_SemiBoldItalic67pt7b, 67, "NotoSans_SemiBoldItalic67pt7b" },
  { &NotoSans_SemiBoldItalic68pt7b, 68, "NotoSans_SemiBoldItalic68pt7b" },
  { &NotoSans_SemiBoldItalic69pt7b, 69, "NotoSans_SemiBoldItalic69pt7b" },
  { &NotoSans_SemiBoldItalic70pt7b, 70, "NotoSans_SemiBoldItalic70pt7b" },
  { &NotoSans_SemiBoldItalic71pt7b, 71, "NotoSans_SemiBoldItalic71pt7b" },
  { &NotoSans_SemiBoldItalic72pt7b, 72, "NotoSans_SemiBoldItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
