#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &JetBrainsMono_ExtraLight6pt7b, 6, "JetBrainsMono_ExtraLight6pt7b" },
  { &JetBrainsMono_ExtraLight7pt7b, 7, "JetBrainsMono_ExtraLight7pt7b" },
  { &JetBrainsMono_ExtraLight8pt7b, 8, "JetBrainsMono_ExtraLight8pt7b" },
  { &JetBrainsMono_ExtraLight9pt7b, 9, "JetBrainsMono_ExtraLight9pt7b" },
  { &JetBrainsMono_ExtraLight10pt7b, 10, "JetBrainsMono_ExtraLight10pt7b" },
  { &JetBrainsMono_ExtraLight11pt7b, 11, "JetBrainsMono_ExtraLight11pt7b" },
  { &JetBrainsMono_ExtraLight12pt7b, 12, "JetBrainsMono_ExtraLight12pt7b" },
  { &JetBrainsMono_ExtraLight13pt7b, 13, "JetBrainsMono_ExtraLight13pt7b" },
  { &JetBrainsMono_ExtraLight14pt7b, 14, "JetBrainsMono_ExtraLight14pt7b" },
  { &JetBrainsMono_ExtraLight15pt7b, 15, "JetBrainsMono_ExtraLight15pt7b" },
  { &JetBrainsMono_ExtraLight16pt7b, 16, "JetBrainsMono_ExtraLight16pt7b" },
  { &JetBrainsMono_ExtraLight17pt7b, 17, "JetBrainsMono_ExtraLight17pt7b" },
  { &JetBrainsMono_ExtraLight18pt7b, 18, "JetBrainsMono_ExtraLight18pt7b" },
  { &JetBrainsMono_ExtraLight19pt7b, 19, "JetBrainsMono_ExtraLight19pt7b" },
  { &JetBrainsMono_ExtraLight20pt7b, 20, "JetBrainsMono_ExtraLight20pt7b" },
  { &JetBrainsMono_ExtraLight21pt7b, 21, "JetBrainsMono_ExtraLight21pt7b" },
  { &JetBrainsMono_ExtraLight22pt7b, 22, "JetBrainsMono_ExtraLight22pt7b" },
  { &JetBrainsMono_ExtraLight23pt7b, 23, "JetBrainsMono_ExtraLight23pt7b" },
  { &JetBrainsMono_ExtraLight24pt7b, 24, "JetBrainsMono_ExtraLight24pt7b" },
  { &JetBrainsMono_ExtraLight25pt7b, 25, "JetBrainsMono_ExtraLight25pt7b" },
  { &JetBrainsMono_ExtraLight26pt7b, 26, "JetBrainsMono_ExtraLight26pt7b" },
  { &JetBrainsMono_ExtraLight27pt7b, 27, "JetBrainsMono_ExtraLight27pt7b" },
  { &JetBrainsMono_ExtraLight28pt7b, 28, "JetBrainsMono_ExtraLight28pt7b" },
  { &JetBrainsMono_ExtraLight29pt7b, 29, "JetBrainsMono_ExtraLight29pt7b" },
  { &JetBrainsMono_ExtraLight30pt7b, 30, "JetBrainsMono_ExtraLight30pt7b" },
  { &JetBrainsMono_ExtraLight31pt7b, 31, "JetBrainsMono_ExtraLight31pt7b" },
  { &JetBrainsMono_ExtraLight32pt7b, 32, "JetBrainsMono_ExtraLight32pt7b" },
  { &JetBrainsMono_ExtraLight33pt7b, 33, "JetBrainsMono_ExtraLight33pt7b" },
  { &JetBrainsMono_ExtraLight34pt7b, 34, "JetBrainsMono_ExtraLight34pt7b" },
  { &JetBrainsMono_ExtraLight35pt7b, 35, "JetBrainsMono_ExtraLight35pt7b" },
  { &JetBrainsMono_ExtraLight36pt7b, 36, "JetBrainsMono_ExtraLight36pt7b" },
  { &JetBrainsMono_ExtraLight37pt7b, 37, "JetBrainsMono_ExtraLight37pt7b" },
  { &JetBrainsMono_ExtraLight38pt7b, 38, "JetBrainsMono_ExtraLight38pt7b" },
  { &JetBrainsMono_ExtraLight39pt7b, 39, "JetBrainsMono_ExtraLight39pt7b" },
  { &JetBrainsMono_ExtraLight40pt7b, 40, "JetBrainsMono_ExtraLight40pt7b" },
  { &JetBrainsMono_ExtraLight41pt7b, 41, "JetBrainsMono_ExtraLight41pt7b" },
  { &JetBrainsMono_ExtraLight42pt7b, 42, "JetBrainsMono_ExtraLight42pt7b" },
  { &JetBrainsMono_ExtraLight43pt7b, 43, "JetBrainsMono_ExtraLight43pt7b" },
  { &JetBrainsMono_ExtraLight44pt7b, 44, "JetBrainsMono_ExtraLight44pt7b" },
  { &JetBrainsMono_ExtraLight45pt7b, 45, "JetBrainsMono_ExtraLight45pt7b" },
  { &JetBrainsMono_ExtraLight46pt7b, 46, "JetBrainsMono_ExtraLight46pt7b" },
  { &JetBrainsMono_ExtraLight47pt7b, 47, "JetBrainsMono_ExtraLight47pt7b" },
  { &JetBrainsMono_ExtraLight48pt7b, 48, "JetBrainsMono_ExtraLight48pt7b" },
  { &JetBrainsMono_ExtraLight49pt7b, 49, "JetBrainsMono_ExtraLight49pt7b" },
  { &JetBrainsMono_ExtraLight50pt7b, 50, "JetBrainsMono_ExtraLight50pt7b" },
  { &JetBrainsMono_ExtraLight51pt7b, 51, "JetBrainsMono_ExtraLight51pt7b" },
  { &JetBrainsMono_ExtraLight52pt7b, 52, "JetBrainsMono_ExtraLight52pt7b" },
  { &JetBrainsMono_ExtraLight53pt7b, 53, "JetBrainsMono_ExtraLight53pt7b" },
  { &JetBrainsMono_ExtraLight54pt7b, 54, "JetBrainsMono_ExtraLight54pt7b" },
  { &JetBrainsMono_ExtraLight55pt7b, 55, "JetBrainsMono_ExtraLight55pt7b" },
  { &JetBrainsMono_ExtraLight56pt7b, 56, "JetBrainsMono_ExtraLight56pt7b" },
  { &JetBrainsMono_ExtraLight57pt7b, 57, "JetBrainsMono_ExtraLight57pt7b" },
  { &JetBrainsMono_ExtraLight58pt7b, 58, "JetBrainsMono_ExtraLight58pt7b" },
  { &JetBrainsMono_ExtraLight59pt7b, 59, "JetBrainsMono_ExtraLight59pt7b" },
  { &JetBrainsMono_ExtraLight60pt7b, 60, "JetBrainsMono_ExtraLight60pt7b" },
  { &JetBrainsMono_ExtraLight61pt7b, 61, "JetBrainsMono_ExtraLight61pt7b" },
  { &JetBrainsMono_ExtraLight62pt7b, 62, "JetBrainsMono_ExtraLight62pt7b" },
  { &JetBrainsMono_ExtraLight63pt7b, 63, "JetBrainsMono_ExtraLight63pt7b" },
  { &JetBrainsMono_ExtraLight64pt7b, 64, "JetBrainsMono_ExtraLight64pt7b" },
  { &JetBrainsMono_ExtraLight65pt7b, 65, "JetBrainsMono_ExtraLight65pt7b" },
  { &JetBrainsMono_ExtraLight66pt7b, 66, "JetBrainsMono_ExtraLight66pt7b" },
  { &JetBrainsMono_ExtraLight67pt7b, 67, "JetBrainsMono_ExtraLight67pt7b" },
  { &JetBrainsMono_ExtraLight68pt7b, 68, "JetBrainsMono_ExtraLight68pt7b" },
  { &JetBrainsMono_ExtraLight69pt7b, 69, "JetBrainsMono_ExtraLight69pt7b" },
  { &JetBrainsMono_ExtraLight70pt7b, 70, "JetBrainsMono_ExtraLight70pt7b" },
  { &JetBrainsMono_ExtraLight71pt7b, 71, "JetBrainsMono_ExtraLight71pt7b" },
  { &JetBrainsMono_ExtraLight72pt7b, 72, "JetBrainsMono_ExtraLight72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
