#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &RobotoMono_Italic6pt7b, 6, "RobotoMono_Italic6pt7b" },
  { &RobotoMono_Italic7pt7b, 7, "RobotoMono_Italic7pt7b" },
  { &RobotoMono_Italic8pt7b, 8, "RobotoMono_Italic8pt7b" },
  { &RobotoMono_Italic9pt7b, 9, "RobotoMono_Italic9pt7b" },
  { &RobotoMono_Italic10pt7b, 10, "RobotoMono_Italic10pt7b" },
  { &RobotoMono_Italic11pt7b, 11, "RobotoMono_Italic11pt7b" },
  { &RobotoMono_Italic12pt7b, 12, "RobotoMono_Italic12pt7b" },
  { &RobotoMono_Italic13pt7b, 13, "RobotoMono_Italic13pt7b" },
  { &RobotoMono_Italic14pt7b, 14, "RobotoMono_Italic14pt7b" },
  { &RobotoMono_Italic15pt7b, 15, "RobotoMono_Italic15pt7b" },
  { &RobotoMono_Italic16pt7b, 16, "RobotoMono_Italic16pt7b" },
  { &RobotoMono_Italic17pt7b, 17, "RobotoMono_Italic17pt7b" },
  { &RobotoMono_Italic18pt7b, 18, "RobotoMono_Italic18pt7b" },
  { &RobotoMono_Italic19pt7b, 19, "RobotoMono_Italic19pt7b" },
  { &RobotoMono_Italic20pt7b, 20, "RobotoMono_Italic20pt7b" },
  { &RobotoMono_Italic21pt7b, 21, "RobotoMono_Italic21pt7b" },
  { &RobotoMono_Italic22pt7b, 22, "RobotoMono_Italic22pt7b" },
  { &RobotoMono_Italic23pt7b, 23, "RobotoMono_Italic23pt7b" },
  { &RobotoMono_Italic24pt7b, 24, "RobotoMono_Italic24pt7b" },
  { &RobotoMono_Italic25pt7b, 25, "RobotoMono_Italic25pt7b" },
  { &RobotoMono_Italic26pt7b, 26, "RobotoMono_Italic26pt7b" },
  { &RobotoMono_Italic27pt7b, 27, "RobotoMono_Italic27pt7b" },
  { &RobotoMono_Italic28pt7b, 28, "RobotoMono_Italic28pt7b" },
  { &RobotoMono_Italic29pt7b, 29, "RobotoMono_Italic29pt7b" },
  { &RobotoMono_Italic30pt7b, 30, "RobotoMono_Italic30pt7b" },
  { &RobotoMono_Italic31pt7b, 31, "RobotoMono_Italic31pt7b" },
  { &RobotoMono_Italic32pt7b, 32, "RobotoMono_Italic32pt7b" },
  { &RobotoMono_Italic33pt7b, 33, "RobotoMono_Italic33pt7b" },
  { &RobotoMono_Italic34pt7b, 34, "RobotoMono_Italic34pt7b" },
  { &RobotoMono_Italic35pt7b, 35, "RobotoMono_Italic35pt7b" },
  { &RobotoMono_Italic36pt7b, 36, "RobotoMono_Italic36pt7b" },
  { &RobotoMono_Italic37pt7b, 37, "RobotoMono_Italic37pt7b" },
  { &RobotoMono_Italic38pt7b, 38, "RobotoMono_Italic38pt7b" },
  { &RobotoMono_Italic39pt7b, 39, "RobotoMono_Italic39pt7b" },
  { &RobotoMono_Italic40pt7b, 40, "RobotoMono_Italic40pt7b" },
  { &RobotoMono_Italic41pt7b, 41, "RobotoMono_Italic41pt7b" },
  { &RobotoMono_Italic42pt7b, 42, "RobotoMono_Italic42pt7b" },
  { &RobotoMono_Italic43pt7b, 43, "RobotoMono_Italic43pt7b" },
  { &RobotoMono_Italic44pt7b, 44, "RobotoMono_Italic44pt7b" },
  { &RobotoMono_Italic45pt7b, 45, "RobotoMono_Italic45pt7b" },
  { &RobotoMono_Italic46pt7b, 46, "RobotoMono_Italic46pt7b" },
  { &RobotoMono_Italic47pt7b, 47, "RobotoMono_Italic47pt7b" },
  { &RobotoMono_Italic48pt7b, 48, "RobotoMono_Italic48pt7b" },
  { &RobotoMono_Italic49pt7b, 49, "RobotoMono_Italic49pt7b" },
  { &RobotoMono_Italic50pt7b, 50, "RobotoMono_Italic50pt7b" },
  { &RobotoMono_Italic51pt7b, 51, "RobotoMono_Italic51pt7b" },
  { &RobotoMono_Italic52pt7b, 52, "RobotoMono_Italic52pt7b" },
  { &RobotoMono_Italic53pt7b, 53, "RobotoMono_Italic53pt7b" },
  { &RobotoMono_Italic54pt7b, 54, "RobotoMono_Italic54pt7b" },
  { &RobotoMono_Italic55pt7b, 55, "RobotoMono_Italic55pt7b" },
  { &RobotoMono_Italic56pt7b, 56, "RobotoMono_Italic56pt7b" },
  { &RobotoMono_Italic57pt7b, 57, "RobotoMono_Italic57pt7b" },
  { &RobotoMono_Italic58pt7b, 58, "RobotoMono_Italic58pt7b" },
  { &RobotoMono_Italic59pt7b, 59, "RobotoMono_Italic59pt7b" },
  { &RobotoMono_Italic60pt7b, 60, "RobotoMono_Italic60pt7b" },
  { &RobotoMono_Italic61pt7b, 61, "RobotoMono_Italic61pt7b" },
  { &RobotoMono_Italic62pt7b, 62, "RobotoMono_Italic62pt7b" },
  { &RobotoMono_Italic63pt7b, 63, "RobotoMono_Italic63pt7b" },
  { &RobotoMono_Italic64pt7b, 64, "RobotoMono_Italic64pt7b" },
  { &RobotoMono_Italic65pt7b, 65, "RobotoMono_Italic65pt7b" },
  { &RobotoMono_Italic66pt7b, 66, "RobotoMono_Italic66pt7b" },
  { &RobotoMono_Italic67pt7b, 67, "RobotoMono_Italic67pt7b" },
  { &RobotoMono_Italic68pt7b, 68, "RobotoMono_Italic68pt7b" },
  { &RobotoMono_Italic69pt7b, 69, "RobotoMono_Italic69pt7b" },
  { &RobotoMono_Italic70pt7b, 70, "RobotoMono_Italic70pt7b" },
  { &RobotoMono_Italic71pt7b, 71, "RobotoMono_Italic71pt7b" },
  { &RobotoMono_Italic72pt7b, 72, "RobotoMono_Italic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
