#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &RobotoMono_Regular6pt7b, 6, "RobotoMono_Regular6pt7b" },
  { &RobotoMono_Regular7pt7b, 7, "RobotoMono_Regular7pt7b" },
  { &RobotoMono_Regular8pt7b, 8, "RobotoMono_Regular8pt7b" },
  { &RobotoMono_Regular9pt7b, 9, "RobotoMono_Regular9pt7b" },
  { &RobotoMono_Regular10pt7b, 10, "RobotoMono_Regular10pt7b" },
  { &RobotoMono_Regular11pt7b, 11, "RobotoMono_Regular11pt7b" },
  { &RobotoMono_Regular12pt7b, 12, "RobotoMono_Regular12pt7b" },
  { &RobotoMono_Regular13pt7b, 13, "RobotoMono_Regular13pt7b" },
  { &RobotoMono_Regular14pt7b, 14, "RobotoMono_Regular14pt7b" },
  { &RobotoMono_Regular15pt7b, 15, "RobotoMono_Regular15pt7b" },
  { &RobotoMono_Regular16pt7b, 16, "RobotoMono_Regular16pt7b" },
  { &RobotoMono_Regular17pt7b, 17, "RobotoMono_Regular17pt7b" },
  { &RobotoMono_Regular18pt7b, 18, "RobotoMono_Regular18pt7b" },
  { &RobotoMono_Regular19pt7b, 19, "RobotoMono_Regular19pt7b" },
  { &RobotoMono_Regular20pt7b, 20, "RobotoMono_Regular20pt7b" },
  { &RobotoMono_Regular21pt7b, 21, "RobotoMono_Regular21pt7b" },
  { &RobotoMono_Regular22pt7b, 22, "RobotoMono_Regular22pt7b" },
  { &RobotoMono_Regular23pt7b, 23, "RobotoMono_Regular23pt7b" },
  { &RobotoMono_Regular24pt7b, 24, "RobotoMono_Regular24pt7b" },
  { &RobotoMono_Regular25pt7b, 25, "RobotoMono_Regular25pt7b" },
  { &RobotoMono_Regular26pt7b, 26, "RobotoMono_Regular26pt7b" },
  { &RobotoMono_Regular27pt7b, 27, "RobotoMono_Regular27pt7b" },
  { &RobotoMono_Regular28pt7b, 28, "RobotoMono_Regular28pt7b" },
  { &RobotoMono_Regular29pt7b, 29, "RobotoMono_Regular29pt7b" },
  { &RobotoMono_Regular30pt7b, 30, "RobotoMono_Regular30pt7b" },
  { &RobotoMono_Regular31pt7b, 31, "RobotoMono_Regular31pt7b" },
  { &RobotoMono_Regular32pt7b, 32, "RobotoMono_Regular32pt7b" },
  { &RobotoMono_Regular33pt7b, 33, "RobotoMono_Regular33pt7b" },
  { &RobotoMono_Regular34pt7b, 34, "RobotoMono_Regular34pt7b" },
  { &RobotoMono_Regular35pt7b, 35, "RobotoMono_Regular35pt7b" },
  { &RobotoMono_Regular36pt7b, 36, "RobotoMono_Regular36pt7b" },
  { &RobotoMono_Regular37pt7b, 37, "RobotoMono_Regular37pt7b" },
  { &RobotoMono_Regular38pt7b, 38, "RobotoMono_Regular38pt7b" },
  { &RobotoMono_Regular39pt7b, 39, "RobotoMono_Regular39pt7b" },
  { &RobotoMono_Regular40pt7b, 40, "RobotoMono_Regular40pt7b" },
  { &RobotoMono_Regular41pt7b, 41, "RobotoMono_Regular41pt7b" },
  { &RobotoMono_Regular42pt7b, 42, "RobotoMono_Regular42pt7b" },
  { &RobotoMono_Regular43pt7b, 43, "RobotoMono_Regular43pt7b" },
  { &RobotoMono_Regular44pt7b, 44, "RobotoMono_Regular44pt7b" },
  { &RobotoMono_Regular45pt7b, 45, "RobotoMono_Regular45pt7b" },
  { &RobotoMono_Regular46pt7b, 46, "RobotoMono_Regular46pt7b" },
  { &RobotoMono_Regular47pt7b, 47, "RobotoMono_Regular47pt7b" },
  { &RobotoMono_Regular48pt7b, 48, "RobotoMono_Regular48pt7b" },
  { &RobotoMono_Regular49pt7b, 49, "RobotoMono_Regular49pt7b" },
  { &RobotoMono_Regular50pt7b, 50, "RobotoMono_Regular50pt7b" },
  { &RobotoMono_Regular51pt7b, 51, "RobotoMono_Regular51pt7b" },
  { &RobotoMono_Regular52pt7b, 52, "RobotoMono_Regular52pt7b" },
  { &RobotoMono_Regular53pt7b, 53, "RobotoMono_Regular53pt7b" },
  { &RobotoMono_Regular54pt7b, 54, "RobotoMono_Regular54pt7b" },
  { &RobotoMono_Regular55pt7b, 55, "RobotoMono_Regular55pt7b" },
  { &RobotoMono_Regular56pt7b, 56, "RobotoMono_Regular56pt7b" },
  { &RobotoMono_Regular57pt7b, 57, "RobotoMono_Regular57pt7b" },
  { &RobotoMono_Regular58pt7b, 58, "RobotoMono_Regular58pt7b" },
  { &RobotoMono_Regular59pt7b, 59, "RobotoMono_Regular59pt7b" },
  { &RobotoMono_Regular60pt7b, 60, "RobotoMono_Regular60pt7b" },
  { &RobotoMono_Regular61pt7b, 61, "RobotoMono_Regular61pt7b" },
  { &RobotoMono_Regular62pt7b, 62, "RobotoMono_Regular62pt7b" },
  { &RobotoMono_Regular63pt7b, 63, "RobotoMono_Regular63pt7b" },
  { &RobotoMono_Regular64pt7b, 64, "RobotoMono_Regular64pt7b" },
  { &RobotoMono_Regular65pt7b, 65, "RobotoMono_Regular65pt7b" },
  { &RobotoMono_Regular66pt7b, 66, "RobotoMono_Regular66pt7b" },
  { &RobotoMono_Regular67pt7b, 67, "RobotoMono_Regular67pt7b" },
  { &RobotoMono_Regular68pt7b, 68, "RobotoMono_Regular68pt7b" },
  { &RobotoMono_Regular69pt7b, 69, "RobotoMono_Regular69pt7b" },
  { &RobotoMono_Regular70pt7b, 70, "RobotoMono_Regular70pt7b" },
  { &RobotoMono_Regular71pt7b, 71, "RobotoMono_Regular71pt7b" },
  { &RobotoMono_Regular72pt7b, 72, "RobotoMono_Regular72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
