#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_ExtraCondensed_ExtraLight6pt7b, 6, "NotoSans_ExtraCondensed_ExtraLight6pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight7pt7b, 7, "NotoSans_ExtraCondensed_ExtraLight7pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight8pt7b, 8, "NotoSans_ExtraCondensed_ExtraLight8pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight9pt7b, 9, "NotoSans_ExtraCondensed_ExtraLight9pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight10pt7b, 10, "NotoSans_ExtraCondensed_ExtraLight10pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight11pt7b, 11, "NotoSans_ExtraCondensed_ExtraLight11pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight12pt7b, 12, "NotoSans_ExtraCondensed_ExtraLight12pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight13pt7b, 13, "NotoSans_ExtraCondensed_ExtraLight13pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight14pt7b, 14, "NotoSans_ExtraCondensed_ExtraLight14pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight15pt7b, 15, "NotoSans_ExtraCondensed_ExtraLight15pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight16pt7b, 16, "NotoSans_ExtraCondensed_ExtraLight16pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight17pt7b, 17, "NotoSans_ExtraCondensed_ExtraLight17pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight18pt7b, 18, "NotoSans_ExtraCondensed_ExtraLight18pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight19pt7b, 19, "NotoSans_ExtraCondensed_ExtraLight19pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight20pt7b, 20, "NotoSans_ExtraCondensed_ExtraLight20pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight21pt7b, 21, "NotoSans_ExtraCondensed_ExtraLight21pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight22pt7b, 22, "NotoSans_ExtraCondensed_ExtraLight22pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight23pt7b, 23, "NotoSans_ExtraCondensed_ExtraLight23pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight24pt7b, 24, "NotoSans_ExtraCondensed_ExtraLight24pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight25pt7b, 25, "NotoSans_ExtraCondensed_ExtraLight25pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight26pt7b, 26, "NotoSans_ExtraCondensed_ExtraLight26pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight27pt7b, 27, "NotoSans_ExtraCondensed_ExtraLight27pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight28pt7b, 28, "NotoSans_ExtraCondensed_ExtraLight28pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight29pt7b, 29, "NotoSans_ExtraCondensed_ExtraLight29pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight30pt7b, 30, "NotoSans_ExtraCondensed_ExtraLight30pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight31pt7b, 31, "NotoSans_ExtraCondensed_ExtraLight31pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight32pt7b, 32, "NotoSans_ExtraCondensed_ExtraLight32pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight33pt7b, 33, "NotoSans_ExtraCondensed_ExtraLight33pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight34pt7b, 34, "NotoSans_ExtraCondensed_ExtraLight34pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight35pt7b, 35, "NotoSans_ExtraCondensed_ExtraLight35pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight36pt7b, 36, "NotoSans_ExtraCondensed_ExtraLight36pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight37pt7b, 37, "NotoSans_ExtraCondensed_ExtraLight37pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight38pt7b, 38, "NotoSans_ExtraCondensed_ExtraLight38pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight39pt7b, 39, "NotoSans_ExtraCondensed_ExtraLight39pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight40pt7b, 40, "NotoSans_ExtraCondensed_ExtraLight40pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight41pt7b, 41, "NotoSans_ExtraCondensed_ExtraLight41pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight42pt7b, 42, "NotoSans_ExtraCondensed_ExtraLight42pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight43pt7b, 43, "NotoSans_ExtraCondensed_ExtraLight43pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight44pt7b, 44, "NotoSans_ExtraCondensed_ExtraLight44pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight45pt7b, 45, "NotoSans_ExtraCondensed_ExtraLight45pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight46pt7b, 46, "NotoSans_ExtraCondensed_ExtraLight46pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight47pt7b, 47, "NotoSans_ExtraCondensed_ExtraLight47pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight48pt7b, 48, "NotoSans_ExtraCondensed_ExtraLight48pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight49pt7b, 49, "NotoSans_ExtraCondensed_ExtraLight49pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight50pt7b, 50, "NotoSans_ExtraCondensed_ExtraLight50pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight51pt7b, 51, "NotoSans_ExtraCondensed_ExtraLight51pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight52pt7b, 52, "NotoSans_ExtraCondensed_ExtraLight52pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight53pt7b, 53, "NotoSans_ExtraCondensed_ExtraLight53pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight54pt7b, 54, "NotoSans_ExtraCondensed_ExtraLight54pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight55pt7b, 55, "NotoSans_ExtraCondensed_ExtraLight55pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight56pt7b, 56, "NotoSans_ExtraCondensed_ExtraLight56pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight57pt7b, 57, "NotoSans_ExtraCondensed_ExtraLight57pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight58pt7b, 58, "NotoSans_ExtraCondensed_ExtraLight58pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight59pt7b, 59, "NotoSans_ExtraCondensed_ExtraLight59pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight60pt7b, 60, "NotoSans_ExtraCondensed_ExtraLight60pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight61pt7b, 61, "NotoSans_ExtraCondensed_ExtraLight61pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight62pt7b, 62, "NotoSans_ExtraCondensed_ExtraLight62pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight63pt7b, 63, "NotoSans_ExtraCondensed_ExtraLight63pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight64pt7b, 64, "NotoSans_ExtraCondensed_ExtraLight64pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight65pt7b, 65, "NotoSans_ExtraCondensed_ExtraLight65pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight66pt7b, 66, "NotoSans_ExtraCondensed_ExtraLight66pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight67pt7b, 67, "NotoSans_ExtraCondensed_ExtraLight67pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight68pt7b, 68, "NotoSans_ExtraCondensed_ExtraLight68pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight69pt7b, 69, "NotoSans_ExtraCondensed_ExtraLight69pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight70pt7b, 70, "NotoSans_ExtraCondensed_ExtraLight70pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight71pt7b, 71, "NotoSans_ExtraCondensed_ExtraLight71pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLight72pt7b, 72, "NotoSans_ExtraCondensed_ExtraLight72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
