#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &IBMPlexMono_Regular6pt7b, 6, "IBMPlexMono_Regular6pt7b" },
  { &IBMPlexMono_Regular7pt7b, 7, "IBMPlexMono_Regular7pt7b" },
  { &IBMPlexMono_Regular8pt7b, 8, "IBMPlexMono_Regular8pt7b" },
  { &IBMPlexMono_Regular9pt7b, 9, "IBMPlexMono_Regular9pt7b" },
  { &IBMPlexMono_Regular10pt7b, 10, "IBMPlexMono_Regular10pt7b" },
  { &IBMPlexMono_Regular11pt7b, 11, "IBMPlexMono_Regular11pt7b" },
  { &IBMPlexMono_Regular12pt7b, 12, "IBMPlexMono_Regular12pt7b" },
  { &IBMPlexMono_Regular13pt7b, 13, "IBMPlexMono_Regular13pt7b" },
  { &IBMPlexMono_Regular14pt7b, 14, "IBMPlexMono_Regular14pt7b" },
  { &IBMPlexMono_Regular15pt7b, 15, "IBMPlexMono_Regular15pt7b" },
  { &IBMPlexMono_Regular16pt7b, 16, "IBMPlexMono_Regular16pt7b" },
  { &IBMPlexMono_Regular17pt7b, 17, "IBMPlexMono_Regular17pt7b" },
  { &IBMPlexMono_Regular18pt7b, 18, "IBMPlexMono_Regular18pt7b" },
  { &IBMPlexMono_Regular19pt7b, 19, "IBMPlexMono_Regular19pt7b" },
  { &IBMPlexMono_Regular20pt7b, 20, "IBMPlexMono_Regular20pt7b" },
  { &IBMPlexMono_Regular21pt7b, 21, "IBMPlexMono_Regular21pt7b" },
  { &IBMPlexMono_Regular22pt7b, 22, "IBMPlexMono_Regular22pt7b" },
  { &IBMPlexMono_Regular23pt7b, 23, "IBMPlexMono_Regular23pt7b" },
  { &IBMPlexMono_Regular24pt7b, 24, "IBMPlexMono_Regular24pt7b" },
  { &IBMPlexMono_Regular25pt7b, 25, "IBMPlexMono_Regular25pt7b" },
  { &IBMPlexMono_Regular26pt7b, 26, "IBMPlexMono_Regular26pt7b" },
  { &IBMPlexMono_Regular27pt7b, 27, "IBMPlexMono_Regular27pt7b" },
  { &IBMPlexMono_Regular28pt7b, 28, "IBMPlexMono_Regular28pt7b" },
  { &IBMPlexMono_Regular29pt7b, 29, "IBMPlexMono_Regular29pt7b" },
  { &IBMPlexMono_Regular30pt7b, 30, "IBMPlexMono_Regular30pt7b" },
  { &IBMPlexMono_Regular31pt7b, 31, "IBMPlexMono_Regular31pt7b" },
  { &IBMPlexMono_Regular32pt7b, 32, "IBMPlexMono_Regular32pt7b" },
  { &IBMPlexMono_Regular33pt7b, 33, "IBMPlexMono_Regular33pt7b" },
  { &IBMPlexMono_Regular34pt7b, 34, "IBMPlexMono_Regular34pt7b" },
  { &IBMPlexMono_Regular35pt7b, 35, "IBMPlexMono_Regular35pt7b" },
  { &IBMPlexMono_Regular36pt7b, 36, "IBMPlexMono_Regular36pt7b" },
  { &IBMPlexMono_Regular37pt7b, 37, "IBMPlexMono_Regular37pt7b" },
  { &IBMPlexMono_Regular38pt7b, 38, "IBMPlexMono_Regular38pt7b" },
  { &IBMPlexMono_Regular39pt7b, 39, "IBMPlexMono_Regular39pt7b" },
  { &IBMPlexMono_Regular40pt7b, 40, "IBMPlexMono_Regular40pt7b" },
  { &IBMPlexMono_Regular41pt7b, 41, "IBMPlexMono_Regular41pt7b" },
  { &IBMPlexMono_Regular42pt7b, 42, "IBMPlexMono_Regular42pt7b" },
  { &IBMPlexMono_Regular43pt7b, 43, "IBMPlexMono_Regular43pt7b" },
  { &IBMPlexMono_Regular44pt7b, 44, "IBMPlexMono_Regular44pt7b" },
  { &IBMPlexMono_Regular45pt7b, 45, "IBMPlexMono_Regular45pt7b" },
  { &IBMPlexMono_Regular46pt7b, 46, "IBMPlexMono_Regular46pt7b" },
  { &IBMPlexMono_Regular47pt7b, 47, "IBMPlexMono_Regular47pt7b" },
  { &IBMPlexMono_Regular48pt7b, 48, "IBMPlexMono_Regular48pt7b" },
  { &IBMPlexMono_Regular49pt7b, 49, "IBMPlexMono_Regular49pt7b" },
  { &IBMPlexMono_Regular50pt7b, 50, "IBMPlexMono_Regular50pt7b" },
  { &IBMPlexMono_Regular51pt7b, 51, "IBMPlexMono_Regular51pt7b" },
  { &IBMPlexMono_Regular52pt7b, 52, "IBMPlexMono_Regular52pt7b" },
  { &IBMPlexMono_Regular53pt7b, 53, "IBMPlexMono_Regular53pt7b" },
  { &IBMPlexMono_Regular54pt7b, 54, "IBMPlexMono_Regular54pt7b" },
  { &IBMPlexMono_Regular55pt7b, 55, "IBMPlexMono_Regular55pt7b" },
  { &IBMPlexMono_Regular56pt7b, 56, "IBMPlexMono_Regular56pt7b" },
  { &IBMPlexMono_Regular57pt7b, 57, "IBMPlexMono_Regular57pt7b" },
  { &IBMPlexMono_Regular58pt7b, 58, "IBMPlexMono_Regular58pt7b" },
  { &IBMPlexMono_Regular59pt7b, 59, "IBMPlexMono_Regular59pt7b" },
  { &IBMPlexMono_Regular60pt7b, 60, "IBMPlexMono_Regular60pt7b" },
  { &IBMPlexMono_Regular61pt7b, 61, "IBMPlexMono_Regular61pt7b" },
  { &IBMPlexMono_Regular62pt7b, 62, "IBMPlexMono_Regular62pt7b" },
  { &IBMPlexMono_Regular63pt7b, 63, "IBMPlexMono_Regular63pt7b" },
  { &IBMPlexMono_Regular64pt7b, 64, "IBMPlexMono_Regular64pt7b" },
  { &IBMPlexMono_Regular65pt7b, 65, "IBMPlexMono_Regular65pt7b" },
  { &IBMPlexMono_Regular66pt7b, 66, "IBMPlexMono_Regular66pt7b" },
  { &IBMPlexMono_Regular67pt7b, 67, "IBMPlexMono_Regular67pt7b" },
  { &IBMPlexMono_Regular68pt7b, 68, "IBMPlexMono_Regular68pt7b" },
  { &IBMPlexMono_Regular69pt7b, 69, "IBMPlexMono_Regular69pt7b" },
  { &IBMPlexMono_Regular70pt7b, 70, "IBMPlexMono_Regular70pt7b" },
  { &IBMPlexMono_Regular71pt7b, 71, "IBMPlexMono_Regular71pt7b" },
  { &IBMPlexMono_Regular72pt7b, 72, "IBMPlexMono_Regular72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
