#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &JetBrainsMono_ExtraBoldItalic6pt7b, 6, "JetBrainsMono_ExtraBoldItalic6pt7b" },
  { &JetBrainsMono_ExtraBoldItalic7pt7b, 7, "JetBrainsMono_ExtraBoldItalic7pt7b" },
  { &JetBrainsMono_ExtraBoldItalic8pt7b, 8, "JetBrainsMono_ExtraBoldItalic8pt7b" },
  { &JetBrainsMono_ExtraBoldItalic9pt7b, 9, "JetBrainsMono_ExtraBoldItalic9pt7b" },
  { &JetBrainsMono_ExtraBoldItalic10pt7b, 10, "JetBrainsMono_ExtraBoldItalic10pt7b" },
  { &JetBrainsMono_ExtraBoldItalic11pt7b, 11, "JetBrainsMono_ExtraBoldItalic11pt7b" },
  { &JetBrainsMono_ExtraBoldItalic12pt7b, 12, "JetBrainsMono_ExtraBoldItalic12pt7b" },
  { &JetBrainsMono_ExtraBoldItalic13pt7b, 13, "JetBrainsMono_ExtraBoldItalic13pt7b" },
  { &JetBrainsMono_ExtraBoldItalic14pt7b, 14, "JetBrainsMono_ExtraBoldItalic14pt7b" },
  { &JetBrainsMono_ExtraBoldItalic15pt7b, 15, "JetBrainsMono_ExtraBoldItalic15pt7b" },
  { &JetBrainsMono_ExtraBoldItalic16pt7b, 16, "JetBrainsMono_ExtraBoldItalic16pt7b" },
  { &JetBrainsMono_ExtraBoldItalic17pt7b, 17, "JetBrainsMono_ExtraBoldItalic17pt7b" },
  { &JetBrainsMono_ExtraBoldItalic18pt7b, 18, "JetBrainsMono_ExtraBoldItalic18pt7b" },
  { &JetBrainsMono_ExtraBoldItalic19pt7b, 19, "JetBrainsMono_ExtraBoldItalic19pt7b" },
  { &JetBrainsMono_ExtraBoldItalic20pt7b, 20, "JetBrainsMono_ExtraBoldItalic20pt7b" },
  { &JetBrainsMono_ExtraBoldItalic21pt7b, 21, "JetBrainsMono_ExtraBoldItalic21pt7b" },
  { &JetBrainsMono_ExtraBoldItalic22pt7b, 22, "JetBrainsMono_ExtraBoldItalic22pt7b" },
  { &JetBrainsMono_ExtraBoldItalic23pt7b, 23, "JetBrainsMono_ExtraBoldItalic23pt7b" },
  { &JetBrainsMono_ExtraBoldItalic24pt7b, 24, "JetBrainsMono_ExtraBoldItalic24pt7b" },
  { &JetBrainsMono_ExtraBoldItalic25pt7b, 25, "JetBrainsMono_ExtraBoldItalic25pt7b" },
  { &JetBrainsMono_ExtraBoldItalic26pt7b, 26, "JetBrainsMono_ExtraBoldItalic26pt7b" },
  { &JetBrainsMono_ExtraBoldItalic27pt7b, 27, "JetBrainsMono_ExtraBoldItalic27pt7b" },
  { &JetBrainsMono_ExtraBoldItalic28pt7b, 28, "JetBrainsMono_ExtraBoldItalic28pt7b" },
  { &JetBrainsMono_ExtraBoldItalic29pt7b, 29, "JetBrainsMono_ExtraBoldItalic29pt7b" },
  { &JetBrainsMono_ExtraBoldItalic30pt7b, 30, "JetBrainsMono_ExtraBoldItalic30pt7b" },
  { &JetBrainsMono_ExtraBoldItalic31pt7b, 31, "JetBrainsMono_ExtraBoldItalic31pt7b" },
  { &JetBrainsMono_ExtraBoldItalic32pt7b, 32, "JetBrainsMono_ExtraBoldItalic32pt7b" },
  { &JetBrainsMono_ExtraBoldItalic33pt7b, 33, "JetBrainsMono_ExtraBoldItalic33pt7b" },
  { &JetBrainsMono_ExtraBoldItalic34pt7b, 34, "JetBrainsMono_ExtraBoldItalic34pt7b" },
  { &JetBrainsMono_ExtraBoldItalic35pt7b, 35, "JetBrainsMono_ExtraBoldItalic35pt7b" },
  { &JetBrainsMono_ExtraBoldItalic36pt7b, 36, "JetBrainsMono_ExtraBoldItalic36pt7b" },
  { &JetBrainsMono_ExtraBoldItalic37pt7b, 37, "JetBrainsMono_ExtraBoldItalic37pt7b" },
  { &JetBrainsMono_ExtraBoldItalic38pt7b, 38, "JetBrainsMono_ExtraBoldItalic38pt7b" },
  { &JetBrainsMono_ExtraBoldItalic39pt7b, 39, "JetBrainsMono_ExtraBoldItalic39pt7b" },
  { &JetBrainsMono_ExtraBoldItalic40pt7b, 40, "JetBrainsMono_ExtraBoldItalic40pt7b" },
  { &JetBrainsMono_ExtraBoldItalic41pt7b, 41, "JetBrainsMono_ExtraBoldItalic41pt7b" },
  { &JetBrainsMono_ExtraBoldItalic42pt7b, 42, "JetBrainsMono_ExtraBoldItalic42pt7b" },
  { &JetBrainsMono_ExtraBoldItalic43pt7b, 43, "JetBrainsMono_ExtraBoldItalic43pt7b" },
  { &JetBrainsMono_ExtraBoldItalic44pt7b, 44, "JetBrainsMono_ExtraBoldItalic44pt7b" },
  { &JetBrainsMono_ExtraBoldItalic45pt7b, 45, "JetBrainsMono_ExtraBoldItalic45pt7b" },
  { &JetBrainsMono_ExtraBoldItalic46pt7b, 46, "JetBrainsMono_ExtraBoldItalic46pt7b" },
  { &JetBrainsMono_ExtraBoldItalic47pt7b, 47, "JetBrainsMono_ExtraBoldItalic47pt7b" },
  { &JetBrainsMono_ExtraBoldItalic48pt7b, 48, "JetBrainsMono_ExtraBoldItalic48pt7b" },
  { &JetBrainsMono_ExtraBoldItalic49pt7b, 49, "JetBrainsMono_ExtraBoldItalic49pt7b" },
  { &JetBrainsMono_ExtraBoldItalic50pt7b, 50, "JetBrainsMono_ExtraBoldItalic50pt7b" },
  { &JetBrainsMono_ExtraBoldItalic51pt7b, 51, "JetBrainsMono_ExtraBoldItalic51pt7b" },
  { &JetBrainsMono_ExtraBoldItalic52pt7b, 52, "JetBrainsMono_ExtraBoldItalic52pt7b" },
  { &JetBrainsMono_ExtraBoldItalic53pt7b, 53, "JetBrainsMono_ExtraBoldItalic53pt7b" },
  { &JetBrainsMono_ExtraBoldItalic54pt7b, 54, "JetBrainsMono_ExtraBoldItalic54pt7b" },
  { &JetBrainsMono_ExtraBoldItalic55pt7b, 55, "JetBrainsMono_ExtraBoldItalic55pt7b" },
  { &JetBrainsMono_ExtraBoldItalic56pt7b, 56, "JetBrainsMono_ExtraBoldItalic56pt7b" },
  { &JetBrainsMono_ExtraBoldItalic57pt7b, 57, "JetBrainsMono_ExtraBoldItalic57pt7b" },
  { &JetBrainsMono_ExtraBoldItalic58pt7b, 58, "JetBrainsMono_ExtraBoldItalic58pt7b" },
  { &JetBrainsMono_ExtraBoldItalic59pt7b, 59, "JetBrainsMono_ExtraBoldItalic59pt7b" },
  { &JetBrainsMono_ExtraBoldItalic60pt7b, 60, "JetBrainsMono_ExtraBoldItalic60pt7b" },
  { &JetBrainsMono_ExtraBoldItalic61pt7b, 61, "JetBrainsMono_ExtraBoldItalic61pt7b" },
  { &JetBrainsMono_ExtraBoldItalic62pt7b, 62, "JetBrainsMono_ExtraBoldItalic62pt7b" },
  { &JetBrainsMono_ExtraBoldItalic63pt7b, 63, "JetBrainsMono_ExtraBoldItalic63pt7b" },
  { &JetBrainsMono_ExtraBoldItalic64pt7b, 64, "JetBrainsMono_ExtraBoldItalic64pt7b" },
  { &JetBrainsMono_ExtraBoldItalic65pt7b, 65, "JetBrainsMono_ExtraBoldItalic65pt7b" },
  { &JetBrainsMono_ExtraBoldItalic66pt7b, 66, "JetBrainsMono_ExtraBoldItalic66pt7b" },
  { &JetBrainsMono_ExtraBoldItalic67pt7b, 67, "JetBrainsMono_ExtraBoldItalic67pt7b" },
  { &JetBrainsMono_ExtraBoldItalic68pt7b, 68, "JetBrainsMono_ExtraBoldItalic68pt7b" },
  { &JetBrainsMono_ExtraBoldItalic69pt7b, 69, "JetBrainsMono_ExtraBoldItalic69pt7b" },
  { &JetBrainsMono_ExtraBoldItalic70pt7b, 70, "JetBrainsMono_ExtraBoldItalic70pt7b" },
  { &JetBrainsMono_ExtraBoldItalic71pt7b, 71, "JetBrainsMono_ExtraBoldItalic71pt7b" },
  { &JetBrainsMono_ExtraBoldItalic72pt7b, 72, "JetBrainsMono_ExtraBoldItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
