#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &JetBrainsMono_Regular6pt7b, 6, "JetBrainsMono_Regular6pt7b" },
  { &JetBrainsMono_Regular7pt7b, 7, "JetBrainsMono_Regular7pt7b" },
  { &JetBrainsMono_Regular8pt7b, 8, "JetBrainsMono_Regular8pt7b" },
  { &JetBrainsMono_Regular9pt7b, 9, "JetBrainsMono_Regular9pt7b" },
  { &JetBrainsMono_Regular10pt7b, 10, "JetBrainsMono_Regular10pt7b" },
  { &JetBrainsMono_Regular11pt7b, 11, "JetBrainsMono_Regular11pt7b" },
  { &JetBrainsMono_Regular12pt7b, 12, "JetBrainsMono_Regular12pt7b" },
  { &JetBrainsMono_Regular13pt7b, 13, "JetBrainsMono_Regular13pt7b" },
  { &JetBrainsMono_Regular14pt7b, 14, "JetBrainsMono_Regular14pt7b" },
  { &JetBrainsMono_Regular15pt7b, 15, "JetBrainsMono_Regular15pt7b" },
  { &JetBrainsMono_Regular16pt7b, 16, "JetBrainsMono_Regular16pt7b" },
  { &JetBrainsMono_Regular17pt7b, 17, "JetBrainsMono_Regular17pt7b" },
  { &JetBrainsMono_Regular18pt7b, 18, "JetBrainsMono_Regular18pt7b" },
  { &JetBrainsMono_Regular19pt7b, 19, "JetBrainsMono_Regular19pt7b" },
  { &JetBrainsMono_Regular20pt7b, 20, "JetBrainsMono_Regular20pt7b" },
  { &JetBrainsMono_Regular21pt7b, 21, "JetBrainsMono_Regular21pt7b" },
  { &JetBrainsMono_Regular22pt7b, 22, "JetBrainsMono_Regular22pt7b" },
  { &JetBrainsMono_Regular23pt7b, 23, "JetBrainsMono_Regular23pt7b" },
  { &JetBrainsMono_Regular24pt7b, 24, "JetBrainsMono_Regular24pt7b" },
  { &JetBrainsMono_Regular25pt7b, 25, "JetBrainsMono_Regular25pt7b" },
  { &JetBrainsMono_Regular26pt7b, 26, "JetBrainsMono_Regular26pt7b" },
  { &JetBrainsMono_Regular27pt7b, 27, "JetBrainsMono_Regular27pt7b" },
  { &JetBrainsMono_Regular28pt7b, 28, "JetBrainsMono_Regular28pt7b" },
  { &JetBrainsMono_Regular29pt7b, 29, "JetBrainsMono_Regular29pt7b" },
  { &JetBrainsMono_Regular30pt7b, 30, "JetBrainsMono_Regular30pt7b" },
  { &JetBrainsMono_Regular31pt7b, 31, "JetBrainsMono_Regular31pt7b" },
  { &JetBrainsMono_Regular32pt7b, 32, "JetBrainsMono_Regular32pt7b" },
  { &JetBrainsMono_Regular33pt7b, 33, "JetBrainsMono_Regular33pt7b" },
  { &JetBrainsMono_Regular34pt7b, 34, "JetBrainsMono_Regular34pt7b" },
  { &JetBrainsMono_Regular35pt7b, 35, "JetBrainsMono_Regular35pt7b" },
  { &JetBrainsMono_Regular36pt7b, 36, "JetBrainsMono_Regular36pt7b" },
  { &JetBrainsMono_Regular37pt7b, 37, "JetBrainsMono_Regular37pt7b" },
  { &JetBrainsMono_Regular38pt7b, 38, "JetBrainsMono_Regular38pt7b" },
  { &JetBrainsMono_Regular39pt7b, 39, "JetBrainsMono_Regular39pt7b" },
  { &JetBrainsMono_Regular40pt7b, 40, "JetBrainsMono_Regular40pt7b" },
  { &JetBrainsMono_Regular41pt7b, 41, "JetBrainsMono_Regular41pt7b" },
  { &JetBrainsMono_Regular42pt7b, 42, "JetBrainsMono_Regular42pt7b" },
  { &JetBrainsMono_Regular43pt7b, 43, "JetBrainsMono_Regular43pt7b" },
  { &JetBrainsMono_Regular44pt7b, 44, "JetBrainsMono_Regular44pt7b" },
  { &JetBrainsMono_Regular45pt7b, 45, "JetBrainsMono_Regular45pt7b" },
  { &JetBrainsMono_Regular46pt7b, 46, "JetBrainsMono_Regular46pt7b" },
  { &JetBrainsMono_Regular47pt7b, 47, "JetBrainsMono_Regular47pt7b" },
  { &JetBrainsMono_Regular48pt7b, 48, "JetBrainsMono_Regular48pt7b" },
  { &JetBrainsMono_Regular49pt7b, 49, "JetBrainsMono_Regular49pt7b" },
  { &JetBrainsMono_Regular50pt7b, 50, "JetBrainsMono_Regular50pt7b" },
  { &JetBrainsMono_Regular51pt7b, 51, "JetBrainsMono_Regular51pt7b" },
  { &JetBrainsMono_Regular52pt7b, 52, "JetBrainsMono_Regular52pt7b" },
  { &JetBrainsMono_Regular53pt7b, 53, "JetBrainsMono_Regular53pt7b" },
  { &JetBrainsMono_Regular54pt7b, 54, "JetBrainsMono_Regular54pt7b" },
  { &JetBrainsMono_Regular55pt7b, 55, "JetBrainsMono_Regular55pt7b" },
  { &JetBrainsMono_Regular56pt7b, 56, "JetBrainsMono_Regular56pt7b" },
  { &JetBrainsMono_Regular57pt7b, 57, "JetBrainsMono_Regular57pt7b" },
  { &JetBrainsMono_Regular58pt7b, 58, "JetBrainsMono_Regular58pt7b" },
  { &JetBrainsMono_Regular59pt7b, 59, "JetBrainsMono_Regular59pt7b" },
  { &JetBrainsMono_Regular60pt7b, 60, "JetBrainsMono_Regular60pt7b" },
  { &JetBrainsMono_Regular61pt7b, 61, "JetBrainsMono_Regular61pt7b" },
  { &JetBrainsMono_Regular62pt7b, 62, "JetBrainsMono_Regular62pt7b" },
  { &JetBrainsMono_Regular63pt7b, 63, "JetBrainsMono_Regular63pt7b" },
  { &JetBrainsMono_Regular64pt7b, 64, "JetBrainsMono_Regular64pt7b" },
  { &JetBrainsMono_Regular65pt7b, 65, "JetBrainsMono_Regular65pt7b" },
  { &JetBrainsMono_Regular66pt7b, 66, "JetBrainsMono_Regular66pt7b" },
  { &JetBrainsMono_Regular67pt7b, 67, "JetBrainsMono_Regular67pt7b" },
  { &JetBrainsMono_Regular68pt7b, 68, "JetBrainsMono_Regular68pt7b" },
  { &JetBrainsMono_Regular69pt7b, 69, "JetBrainsMono_Regular69pt7b" },
  { &JetBrainsMono_Regular70pt7b, 70, "JetBrainsMono_Regular70pt7b" },
  { &JetBrainsMono_Regular71pt7b, 71, "JetBrainsMono_Regular71pt7b" },
  { &JetBrainsMono_Regular72pt7b, 72, "JetBrainsMono_Regular72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
