#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &UbuntuSansMono_BoldItalic6pt7b, 6, "UbuntuSansMono_BoldItalic6pt7b" },
  { &UbuntuSansMono_BoldItalic7pt7b, 7, "UbuntuSansMono_BoldItalic7pt7b" },
  { &UbuntuSansMono_BoldItalic8pt7b, 8, "UbuntuSansMono_BoldItalic8pt7b" },
  { &UbuntuSansMono_BoldItalic9pt7b, 9, "UbuntuSansMono_BoldItalic9pt7b" },
  { &UbuntuSansMono_BoldItalic10pt7b, 10, "UbuntuSansMono_BoldItalic10pt7b" },
  { &UbuntuSansMono_BoldItalic11pt7b, 11, "UbuntuSansMono_BoldItalic11pt7b" },
  { &UbuntuSansMono_BoldItalic12pt7b, 12, "UbuntuSansMono_BoldItalic12pt7b" },
  { &UbuntuSansMono_BoldItalic13pt7b, 13, "UbuntuSansMono_BoldItalic13pt7b" },
  { &UbuntuSansMono_BoldItalic14pt7b, 14, "UbuntuSansMono_BoldItalic14pt7b" },
  { &UbuntuSansMono_BoldItalic15pt7b, 15, "UbuntuSansMono_BoldItalic15pt7b" },
  { &UbuntuSansMono_BoldItalic16pt7b, 16, "UbuntuSansMono_BoldItalic16pt7b" },
  { &UbuntuSansMono_BoldItalic17pt7b, 17, "UbuntuSansMono_BoldItalic17pt7b" },
  { &UbuntuSansMono_BoldItalic18pt7b, 18, "UbuntuSansMono_BoldItalic18pt7b" },
  { &UbuntuSansMono_BoldItalic19pt7b, 19, "UbuntuSansMono_BoldItalic19pt7b" },
  { &UbuntuSansMono_BoldItalic20pt7b, 20, "UbuntuSansMono_BoldItalic20pt7b" },
  { &UbuntuSansMono_BoldItalic21pt7b, 21, "UbuntuSansMono_BoldItalic21pt7b" },
  { &UbuntuSansMono_BoldItalic22pt7b, 22, "UbuntuSansMono_BoldItalic22pt7b" },
  { &UbuntuSansMono_BoldItalic23pt7b, 23, "UbuntuSansMono_BoldItalic23pt7b" },
  { &UbuntuSansMono_BoldItalic24pt7b, 24, "UbuntuSansMono_BoldItalic24pt7b" },
  { &UbuntuSansMono_BoldItalic25pt7b, 25, "UbuntuSansMono_BoldItalic25pt7b" },
  { &UbuntuSansMono_BoldItalic26pt7b, 26, "UbuntuSansMono_BoldItalic26pt7b" },
  { &UbuntuSansMono_BoldItalic27pt7b, 27, "UbuntuSansMono_BoldItalic27pt7b" },
  { &UbuntuSansMono_BoldItalic28pt7b, 28, "UbuntuSansMono_BoldItalic28pt7b" },
  { &UbuntuSansMono_BoldItalic29pt7b, 29, "UbuntuSansMono_BoldItalic29pt7b" },
  { &UbuntuSansMono_BoldItalic30pt7b, 30, "UbuntuSansMono_BoldItalic30pt7b" },
  { &UbuntuSansMono_BoldItalic31pt7b, 31, "UbuntuSansMono_BoldItalic31pt7b" },
  { &UbuntuSansMono_BoldItalic32pt7b, 32, "UbuntuSansMono_BoldItalic32pt7b" },
  { &UbuntuSansMono_BoldItalic33pt7b, 33, "UbuntuSansMono_BoldItalic33pt7b" },
  { &UbuntuSansMono_BoldItalic34pt7b, 34, "UbuntuSansMono_BoldItalic34pt7b" },
  { &UbuntuSansMono_BoldItalic35pt7b, 35, "UbuntuSansMono_BoldItalic35pt7b" },
  { &UbuntuSansMono_BoldItalic36pt7b, 36, "UbuntuSansMono_BoldItalic36pt7b" },
  { &UbuntuSansMono_BoldItalic37pt7b, 37, "UbuntuSansMono_BoldItalic37pt7b" },
  { &UbuntuSansMono_BoldItalic38pt7b, 38, "UbuntuSansMono_BoldItalic38pt7b" },
  { &UbuntuSansMono_BoldItalic39pt7b, 39, "UbuntuSansMono_BoldItalic39pt7b" },
  { &UbuntuSansMono_BoldItalic40pt7b, 40, "UbuntuSansMono_BoldItalic40pt7b" },
  { &UbuntuSansMono_BoldItalic41pt7b, 41, "UbuntuSansMono_BoldItalic41pt7b" },
  { &UbuntuSansMono_BoldItalic42pt7b, 42, "UbuntuSansMono_BoldItalic42pt7b" },
  { &UbuntuSansMono_BoldItalic43pt7b, 43, "UbuntuSansMono_BoldItalic43pt7b" },
  { &UbuntuSansMono_BoldItalic44pt7b, 44, "UbuntuSansMono_BoldItalic44pt7b" },
  { &UbuntuSansMono_BoldItalic45pt7b, 45, "UbuntuSansMono_BoldItalic45pt7b" },
  { &UbuntuSansMono_BoldItalic46pt7b, 46, "UbuntuSansMono_BoldItalic46pt7b" },
  { &UbuntuSansMono_BoldItalic47pt7b, 47, "UbuntuSansMono_BoldItalic47pt7b" },
  { &UbuntuSansMono_BoldItalic48pt7b, 48, "UbuntuSansMono_BoldItalic48pt7b" },
  { &UbuntuSansMono_BoldItalic49pt7b, 49, "UbuntuSansMono_BoldItalic49pt7b" },
  { &UbuntuSansMono_BoldItalic50pt7b, 50, "UbuntuSansMono_BoldItalic50pt7b" },
  { &UbuntuSansMono_BoldItalic51pt7b, 51, "UbuntuSansMono_BoldItalic51pt7b" },
  { &UbuntuSansMono_BoldItalic52pt7b, 52, "UbuntuSansMono_BoldItalic52pt7b" },
  { &UbuntuSansMono_BoldItalic53pt7b, 53, "UbuntuSansMono_BoldItalic53pt7b" },
  { &UbuntuSansMono_BoldItalic54pt7b, 54, "UbuntuSansMono_BoldItalic54pt7b" },
  { &UbuntuSansMono_BoldItalic55pt7b, 55, "UbuntuSansMono_BoldItalic55pt7b" },
  { &UbuntuSansMono_BoldItalic56pt7b, 56, "UbuntuSansMono_BoldItalic56pt7b" },
  { &UbuntuSansMono_BoldItalic57pt7b, 57, "UbuntuSansMono_BoldItalic57pt7b" },
  { &UbuntuSansMono_BoldItalic58pt7b, 58, "UbuntuSansMono_BoldItalic58pt7b" },
  { &UbuntuSansMono_BoldItalic59pt7b, 59, "UbuntuSansMono_BoldItalic59pt7b" },
  { &UbuntuSansMono_BoldItalic60pt7b, 60, "UbuntuSansMono_BoldItalic60pt7b" },
  { &UbuntuSansMono_BoldItalic61pt7b, 61, "UbuntuSansMono_BoldItalic61pt7b" },
  { &UbuntuSansMono_BoldItalic62pt7b, 62, "UbuntuSansMono_BoldItalic62pt7b" },
  { &UbuntuSansMono_BoldItalic63pt7b, 63, "UbuntuSansMono_BoldItalic63pt7b" },
  { &UbuntuSansMono_BoldItalic64pt7b, 64, "UbuntuSansMono_BoldItalic64pt7b" },
  { &UbuntuSansMono_BoldItalic65pt7b, 65, "UbuntuSansMono_BoldItalic65pt7b" },
  { &UbuntuSansMono_BoldItalic66pt7b, 66, "UbuntuSansMono_BoldItalic66pt7b" },
  { &UbuntuSansMono_BoldItalic67pt7b, 67, "UbuntuSansMono_BoldItalic67pt7b" },
  { &UbuntuSansMono_BoldItalic68pt7b, 68, "UbuntuSansMono_BoldItalic68pt7b" },
  { &UbuntuSansMono_BoldItalic69pt7b, 69, "UbuntuSansMono_BoldItalic69pt7b" },
  { &UbuntuSansMono_BoldItalic70pt7b, 70, "UbuntuSansMono_BoldItalic70pt7b" },
  { &UbuntuSansMono_BoldItalic71pt7b, 71, "UbuntuSansMono_BoldItalic71pt7b" },
  { &UbuntuSansMono_BoldItalic72pt7b, 72, "UbuntuSansMono_BoldItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
