#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &UbuntuMono_Bold6pt7b, 6, "UbuntuMono_Bold6pt7b" },
  { &UbuntuMono_Bold7pt7b, 7, "UbuntuMono_Bold7pt7b" },
  { &UbuntuMono_Bold8pt7b, 8, "UbuntuMono_Bold8pt7b" },
  { &UbuntuMono_Bold9pt7b, 9, "UbuntuMono_Bold9pt7b" },
  { &UbuntuMono_Bold10pt7b, 10, "UbuntuMono_Bold10pt7b" },
  { &UbuntuMono_Bold11pt7b, 11, "UbuntuMono_Bold11pt7b" },
  { &UbuntuMono_Bold12pt7b, 12, "UbuntuMono_Bold12pt7b" },
  { &UbuntuMono_Bold13pt7b, 13, "UbuntuMono_Bold13pt7b" },
  { &UbuntuMono_Bold14pt7b, 14, "UbuntuMono_Bold14pt7b" },
  { &UbuntuMono_Bold15pt7b, 15, "UbuntuMono_Bold15pt7b" },
  { &UbuntuMono_Bold16pt7b, 16, "UbuntuMono_Bold16pt7b" },
  { &UbuntuMono_Bold17pt7b, 17, "UbuntuMono_Bold17pt7b" },
  { &UbuntuMono_Bold18pt7b, 18, "UbuntuMono_Bold18pt7b" },
  { &UbuntuMono_Bold19pt7b, 19, "UbuntuMono_Bold19pt7b" },
  { &UbuntuMono_Bold20pt7b, 20, "UbuntuMono_Bold20pt7b" },
  { &UbuntuMono_Bold21pt7b, 21, "UbuntuMono_Bold21pt7b" },
  { &UbuntuMono_Bold22pt7b, 22, "UbuntuMono_Bold22pt7b" },
  { &UbuntuMono_Bold23pt7b, 23, "UbuntuMono_Bold23pt7b" },
  { &UbuntuMono_Bold24pt7b, 24, "UbuntuMono_Bold24pt7b" },
  { &UbuntuMono_Bold25pt7b, 25, "UbuntuMono_Bold25pt7b" },
  { &UbuntuMono_Bold26pt7b, 26, "UbuntuMono_Bold26pt7b" },
  { &UbuntuMono_Bold27pt7b, 27, "UbuntuMono_Bold27pt7b" },
  { &UbuntuMono_Bold28pt7b, 28, "UbuntuMono_Bold28pt7b" },
  { &UbuntuMono_Bold29pt7b, 29, "UbuntuMono_Bold29pt7b" },
  { &UbuntuMono_Bold30pt7b, 30, "UbuntuMono_Bold30pt7b" },
  { &UbuntuMono_Bold31pt7b, 31, "UbuntuMono_Bold31pt7b" },
  { &UbuntuMono_Bold32pt7b, 32, "UbuntuMono_Bold32pt7b" },
  { &UbuntuMono_Bold33pt7b, 33, "UbuntuMono_Bold33pt7b" },
  { &UbuntuMono_Bold34pt7b, 34, "UbuntuMono_Bold34pt7b" },
  { &UbuntuMono_Bold35pt7b, 35, "UbuntuMono_Bold35pt7b" },
  { &UbuntuMono_Bold36pt7b, 36, "UbuntuMono_Bold36pt7b" },
  { &UbuntuMono_Bold37pt7b, 37, "UbuntuMono_Bold37pt7b" },
  { &UbuntuMono_Bold38pt7b, 38, "UbuntuMono_Bold38pt7b" },
  { &UbuntuMono_Bold39pt7b, 39, "UbuntuMono_Bold39pt7b" },
  { &UbuntuMono_Bold40pt7b, 40, "UbuntuMono_Bold40pt7b" },
  { &UbuntuMono_Bold41pt7b, 41, "UbuntuMono_Bold41pt7b" },
  { &UbuntuMono_Bold42pt7b, 42, "UbuntuMono_Bold42pt7b" },
  { &UbuntuMono_Bold43pt7b, 43, "UbuntuMono_Bold43pt7b" },
  { &UbuntuMono_Bold44pt7b, 44, "UbuntuMono_Bold44pt7b" },
  { &UbuntuMono_Bold45pt7b, 45, "UbuntuMono_Bold45pt7b" },
  { &UbuntuMono_Bold46pt7b, 46, "UbuntuMono_Bold46pt7b" },
  { &UbuntuMono_Bold47pt7b, 47, "UbuntuMono_Bold47pt7b" },
  { &UbuntuMono_Bold48pt7b, 48, "UbuntuMono_Bold48pt7b" },
  { &UbuntuMono_Bold49pt7b, 49, "UbuntuMono_Bold49pt7b" },
  { &UbuntuMono_Bold50pt7b, 50, "UbuntuMono_Bold50pt7b" },
  { &UbuntuMono_Bold51pt7b, 51, "UbuntuMono_Bold51pt7b" },
  { &UbuntuMono_Bold52pt7b, 52, "UbuntuMono_Bold52pt7b" },
  { &UbuntuMono_Bold53pt7b, 53, "UbuntuMono_Bold53pt7b" },
  { &UbuntuMono_Bold54pt7b, 54, "UbuntuMono_Bold54pt7b" },
  { &UbuntuMono_Bold55pt7b, 55, "UbuntuMono_Bold55pt7b" },
  { &UbuntuMono_Bold56pt7b, 56, "UbuntuMono_Bold56pt7b" },
  { &UbuntuMono_Bold57pt7b, 57, "UbuntuMono_Bold57pt7b" },
  { &UbuntuMono_Bold58pt7b, 58, "UbuntuMono_Bold58pt7b" },
  { &UbuntuMono_Bold59pt7b, 59, "UbuntuMono_Bold59pt7b" },
  { &UbuntuMono_Bold60pt7b, 60, "UbuntuMono_Bold60pt7b" },
  { &UbuntuMono_Bold61pt7b, 61, "UbuntuMono_Bold61pt7b" },
  { &UbuntuMono_Bold62pt7b, 62, "UbuntuMono_Bold62pt7b" },
  { &UbuntuMono_Bold63pt7b, 63, "UbuntuMono_Bold63pt7b" },
  { &UbuntuMono_Bold64pt7b, 64, "UbuntuMono_Bold64pt7b" },
  { &UbuntuMono_Bold65pt7b, 65, "UbuntuMono_Bold65pt7b" },
  { &UbuntuMono_Bold66pt7b, 66, "UbuntuMono_Bold66pt7b" },
  { &UbuntuMono_Bold67pt7b, 67, "UbuntuMono_Bold67pt7b" },
  { &UbuntuMono_Bold68pt7b, 68, "UbuntuMono_Bold68pt7b" },
  { &UbuntuMono_Bold69pt7b, 69, "UbuntuMono_Bold69pt7b" },
  { &UbuntuMono_Bold70pt7b, 70, "UbuntuMono_Bold70pt7b" },
  { &UbuntuMono_Bold71pt7b, 71, "UbuntuMono_Bold71pt7b" },
  { &UbuntuMono_Bold72pt7b, 72, "UbuntuMono_Bold72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
