#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &UbuntuSansMono_SemiBold6pt7b, 6, "UbuntuSansMono_SemiBold6pt7b" },
  { &UbuntuSansMono_SemiBold7pt7b, 7, "UbuntuSansMono_SemiBold7pt7b" },
  { &UbuntuSansMono_SemiBold8pt7b, 8, "UbuntuSansMono_SemiBold8pt7b" },
  { &UbuntuSansMono_SemiBold9pt7b, 9, "UbuntuSansMono_SemiBold9pt7b" },
  { &UbuntuSansMono_SemiBold10pt7b, 10, "UbuntuSansMono_SemiBold10pt7b" },
  { &UbuntuSansMono_SemiBold11pt7b, 11, "UbuntuSansMono_SemiBold11pt7b" },
  { &UbuntuSansMono_SemiBold12pt7b, 12, "UbuntuSansMono_SemiBold12pt7b" },
  { &UbuntuSansMono_SemiBold13pt7b, 13, "UbuntuSansMono_SemiBold13pt7b" },
  { &UbuntuSansMono_SemiBold14pt7b, 14, "UbuntuSansMono_SemiBold14pt7b" },
  { &UbuntuSansMono_SemiBold15pt7b, 15, "UbuntuSansMono_SemiBold15pt7b" },
  { &UbuntuSansMono_SemiBold16pt7b, 16, "UbuntuSansMono_SemiBold16pt7b" },
  { &UbuntuSansMono_SemiBold17pt7b, 17, "UbuntuSansMono_SemiBold17pt7b" },
  { &UbuntuSansMono_SemiBold18pt7b, 18, "UbuntuSansMono_SemiBold18pt7b" },
  { &UbuntuSansMono_SemiBold19pt7b, 19, "UbuntuSansMono_SemiBold19pt7b" },
  { &UbuntuSansMono_SemiBold20pt7b, 20, "UbuntuSansMono_SemiBold20pt7b" },
  { &UbuntuSansMono_SemiBold21pt7b, 21, "UbuntuSansMono_SemiBold21pt7b" },
  { &UbuntuSansMono_SemiBold22pt7b, 22, "UbuntuSansMono_SemiBold22pt7b" },
  { &UbuntuSansMono_SemiBold23pt7b, 23, "UbuntuSansMono_SemiBold23pt7b" },
  { &UbuntuSansMono_SemiBold24pt7b, 24, "UbuntuSansMono_SemiBold24pt7b" },
  { &UbuntuSansMono_SemiBold25pt7b, 25, "UbuntuSansMono_SemiBold25pt7b" },
  { &UbuntuSansMono_SemiBold26pt7b, 26, "UbuntuSansMono_SemiBold26pt7b" },
  { &UbuntuSansMono_SemiBold27pt7b, 27, "UbuntuSansMono_SemiBold27pt7b" },
  { &UbuntuSansMono_SemiBold28pt7b, 28, "UbuntuSansMono_SemiBold28pt7b" },
  { &UbuntuSansMono_SemiBold29pt7b, 29, "UbuntuSansMono_SemiBold29pt7b" },
  { &UbuntuSansMono_SemiBold30pt7b, 30, "UbuntuSansMono_SemiBold30pt7b" },
  { &UbuntuSansMono_SemiBold31pt7b, 31, "UbuntuSansMono_SemiBold31pt7b" },
  { &UbuntuSansMono_SemiBold32pt7b, 32, "UbuntuSansMono_SemiBold32pt7b" },
  { &UbuntuSansMono_SemiBold33pt7b, 33, "UbuntuSansMono_SemiBold33pt7b" },
  { &UbuntuSansMono_SemiBold34pt7b, 34, "UbuntuSansMono_SemiBold34pt7b" },
  { &UbuntuSansMono_SemiBold35pt7b, 35, "UbuntuSansMono_SemiBold35pt7b" },
  { &UbuntuSansMono_SemiBold36pt7b, 36, "UbuntuSansMono_SemiBold36pt7b" },
  { &UbuntuSansMono_SemiBold37pt7b, 37, "UbuntuSansMono_SemiBold37pt7b" },
  { &UbuntuSansMono_SemiBold38pt7b, 38, "UbuntuSansMono_SemiBold38pt7b" },
  { &UbuntuSansMono_SemiBold39pt7b, 39, "UbuntuSansMono_SemiBold39pt7b" },
  { &UbuntuSansMono_SemiBold40pt7b, 40, "UbuntuSansMono_SemiBold40pt7b" },
  { &UbuntuSansMono_SemiBold41pt7b, 41, "UbuntuSansMono_SemiBold41pt7b" },
  { &UbuntuSansMono_SemiBold42pt7b, 42, "UbuntuSansMono_SemiBold42pt7b" },
  { &UbuntuSansMono_SemiBold43pt7b, 43, "UbuntuSansMono_SemiBold43pt7b" },
  { &UbuntuSansMono_SemiBold44pt7b, 44, "UbuntuSansMono_SemiBold44pt7b" },
  { &UbuntuSansMono_SemiBold45pt7b, 45, "UbuntuSansMono_SemiBold45pt7b" },
  { &UbuntuSansMono_SemiBold46pt7b, 46, "UbuntuSansMono_SemiBold46pt7b" },
  { &UbuntuSansMono_SemiBold47pt7b, 47, "UbuntuSansMono_SemiBold47pt7b" },
  { &UbuntuSansMono_SemiBold48pt7b, 48, "UbuntuSansMono_SemiBold48pt7b" },
  { &UbuntuSansMono_SemiBold49pt7b, 49, "UbuntuSansMono_SemiBold49pt7b" },
  { &UbuntuSansMono_SemiBold50pt7b, 50, "UbuntuSansMono_SemiBold50pt7b" },
  { &UbuntuSansMono_SemiBold51pt7b, 51, "UbuntuSansMono_SemiBold51pt7b" },
  { &UbuntuSansMono_SemiBold52pt7b, 52, "UbuntuSansMono_SemiBold52pt7b" },
  { &UbuntuSansMono_SemiBold53pt7b, 53, "UbuntuSansMono_SemiBold53pt7b" },
  { &UbuntuSansMono_SemiBold54pt7b, 54, "UbuntuSansMono_SemiBold54pt7b" },
  { &UbuntuSansMono_SemiBold55pt7b, 55, "UbuntuSansMono_SemiBold55pt7b" },
  { &UbuntuSansMono_SemiBold56pt7b, 56, "UbuntuSansMono_SemiBold56pt7b" },
  { &UbuntuSansMono_SemiBold57pt7b, 57, "UbuntuSansMono_SemiBold57pt7b" },
  { &UbuntuSansMono_SemiBold58pt7b, 58, "UbuntuSansMono_SemiBold58pt7b" },
  { &UbuntuSansMono_SemiBold59pt7b, 59, "UbuntuSansMono_SemiBold59pt7b" },
  { &UbuntuSansMono_SemiBold60pt7b, 60, "UbuntuSansMono_SemiBold60pt7b" },
  { &UbuntuSansMono_SemiBold61pt7b, 61, "UbuntuSansMono_SemiBold61pt7b" },
  { &UbuntuSansMono_SemiBold62pt7b, 62, "UbuntuSansMono_SemiBold62pt7b" },
  { &UbuntuSansMono_SemiBold63pt7b, 63, "UbuntuSansMono_SemiBold63pt7b" },
  { &UbuntuSansMono_SemiBold64pt7b, 64, "UbuntuSansMono_SemiBold64pt7b" },
  { &UbuntuSansMono_SemiBold65pt7b, 65, "UbuntuSansMono_SemiBold65pt7b" },
  { &UbuntuSansMono_SemiBold66pt7b, 66, "UbuntuSansMono_SemiBold66pt7b" },
  { &UbuntuSansMono_SemiBold67pt7b, 67, "UbuntuSansMono_SemiBold67pt7b" },
  { &UbuntuSansMono_SemiBold68pt7b, 68, "UbuntuSansMono_SemiBold68pt7b" },
  { &UbuntuSansMono_SemiBold69pt7b, 69, "UbuntuSansMono_SemiBold69pt7b" },
  { &UbuntuSansMono_SemiBold70pt7b, 70, "UbuntuSansMono_SemiBold70pt7b" },
  { &UbuntuSansMono_SemiBold71pt7b, 71, "UbuntuSansMono_SemiBold71pt7b" },
  { &UbuntuSansMono_SemiBold72pt7b, 72, "UbuntuSansMono_SemiBold72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
