#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &IBMPlexMono_ExtraLightItalic6pt7b, 6, "IBMPlexMono_ExtraLightItalic6pt7b" },
  { &IBMPlexMono_ExtraLightItalic7pt7b, 7, "IBMPlexMono_ExtraLightItalic7pt7b" },
  { &IBMPlexMono_ExtraLightItalic8pt7b, 8, "IBMPlexMono_ExtraLightItalic8pt7b" },
  { &IBMPlexMono_ExtraLightItalic9pt7b, 9, "IBMPlexMono_ExtraLightItalic9pt7b" },
  { &IBMPlexMono_ExtraLightItalic10pt7b, 10, "IBMPlexMono_ExtraLightItalic10pt7b" },
  { &IBMPlexMono_ExtraLightItalic11pt7b, 11, "IBMPlexMono_ExtraLightItalic11pt7b" },
  { &IBMPlexMono_ExtraLightItalic12pt7b, 12, "IBMPlexMono_ExtraLightItalic12pt7b" },
  { &IBMPlexMono_ExtraLightItalic13pt7b, 13, "IBMPlexMono_ExtraLightItalic13pt7b" },
  { &IBMPlexMono_ExtraLightItalic14pt7b, 14, "IBMPlexMono_ExtraLightItalic14pt7b" },
  { &IBMPlexMono_ExtraLightItalic15pt7b, 15, "IBMPlexMono_ExtraLightItalic15pt7b" },
  { &IBMPlexMono_ExtraLightItalic16pt7b, 16, "IBMPlexMono_ExtraLightItalic16pt7b" },
  { &IBMPlexMono_ExtraLightItalic17pt7b, 17, "IBMPlexMono_ExtraLightItalic17pt7b" },
  { &IBMPlexMono_ExtraLightItalic18pt7b, 18, "IBMPlexMono_ExtraLightItalic18pt7b" },
  { &IBMPlexMono_ExtraLightItalic19pt7b, 19, "IBMPlexMono_ExtraLightItalic19pt7b" },
  { &IBMPlexMono_ExtraLightItalic20pt7b, 20, "IBMPlexMono_ExtraLightItalic20pt7b" },
  { &IBMPlexMono_ExtraLightItalic21pt7b, 21, "IBMPlexMono_ExtraLightItalic21pt7b" },
  { &IBMPlexMono_ExtraLightItalic22pt7b, 22, "IBMPlexMono_ExtraLightItalic22pt7b" },
  { &IBMPlexMono_ExtraLightItalic23pt7b, 23, "IBMPlexMono_ExtraLightItalic23pt7b" },
  { &IBMPlexMono_ExtraLightItalic24pt7b, 24, "IBMPlexMono_ExtraLightItalic24pt7b" },
  { &IBMPlexMono_ExtraLightItalic25pt7b, 25, "IBMPlexMono_ExtraLightItalic25pt7b" },
  { &IBMPlexMono_ExtraLightItalic26pt7b, 26, "IBMPlexMono_ExtraLightItalic26pt7b" },
  { &IBMPlexMono_ExtraLightItalic27pt7b, 27, "IBMPlexMono_ExtraLightItalic27pt7b" },
  { &IBMPlexMono_ExtraLightItalic28pt7b, 28, "IBMPlexMono_ExtraLightItalic28pt7b" },
  { &IBMPlexMono_ExtraLightItalic29pt7b, 29, "IBMPlexMono_ExtraLightItalic29pt7b" },
  { &IBMPlexMono_ExtraLightItalic30pt7b, 30, "IBMPlexMono_ExtraLightItalic30pt7b" },
  { &IBMPlexMono_ExtraLightItalic31pt7b, 31, "IBMPlexMono_ExtraLightItalic31pt7b" },
  { &IBMPlexMono_ExtraLightItalic32pt7b, 32, "IBMPlexMono_ExtraLightItalic32pt7b" },
  { &IBMPlexMono_ExtraLightItalic33pt7b, 33, "IBMPlexMono_ExtraLightItalic33pt7b" },
  { &IBMPlexMono_ExtraLightItalic34pt7b, 34, "IBMPlexMono_ExtraLightItalic34pt7b" },
  { &IBMPlexMono_ExtraLightItalic35pt7b, 35, "IBMPlexMono_ExtraLightItalic35pt7b" },
  { &IBMPlexMono_ExtraLightItalic36pt7b, 36, "IBMPlexMono_ExtraLightItalic36pt7b" },
  { &IBMPlexMono_ExtraLightItalic37pt7b, 37, "IBMPlexMono_ExtraLightItalic37pt7b" },
  { &IBMPlexMono_ExtraLightItalic38pt7b, 38, "IBMPlexMono_ExtraLightItalic38pt7b" },
  { &IBMPlexMono_ExtraLightItalic39pt7b, 39, "IBMPlexMono_ExtraLightItalic39pt7b" },
  { &IBMPlexMono_ExtraLightItalic40pt7b, 40, "IBMPlexMono_ExtraLightItalic40pt7b" },
  { &IBMPlexMono_ExtraLightItalic41pt7b, 41, "IBMPlexMono_ExtraLightItalic41pt7b" },
  { &IBMPlexMono_ExtraLightItalic42pt7b, 42, "IBMPlexMono_ExtraLightItalic42pt7b" },
  { &IBMPlexMono_ExtraLightItalic43pt7b, 43, "IBMPlexMono_ExtraLightItalic43pt7b" },
  { &IBMPlexMono_ExtraLightItalic44pt7b, 44, "IBMPlexMono_ExtraLightItalic44pt7b" },
  { &IBMPlexMono_ExtraLightItalic45pt7b, 45, "IBMPlexMono_ExtraLightItalic45pt7b" },
  { &IBMPlexMono_ExtraLightItalic46pt7b, 46, "IBMPlexMono_ExtraLightItalic46pt7b" },
  { &IBMPlexMono_ExtraLightItalic47pt7b, 47, "IBMPlexMono_ExtraLightItalic47pt7b" },
  { &IBMPlexMono_ExtraLightItalic48pt7b, 48, "IBMPlexMono_ExtraLightItalic48pt7b" },
  { &IBMPlexMono_ExtraLightItalic49pt7b, 49, "IBMPlexMono_ExtraLightItalic49pt7b" },
  { &IBMPlexMono_ExtraLightItalic50pt7b, 50, "IBMPlexMono_ExtraLightItalic50pt7b" },
  { &IBMPlexMono_ExtraLightItalic51pt7b, 51, "IBMPlexMono_ExtraLightItalic51pt7b" },
  { &IBMPlexMono_ExtraLightItalic52pt7b, 52, "IBMPlexMono_ExtraLightItalic52pt7b" },
  { &IBMPlexMono_ExtraLightItalic53pt7b, 53, "IBMPlexMono_ExtraLightItalic53pt7b" },
  { &IBMPlexMono_ExtraLightItalic54pt7b, 54, "IBMPlexMono_ExtraLightItalic54pt7b" },
  { &IBMPlexMono_ExtraLightItalic55pt7b, 55, "IBMPlexMono_ExtraLightItalic55pt7b" },
  { &IBMPlexMono_ExtraLightItalic56pt7b, 56, "IBMPlexMono_ExtraLightItalic56pt7b" },
  { &IBMPlexMono_ExtraLightItalic57pt7b, 57, "IBMPlexMono_ExtraLightItalic57pt7b" },
  { &IBMPlexMono_ExtraLightItalic58pt7b, 58, "IBMPlexMono_ExtraLightItalic58pt7b" },
  { &IBMPlexMono_ExtraLightItalic59pt7b, 59, "IBMPlexMono_ExtraLightItalic59pt7b" },
  { &IBMPlexMono_ExtraLightItalic60pt7b, 60, "IBMPlexMono_ExtraLightItalic60pt7b" },
  { &IBMPlexMono_ExtraLightItalic61pt7b, 61, "IBMPlexMono_ExtraLightItalic61pt7b" },
  { &IBMPlexMono_ExtraLightItalic62pt7b, 62, "IBMPlexMono_ExtraLightItalic62pt7b" },
  { &IBMPlexMono_ExtraLightItalic63pt7b, 63, "IBMPlexMono_ExtraLightItalic63pt7b" },
  { &IBMPlexMono_ExtraLightItalic64pt7b, 64, "IBMPlexMono_ExtraLightItalic64pt7b" },
  { &IBMPlexMono_ExtraLightItalic65pt7b, 65, "IBMPlexMono_ExtraLightItalic65pt7b" },
  { &IBMPlexMono_ExtraLightItalic66pt7b, 66, "IBMPlexMono_ExtraLightItalic66pt7b" },
  { &IBMPlexMono_ExtraLightItalic67pt7b, 67, "IBMPlexMono_ExtraLightItalic67pt7b" },
  { &IBMPlexMono_ExtraLightItalic68pt7b, 68, "IBMPlexMono_ExtraLightItalic68pt7b" },
  { &IBMPlexMono_ExtraLightItalic69pt7b, 69, "IBMPlexMono_ExtraLightItalic69pt7b" },
  { &IBMPlexMono_ExtraLightItalic70pt7b, 70, "IBMPlexMono_ExtraLightItalic70pt7b" },
  { &IBMPlexMono_ExtraLightItalic71pt7b, 71, "IBMPlexMono_ExtraLightItalic71pt7b" },
  { &IBMPlexMono_ExtraLightItalic72pt7b, 72, "IBMPlexMono_ExtraLightItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
