#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_SemiCondensed_SemiBold6pt7b, 6, "NotoSans_SemiCondensed_SemiBold6pt7b" },
  { &NotoSans_SemiCondensed_SemiBold7pt7b, 7, "NotoSans_SemiCondensed_SemiBold7pt7b" },
  { &NotoSans_SemiCondensed_SemiBold8pt7b, 8, "NotoSans_SemiCondensed_SemiBold8pt7b" },
  { &NotoSans_SemiCondensed_SemiBold9pt7b, 9, "NotoSans_SemiCondensed_SemiBold9pt7b" },
  { &NotoSans_SemiCondensed_SemiBold10pt7b, 10, "NotoSans_SemiCondensed_SemiBold10pt7b" },
  { &NotoSans_SemiCondensed_SemiBold11pt7b, 11, "NotoSans_SemiCondensed_SemiBold11pt7b" },
  { &NotoSans_SemiCondensed_SemiBold12pt7b, 12, "NotoSans_SemiCondensed_SemiBold12pt7b" },
  { &NotoSans_SemiCondensed_SemiBold13pt7b, 13, "NotoSans_SemiCondensed_SemiBold13pt7b" },
  { &NotoSans_SemiCondensed_SemiBold14pt7b, 14, "NotoSans_SemiCondensed_SemiBold14pt7b" },
  { &NotoSans_SemiCondensed_SemiBold15pt7b, 15, "NotoSans_SemiCondensed_SemiBold15pt7b" },
  { &NotoSans_SemiCondensed_SemiBold16pt7b, 16, "NotoSans_SemiCondensed_SemiBold16pt7b" },
  { &NotoSans_SemiCondensed_SemiBold17pt7b, 17, "NotoSans_SemiCondensed_SemiBold17pt7b" },
  { &NotoSans_SemiCondensed_SemiBold18pt7b, 18, "NotoSans_SemiCondensed_SemiBold18pt7b" },
  { &NotoSans_SemiCondensed_SemiBold19pt7b, 19, "NotoSans_SemiCondensed_SemiBold19pt7b" },
  { &NotoSans_SemiCondensed_SemiBold20pt7b, 20, "NotoSans_SemiCondensed_SemiBold20pt7b" },
  { &NotoSans_SemiCondensed_SemiBold21pt7b, 21, "NotoSans_SemiCondensed_SemiBold21pt7b" },
  { &NotoSans_SemiCondensed_SemiBold22pt7b, 22, "NotoSans_SemiCondensed_SemiBold22pt7b" },
  { &NotoSans_SemiCondensed_SemiBold23pt7b, 23, "NotoSans_SemiCondensed_SemiBold23pt7b" },
  { &NotoSans_SemiCondensed_SemiBold24pt7b, 24, "NotoSans_SemiCondensed_SemiBold24pt7b" },
  { &NotoSans_SemiCondensed_SemiBold25pt7b, 25, "NotoSans_SemiCondensed_SemiBold25pt7b" },
  { &NotoSans_SemiCondensed_SemiBold26pt7b, 26, "NotoSans_SemiCondensed_SemiBold26pt7b" },
  { &NotoSans_SemiCondensed_SemiBold27pt7b, 27, "NotoSans_SemiCondensed_SemiBold27pt7b" },
  { &NotoSans_SemiCondensed_SemiBold28pt7b, 28, "NotoSans_SemiCondensed_SemiBold28pt7b" },
  { &NotoSans_SemiCondensed_SemiBold29pt7b, 29, "NotoSans_SemiCondensed_SemiBold29pt7b" },
  { &NotoSans_SemiCondensed_SemiBold30pt7b, 30, "NotoSans_SemiCondensed_SemiBold30pt7b" },
  { &NotoSans_SemiCondensed_SemiBold31pt7b, 31, "NotoSans_SemiCondensed_SemiBold31pt7b" },
  { &NotoSans_SemiCondensed_SemiBold32pt7b, 32, "NotoSans_SemiCondensed_SemiBold32pt7b" },
  { &NotoSans_SemiCondensed_SemiBold33pt7b, 33, "NotoSans_SemiCondensed_SemiBold33pt7b" },
  { &NotoSans_SemiCondensed_SemiBold34pt7b, 34, "NotoSans_SemiCondensed_SemiBold34pt7b" },
  { &NotoSans_SemiCondensed_SemiBold35pt7b, 35, "NotoSans_SemiCondensed_SemiBold35pt7b" },
  { &NotoSans_SemiCondensed_SemiBold36pt7b, 36, "NotoSans_SemiCondensed_SemiBold36pt7b" },
  { &NotoSans_SemiCondensed_SemiBold37pt7b, 37, "NotoSans_SemiCondensed_SemiBold37pt7b" },
  { &NotoSans_SemiCondensed_SemiBold38pt7b, 38, "NotoSans_SemiCondensed_SemiBold38pt7b" },
  { &NotoSans_SemiCondensed_SemiBold39pt7b, 39, "NotoSans_SemiCondensed_SemiBold39pt7b" },
  { &NotoSans_SemiCondensed_SemiBold40pt7b, 40, "NotoSans_SemiCondensed_SemiBold40pt7b" },
  { &NotoSans_SemiCondensed_SemiBold41pt7b, 41, "NotoSans_SemiCondensed_SemiBold41pt7b" },
  { &NotoSans_SemiCondensed_SemiBold42pt7b, 42, "NotoSans_SemiCondensed_SemiBold42pt7b" },
  { &NotoSans_SemiCondensed_SemiBold43pt7b, 43, "NotoSans_SemiCondensed_SemiBold43pt7b" },
  { &NotoSans_SemiCondensed_SemiBold44pt7b, 44, "NotoSans_SemiCondensed_SemiBold44pt7b" },
  { &NotoSans_SemiCondensed_SemiBold45pt7b, 45, "NotoSans_SemiCondensed_SemiBold45pt7b" },
  { &NotoSans_SemiCondensed_SemiBold46pt7b, 46, "NotoSans_SemiCondensed_SemiBold46pt7b" },
  { &NotoSans_SemiCondensed_SemiBold47pt7b, 47, "NotoSans_SemiCondensed_SemiBold47pt7b" },
  { &NotoSans_SemiCondensed_SemiBold48pt7b, 48, "NotoSans_SemiCondensed_SemiBold48pt7b" },
  { &NotoSans_SemiCondensed_SemiBold49pt7b, 49, "NotoSans_SemiCondensed_SemiBold49pt7b" },
  { &NotoSans_SemiCondensed_SemiBold50pt7b, 50, "NotoSans_SemiCondensed_SemiBold50pt7b" },
  { &NotoSans_SemiCondensed_SemiBold51pt7b, 51, "NotoSans_SemiCondensed_SemiBold51pt7b" },
  { &NotoSans_SemiCondensed_SemiBold52pt7b, 52, "NotoSans_SemiCondensed_SemiBold52pt7b" },
  { &NotoSans_SemiCondensed_SemiBold53pt7b, 53, "NotoSans_SemiCondensed_SemiBold53pt7b" },
  { &NotoSans_SemiCondensed_SemiBold54pt7b, 54, "NotoSans_SemiCondensed_SemiBold54pt7b" },
  { &NotoSans_SemiCondensed_SemiBold55pt7b, 55, "NotoSans_SemiCondensed_SemiBold55pt7b" },
  { &NotoSans_SemiCondensed_SemiBold56pt7b, 56, "NotoSans_SemiCondensed_SemiBold56pt7b" },
  { &NotoSans_SemiCondensed_SemiBold57pt7b, 57, "NotoSans_SemiCondensed_SemiBold57pt7b" },
  { &NotoSans_SemiCondensed_SemiBold58pt7b, 58, "NotoSans_SemiCondensed_SemiBold58pt7b" },
  { &NotoSans_SemiCondensed_SemiBold59pt7b, 59, "NotoSans_SemiCondensed_SemiBold59pt7b" },
  { &NotoSans_SemiCondensed_SemiBold60pt7b, 60, "NotoSans_SemiCondensed_SemiBold60pt7b" },
  { &NotoSans_SemiCondensed_SemiBold61pt7b, 61, "NotoSans_SemiCondensed_SemiBold61pt7b" },
  { &NotoSans_SemiCondensed_SemiBold62pt7b, 62, "NotoSans_SemiCondensed_SemiBold62pt7b" },
  { &NotoSans_SemiCondensed_SemiBold63pt7b, 63, "NotoSans_SemiCondensed_SemiBold63pt7b" },
  { &NotoSans_SemiCondensed_SemiBold64pt7b, 64, "NotoSans_SemiCondensed_SemiBold64pt7b" },
  { &NotoSans_SemiCondensed_SemiBold65pt7b, 65, "NotoSans_SemiCondensed_SemiBold65pt7b" },
  { &NotoSans_SemiCondensed_SemiBold66pt7b, 66, "NotoSans_SemiCondensed_SemiBold66pt7b" },
  { &NotoSans_SemiCondensed_SemiBold67pt7b, 67, "NotoSans_SemiCondensed_SemiBold67pt7b" },
  { &NotoSans_SemiCondensed_SemiBold68pt7b, 68, "NotoSans_SemiCondensed_SemiBold68pt7b" },
  { &NotoSans_SemiCondensed_SemiBold69pt7b, 69, "NotoSans_SemiCondensed_SemiBold69pt7b" },
  { &NotoSans_SemiCondensed_SemiBold70pt7b, 70, "NotoSans_SemiCondensed_SemiBold70pt7b" },
  { &NotoSans_SemiCondensed_SemiBold71pt7b, 71, "NotoSans_SemiCondensed_SemiBold71pt7b" },
  { &NotoSans_SemiCondensed_SemiBold72pt7b, 72, "NotoSans_SemiCondensed_SemiBold72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
