#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_Condensed_SemiBold6pt7b, 6, "NotoSans_Condensed_SemiBold6pt7b" },
  { &NotoSans_Condensed_SemiBold7pt7b, 7, "NotoSans_Condensed_SemiBold7pt7b" },
  { &NotoSans_Condensed_SemiBold8pt7b, 8, "NotoSans_Condensed_SemiBold8pt7b" },
  { &NotoSans_Condensed_SemiBold9pt7b, 9, "NotoSans_Condensed_SemiBold9pt7b" },
  { &NotoSans_Condensed_SemiBold10pt7b, 10, "NotoSans_Condensed_SemiBold10pt7b" },
  { &NotoSans_Condensed_SemiBold11pt7b, 11, "NotoSans_Condensed_SemiBold11pt7b" },
  { &NotoSans_Condensed_SemiBold12pt7b, 12, "NotoSans_Condensed_SemiBold12pt7b" },
  { &NotoSans_Condensed_SemiBold13pt7b, 13, "NotoSans_Condensed_SemiBold13pt7b" },
  { &NotoSans_Condensed_SemiBold14pt7b, 14, "NotoSans_Condensed_SemiBold14pt7b" },
  { &NotoSans_Condensed_SemiBold15pt7b, 15, "NotoSans_Condensed_SemiBold15pt7b" },
  { &NotoSans_Condensed_SemiBold16pt7b, 16, "NotoSans_Condensed_SemiBold16pt7b" },
  { &NotoSans_Condensed_SemiBold17pt7b, 17, "NotoSans_Condensed_SemiBold17pt7b" },
  { &NotoSans_Condensed_SemiBold18pt7b, 18, "NotoSans_Condensed_SemiBold18pt7b" },
  { &NotoSans_Condensed_SemiBold19pt7b, 19, "NotoSans_Condensed_SemiBold19pt7b" },
  { &NotoSans_Condensed_SemiBold20pt7b, 20, "NotoSans_Condensed_SemiBold20pt7b" },
  { &NotoSans_Condensed_SemiBold21pt7b, 21, "NotoSans_Condensed_SemiBold21pt7b" },
  { &NotoSans_Condensed_SemiBold22pt7b, 22, "NotoSans_Condensed_SemiBold22pt7b" },
  { &NotoSans_Condensed_SemiBold23pt7b, 23, "NotoSans_Condensed_SemiBold23pt7b" },
  { &NotoSans_Condensed_SemiBold24pt7b, 24, "NotoSans_Condensed_SemiBold24pt7b" },
  { &NotoSans_Condensed_SemiBold25pt7b, 25, "NotoSans_Condensed_SemiBold25pt7b" },
  { &NotoSans_Condensed_SemiBold26pt7b, 26, "NotoSans_Condensed_SemiBold26pt7b" },
  { &NotoSans_Condensed_SemiBold27pt7b, 27, "NotoSans_Condensed_SemiBold27pt7b" },
  { &NotoSans_Condensed_SemiBold28pt7b, 28, "NotoSans_Condensed_SemiBold28pt7b" },
  { &NotoSans_Condensed_SemiBold29pt7b, 29, "NotoSans_Condensed_SemiBold29pt7b" },
  { &NotoSans_Condensed_SemiBold30pt7b, 30, "NotoSans_Condensed_SemiBold30pt7b" },
  { &NotoSans_Condensed_SemiBold31pt7b, 31, "NotoSans_Condensed_SemiBold31pt7b" },
  { &NotoSans_Condensed_SemiBold32pt7b, 32, "NotoSans_Condensed_SemiBold32pt7b" },
  { &NotoSans_Condensed_SemiBold33pt7b, 33, "NotoSans_Condensed_SemiBold33pt7b" },
  { &NotoSans_Condensed_SemiBold34pt7b, 34, "NotoSans_Condensed_SemiBold34pt7b" },
  { &NotoSans_Condensed_SemiBold35pt7b, 35, "NotoSans_Condensed_SemiBold35pt7b" },
  { &NotoSans_Condensed_SemiBold36pt7b, 36, "NotoSans_Condensed_SemiBold36pt7b" },
  { &NotoSans_Condensed_SemiBold37pt7b, 37, "NotoSans_Condensed_SemiBold37pt7b" },
  { &NotoSans_Condensed_SemiBold38pt7b, 38, "NotoSans_Condensed_SemiBold38pt7b" },
  { &NotoSans_Condensed_SemiBold39pt7b, 39, "NotoSans_Condensed_SemiBold39pt7b" },
  { &NotoSans_Condensed_SemiBold40pt7b, 40, "NotoSans_Condensed_SemiBold40pt7b" },
  { &NotoSans_Condensed_SemiBold41pt7b, 41, "NotoSans_Condensed_SemiBold41pt7b" },
  { &NotoSans_Condensed_SemiBold42pt7b, 42, "NotoSans_Condensed_SemiBold42pt7b" },
  { &NotoSans_Condensed_SemiBold43pt7b, 43, "NotoSans_Condensed_SemiBold43pt7b" },
  { &NotoSans_Condensed_SemiBold44pt7b, 44, "NotoSans_Condensed_SemiBold44pt7b" },
  { &NotoSans_Condensed_SemiBold45pt7b, 45, "NotoSans_Condensed_SemiBold45pt7b" },
  { &NotoSans_Condensed_SemiBold46pt7b, 46, "NotoSans_Condensed_SemiBold46pt7b" },
  { &NotoSans_Condensed_SemiBold47pt7b, 47, "NotoSans_Condensed_SemiBold47pt7b" },
  { &NotoSans_Condensed_SemiBold48pt7b, 48, "NotoSans_Condensed_SemiBold48pt7b" },
  { &NotoSans_Condensed_SemiBold49pt7b, 49, "NotoSans_Condensed_SemiBold49pt7b" },
  { &NotoSans_Condensed_SemiBold50pt7b, 50, "NotoSans_Condensed_SemiBold50pt7b" },
  { &NotoSans_Condensed_SemiBold51pt7b, 51, "NotoSans_Condensed_SemiBold51pt7b" },
  { &NotoSans_Condensed_SemiBold52pt7b, 52, "NotoSans_Condensed_SemiBold52pt7b" },
  { &NotoSans_Condensed_SemiBold53pt7b, 53, "NotoSans_Condensed_SemiBold53pt7b" },
  { &NotoSans_Condensed_SemiBold54pt7b, 54, "NotoSans_Condensed_SemiBold54pt7b" },
  { &NotoSans_Condensed_SemiBold55pt7b, 55, "NotoSans_Condensed_SemiBold55pt7b" },
  { &NotoSans_Condensed_SemiBold56pt7b, 56, "NotoSans_Condensed_SemiBold56pt7b" },
  { &NotoSans_Condensed_SemiBold57pt7b, 57, "NotoSans_Condensed_SemiBold57pt7b" },
  { &NotoSans_Condensed_SemiBold58pt7b, 58, "NotoSans_Condensed_SemiBold58pt7b" },
  { &NotoSans_Condensed_SemiBold59pt7b, 59, "NotoSans_Condensed_SemiBold59pt7b" },
  { &NotoSans_Condensed_SemiBold60pt7b, 60, "NotoSans_Condensed_SemiBold60pt7b" },
  { &NotoSans_Condensed_SemiBold61pt7b, 61, "NotoSans_Condensed_SemiBold61pt7b" },
  { &NotoSans_Condensed_SemiBold62pt7b, 62, "NotoSans_Condensed_SemiBold62pt7b" },
  { &NotoSans_Condensed_SemiBold63pt7b, 63, "NotoSans_Condensed_SemiBold63pt7b" },
  { &NotoSans_Condensed_SemiBold64pt7b, 64, "NotoSans_Condensed_SemiBold64pt7b" },
  { &NotoSans_Condensed_SemiBold65pt7b, 65, "NotoSans_Condensed_SemiBold65pt7b" },
  { &NotoSans_Condensed_SemiBold66pt7b, 66, "NotoSans_Condensed_SemiBold66pt7b" },
  { &NotoSans_Condensed_SemiBold67pt7b, 67, "NotoSans_Condensed_SemiBold67pt7b" },
  { &NotoSans_Condensed_SemiBold68pt7b, 68, "NotoSans_Condensed_SemiBold68pt7b" },
  { &NotoSans_Condensed_SemiBold69pt7b, 69, "NotoSans_Condensed_SemiBold69pt7b" },
  { &NotoSans_Condensed_SemiBold70pt7b, 70, "NotoSans_Condensed_SemiBold70pt7b" },
  { &NotoSans_Condensed_SemiBold71pt7b, 71, "NotoSans_Condensed_SemiBold71pt7b" },
  { &NotoSans_Condensed_SemiBold72pt7b, 72, "NotoSans_Condensed_SemiBold72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
