#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &RobotoMono_ExtraLight6pt7b, 6, "RobotoMono_ExtraLight6pt7b" },
  { &RobotoMono_ExtraLight7pt7b, 7, "RobotoMono_ExtraLight7pt7b" },
  { &RobotoMono_ExtraLight8pt7b, 8, "RobotoMono_ExtraLight8pt7b" },
  { &RobotoMono_ExtraLight9pt7b, 9, "RobotoMono_ExtraLight9pt7b" },
  { &RobotoMono_ExtraLight10pt7b, 10, "RobotoMono_ExtraLight10pt7b" },
  { &RobotoMono_ExtraLight11pt7b, 11, "RobotoMono_ExtraLight11pt7b" },
  { &RobotoMono_ExtraLight12pt7b, 12, "RobotoMono_ExtraLight12pt7b" },
  { &RobotoMono_ExtraLight13pt7b, 13, "RobotoMono_ExtraLight13pt7b" },
  { &RobotoMono_ExtraLight14pt7b, 14, "RobotoMono_ExtraLight14pt7b" },
  { &RobotoMono_ExtraLight15pt7b, 15, "RobotoMono_ExtraLight15pt7b" },
  { &RobotoMono_ExtraLight16pt7b, 16, "RobotoMono_ExtraLight16pt7b" },
  { &RobotoMono_ExtraLight17pt7b, 17, "RobotoMono_ExtraLight17pt7b" },
  { &RobotoMono_ExtraLight18pt7b, 18, "RobotoMono_ExtraLight18pt7b" },
  { &RobotoMono_ExtraLight19pt7b, 19, "RobotoMono_ExtraLight19pt7b" },
  { &RobotoMono_ExtraLight20pt7b, 20, "RobotoMono_ExtraLight20pt7b" },
  { &RobotoMono_ExtraLight21pt7b, 21, "RobotoMono_ExtraLight21pt7b" },
  { &RobotoMono_ExtraLight22pt7b, 22, "RobotoMono_ExtraLight22pt7b" },
  { &RobotoMono_ExtraLight23pt7b, 23, "RobotoMono_ExtraLight23pt7b" },
  { &RobotoMono_ExtraLight24pt7b, 24, "RobotoMono_ExtraLight24pt7b" },
  { &RobotoMono_ExtraLight25pt7b, 25, "RobotoMono_ExtraLight25pt7b" },
  { &RobotoMono_ExtraLight26pt7b, 26, "RobotoMono_ExtraLight26pt7b" },
  { &RobotoMono_ExtraLight27pt7b, 27, "RobotoMono_ExtraLight27pt7b" },
  { &RobotoMono_ExtraLight28pt7b, 28, "RobotoMono_ExtraLight28pt7b" },
  { &RobotoMono_ExtraLight29pt7b, 29, "RobotoMono_ExtraLight29pt7b" },
  { &RobotoMono_ExtraLight30pt7b, 30, "RobotoMono_ExtraLight30pt7b" },
  { &RobotoMono_ExtraLight31pt7b, 31, "RobotoMono_ExtraLight31pt7b" },
  { &RobotoMono_ExtraLight32pt7b, 32, "RobotoMono_ExtraLight32pt7b" },
  { &RobotoMono_ExtraLight33pt7b, 33, "RobotoMono_ExtraLight33pt7b" },
  { &RobotoMono_ExtraLight34pt7b, 34, "RobotoMono_ExtraLight34pt7b" },
  { &RobotoMono_ExtraLight35pt7b, 35, "RobotoMono_ExtraLight35pt7b" },
  { &RobotoMono_ExtraLight36pt7b, 36, "RobotoMono_ExtraLight36pt7b" },
  { &RobotoMono_ExtraLight37pt7b, 37, "RobotoMono_ExtraLight37pt7b" },
  { &RobotoMono_ExtraLight38pt7b, 38, "RobotoMono_ExtraLight38pt7b" },
  { &RobotoMono_ExtraLight39pt7b, 39, "RobotoMono_ExtraLight39pt7b" },
  { &RobotoMono_ExtraLight40pt7b, 40, "RobotoMono_ExtraLight40pt7b" },
  { &RobotoMono_ExtraLight41pt7b, 41, "RobotoMono_ExtraLight41pt7b" },
  { &RobotoMono_ExtraLight42pt7b, 42, "RobotoMono_ExtraLight42pt7b" },
  { &RobotoMono_ExtraLight43pt7b, 43, "RobotoMono_ExtraLight43pt7b" },
  { &RobotoMono_ExtraLight44pt7b, 44, "RobotoMono_ExtraLight44pt7b" },
  { &RobotoMono_ExtraLight45pt7b, 45, "RobotoMono_ExtraLight45pt7b" },
  { &RobotoMono_ExtraLight46pt7b, 46, "RobotoMono_ExtraLight46pt7b" },
  { &RobotoMono_ExtraLight47pt7b, 47, "RobotoMono_ExtraLight47pt7b" },
  { &RobotoMono_ExtraLight48pt7b, 48, "RobotoMono_ExtraLight48pt7b" },
  { &RobotoMono_ExtraLight49pt7b, 49, "RobotoMono_ExtraLight49pt7b" },
  { &RobotoMono_ExtraLight50pt7b, 50, "RobotoMono_ExtraLight50pt7b" },
  { &RobotoMono_ExtraLight51pt7b, 51, "RobotoMono_ExtraLight51pt7b" },
  { &RobotoMono_ExtraLight52pt7b, 52, "RobotoMono_ExtraLight52pt7b" },
  { &RobotoMono_ExtraLight53pt7b, 53, "RobotoMono_ExtraLight53pt7b" },
  { &RobotoMono_ExtraLight54pt7b, 54, "RobotoMono_ExtraLight54pt7b" },
  { &RobotoMono_ExtraLight55pt7b, 55, "RobotoMono_ExtraLight55pt7b" },
  { &RobotoMono_ExtraLight56pt7b, 56, "RobotoMono_ExtraLight56pt7b" },
  { &RobotoMono_ExtraLight57pt7b, 57, "RobotoMono_ExtraLight57pt7b" },
  { &RobotoMono_ExtraLight58pt7b, 58, "RobotoMono_ExtraLight58pt7b" },
  { &RobotoMono_ExtraLight59pt7b, 59, "RobotoMono_ExtraLight59pt7b" },
  { &RobotoMono_ExtraLight60pt7b, 60, "RobotoMono_ExtraLight60pt7b" },
  { &RobotoMono_ExtraLight61pt7b, 61, "RobotoMono_ExtraLight61pt7b" },
  { &RobotoMono_ExtraLight62pt7b, 62, "RobotoMono_ExtraLight62pt7b" },
  { &RobotoMono_ExtraLight63pt7b, 63, "RobotoMono_ExtraLight63pt7b" },
  { &RobotoMono_ExtraLight64pt7b, 64, "RobotoMono_ExtraLight64pt7b" },
  { &RobotoMono_ExtraLight65pt7b, 65, "RobotoMono_ExtraLight65pt7b" },
  { &RobotoMono_ExtraLight66pt7b, 66, "RobotoMono_ExtraLight66pt7b" },
  { &RobotoMono_ExtraLight67pt7b, 67, "RobotoMono_ExtraLight67pt7b" },
  { &RobotoMono_ExtraLight68pt7b, 68, "RobotoMono_ExtraLight68pt7b" },
  { &RobotoMono_ExtraLight69pt7b, 69, "RobotoMono_ExtraLight69pt7b" },
  { &RobotoMono_ExtraLight70pt7b, 70, "RobotoMono_ExtraLight70pt7b" },
  { &RobotoMono_ExtraLight71pt7b, 71, "RobotoMono_ExtraLight71pt7b" },
  { &RobotoMono_ExtraLight72pt7b, 72, "RobotoMono_ExtraLight72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
