#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &UbuntuSansMono_Regular6pt7b, 6, "UbuntuSansMono_Regular6pt7b" },
  { &UbuntuSansMono_Regular7pt7b, 7, "UbuntuSansMono_Regular7pt7b" },
  { &UbuntuSansMono_Regular8pt7b, 8, "UbuntuSansMono_Regular8pt7b" },
  { &UbuntuSansMono_Regular9pt7b, 9, "UbuntuSansMono_Regular9pt7b" },
  { &UbuntuSansMono_Regular10pt7b, 10, "UbuntuSansMono_Regular10pt7b" },
  { &UbuntuSansMono_Regular11pt7b, 11, "UbuntuSansMono_Regular11pt7b" },
  { &UbuntuSansMono_Regular12pt7b, 12, "UbuntuSansMono_Regular12pt7b" },
  { &UbuntuSansMono_Regular13pt7b, 13, "UbuntuSansMono_Regular13pt7b" },
  { &UbuntuSansMono_Regular14pt7b, 14, "UbuntuSansMono_Regular14pt7b" },
  { &UbuntuSansMono_Regular15pt7b, 15, "UbuntuSansMono_Regular15pt7b" },
  { &UbuntuSansMono_Regular16pt7b, 16, "UbuntuSansMono_Regular16pt7b" },
  { &UbuntuSansMono_Regular17pt7b, 17, "UbuntuSansMono_Regular17pt7b" },
  { &UbuntuSansMono_Regular18pt7b, 18, "UbuntuSansMono_Regular18pt7b" },
  { &UbuntuSansMono_Regular19pt7b, 19, "UbuntuSansMono_Regular19pt7b" },
  { &UbuntuSansMono_Regular20pt7b, 20, "UbuntuSansMono_Regular20pt7b" },
  { &UbuntuSansMono_Regular21pt7b, 21, "UbuntuSansMono_Regular21pt7b" },
  { &UbuntuSansMono_Regular22pt7b, 22, "UbuntuSansMono_Regular22pt7b" },
  { &UbuntuSansMono_Regular23pt7b, 23, "UbuntuSansMono_Regular23pt7b" },
  { &UbuntuSansMono_Regular24pt7b, 24, "UbuntuSansMono_Regular24pt7b" },
  { &UbuntuSansMono_Regular25pt7b, 25, "UbuntuSansMono_Regular25pt7b" },
  { &UbuntuSansMono_Regular26pt7b, 26, "UbuntuSansMono_Regular26pt7b" },
  { &UbuntuSansMono_Regular27pt7b, 27, "UbuntuSansMono_Regular27pt7b" },
  { &UbuntuSansMono_Regular28pt7b, 28, "UbuntuSansMono_Regular28pt7b" },
  { &UbuntuSansMono_Regular29pt7b, 29, "UbuntuSansMono_Regular29pt7b" },
  { &UbuntuSansMono_Regular30pt7b, 30, "UbuntuSansMono_Regular30pt7b" },
  { &UbuntuSansMono_Regular31pt7b, 31, "UbuntuSansMono_Regular31pt7b" },
  { &UbuntuSansMono_Regular32pt7b, 32, "UbuntuSansMono_Regular32pt7b" },
  { &UbuntuSansMono_Regular33pt7b, 33, "UbuntuSansMono_Regular33pt7b" },
  { &UbuntuSansMono_Regular34pt7b, 34, "UbuntuSansMono_Regular34pt7b" },
  { &UbuntuSansMono_Regular35pt7b, 35, "UbuntuSansMono_Regular35pt7b" },
  { &UbuntuSansMono_Regular36pt7b, 36, "UbuntuSansMono_Regular36pt7b" },
  { &UbuntuSansMono_Regular37pt7b, 37, "UbuntuSansMono_Regular37pt7b" },
  { &UbuntuSansMono_Regular38pt7b, 38, "UbuntuSansMono_Regular38pt7b" },
  { &UbuntuSansMono_Regular39pt7b, 39, "UbuntuSansMono_Regular39pt7b" },
  { &UbuntuSansMono_Regular40pt7b, 40, "UbuntuSansMono_Regular40pt7b" },
  { &UbuntuSansMono_Regular41pt7b, 41, "UbuntuSansMono_Regular41pt7b" },
  { &UbuntuSansMono_Regular42pt7b, 42, "UbuntuSansMono_Regular42pt7b" },
  { &UbuntuSansMono_Regular43pt7b, 43, "UbuntuSansMono_Regular43pt7b" },
  { &UbuntuSansMono_Regular44pt7b, 44, "UbuntuSansMono_Regular44pt7b" },
  { &UbuntuSansMono_Regular45pt7b, 45, "UbuntuSansMono_Regular45pt7b" },
  { &UbuntuSansMono_Regular46pt7b, 46, "UbuntuSansMono_Regular46pt7b" },
  { &UbuntuSansMono_Regular47pt7b, 47, "UbuntuSansMono_Regular47pt7b" },
  { &UbuntuSansMono_Regular48pt7b, 48, "UbuntuSansMono_Regular48pt7b" },
  { &UbuntuSansMono_Regular49pt7b, 49, "UbuntuSansMono_Regular49pt7b" },
  { &UbuntuSansMono_Regular50pt7b, 50, "UbuntuSansMono_Regular50pt7b" },
  { &UbuntuSansMono_Regular51pt7b, 51, "UbuntuSansMono_Regular51pt7b" },
  { &UbuntuSansMono_Regular52pt7b, 52, "UbuntuSansMono_Regular52pt7b" },
  { &UbuntuSansMono_Regular53pt7b, 53, "UbuntuSansMono_Regular53pt7b" },
  { &UbuntuSansMono_Regular54pt7b, 54, "UbuntuSansMono_Regular54pt7b" },
  { &UbuntuSansMono_Regular55pt7b, 55, "UbuntuSansMono_Regular55pt7b" },
  { &UbuntuSansMono_Regular56pt7b, 56, "UbuntuSansMono_Regular56pt7b" },
  { &UbuntuSansMono_Regular57pt7b, 57, "UbuntuSansMono_Regular57pt7b" },
  { &UbuntuSansMono_Regular58pt7b, 58, "UbuntuSansMono_Regular58pt7b" },
  { &UbuntuSansMono_Regular59pt7b, 59, "UbuntuSansMono_Regular59pt7b" },
  { &UbuntuSansMono_Regular60pt7b, 60, "UbuntuSansMono_Regular60pt7b" },
  { &UbuntuSansMono_Regular61pt7b, 61, "UbuntuSansMono_Regular61pt7b" },
  { &UbuntuSansMono_Regular62pt7b, 62, "UbuntuSansMono_Regular62pt7b" },
  { &UbuntuSansMono_Regular63pt7b, 63, "UbuntuSansMono_Regular63pt7b" },
  { &UbuntuSansMono_Regular64pt7b, 64, "UbuntuSansMono_Regular64pt7b" },
  { &UbuntuSansMono_Regular65pt7b, 65, "UbuntuSansMono_Regular65pt7b" },
  { &UbuntuSansMono_Regular66pt7b, 66, "UbuntuSansMono_Regular66pt7b" },
  { &UbuntuSansMono_Regular67pt7b, 67, "UbuntuSansMono_Regular67pt7b" },
  { &UbuntuSansMono_Regular68pt7b, 68, "UbuntuSansMono_Regular68pt7b" },
  { &UbuntuSansMono_Regular69pt7b, 69, "UbuntuSansMono_Regular69pt7b" },
  { &UbuntuSansMono_Regular70pt7b, 70, "UbuntuSansMono_Regular70pt7b" },
  { &UbuntuSansMono_Regular71pt7b, 71, "UbuntuSansMono_Regular71pt7b" },
  { &UbuntuSansMono_Regular72pt7b, 72, "UbuntuSansMono_Regular72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
