#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_SemiCondensed_Thin6pt7b, 6, "NotoSans_SemiCondensed_Thin6pt7b" },
  { &NotoSans_SemiCondensed_Thin7pt7b, 7, "NotoSans_SemiCondensed_Thin7pt7b" },
  { &NotoSans_SemiCondensed_Thin8pt7b, 8, "NotoSans_SemiCondensed_Thin8pt7b" },
  { &NotoSans_SemiCondensed_Thin9pt7b, 9, "NotoSans_SemiCondensed_Thin9pt7b" },
  { &NotoSans_SemiCondensed_Thin10pt7b, 10, "NotoSans_SemiCondensed_Thin10pt7b" },
  { &NotoSans_SemiCondensed_Thin11pt7b, 11, "NotoSans_SemiCondensed_Thin11pt7b" },
  { &NotoSans_SemiCondensed_Thin12pt7b, 12, "NotoSans_SemiCondensed_Thin12pt7b" },
  { &NotoSans_SemiCondensed_Thin13pt7b, 13, "NotoSans_SemiCondensed_Thin13pt7b" },
  { &NotoSans_SemiCondensed_Thin14pt7b, 14, "NotoSans_SemiCondensed_Thin14pt7b" },
  { &NotoSans_SemiCondensed_Thin15pt7b, 15, "NotoSans_SemiCondensed_Thin15pt7b" },
  { &NotoSans_SemiCondensed_Thin16pt7b, 16, "NotoSans_SemiCondensed_Thin16pt7b" },
  { &NotoSans_SemiCondensed_Thin17pt7b, 17, "NotoSans_SemiCondensed_Thin17pt7b" },
  { &NotoSans_SemiCondensed_Thin18pt7b, 18, "NotoSans_SemiCondensed_Thin18pt7b" },
  { &NotoSans_SemiCondensed_Thin19pt7b, 19, "NotoSans_SemiCondensed_Thin19pt7b" },
  { &NotoSans_SemiCondensed_Thin20pt7b, 20, "NotoSans_SemiCondensed_Thin20pt7b" },
  { &NotoSans_SemiCondensed_Thin21pt7b, 21, "NotoSans_SemiCondensed_Thin21pt7b" },
  { &NotoSans_SemiCondensed_Thin22pt7b, 22, "NotoSans_SemiCondensed_Thin22pt7b" },
  { &NotoSans_SemiCondensed_Thin23pt7b, 23, "NotoSans_SemiCondensed_Thin23pt7b" },
  { &NotoSans_SemiCondensed_Thin24pt7b, 24, "NotoSans_SemiCondensed_Thin24pt7b" },
  { &NotoSans_SemiCondensed_Thin25pt7b, 25, "NotoSans_SemiCondensed_Thin25pt7b" },
  { &NotoSans_SemiCondensed_Thin26pt7b, 26, "NotoSans_SemiCondensed_Thin26pt7b" },
  { &NotoSans_SemiCondensed_Thin27pt7b, 27, "NotoSans_SemiCondensed_Thin27pt7b" },
  { &NotoSans_SemiCondensed_Thin28pt7b, 28, "NotoSans_SemiCondensed_Thin28pt7b" },
  { &NotoSans_SemiCondensed_Thin29pt7b, 29, "NotoSans_SemiCondensed_Thin29pt7b" },
  { &NotoSans_SemiCondensed_Thin30pt7b, 30, "NotoSans_SemiCondensed_Thin30pt7b" },
  { &NotoSans_SemiCondensed_Thin31pt7b, 31, "NotoSans_SemiCondensed_Thin31pt7b" },
  { &NotoSans_SemiCondensed_Thin32pt7b, 32, "NotoSans_SemiCondensed_Thin32pt7b" },
  { &NotoSans_SemiCondensed_Thin33pt7b, 33, "NotoSans_SemiCondensed_Thin33pt7b" },
  { &NotoSans_SemiCondensed_Thin34pt7b, 34, "NotoSans_SemiCondensed_Thin34pt7b" },
  { &NotoSans_SemiCondensed_Thin35pt7b, 35, "NotoSans_SemiCondensed_Thin35pt7b" },
  { &NotoSans_SemiCondensed_Thin36pt7b, 36, "NotoSans_SemiCondensed_Thin36pt7b" },
  { &NotoSans_SemiCondensed_Thin37pt7b, 37, "NotoSans_SemiCondensed_Thin37pt7b" },
  { &NotoSans_SemiCondensed_Thin38pt7b, 38, "NotoSans_SemiCondensed_Thin38pt7b" },
  { &NotoSans_SemiCondensed_Thin39pt7b, 39, "NotoSans_SemiCondensed_Thin39pt7b" },
  { &NotoSans_SemiCondensed_Thin40pt7b, 40, "NotoSans_SemiCondensed_Thin40pt7b" },
  { &NotoSans_SemiCondensed_Thin41pt7b, 41, "NotoSans_SemiCondensed_Thin41pt7b" },
  { &NotoSans_SemiCondensed_Thin42pt7b, 42, "NotoSans_SemiCondensed_Thin42pt7b" },
  { &NotoSans_SemiCondensed_Thin43pt7b, 43, "NotoSans_SemiCondensed_Thin43pt7b" },
  { &NotoSans_SemiCondensed_Thin44pt7b, 44, "NotoSans_SemiCondensed_Thin44pt7b" },
  { &NotoSans_SemiCondensed_Thin45pt7b, 45, "NotoSans_SemiCondensed_Thin45pt7b" },
  { &NotoSans_SemiCondensed_Thin46pt7b, 46, "NotoSans_SemiCondensed_Thin46pt7b" },
  { &NotoSans_SemiCondensed_Thin47pt7b, 47, "NotoSans_SemiCondensed_Thin47pt7b" },
  { &NotoSans_SemiCondensed_Thin48pt7b, 48, "NotoSans_SemiCondensed_Thin48pt7b" },
  { &NotoSans_SemiCondensed_Thin49pt7b, 49, "NotoSans_SemiCondensed_Thin49pt7b" },
  { &NotoSans_SemiCondensed_Thin50pt7b, 50, "NotoSans_SemiCondensed_Thin50pt7b" },
  { &NotoSans_SemiCondensed_Thin51pt7b, 51, "NotoSans_SemiCondensed_Thin51pt7b" },
  { &NotoSans_SemiCondensed_Thin52pt7b, 52, "NotoSans_SemiCondensed_Thin52pt7b" },
  { &NotoSans_SemiCondensed_Thin53pt7b, 53, "NotoSans_SemiCondensed_Thin53pt7b" },
  { &NotoSans_SemiCondensed_Thin54pt7b, 54, "NotoSans_SemiCondensed_Thin54pt7b" },
  { &NotoSans_SemiCondensed_Thin55pt7b, 55, "NotoSans_SemiCondensed_Thin55pt7b" },
  { &NotoSans_SemiCondensed_Thin56pt7b, 56, "NotoSans_SemiCondensed_Thin56pt7b" },
  { &NotoSans_SemiCondensed_Thin57pt7b, 57, "NotoSans_SemiCondensed_Thin57pt7b" },
  { &NotoSans_SemiCondensed_Thin58pt7b, 58, "NotoSans_SemiCondensed_Thin58pt7b" },
  { &NotoSans_SemiCondensed_Thin59pt7b, 59, "NotoSans_SemiCondensed_Thin59pt7b" },
  { &NotoSans_SemiCondensed_Thin60pt7b, 60, "NotoSans_SemiCondensed_Thin60pt7b" },
  { &NotoSans_SemiCondensed_Thin61pt7b, 61, "NotoSans_SemiCondensed_Thin61pt7b" },
  { &NotoSans_SemiCondensed_Thin62pt7b, 62, "NotoSans_SemiCondensed_Thin62pt7b" },
  { &NotoSans_SemiCondensed_Thin63pt7b, 63, "NotoSans_SemiCondensed_Thin63pt7b" },
  { &NotoSans_SemiCondensed_Thin64pt7b, 64, "NotoSans_SemiCondensed_Thin64pt7b" },
  { &NotoSans_SemiCondensed_Thin65pt7b, 65, "NotoSans_SemiCondensed_Thin65pt7b" },
  { &NotoSans_SemiCondensed_Thin66pt7b, 66, "NotoSans_SemiCondensed_Thin66pt7b" },
  { &NotoSans_SemiCondensed_Thin67pt7b, 67, "NotoSans_SemiCondensed_Thin67pt7b" },
  { &NotoSans_SemiCondensed_Thin68pt7b, 68, "NotoSans_SemiCondensed_Thin68pt7b" },
  { &NotoSans_SemiCondensed_Thin69pt7b, 69, "NotoSans_SemiCondensed_Thin69pt7b" },
  { &NotoSans_SemiCondensed_Thin70pt7b, 70, "NotoSans_SemiCondensed_Thin70pt7b" },
  { &NotoSans_SemiCondensed_Thin71pt7b, 71, "NotoSans_SemiCondensed_Thin71pt7b" },
  { &NotoSans_SemiCondensed_Thin72pt7b, 72, "NotoSans_SemiCondensed_Thin72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
