#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &LiberationMono_Italic6pt7b, 6, "LiberationMono_Italic6pt7b" },
  { &LiberationMono_Italic7pt7b, 7, "LiberationMono_Italic7pt7b" },
  { &LiberationMono_Italic8pt7b, 8, "LiberationMono_Italic8pt7b" },
  { &LiberationMono_Italic9pt7b, 9, "LiberationMono_Italic9pt7b" },
  { &LiberationMono_Italic10pt7b, 10, "LiberationMono_Italic10pt7b" },
  { &LiberationMono_Italic11pt7b, 11, "LiberationMono_Italic11pt7b" },
  { &LiberationMono_Italic12pt7b, 12, "LiberationMono_Italic12pt7b" },
  { &LiberationMono_Italic13pt7b, 13, "LiberationMono_Italic13pt7b" },
  { &LiberationMono_Italic14pt7b, 14, "LiberationMono_Italic14pt7b" },
  { &LiberationMono_Italic15pt7b, 15, "LiberationMono_Italic15pt7b" },
  { &LiberationMono_Italic16pt7b, 16, "LiberationMono_Italic16pt7b" },
  { &LiberationMono_Italic17pt7b, 17, "LiberationMono_Italic17pt7b" },
  { &LiberationMono_Italic18pt7b, 18, "LiberationMono_Italic18pt7b" },
  { &LiberationMono_Italic19pt7b, 19, "LiberationMono_Italic19pt7b" },
  { &LiberationMono_Italic20pt7b, 20, "LiberationMono_Italic20pt7b" },
  { &LiberationMono_Italic21pt7b, 21, "LiberationMono_Italic21pt7b" },
  { &LiberationMono_Italic22pt7b, 22, "LiberationMono_Italic22pt7b" },
  { &LiberationMono_Italic23pt7b, 23, "LiberationMono_Italic23pt7b" },
  { &LiberationMono_Italic24pt7b, 24, "LiberationMono_Italic24pt7b" },
  { &LiberationMono_Italic25pt7b, 25, "LiberationMono_Italic25pt7b" },
  { &LiberationMono_Italic26pt7b, 26, "LiberationMono_Italic26pt7b" },
  { &LiberationMono_Italic27pt7b, 27, "LiberationMono_Italic27pt7b" },
  { &LiberationMono_Italic28pt7b, 28, "LiberationMono_Italic28pt7b" },
  { &LiberationMono_Italic29pt7b, 29, "LiberationMono_Italic29pt7b" },
  { &LiberationMono_Italic30pt7b, 30, "LiberationMono_Italic30pt7b" },
  { &LiberationMono_Italic31pt7b, 31, "LiberationMono_Italic31pt7b" },
  { &LiberationMono_Italic32pt7b, 32, "LiberationMono_Italic32pt7b" },
  { &LiberationMono_Italic33pt7b, 33, "LiberationMono_Italic33pt7b" },
  { &LiberationMono_Italic34pt7b, 34, "LiberationMono_Italic34pt7b" },
  { &LiberationMono_Italic35pt7b, 35, "LiberationMono_Italic35pt7b" },
  { &LiberationMono_Italic36pt7b, 36, "LiberationMono_Italic36pt7b" },
  { &LiberationMono_Italic37pt7b, 37, "LiberationMono_Italic37pt7b" },
  { &LiberationMono_Italic38pt7b, 38, "LiberationMono_Italic38pt7b" },
  { &LiberationMono_Italic39pt7b, 39, "LiberationMono_Italic39pt7b" },
  { &LiberationMono_Italic40pt7b, 40, "LiberationMono_Italic40pt7b" },
  { &LiberationMono_Italic41pt7b, 41, "LiberationMono_Italic41pt7b" },
  { &LiberationMono_Italic42pt7b, 42, "LiberationMono_Italic42pt7b" },
  { &LiberationMono_Italic43pt7b, 43, "LiberationMono_Italic43pt7b" },
  { &LiberationMono_Italic44pt7b, 44, "LiberationMono_Italic44pt7b" },
  { &LiberationMono_Italic45pt7b, 45, "LiberationMono_Italic45pt7b" },
  { &LiberationMono_Italic46pt7b, 46, "LiberationMono_Italic46pt7b" },
  { &LiberationMono_Italic47pt7b, 47, "LiberationMono_Italic47pt7b" },
  { &LiberationMono_Italic48pt7b, 48, "LiberationMono_Italic48pt7b" },
  { &LiberationMono_Italic49pt7b, 49, "LiberationMono_Italic49pt7b" },
  { &LiberationMono_Italic50pt7b, 50, "LiberationMono_Italic50pt7b" },
  { &LiberationMono_Italic51pt7b, 51, "LiberationMono_Italic51pt7b" },
  { &LiberationMono_Italic52pt7b, 52, "LiberationMono_Italic52pt7b" },
  { &LiberationMono_Italic53pt7b, 53, "LiberationMono_Italic53pt7b" },
  { &LiberationMono_Italic54pt7b, 54, "LiberationMono_Italic54pt7b" },
  { &LiberationMono_Italic55pt7b, 55, "LiberationMono_Italic55pt7b" },
  { &LiberationMono_Italic56pt7b, 56, "LiberationMono_Italic56pt7b" },
  { &LiberationMono_Italic57pt7b, 57, "LiberationMono_Italic57pt7b" },
  { &LiberationMono_Italic58pt7b, 58, "LiberationMono_Italic58pt7b" },
  { &LiberationMono_Italic59pt7b, 59, "LiberationMono_Italic59pt7b" },
  { &LiberationMono_Italic60pt7b, 60, "LiberationMono_Italic60pt7b" },
  { &LiberationMono_Italic61pt7b, 61, "LiberationMono_Italic61pt7b" },
  { &LiberationMono_Italic62pt7b, 62, "LiberationMono_Italic62pt7b" },
  { &LiberationMono_Italic63pt7b, 63, "LiberationMono_Italic63pt7b" },
  { &LiberationMono_Italic64pt7b, 64, "LiberationMono_Italic64pt7b" },
  { &LiberationMono_Italic65pt7b, 65, "LiberationMono_Italic65pt7b" },
  { &LiberationMono_Italic66pt7b, 66, "LiberationMono_Italic66pt7b" },
  { &LiberationMono_Italic67pt7b, 67, "LiberationMono_Italic67pt7b" },
  { &LiberationMono_Italic68pt7b, 68, "LiberationMono_Italic68pt7b" },
  { &LiberationMono_Italic69pt7b, 69, "LiberationMono_Italic69pt7b" },
  { &LiberationMono_Italic70pt7b, 70, "LiberationMono_Italic70pt7b" },
  { &LiberationMono_Italic71pt7b, 71, "LiberationMono_Italic71pt7b" },
  { &LiberationMono_Italic72pt7b, 72, "LiberationMono_Italic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
