#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_ThinItalic6pt7b, 6, "NotoSans_ThinItalic6pt7b" },
  { &NotoSans_ThinItalic7pt7b, 7, "NotoSans_ThinItalic7pt7b" },
  { &NotoSans_ThinItalic8pt7b, 8, "NotoSans_ThinItalic8pt7b" },
  { &NotoSans_ThinItalic9pt7b, 9, "NotoSans_ThinItalic9pt7b" },
  { &NotoSans_ThinItalic10pt7b, 10, "NotoSans_ThinItalic10pt7b" },
  { &NotoSans_ThinItalic11pt7b, 11, "NotoSans_ThinItalic11pt7b" },
  { &NotoSans_ThinItalic12pt7b, 12, "NotoSans_ThinItalic12pt7b" },
  { &NotoSans_ThinItalic13pt7b, 13, "NotoSans_ThinItalic13pt7b" },
  { &NotoSans_ThinItalic14pt7b, 14, "NotoSans_ThinItalic14pt7b" },
  { &NotoSans_ThinItalic15pt7b, 15, "NotoSans_ThinItalic15pt7b" },
  { &NotoSans_ThinItalic16pt7b, 16, "NotoSans_ThinItalic16pt7b" },
  { &NotoSans_ThinItalic17pt7b, 17, "NotoSans_ThinItalic17pt7b" },
  { &NotoSans_ThinItalic18pt7b, 18, "NotoSans_ThinItalic18pt7b" },
  { &NotoSans_ThinItalic19pt7b, 19, "NotoSans_ThinItalic19pt7b" },
  { &NotoSans_ThinItalic20pt7b, 20, "NotoSans_ThinItalic20pt7b" },
  { &NotoSans_ThinItalic21pt7b, 21, "NotoSans_ThinItalic21pt7b" },
  { &NotoSans_ThinItalic22pt7b, 22, "NotoSans_ThinItalic22pt7b" },
  { &NotoSans_ThinItalic23pt7b, 23, "NotoSans_ThinItalic23pt7b" },
  { &NotoSans_ThinItalic24pt7b, 24, "NotoSans_ThinItalic24pt7b" },
  { &NotoSans_ThinItalic25pt7b, 25, "NotoSans_ThinItalic25pt7b" },
  { &NotoSans_ThinItalic26pt7b, 26, "NotoSans_ThinItalic26pt7b" },
  { &NotoSans_ThinItalic27pt7b, 27, "NotoSans_ThinItalic27pt7b" },
  { &NotoSans_ThinItalic28pt7b, 28, "NotoSans_ThinItalic28pt7b" },
  { &NotoSans_ThinItalic29pt7b, 29, "NotoSans_ThinItalic29pt7b" },
  { &NotoSans_ThinItalic30pt7b, 30, "NotoSans_ThinItalic30pt7b" },
  { &NotoSans_ThinItalic31pt7b, 31, "NotoSans_ThinItalic31pt7b" },
  { &NotoSans_ThinItalic32pt7b, 32, "NotoSans_ThinItalic32pt7b" },
  { &NotoSans_ThinItalic33pt7b, 33, "NotoSans_ThinItalic33pt7b" },
  { &NotoSans_ThinItalic34pt7b, 34, "NotoSans_ThinItalic34pt7b" },
  { &NotoSans_ThinItalic35pt7b, 35, "NotoSans_ThinItalic35pt7b" },
  { &NotoSans_ThinItalic36pt7b, 36, "NotoSans_ThinItalic36pt7b" },
  { &NotoSans_ThinItalic37pt7b, 37, "NotoSans_ThinItalic37pt7b" },
  { &NotoSans_ThinItalic38pt7b, 38, "NotoSans_ThinItalic38pt7b" },
  { &NotoSans_ThinItalic39pt7b, 39, "NotoSans_ThinItalic39pt7b" },
  { &NotoSans_ThinItalic40pt7b, 40, "NotoSans_ThinItalic40pt7b" },
  { &NotoSans_ThinItalic41pt7b, 41, "NotoSans_ThinItalic41pt7b" },
  { &NotoSans_ThinItalic42pt7b, 42, "NotoSans_ThinItalic42pt7b" },
  { &NotoSans_ThinItalic43pt7b, 43, "NotoSans_ThinItalic43pt7b" },
  { &NotoSans_ThinItalic44pt7b, 44, "NotoSans_ThinItalic44pt7b" },
  { &NotoSans_ThinItalic45pt7b, 45, "NotoSans_ThinItalic45pt7b" },
  { &NotoSans_ThinItalic46pt7b, 46, "NotoSans_ThinItalic46pt7b" },
  { &NotoSans_ThinItalic47pt7b, 47, "NotoSans_ThinItalic47pt7b" },
  { &NotoSans_ThinItalic48pt7b, 48, "NotoSans_ThinItalic48pt7b" },
  { &NotoSans_ThinItalic49pt7b, 49, "NotoSans_ThinItalic49pt7b" },
  { &NotoSans_ThinItalic50pt7b, 50, "NotoSans_ThinItalic50pt7b" },
  { &NotoSans_ThinItalic51pt7b, 51, "NotoSans_ThinItalic51pt7b" },
  { &NotoSans_ThinItalic52pt7b, 52, "NotoSans_ThinItalic52pt7b" },
  { &NotoSans_ThinItalic53pt7b, 53, "NotoSans_ThinItalic53pt7b" },
  { &NotoSans_ThinItalic54pt7b, 54, "NotoSans_ThinItalic54pt7b" },
  { &NotoSans_ThinItalic55pt7b, 55, "NotoSans_ThinItalic55pt7b" },
  { &NotoSans_ThinItalic56pt7b, 56, "NotoSans_ThinItalic56pt7b" },
  { &NotoSans_ThinItalic57pt7b, 57, "NotoSans_ThinItalic57pt7b" },
  { &NotoSans_ThinItalic58pt7b, 58, "NotoSans_ThinItalic58pt7b" },
  { &NotoSans_ThinItalic59pt7b, 59, "NotoSans_ThinItalic59pt7b" },
  { &NotoSans_ThinItalic60pt7b, 60, "NotoSans_ThinItalic60pt7b" },
  { &NotoSans_ThinItalic61pt7b, 61, "NotoSans_ThinItalic61pt7b" },
  { &NotoSans_ThinItalic62pt7b, 62, "NotoSans_ThinItalic62pt7b" },
  { &NotoSans_ThinItalic63pt7b, 63, "NotoSans_ThinItalic63pt7b" },
  { &NotoSans_ThinItalic64pt7b, 64, "NotoSans_ThinItalic64pt7b" },
  { &NotoSans_ThinItalic65pt7b, 65, "NotoSans_ThinItalic65pt7b" },
  { &NotoSans_ThinItalic66pt7b, 66, "NotoSans_ThinItalic66pt7b" },
  { &NotoSans_ThinItalic67pt7b, 67, "NotoSans_ThinItalic67pt7b" },
  { &NotoSans_ThinItalic68pt7b, 68, "NotoSans_ThinItalic68pt7b" },
  { &NotoSans_ThinItalic69pt7b, 69, "NotoSans_ThinItalic69pt7b" },
  { &NotoSans_ThinItalic70pt7b, 70, "NotoSans_ThinItalic70pt7b" },
  { &NotoSans_ThinItalic71pt7b, 71, "NotoSans_ThinItalic71pt7b" },
  { &NotoSans_ThinItalic72pt7b, 72, "NotoSans_ThinItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
