#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &IBMPlexMono_LightItalic6pt7b, 6, "IBMPlexMono_LightItalic6pt7b" },
  { &IBMPlexMono_LightItalic7pt7b, 7, "IBMPlexMono_LightItalic7pt7b" },
  { &IBMPlexMono_LightItalic8pt7b, 8, "IBMPlexMono_LightItalic8pt7b" },
  { &IBMPlexMono_LightItalic9pt7b, 9, "IBMPlexMono_LightItalic9pt7b" },
  { &IBMPlexMono_LightItalic10pt7b, 10, "IBMPlexMono_LightItalic10pt7b" },
  { &IBMPlexMono_LightItalic11pt7b, 11, "IBMPlexMono_LightItalic11pt7b" },
  { &IBMPlexMono_LightItalic12pt7b, 12, "IBMPlexMono_LightItalic12pt7b" },
  { &IBMPlexMono_LightItalic13pt7b, 13, "IBMPlexMono_LightItalic13pt7b" },
  { &IBMPlexMono_LightItalic14pt7b, 14, "IBMPlexMono_LightItalic14pt7b" },
  { &IBMPlexMono_LightItalic15pt7b, 15, "IBMPlexMono_LightItalic15pt7b" },
  { &IBMPlexMono_LightItalic16pt7b, 16, "IBMPlexMono_LightItalic16pt7b" },
  { &IBMPlexMono_LightItalic17pt7b, 17, "IBMPlexMono_LightItalic17pt7b" },
  { &IBMPlexMono_LightItalic18pt7b, 18, "IBMPlexMono_LightItalic18pt7b" },
  { &IBMPlexMono_LightItalic19pt7b, 19, "IBMPlexMono_LightItalic19pt7b" },
  { &IBMPlexMono_LightItalic20pt7b, 20, "IBMPlexMono_LightItalic20pt7b" },
  { &IBMPlexMono_LightItalic21pt7b, 21, "IBMPlexMono_LightItalic21pt7b" },
  { &IBMPlexMono_LightItalic22pt7b, 22, "IBMPlexMono_LightItalic22pt7b" },
  { &IBMPlexMono_LightItalic23pt7b, 23, "IBMPlexMono_LightItalic23pt7b" },
  { &IBMPlexMono_LightItalic24pt7b, 24, "IBMPlexMono_LightItalic24pt7b" },
  { &IBMPlexMono_LightItalic25pt7b, 25, "IBMPlexMono_LightItalic25pt7b" },
  { &IBMPlexMono_LightItalic26pt7b, 26, "IBMPlexMono_LightItalic26pt7b" },
  { &IBMPlexMono_LightItalic27pt7b, 27, "IBMPlexMono_LightItalic27pt7b" },
  { &IBMPlexMono_LightItalic28pt7b, 28, "IBMPlexMono_LightItalic28pt7b" },
  { &IBMPlexMono_LightItalic29pt7b, 29, "IBMPlexMono_LightItalic29pt7b" },
  { &IBMPlexMono_LightItalic30pt7b, 30, "IBMPlexMono_LightItalic30pt7b" },
  { &IBMPlexMono_LightItalic31pt7b, 31, "IBMPlexMono_LightItalic31pt7b" },
  { &IBMPlexMono_LightItalic32pt7b, 32, "IBMPlexMono_LightItalic32pt7b" },
  { &IBMPlexMono_LightItalic33pt7b, 33, "IBMPlexMono_LightItalic33pt7b" },
  { &IBMPlexMono_LightItalic34pt7b, 34, "IBMPlexMono_LightItalic34pt7b" },
  { &IBMPlexMono_LightItalic35pt7b, 35, "IBMPlexMono_LightItalic35pt7b" },
  { &IBMPlexMono_LightItalic36pt7b, 36, "IBMPlexMono_LightItalic36pt7b" },
  { &IBMPlexMono_LightItalic37pt7b, 37, "IBMPlexMono_LightItalic37pt7b" },
  { &IBMPlexMono_LightItalic38pt7b, 38, "IBMPlexMono_LightItalic38pt7b" },
  { &IBMPlexMono_LightItalic39pt7b, 39, "IBMPlexMono_LightItalic39pt7b" },
  { &IBMPlexMono_LightItalic40pt7b, 40, "IBMPlexMono_LightItalic40pt7b" },
  { &IBMPlexMono_LightItalic41pt7b, 41, "IBMPlexMono_LightItalic41pt7b" },
  { &IBMPlexMono_LightItalic42pt7b, 42, "IBMPlexMono_LightItalic42pt7b" },
  { &IBMPlexMono_LightItalic43pt7b, 43, "IBMPlexMono_LightItalic43pt7b" },
  { &IBMPlexMono_LightItalic44pt7b, 44, "IBMPlexMono_LightItalic44pt7b" },
  { &IBMPlexMono_LightItalic45pt7b, 45, "IBMPlexMono_LightItalic45pt7b" },
  { &IBMPlexMono_LightItalic46pt7b, 46, "IBMPlexMono_LightItalic46pt7b" },
  { &IBMPlexMono_LightItalic47pt7b, 47, "IBMPlexMono_LightItalic47pt7b" },
  { &IBMPlexMono_LightItalic48pt7b, 48, "IBMPlexMono_LightItalic48pt7b" },
  { &IBMPlexMono_LightItalic49pt7b, 49, "IBMPlexMono_LightItalic49pt7b" },
  { &IBMPlexMono_LightItalic50pt7b, 50, "IBMPlexMono_LightItalic50pt7b" },
  { &IBMPlexMono_LightItalic51pt7b, 51, "IBMPlexMono_LightItalic51pt7b" },
  { &IBMPlexMono_LightItalic52pt7b, 52, "IBMPlexMono_LightItalic52pt7b" },
  { &IBMPlexMono_LightItalic53pt7b, 53, "IBMPlexMono_LightItalic53pt7b" },
  { &IBMPlexMono_LightItalic54pt7b, 54, "IBMPlexMono_LightItalic54pt7b" },
  { &IBMPlexMono_LightItalic55pt7b, 55, "IBMPlexMono_LightItalic55pt7b" },
  { &IBMPlexMono_LightItalic56pt7b, 56, "IBMPlexMono_LightItalic56pt7b" },
  { &IBMPlexMono_LightItalic57pt7b, 57, "IBMPlexMono_LightItalic57pt7b" },
  { &IBMPlexMono_LightItalic58pt7b, 58, "IBMPlexMono_LightItalic58pt7b" },
  { &IBMPlexMono_LightItalic59pt7b, 59, "IBMPlexMono_LightItalic59pt7b" },
  { &IBMPlexMono_LightItalic60pt7b, 60, "IBMPlexMono_LightItalic60pt7b" },
  { &IBMPlexMono_LightItalic61pt7b, 61, "IBMPlexMono_LightItalic61pt7b" },
  { &IBMPlexMono_LightItalic62pt7b, 62, "IBMPlexMono_LightItalic62pt7b" },
  { &IBMPlexMono_LightItalic63pt7b, 63, "IBMPlexMono_LightItalic63pt7b" },
  { &IBMPlexMono_LightItalic64pt7b, 64, "IBMPlexMono_LightItalic64pt7b" },
  { &IBMPlexMono_LightItalic65pt7b, 65, "IBMPlexMono_LightItalic65pt7b" },
  { &IBMPlexMono_LightItalic66pt7b, 66, "IBMPlexMono_LightItalic66pt7b" },
  { &IBMPlexMono_LightItalic67pt7b, 67, "IBMPlexMono_LightItalic67pt7b" },
  { &IBMPlexMono_LightItalic68pt7b, 68, "IBMPlexMono_LightItalic68pt7b" },
  { &IBMPlexMono_LightItalic69pt7b, 69, "IBMPlexMono_LightItalic69pt7b" },
  { &IBMPlexMono_LightItalic70pt7b, 70, "IBMPlexMono_LightItalic70pt7b" },
  { &IBMPlexMono_LightItalic71pt7b, 71, "IBMPlexMono_LightItalic71pt7b" },
  { &IBMPlexMono_LightItalic72pt7b, 72, "IBMPlexMono_LightItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
