#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &JetBrainsMono_ExtraLightItalic6pt7b, 6, "JetBrainsMono_ExtraLightItalic6pt7b" },
  { &JetBrainsMono_ExtraLightItalic7pt7b, 7, "JetBrainsMono_ExtraLightItalic7pt7b" },
  { &JetBrainsMono_ExtraLightItalic8pt7b, 8, "JetBrainsMono_ExtraLightItalic8pt7b" },
  { &JetBrainsMono_ExtraLightItalic9pt7b, 9, "JetBrainsMono_ExtraLightItalic9pt7b" },
  { &JetBrainsMono_ExtraLightItalic10pt7b, 10, "JetBrainsMono_ExtraLightItalic10pt7b" },
  { &JetBrainsMono_ExtraLightItalic11pt7b, 11, "JetBrainsMono_ExtraLightItalic11pt7b" },
  { &JetBrainsMono_ExtraLightItalic12pt7b, 12, "JetBrainsMono_ExtraLightItalic12pt7b" },
  { &JetBrainsMono_ExtraLightItalic13pt7b, 13, "JetBrainsMono_ExtraLightItalic13pt7b" },
  { &JetBrainsMono_ExtraLightItalic14pt7b, 14, "JetBrainsMono_ExtraLightItalic14pt7b" },
  { &JetBrainsMono_ExtraLightItalic15pt7b, 15, "JetBrainsMono_ExtraLightItalic15pt7b" },
  { &JetBrainsMono_ExtraLightItalic16pt7b, 16, "JetBrainsMono_ExtraLightItalic16pt7b" },
  { &JetBrainsMono_ExtraLightItalic17pt7b, 17, "JetBrainsMono_ExtraLightItalic17pt7b" },
  { &JetBrainsMono_ExtraLightItalic18pt7b, 18, "JetBrainsMono_ExtraLightItalic18pt7b" },
  { &JetBrainsMono_ExtraLightItalic19pt7b, 19, "JetBrainsMono_ExtraLightItalic19pt7b" },
  { &JetBrainsMono_ExtraLightItalic20pt7b, 20, "JetBrainsMono_ExtraLightItalic20pt7b" },
  { &JetBrainsMono_ExtraLightItalic21pt7b, 21, "JetBrainsMono_ExtraLightItalic21pt7b" },
  { &JetBrainsMono_ExtraLightItalic22pt7b, 22, "JetBrainsMono_ExtraLightItalic22pt7b" },
  { &JetBrainsMono_ExtraLightItalic23pt7b, 23, "JetBrainsMono_ExtraLightItalic23pt7b" },
  { &JetBrainsMono_ExtraLightItalic24pt7b, 24, "JetBrainsMono_ExtraLightItalic24pt7b" },
  { &JetBrainsMono_ExtraLightItalic25pt7b, 25, "JetBrainsMono_ExtraLightItalic25pt7b" },
  { &JetBrainsMono_ExtraLightItalic26pt7b, 26, "JetBrainsMono_ExtraLightItalic26pt7b" },
  { &JetBrainsMono_ExtraLightItalic27pt7b, 27, "JetBrainsMono_ExtraLightItalic27pt7b" },
  { &JetBrainsMono_ExtraLightItalic28pt7b, 28, "JetBrainsMono_ExtraLightItalic28pt7b" },
  { &JetBrainsMono_ExtraLightItalic29pt7b, 29, "JetBrainsMono_ExtraLightItalic29pt7b" },
  { &JetBrainsMono_ExtraLightItalic30pt7b, 30, "JetBrainsMono_ExtraLightItalic30pt7b" },
  { &JetBrainsMono_ExtraLightItalic31pt7b, 31, "JetBrainsMono_ExtraLightItalic31pt7b" },
  { &JetBrainsMono_ExtraLightItalic32pt7b, 32, "JetBrainsMono_ExtraLightItalic32pt7b" },
  { &JetBrainsMono_ExtraLightItalic33pt7b, 33, "JetBrainsMono_ExtraLightItalic33pt7b" },
  { &JetBrainsMono_ExtraLightItalic34pt7b, 34, "JetBrainsMono_ExtraLightItalic34pt7b" },
  { &JetBrainsMono_ExtraLightItalic35pt7b, 35, "JetBrainsMono_ExtraLightItalic35pt7b" },
  { &JetBrainsMono_ExtraLightItalic36pt7b, 36, "JetBrainsMono_ExtraLightItalic36pt7b" },
  { &JetBrainsMono_ExtraLightItalic37pt7b, 37, "JetBrainsMono_ExtraLightItalic37pt7b" },
  { &JetBrainsMono_ExtraLightItalic38pt7b, 38, "JetBrainsMono_ExtraLightItalic38pt7b" },
  { &JetBrainsMono_ExtraLightItalic39pt7b, 39, "JetBrainsMono_ExtraLightItalic39pt7b" },
  { &JetBrainsMono_ExtraLightItalic40pt7b, 40, "JetBrainsMono_ExtraLightItalic40pt7b" },
  { &JetBrainsMono_ExtraLightItalic41pt7b, 41, "JetBrainsMono_ExtraLightItalic41pt7b" },
  { &JetBrainsMono_ExtraLightItalic42pt7b, 42, "JetBrainsMono_ExtraLightItalic42pt7b" },
  { &JetBrainsMono_ExtraLightItalic43pt7b, 43, "JetBrainsMono_ExtraLightItalic43pt7b" },
  { &JetBrainsMono_ExtraLightItalic44pt7b, 44, "JetBrainsMono_ExtraLightItalic44pt7b" },
  { &JetBrainsMono_ExtraLightItalic45pt7b, 45, "JetBrainsMono_ExtraLightItalic45pt7b" },
  { &JetBrainsMono_ExtraLightItalic46pt7b, 46, "JetBrainsMono_ExtraLightItalic46pt7b" },
  { &JetBrainsMono_ExtraLightItalic47pt7b, 47, "JetBrainsMono_ExtraLightItalic47pt7b" },
  { &JetBrainsMono_ExtraLightItalic48pt7b, 48, "JetBrainsMono_ExtraLightItalic48pt7b" },
  { &JetBrainsMono_ExtraLightItalic49pt7b, 49, "JetBrainsMono_ExtraLightItalic49pt7b" },
  { &JetBrainsMono_ExtraLightItalic50pt7b, 50, "JetBrainsMono_ExtraLightItalic50pt7b" },
  { &JetBrainsMono_ExtraLightItalic51pt7b, 51, "JetBrainsMono_ExtraLightItalic51pt7b" },
  { &JetBrainsMono_ExtraLightItalic52pt7b, 52, "JetBrainsMono_ExtraLightItalic52pt7b" },
  { &JetBrainsMono_ExtraLightItalic53pt7b, 53, "JetBrainsMono_ExtraLightItalic53pt7b" },
  { &JetBrainsMono_ExtraLightItalic54pt7b, 54, "JetBrainsMono_ExtraLightItalic54pt7b" },
  { &JetBrainsMono_ExtraLightItalic55pt7b, 55, "JetBrainsMono_ExtraLightItalic55pt7b" },
  { &JetBrainsMono_ExtraLightItalic56pt7b, 56, "JetBrainsMono_ExtraLightItalic56pt7b" },
  { &JetBrainsMono_ExtraLightItalic57pt7b, 57, "JetBrainsMono_ExtraLightItalic57pt7b" },
  { &JetBrainsMono_ExtraLightItalic58pt7b, 58, "JetBrainsMono_ExtraLightItalic58pt7b" },
  { &JetBrainsMono_ExtraLightItalic59pt7b, 59, "JetBrainsMono_ExtraLightItalic59pt7b" },
  { &JetBrainsMono_ExtraLightItalic60pt7b, 60, "JetBrainsMono_ExtraLightItalic60pt7b" },
  { &JetBrainsMono_ExtraLightItalic61pt7b, 61, "JetBrainsMono_ExtraLightItalic61pt7b" },
  { &JetBrainsMono_ExtraLightItalic62pt7b, 62, "JetBrainsMono_ExtraLightItalic62pt7b" },
  { &JetBrainsMono_ExtraLightItalic63pt7b, 63, "JetBrainsMono_ExtraLightItalic63pt7b" },
  { &JetBrainsMono_ExtraLightItalic64pt7b, 64, "JetBrainsMono_ExtraLightItalic64pt7b" },
  { &JetBrainsMono_ExtraLightItalic65pt7b, 65, "JetBrainsMono_ExtraLightItalic65pt7b" },
  { &JetBrainsMono_ExtraLightItalic66pt7b, 66, "JetBrainsMono_ExtraLightItalic66pt7b" },
  { &JetBrainsMono_ExtraLightItalic67pt7b, 67, "JetBrainsMono_ExtraLightItalic67pt7b" },
  { &JetBrainsMono_ExtraLightItalic68pt7b, 68, "JetBrainsMono_ExtraLightItalic68pt7b" },
  { &JetBrainsMono_ExtraLightItalic69pt7b, 69, "JetBrainsMono_ExtraLightItalic69pt7b" },
  { &JetBrainsMono_ExtraLightItalic70pt7b, 70, "JetBrainsMono_ExtraLightItalic70pt7b" },
  { &JetBrainsMono_ExtraLightItalic71pt7b, 71, "JetBrainsMono_ExtraLightItalic71pt7b" },
  { &JetBrainsMono_ExtraLightItalic72pt7b, 72, "JetBrainsMono_ExtraLightItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
