#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_Condensed_Medium6pt7b, 6, "NotoSans_Condensed_Medium6pt7b" },
  { &NotoSans_Condensed_Medium7pt7b, 7, "NotoSans_Condensed_Medium7pt7b" },
  { &NotoSans_Condensed_Medium8pt7b, 8, "NotoSans_Condensed_Medium8pt7b" },
  { &NotoSans_Condensed_Medium9pt7b, 9, "NotoSans_Condensed_Medium9pt7b" },
  { &NotoSans_Condensed_Medium10pt7b, 10, "NotoSans_Condensed_Medium10pt7b" },
  { &NotoSans_Condensed_Medium11pt7b, 11, "NotoSans_Condensed_Medium11pt7b" },
  { &NotoSans_Condensed_Medium12pt7b, 12, "NotoSans_Condensed_Medium12pt7b" },
  { &NotoSans_Condensed_Medium13pt7b, 13, "NotoSans_Condensed_Medium13pt7b" },
  { &NotoSans_Condensed_Medium14pt7b, 14, "NotoSans_Condensed_Medium14pt7b" },
  { &NotoSans_Condensed_Medium15pt7b, 15, "NotoSans_Condensed_Medium15pt7b" },
  { &NotoSans_Condensed_Medium16pt7b, 16, "NotoSans_Condensed_Medium16pt7b" },
  { &NotoSans_Condensed_Medium17pt7b, 17, "NotoSans_Condensed_Medium17pt7b" },
  { &NotoSans_Condensed_Medium18pt7b, 18, "NotoSans_Condensed_Medium18pt7b" },
  { &NotoSans_Condensed_Medium19pt7b, 19, "NotoSans_Condensed_Medium19pt7b" },
  { &NotoSans_Condensed_Medium20pt7b, 20, "NotoSans_Condensed_Medium20pt7b" },
  { &NotoSans_Condensed_Medium21pt7b, 21, "NotoSans_Condensed_Medium21pt7b" },
  { &NotoSans_Condensed_Medium22pt7b, 22, "NotoSans_Condensed_Medium22pt7b" },
  { &NotoSans_Condensed_Medium23pt7b, 23, "NotoSans_Condensed_Medium23pt7b" },
  { &NotoSans_Condensed_Medium24pt7b, 24, "NotoSans_Condensed_Medium24pt7b" },
  { &NotoSans_Condensed_Medium25pt7b, 25, "NotoSans_Condensed_Medium25pt7b" },
  { &NotoSans_Condensed_Medium26pt7b, 26, "NotoSans_Condensed_Medium26pt7b" },
  { &NotoSans_Condensed_Medium27pt7b, 27, "NotoSans_Condensed_Medium27pt7b" },
  { &NotoSans_Condensed_Medium28pt7b, 28, "NotoSans_Condensed_Medium28pt7b" },
  { &NotoSans_Condensed_Medium29pt7b, 29, "NotoSans_Condensed_Medium29pt7b" },
  { &NotoSans_Condensed_Medium30pt7b, 30, "NotoSans_Condensed_Medium30pt7b" },
  { &NotoSans_Condensed_Medium31pt7b, 31, "NotoSans_Condensed_Medium31pt7b" },
  { &NotoSans_Condensed_Medium32pt7b, 32, "NotoSans_Condensed_Medium32pt7b" },
  { &NotoSans_Condensed_Medium33pt7b, 33, "NotoSans_Condensed_Medium33pt7b" },
  { &NotoSans_Condensed_Medium34pt7b, 34, "NotoSans_Condensed_Medium34pt7b" },
  { &NotoSans_Condensed_Medium35pt7b, 35, "NotoSans_Condensed_Medium35pt7b" },
  { &NotoSans_Condensed_Medium36pt7b, 36, "NotoSans_Condensed_Medium36pt7b" },
  { &NotoSans_Condensed_Medium37pt7b, 37, "NotoSans_Condensed_Medium37pt7b" },
  { &NotoSans_Condensed_Medium38pt7b, 38, "NotoSans_Condensed_Medium38pt7b" },
  { &NotoSans_Condensed_Medium39pt7b, 39, "NotoSans_Condensed_Medium39pt7b" },
  { &NotoSans_Condensed_Medium40pt7b, 40, "NotoSans_Condensed_Medium40pt7b" },
  { &NotoSans_Condensed_Medium41pt7b, 41, "NotoSans_Condensed_Medium41pt7b" },
  { &NotoSans_Condensed_Medium42pt7b, 42, "NotoSans_Condensed_Medium42pt7b" },
  { &NotoSans_Condensed_Medium43pt7b, 43, "NotoSans_Condensed_Medium43pt7b" },
  { &NotoSans_Condensed_Medium44pt7b, 44, "NotoSans_Condensed_Medium44pt7b" },
  { &NotoSans_Condensed_Medium45pt7b, 45, "NotoSans_Condensed_Medium45pt7b" },
  { &NotoSans_Condensed_Medium46pt7b, 46, "NotoSans_Condensed_Medium46pt7b" },
  { &NotoSans_Condensed_Medium47pt7b, 47, "NotoSans_Condensed_Medium47pt7b" },
  { &NotoSans_Condensed_Medium48pt7b, 48, "NotoSans_Condensed_Medium48pt7b" },
  { &NotoSans_Condensed_Medium49pt7b, 49, "NotoSans_Condensed_Medium49pt7b" },
  { &NotoSans_Condensed_Medium50pt7b, 50, "NotoSans_Condensed_Medium50pt7b" },
  { &NotoSans_Condensed_Medium51pt7b, 51, "NotoSans_Condensed_Medium51pt7b" },
  { &NotoSans_Condensed_Medium52pt7b, 52, "NotoSans_Condensed_Medium52pt7b" },
  { &NotoSans_Condensed_Medium53pt7b, 53, "NotoSans_Condensed_Medium53pt7b" },
  { &NotoSans_Condensed_Medium54pt7b, 54, "NotoSans_Condensed_Medium54pt7b" },
  { &NotoSans_Condensed_Medium55pt7b, 55, "NotoSans_Condensed_Medium55pt7b" },
  { &NotoSans_Condensed_Medium56pt7b, 56, "NotoSans_Condensed_Medium56pt7b" },
  { &NotoSans_Condensed_Medium57pt7b, 57, "NotoSans_Condensed_Medium57pt7b" },
  { &NotoSans_Condensed_Medium58pt7b, 58, "NotoSans_Condensed_Medium58pt7b" },
  { &NotoSans_Condensed_Medium59pt7b, 59, "NotoSans_Condensed_Medium59pt7b" },
  { &NotoSans_Condensed_Medium60pt7b, 60, "NotoSans_Condensed_Medium60pt7b" },
  { &NotoSans_Condensed_Medium61pt7b, 61, "NotoSans_Condensed_Medium61pt7b" },
  { &NotoSans_Condensed_Medium62pt7b, 62, "NotoSans_Condensed_Medium62pt7b" },
  { &NotoSans_Condensed_Medium63pt7b, 63, "NotoSans_Condensed_Medium63pt7b" },
  { &NotoSans_Condensed_Medium64pt7b, 64, "NotoSans_Condensed_Medium64pt7b" },
  { &NotoSans_Condensed_Medium65pt7b, 65, "NotoSans_Condensed_Medium65pt7b" },
  { &NotoSans_Condensed_Medium66pt7b, 66, "NotoSans_Condensed_Medium66pt7b" },
  { &NotoSans_Condensed_Medium67pt7b, 67, "NotoSans_Condensed_Medium67pt7b" },
  { &NotoSans_Condensed_Medium68pt7b, 68, "NotoSans_Condensed_Medium68pt7b" },
  { &NotoSans_Condensed_Medium69pt7b, 69, "NotoSans_Condensed_Medium69pt7b" },
  { &NotoSans_Condensed_Medium70pt7b, 70, "NotoSans_Condensed_Medium70pt7b" },
  { &NotoSans_Condensed_Medium71pt7b, 71, "NotoSans_Condensed_Medium71pt7b" },
  { &NotoSans_Condensed_Medium72pt7b, 72, "NotoSans_Condensed_Medium72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
