#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_ExtraBold6pt7b, 6, "NotoSans_ExtraBold6pt7b" },
  { &NotoSans_ExtraBold7pt7b, 7, "NotoSans_ExtraBold7pt7b" },
  { &NotoSans_ExtraBold8pt7b, 8, "NotoSans_ExtraBold8pt7b" },
  { &NotoSans_ExtraBold9pt7b, 9, "NotoSans_ExtraBold9pt7b" },
  { &NotoSans_ExtraBold10pt7b, 10, "NotoSans_ExtraBold10pt7b" },
  { &NotoSans_ExtraBold11pt7b, 11, "NotoSans_ExtraBold11pt7b" },
  { &NotoSans_ExtraBold12pt7b, 12, "NotoSans_ExtraBold12pt7b" },
  { &NotoSans_ExtraBold13pt7b, 13, "NotoSans_ExtraBold13pt7b" },
  { &NotoSans_ExtraBold14pt7b, 14, "NotoSans_ExtraBold14pt7b" },
  { &NotoSans_ExtraBold15pt7b, 15, "NotoSans_ExtraBold15pt7b" },
  { &NotoSans_ExtraBold16pt7b, 16, "NotoSans_ExtraBold16pt7b" },
  { &NotoSans_ExtraBold17pt7b, 17, "NotoSans_ExtraBold17pt7b" },
  { &NotoSans_ExtraBold18pt7b, 18, "NotoSans_ExtraBold18pt7b" },
  { &NotoSans_ExtraBold19pt7b, 19, "NotoSans_ExtraBold19pt7b" },
  { &NotoSans_ExtraBold20pt7b, 20, "NotoSans_ExtraBold20pt7b" },
  { &NotoSans_ExtraBold21pt7b, 21, "NotoSans_ExtraBold21pt7b" },
  { &NotoSans_ExtraBold22pt7b, 22, "NotoSans_ExtraBold22pt7b" },
  { &NotoSans_ExtraBold23pt7b, 23, "NotoSans_ExtraBold23pt7b" },
  { &NotoSans_ExtraBold24pt7b, 24, "NotoSans_ExtraBold24pt7b" },
  { &NotoSans_ExtraBold25pt7b, 25, "NotoSans_ExtraBold25pt7b" },
  { &NotoSans_ExtraBold26pt7b, 26, "NotoSans_ExtraBold26pt7b" },
  { &NotoSans_ExtraBold27pt7b, 27, "NotoSans_ExtraBold27pt7b" },
  { &NotoSans_ExtraBold28pt7b, 28, "NotoSans_ExtraBold28pt7b" },
  { &NotoSans_ExtraBold29pt7b, 29, "NotoSans_ExtraBold29pt7b" },
  { &NotoSans_ExtraBold30pt7b, 30, "NotoSans_ExtraBold30pt7b" },
  { &NotoSans_ExtraBold31pt7b, 31, "NotoSans_ExtraBold31pt7b" },
  { &NotoSans_ExtraBold32pt7b, 32, "NotoSans_ExtraBold32pt7b" },
  { &NotoSans_ExtraBold33pt7b, 33, "NotoSans_ExtraBold33pt7b" },
  { &NotoSans_ExtraBold34pt7b, 34, "NotoSans_ExtraBold34pt7b" },
  { &NotoSans_ExtraBold35pt7b, 35, "NotoSans_ExtraBold35pt7b" },
  { &NotoSans_ExtraBold36pt7b, 36, "NotoSans_ExtraBold36pt7b" },
  { &NotoSans_ExtraBold37pt7b, 37, "NotoSans_ExtraBold37pt7b" },
  { &NotoSans_ExtraBold38pt7b, 38, "NotoSans_ExtraBold38pt7b" },
  { &NotoSans_ExtraBold39pt7b, 39, "NotoSans_ExtraBold39pt7b" },
  { &NotoSans_ExtraBold40pt7b, 40, "NotoSans_ExtraBold40pt7b" },
  { &NotoSans_ExtraBold41pt7b, 41, "NotoSans_ExtraBold41pt7b" },
  { &NotoSans_ExtraBold42pt7b, 42, "NotoSans_ExtraBold42pt7b" },
  { &NotoSans_ExtraBold43pt7b, 43, "NotoSans_ExtraBold43pt7b" },
  { &NotoSans_ExtraBold44pt7b, 44, "NotoSans_ExtraBold44pt7b" },
  { &NotoSans_ExtraBold45pt7b, 45, "NotoSans_ExtraBold45pt7b" },
  { &NotoSans_ExtraBold46pt7b, 46, "NotoSans_ExtraBold46pt7b" },
  { &NotoSans_ExtraBold47pt7b, 47, "NotoSans_ExtraBold47pt7b" },
  { &NotoSans_ExtraBold48pt7b, 48, "NotoSans_ExtraBold48pt7b" },
  { &NotoSans_ExtraBold49pt7b, 49, "NotoSans_ExtraBold49pt7b" },
  { &NotoSans_ExtraBold50pt7b, 50, "NotoSans_ExtraBold50pt7b" },
  { &NotoSans_ExtraBold51pt7b, 51, "NotoSans_ExtraBold51pt7b" },
  { &NotoSans_ExtraBold52pt7b, 52, "NotoSans_ExtraBold52pt7b" },
  { &NotoSans_ExtraBold53pt7b, 53, "NotoSans_ExtraBold53pt7b" },
  { &NotoSans_ExtraBold54pt7b, 54, "NotoSans_ExtraBold54pt7b" },
  { &NotoSans_ExtraBold55pt7b, 55, "NotoSans_ExtraBold55pt7b" },
  { &NotoSans_ExtraBold56pt7b, 56, "NotoSans_ExtraBold56pt7b" },
  { &NotoSans_ExtraBold57pt7b, 57, "NotoSans_ExtraBold57pt7b" },
  { &NotoSans_ExtraBold58pt7b, 58, "NotoSans_ExtraBold58pt7b" },
  { &NotoSans_ExtraBold59pt7b, 59, "NotoSans_ExtraBold59pt7b" },
  { &NotoSans_ExtraBold60pt7b, 60, "NotoSans_ExtraBold60pt7b" },
  { &NotoSans_ExtraBold61pt7b, 61, "NotoSans_ExtraBold61pt7b" },
  { &NotoSans_ExtraBold62pt7b, 62, "NotoSans_ExtraBold62pt7b" },
  { &NotoSans_ExtraBold63pt7b, 63, "NotoSans_ExtraBold63pt7b" },
  { &NotoSans_ExtraBold64pt7b, 64, "NotoSans_ExtraBold64pt7b" },
  { &NotoSans_ExtraBold65pt7b, 65, "NotoSans_ExtraBold65pt7b" },
  { &NotoSans_ExtraBold66pt7b, 66, "NotoSans_ExtraBold66pt7b" },
  { &NotoSans_ExtraBold67pt7b, 67, "NotoSans_ExtraBold67pt7b" },
  { &NotoSans_ExtraBold68pt7b, 68, "NotoSans_ExtraBold68pt7b" },
  { &NotoSans_ExtraBold69pt7b, 69, "NotoSans_ExtraBold69pt7b" },
  { &NotoSans_ExtraBold70pt7b, 70, "NotoSans_ExtraBold70pt7b" },
  { &NotoSans_ExtraBold71pt7b, 71, "NotoSans_ExtraBold71pt7b" },
  { &NotoSans_ExtraBold72pt7b, 72, "NotoSans_ExtraBold72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
