#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &JetBrainsMono_SemiBoldItalic6pt7b, 6, "JetBrainsMono_SemiBoldItalic6pt7b" },
  { &JetBrainsMono_SemiBoldItalic7pt7b, 7, "JetBrainsMono_SemiBoldItalic7pt7b" },
  { &JetBrainsMono_SemiBoldItalic8pt7b, 8, "JetBrainsMono_SemiBoldItalic8pt7b" },
  { &JetBrainsMono_SemiBoldItalic9pt7b, 9, "JetBrainsMono_SemiBoldItalic9pt7b" },
  { &JetBrainsMono_SemiBoldItalic10pt7b, 10, "JetBrainsMono_SemiBoldItalic10pt7b" },
  { &JetBrainsMono_SemiBoldItalic11pt7b, 11, "JetBrainsMono_SemiBoldItalic11pt7b" },
  { &JetBrainsMono_SemiBoldItalic12pt7b, 12, "JetBrainsMono_SemiBoldItalic12pt7b" },
  { &JetBrainsMono_SemiBoldItalic13pt7b, 13, "JetBrainsMono_SemiBoldItalic13pt7b" },
  { &JetBrainsMono_SemiBoldItalic14pt7b, 14, "JetBrainsMono_SemiBoldItalic14pt7b" },
  { &JetBrainsMono_SemiBoldItalic15pt7b, 15, "JetBrainsMono_SemiBoldItalic15pt7b" },
  { &JetBrainsMono_SemiBoldItalic16pt7b, 16, "JetBrainsMono_SemiBoldItalic16pt7b" },
  { &JetBrainsMono_SemiBoldItalic17pt7b, 17, "JetBrainsMono_SemiBoldItalic17pt7b" },
  { &JetBrainsMono_SemiBoldItalic18pt7b, 18, "JetBrainsMono_SemiBoldItalic18pt7b" },
  { &JetBrainsMono_SemiBoldItalic19pt7b, 19, "JetBrainsMono_SemiBoldItalic19pt7b" },
  { &JetBrainsMono_SemiBoldItalic20pt7b, 20, "JetBrainsMono_SemiBoldItalic20pt7b" },
  { &JetBrainsMono_SemiBoldItalic21pt7b, 21, "JetBrainsMono_SemiBoldItalic21pt7b" },
  { &JetBrainsMono_SemiBoldItalic22pt7b, 22, "JetBrainsMono_SemiBoldItalic22pt7b" },
  { &JetBrainsMono_SemiBoldItalic23pt7b, 23, "JetBrainsMono_SemiBoldItalic23pt7b" },
  { &JetBrainsMono_SemiBoldItalic24pt7b, 24, "JetBrainsMono_SemiBoldItalic24pt7b" },
  { &JetBrainsMono_SemiBoldItalic25pt7b, 25, "JetBrainsMono_SemiBoldItalic25pt7b" },
  { &JetBrainsMono_SemiBoldItalic26pt7b, 26, "JetBrainsMono_SemiBoldItalic26pt7b" },
  { &JetBrainsMono_SemiBoldItalic27pt7b, 27, "JetBrainsMono_SemiBoldItalic27pt7b" },
  { &JetBrainsMono_SemiBoldItalic28pt7b, 28, "JetBrainsMono_SemiBoldItalic28pt7b" },
  { &JetBrainsMono_SemiBoldItalic29pt7b, 29, "JetBrainsMono_SemiBoldItalic29pt7b" },
  { &JetBrainsMono_SemiBoldItalic30pt7b, 30, "JetBrainsMono_SemiBoldItalic30pt7b" },
  { &JetBrainsMono_SemiBoldItalic31pt7b, 31, "JetBrainsMono_SemiBoldItalic31pt7b" },
  { &JetBrainsMono_SemiBoldItalic32pt7b, 32, "JetBrainsMono_SemiBoldItalic32pt7b" },
  { &JetBrainsMono_SemiBoldItalic33pt7b, 33, "JetBrainsMono_SemiBoldItalic33pt7b" },
  { &JetBrainsMono_SemiBoldItalic34pt7b, 34, "JetBrainsMono_SemiBoldItalic34pt7b" },
  { &JetBrainsMono_SemiBoldItalic35pt7b, 35, "JetBrainsMono_SemiBoldItalic35pt7b" },
  { &JetBrainsMono_SemiBoldItalic36pt7b, 36, "JetBrainsMono_SemiBoldItalic36pt7b" },
  { &JetBrainsMono_SemiBoldItalic37pt7b, 37, "JetBrainsMono_SemiBoldItalic37pt7b" },
  { &JetBrainsMono_SemiBoldItalic38pt7b, 38, "JetBrainsMono_SemiBoldItalic38pt7b" },
  { &JetBrainsMono_SemiBoldItalic39pt7b, 39, "JetBrainsMono_SemiBoldItalic39pt7b" },
  { &JetBrainsMono_SemiBoldItalic40pt7b, 40, "JetBrainsMono_SemiBoldItalic40pt7b" },
  { &JetBrainsMono_SemiBoldItalic41pt7b, 41, "JetBrainsMono_SemiBoldItalic41pt7b" },
  { &JetBrainsMono_SemiBoldItalic42pt7b, 42, "JetBrainsMono_SemiBoldItalic42pt7b" },
  { &JetBrainsMono_SemiBoldItalic43pt7b, 43, "JetBrainsMono_SemiBoldItalic43pt7b" },
  { &JetBrainsMono_SemiBoldItalic44pt7b, 44, "JetBrainsMono_SemiBoldItalic44pt7b" },
  { &JetBrainsMono_SemiBoldItalic45pt7b, 45, "JetBrainsMono_SemiBoldItalic45pt7b" },
  { &JetBrainsMono_SemiBoldItalic46pt7b, 46, "JetBrainsMono_SemiBoldItalic46pt7b" },
  { &JetBrainsMono_SemiBoldItalic47pt7b, 47, "JetBrainsMono_SemiBoldItalic47pt7b" },
  { &JetBrainsMono_SemiBoldItalic48pt7b, 48, "JetBrainsMono_SemiBoldItalic48pt7b" },
  { &JetBrainsMono_SemiBoldItalic49pt7b, 49, "JetBrainsMono_SemiBoldItalic49pt7b" },
  { &JetBrainsMono_SemiBoldItalic50pt7b, 50, "JetBrainsMono_SemiBoldItalic50pt7b" },
  { &JetBrainsMono_SemiBoldItalic51pt7b, 51, "JetBrainsMono_SemiBoldItalic51pt7b" },
  { &JetBrainsMono_SemiBoldItalic52pt7b, 52, "JetBrainsMono_SemiBoldItalic52pt7b" },
  { &JetBrainsMono_SemiBoldItalic53pt7b, 53, "JetBrainsMono_SemiBoldItalic53pt7b" },
  { &JetBrainsMono_SemiBoldItalic54pt7b, 54, "JetBrainsMono_SemiBoldItalic54pt7b" },
  { &JetBrainsMono_SemiBoldItalic55pt7b, 55, "JetBrainsMono_SemiBoldItalic55pt7b" },
  { &JetBrainsMono_SemiBoldItalic56pt7b, 56, "JetBrainsMono_SemiBoldItalic56pt7b" },
  { &JetBrainsMono_SemiBoldItalic57pt7b, 57, "JetBrainsMono_SemiBoldItalic57pt7b" },
  { &JetBrainsMono_SemiBoldItalic58pt7b, 58, "JetBrainsMono_SemiBoldItalic58pt7b" },
  { &JetBrainsMono_SemiBoldItalic59pt7b, 59, "JetBrainsMono_SemiBoldItalic59pt7b" },
  { &JetBrainsMono_SemiBoldItalic60pt7b, 60, "JetBrainsMono_SemiBoldItalic60pt7b" },
  { &JetBrainsMono_SemiBoldItalic61pt7b, 61, "JetBrainsMono_SemiBoldItalic61pt7b" },
  { &JetBrainsMono_SemiBoldItalic62pt7b, 62, "JetBrainsMono_SemiBoldItalic62pt7b" },
  { &JetBrainsMono_SemiBoldItalic63pt7b, 63, "JetBrainsMono_SemiBoldItalic63pt7b" },
  { &JetBrainsMono_SemiBoldItalic64pt7b, 64, "JetBrainsMono_SemiBoldItalic64pt7b" },
  { &JetBrainsMono_SemiBoldItalic65pt7b, 65, "JetBrainsMono_SemiBoldItalic65pt7b" },
  { &JetBrainsMono_SemiBoldItalic66pt7b, 66, "JetBrainsMono_SemiBoldItalic66pt7b" },
  { &JetBrainsMono_SemiBoldItalic67pt7b, 67, "JetBrainsMono_SemiBoldItalic67pt7b" },
  { &JetBrainsMono_SemiBoldItalic68pt7b, 68, "JetBrainsMono_SemiBoldItalic68pt7b" },
  { &JetBrainsMono_SemiBoldItalic69pt7b, 69, "JetBrainsMono_SemiBoldItalic69pt7b" },
  { &JetBrainsMono_SemiBoldItalic70pt7b, 70, "JetBrainsMono_SemiBoldItalic70pt7b" },
  { &JetBrainsMono_SemiBoldItalic71pt7b, 71, "JetBrainsMono_SemiBoldItalic71pt7b" },
  { &JetBrainsMono_SemiBoldItalic72pt7b, 72, "JetBrainsMono_SemiBoldItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
