#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_MediumItalic6pt7b, 6, "NotoSans_MediumItalic6pt7b" },
  { &NotoSans_MediumItalic7pt7b, 7, "NotoSans_MediumItalic7pt7b" },
  { &NotoSans_MediumItalic8pt7b, 8, "NotoSans_MediumItalic8pt7b" },
  { &NotoSans_MediumItalic9pt7b, 9, "NotoSans_MediumItalic9pt7b" },
  { &NotoSans_MediumItalic10pt7b, 10, "NotoSans_MediumItalic10pt7b" },
  { &NotoSans_MediumItalic11pt7b, 11, "NotoSans_MediumItalic11pt7b" },
  { &NotoSans_MediumItalic12pt7b, 12, "NotoSans_MediumItalic12pt7b" },
  { &NotoSans_MediumItalic13pt7b, 13, "NotoSans_MediumItalic13pt7b" },
  { &NotoSans_MediumItalic14pt7b, 14, "NotoSans_MediumItalic14pt7b" },
  { &NotoSans_MediumItalic15pt7b, 15, "NotoSans_MediumItalic15pt7b" },
  { &NotoSans_MediumItalic16pt7b, 16, "NotoSans_MediumItalic16pt7b" },
  { &NotoSans_MediumItalic17pt7b, 17, "NotoSans_MediumItalic17pt7b" },
  { &NotoSans_MediumItalic18pt7b, 18, "NotoSans_MediumItalic18pt7b" },
  { &NotoSans_MediumItalic19pt7b, 19, "NotoSans_MediumItalic19pt7b" },
  { &NotoSans_MediumItalic20pt7b, 20, "NotoSans_MediumItalic20pt7b" },
  { &NotoSans_MediumItalic21pt7b, 21, "NotoSans_MediumItalic21pt7b" },
  { &NotoSans_MediumItalic22pt7b, 22, "NotoSans_MediumItalic22pt7b" },
  { &NotoSans_MediumItalic23pt7b, 23, "NotoSans_MediumItalic23pt7b" },
  { &NotoSans_MediumItalic24pt7b, 24, "NotoSans_MediumItalic24pt7b" },
  { &NotoSans_MediumItalic25pt7b, 25, "NotoSans_MediumItalic25pt7b" },
  { &NotoSans_MediumItalic26pt7b, 26, "NotoSans_MediumItalic26pt7b" },
  { &NotoSans_MediumItalic27pt7b, 27, "NotoSans_MediumItalic27pt7b" },
  { &NotoSans_MediumItalic28pt7b, 28, "NotoSans_MediumItalic28pt7b" },
  { &NotoSans_MediumItalic29pt7b, 29, "NotoSans_MediumItalic29pt7b" },
  { &NotoSans_MediumItalic30pt7b, 30, "NotoSans_MediumItalic30pt7b" },
  { &NotoSans_MediumItalic31pt7b, 31, "NotoSans_MediumItalic31pt7b" },
  { &NotoSans_MediumItalic32pt7b, 32, "NotoSans_MediumItalic32pt7b" },
  { &NotoSans_MediumItalic33pt7b, 33, "NotoSans_MediumItalic33pt7b" },
  { &NotoSans_MediumItalic34pt7b, 34, "NotoSans_MediumItalic34pt7b" },
  { &NotoSans_MediumItalic35pt7b, 35, "NotoSans_MediumItalic35pt7b" },
  { &NotoSans_MediumItalic36pt7b, 36, "NotoSans_MediumItalic36pt7b" },
  { &NotoSans_MediumItalic37pt7b, 37, "NotoSans_MediumItalic37pt7b" },
  { &NotoSans_MediumItalic38pt7b, 38, "NotoSans_MediumItalic38pt7b" },
  { &NotoSans_MediumItalic39pt7b, 39, "NotoSans_MediumItalic39pt7b" },
  { &NotoSans_MediumItalic40pt7b, 40, "NotoSans_MediumItalic40pt7b" },
  { &NotoSans_MediumItalic41pt7b, 41, "NotoSans_MediumItalic41pt7b" },
  { &NotoSans_MediumItalic42pt7b, 42, "NotoSans_MediumItalic42pt7b" },
  { &NotoSans_MediumItalic43pt7b, 43, "NotoSans_MediumItalic43pt7b" },
  { &NotoSans_MediumItalic44pt7b, 44, "NotoSans_MediumItalic44pt7b" },
  { &NotoSans_MediumItalic45pt7b, 45, "NotoSans_MediumItalic45pt7b" },
  { &NotoSans_MediumItalic46pt7b, 46, "NotoSans_MediumItalic46pt7b" },
  { &NotoSans_MediumItalic47pt7b, 47, "NotoSans_MediumItalic47pt7b" },
  { &NotoSans_MediumItalic48pt7b, 48, "NotoSans_MediumItalic48pt7b" },
  { &NotoSans_MediumItalic49pt7b, 49, "NotoSans_MediumItalic49pt7b" },
  { &NotoSans_MediumItalic50pt7b, 50, "NotoSans_MediumItalic50pt7b" },
  { &NotoSans_MediumItalic51pt7b, 51, "NotoSans_MediumItalic51pt7b" },
  { &NotoSans_MediumItalic52pt7b, 52, "NotoSans_MediumItalic52pt7b" },
  { &NotoSans_MediumItalic53pt7b, 53, "NotoSans_MediumItalic53pt7b" },
  { &NotoSans_MediumItalic54pt7b, 54, "NotoSans_MediumItalic54pt7b" },
  { &NotoSans_MediumItalic55pt7b, 55, "NotoSans_MediumItalic55pt7b" },
  { &NotoSans_MediumItalic56pt7b, 56, "NotoSans_MediumItalic56pt7b" },
  { &NotoSans_MediumItalic57pt7b, 57, "NotoSans_MediumItalic57pt7b" },
  { &NotoSans_MediumItalic58pt7b, 58, "NotoSans_MediumItalic58pt7b" },
  { &NotoSans_MediumItalic59pt7b, 59, "NotoSans_MediumItalic59pt7b" },
  { &NotoSans_MediumItalic60pt7b, 60, "NotoSans_MediumItalic60pt7b" },
  { &NotoSans_MediumItalic61pt7b, 61, "NotoSans_MediumItalic61pt7b" },
  { &NotoSans_MediumItalic62pt7b, 62, "NotoSans_MediumItalic62pt7b" },
  { &NotoSans_MediumItalic63pt7b, 63, "NotoSans_MediumItalic63pt7b" },
  { &NotoSans_MediumItalic64pt7b, 64, "NotoSans_MediumItalic64pt7b" },
  { &NotoSans_MediumItalic65pt7b, 65, "NotoSans_MediumItalic65pt7b" },
  { &NotoSans_MediumItalic66pt7b, 66, "NotoSans_MediumItalic66pt7b" },
  { &NotoSans_MediumItalic67pt7b, 67, "NotoSans_MediumItalic67pt7b" },
  { &NotoSans_MediumItalic68pt7b, 68, "NotoSans_MediumItalic68pt7b" },
  { &NotoSans_MediumItalic69pt7b, 69, "NotoSans_MediumItalic69pt7b" },
  { &NotoSans_MediumItalic70pt7b, 70, "NotoSans_MediumItalic70pt7b" },
  { &NotoSans_MediumItalic71pt7b, 71, "NotoSans_MediumItalic71pt7b" },
  { &NotoSans_MediumItalic72pt7b, 72, "NotoSans_MediumItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
