#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &LiberationMono_Bold6pt7b, 6, "LiberationMono_Bold6pt7b" },
  { &LiberationMono_Bold7pt7b, 7, "LiberationMono_Bold7pt7b" },
  { &LiberationMono_Bold8pt7b, 8, "LiberationMono_Bold8pt7b" },
  { &LiberationMono_Bold9pt7b, 9, "LiberationMono_Bold9pt7b" },
  { &LiberationMono_Bold10pt7b, 10, "LiberationMono_Bold10pt7b" },
  { &LiberationMono_Bold11pt7b, 11, "LiberationMono_Bold11pt7b" },
  { &LiberationMono_Bold12pt7b, 12, "LiberationMono_Bold12pt7b" },
  { &LiberationMono_Bold13pt7b, 13, "LiberationMono_Bold13pt7b" },
  { &LiberationMono_Bold14pt7b, 14, "LiberationMono_Bold14pt7b" },
  { &LiberationMono_Bold15pt7b, 15, "LiberationMono_Bold15pt7b" },
  { &LiberationMono_Bold16pt7b, 16, "LiberationMono_Bold16pt7b" },
  { &LiberationMono_Bold17pt7b, 17, "LiberationMono_Bold17pt7b" },
  { &LiberationMono_Bold18pt7b, 18, "LiberationMono_Bold18pt7b" },
  { &LiberationMono_Bold19pt7b, 19, "LiberationMono_Bold19pt7b" },
  { &LiberationMono_Bold20pt7b, 20, "LiberationMono_Bold20pt7b" },
  { &LiberationMono_Bold21pt7b, 21, "LiberationMono_Bold21pt7b" },
  { &LiberationMono_Bold22pt7b, 22, "LiberationMono_Bold22pt7b" },
  { &LiberationMono_Bold23pt7b, 23, "LiberationMono_Bold23pt7b" },
  { &LiberationMono_Bold24pt7b, 24, "LiberationMono_Bold24pt7b" },
  { &LiberationMono_Bold25pt7b, 25, "LiberationMono_Bold25pt7b" },
  { &LiberationMono_Bold26pt7b, 26, "LiberationMono_Bold26pt7b" },
  { &LiberationMono_Bold27pt7b, 27, "LiberationMono_Bold27pt7b" },
  { &LiberationMono_Bold28pt7b, 28, "LiberationMono_Bold28pt7b" },
  { &LiberationMono_Bold29pt7b, 29, "LiberationMono_Bold29pt7b" },
  { &LiberationMono_Bold30pt7b, 30, "LiberationMono_Bold30pt7b" },
  { &LiberationMono_Bold31pt7b, 31, "LiberationMono_Bold31pt7b" },
  { &LiberationMono_Bold32pt7b, 32, "LiberationMono_Bold32pt7b" },
  { &LiberationMono_Bold33pt7b, 33, "LiberationMono_Bold33pt7b" },
  { &LiberationMono_Bold34pt7b, 34, "LiberationMono_Bold34pt7b" },
  { &LiberationMono_Bold35pt7b, 35, "LiberationMono_Bold35pt7b" },
  { &LiberationMono_Bold36pt7b, 36, "LiberationMono_Bold36pt7b" },
  { &LiberationMono_Bold37pt7b, 37, "LiberationMono_Bold37pt7b" },
  { &LiberationMono_Bold38pt7b, 38, "LiberationMono_Bold38pt7b" },
  { &LiberationMono_Bold39pt7b, 39, "LiberationMono_Bold39pt7b" },
  { &LiberationMono_Bold40pt7b, 40, "LiberationMono_Bold40pt7b" },
  { &LiberationMono_Bold41pt7b, 41, "LiberationMono_Bold41pt7b" },
  { &LiberationMono_Bold42pt7b, 42, "LiberationMono_Bold42pt7b" },
  { &LiberationMono_Bold43pt7b, 43, "LiberationMono_Bold43pt7b" },
  { &LiberationMono_Bold44pt7b, 44, "LiberationMono_Bold44pt7b" },
  { &LiberationMono_Bold45pt7b, 45, "LiberationMono_Bold45pt7b" },
  { &LiberationMono_Bold46pt7b, 46, "LiberationMono_Bold46pt7b" },
  { &LiberationMono_Bold47pt7b, 47, "LiberationMono_Bold47pt7b" },
  { &LiberationMono_Bold48pt7b, 48, "LiberationMono_Bold48pt7b" },
  { &LiberationMono_Bold49pt7b, 49, "LiberationMono_Bold49pt7b" },
  { &LiberationMono_Bold50pt7b, 50, "LiberationMono_Bold50pt7b" },
  { &LiberationMono_Bold51pt7b, 51, "LiberationMono_Bold51pt7b" },
  { &LiberationMono_Bold52pt7b, 52, "LiberationMono_Bold52pt7b" },
  { &LiberationMono_Bold53pt7b, 53, "LiberationMono_Bold53pt7b" },
  { &LiberationMono_Bold54pt7b, 54, "LiberationMono_Bold54pt7b" },
  { &LiberationMono_Bold55pt7b, 55, "LiberationMono_Bold55pt7b" },
  { &LiberationMono_Bold56pt7b, 56, "LiberationMono_Bold56pt7b" },
  { &LiberationMono_Bold57pt7b, 57, "LiberationMono_Bold57pt7b" },
  { &LiberationMono_Bold58pt7b, 58, "LiberationMono_Bold58pt7b" },
  { &LiberationMono_Bold59pt7b, 59, "LiberationMono_Bold59pt7b" },
  { &LiberationMono_Bold60pt7b, 60, "LiberationMono_Bold60pt7b" },
  { &LiberationMono_Bold61pt7b, 61, "LiberationMono_Bold61pt7b" },
  { &LiberationMono_Bold62pt7b, 62, "LiberationMono_Bold62pt7b" },
  { &LiberationMono_Bold63pt7b, 63, "LiberationMono_Bold63pt7b" },
  { &LiberationMono_Bold64pt7b, 64, "LiberationMono_Bold64pt7b" },
  { &LiberationMono_Bold65pt7b, 65, "LiberationMono_Bold65pt7b" },
  { &LiberationMono_Bold66pt7b, 66, "LiberationMono_Bold66pt7b" },
  { &LiberationMono_Bold67pt7b, 67, "LiberationMono_Bold67pt7b" },
  { &LiberationMono_Bold68pt7b, 68, "LiberationMono_Bold68pt7b" },
  { &LiberationMono_Bold69pt7b, 69, "LiberationMono_Bold69pt7b" },
  { &LiberationMono_Bold70pt7b, 70, "LiberationMono_Bold70pt7b" },
  { &LiberationMono_Bold71pt7b, 71, "LiberationMono_Bold71pt7b" },
  { &LiberationMono_Bold72pt7b, 72, "LiberationMono_Bold72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
