#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_ExtraBoldItalic6pt7b, 6, "NotoSans_ExtraBoldItalic6pt7b" },
  { &NotoSans_ExtraBoldItalic7pt7b, 7, "NotoSans_ExtraBoldItalic7pt7b" },
  { &NotoSans_ExtraBoldItalic8pt7b, 8, "NotoSans_ExtraBoldItalic8pt7b" },
  { &NotoSans_ExtraBoldItalic9pt7b, 9, "NotoSans_ExtraBoldItalic9pt7b" },
  { &NotoSans_ExtraBoldItalic10pt7b, 10, "NotoSans_ExtraBoldItalic10pt7b" },
  { &NotoSans_ExtraBoldItalic11pt7b, 11, "NotoSans_ExtraBoldItalic11pt7b" },
  { &NotoSans_ExtraBoldItalic12pt7b, 12, "NotoSans_ExtraBoldItalic12pt7b" },
  { &NotoSans_ExtraBoldItalic13pt7b, 13, "NotoSans_ExtraBoldItalic13pt7b" },
  { &NotoSans_ExtraBoldItalic14pt7b, 14, "NotoSans_ExtraBoldItalic14pt7b" },
  { &NotoSans_ExtraBoldItalic15pt7b, 15, "NotoSans_ExtraBoldItalic15pt7b" },
  { &NotoSans_ExtraBoldItalic16pt7b, 16, "NotoSans_ExtraBoldItalic16pt7b" },
  { &NotoSans_ExtraBoldItalic17pt7b, 17, "NotoSans_ExtraBoldItalic17pt7b" },
  { &NotoSans_ExtraBoldItalic18pt7b, 18, "NotoSans_ExtraBoldItalic18pt7b" },
  { &NotoSans_ExtraBoldItalic19pt7b, 19, "NotoSans_ExtraBoldItalic19pt7b" },
  { &NotoSans_ExtraBoldItalic20pt7b, 20, "NotoSans_ExtraBoldItalic20pt7b" },
  { &NotoSans_ExtraBoldItalic21pt7b, 21, "NotoSans_ExtraBoldItalic21pt7b" },
  { &NotoSans_ExtraBoldItalic22pt7b, 22, "NotoSans_ExtraBoldItalic22pt7b" },
  { &NotoSans_ExtraBoldItalic23pt7b, 23, "NotoSans_ExtraBoldItalic23pt7b" },
  { &NotoSans_ExtraBoldItalic24pt7b, 24, "NotoSans_ExtraBoldItalic24pt7b" },
  { &NotoSans_ExtraBoldItalic25pt7b, 25, "NotoSans_ExtraBoldItalic25pt7b" },
  { &NotoSans_ExtraBoldItalic26pt7b, 26, "NotoSans_ExtraBoldItalic26pt7b" },
  { &NotoSans_ExtraBoldItalic27pt7b, 27, "NotoSans_ExtraBoldItalic27pt7b" },
  { &NotoSans_ExtraBoldItalic28pt7b, 28, "NotoSans_ExtraBoldItalic28pt7b" },
  { &NotoSans_ExtraBoldItalic29pt7b, 29, "NotoSans_ExtraBoldItalic29pt7b" },
  { &NotoSans_ExtraBoldItalic30pt7b, 30, "NotoSans_ExtraBoldItalic30pt7b" },
  { &NotoSans_ExtraBoldItalic31pt7b, 31, "NotoSans_ExtraBoldItalic31pt7b" },
  { &NotoSans_ExtraBoldItalic32pt7b, 32, "NotoSans_ExtraBoldItalic32pt7b" },
  { &NotoSans_ExtraBoldItalic33pt7b, 33, "NotoSans_ExtraBoldItalic33pt7b" },
  { &NotoSans_ExtraBoldItalic34pt7b, 34, "NotoSans_ExtraBoldItalic34pt7b" },
  { &NotoSans_ExtraBoldItalic35pt7b, 35, "NotoSans_ExtraBoldItalic35pt7b" },
  { &NotoSans_ExtraBoldItalic36pt7b, 36, "NotoSans_ExtraBoldItalic36pt7b" },
  { &NotoSans_ExtraBoldItalic37pt7b, 37, "NotoSans_ExtraBoldItalic37pt7b" },
  { &NotoSans_ExtraBoldItalic38pt7b, 38, "NotoSans_ExtraBoldItalic38pt7b" },
  { &NotoSans_ExtraBoldItalic39pt7b, 39, "NotoSans_ExtraBoldItalic39pt7b" },
  { &NotoSans_ExtraBoldItalic40pt7b, 40, "NotoSans_ExtraBoldItalic40pt7b" },
  { &NotoSans_ExtraBoldItalic41pt7b, 41, "NotoSans_ExtraBoldItalic41pt7b" },
  { &NotoSans_ExtraBoldItalic42pt7b, 42, "NotoSans_ExtraBoldItalic42pt7b" },
  { &NotoSans_ExtraBoldItalic43pt7b, 43, "NotoSans_ExtraBoldItalic43pt7b" },
  { &NotoSans_ExtraBoldItalic44pt7b, 44, "NotoSans_ExtraBoldItalic44pt7b" },
  { &NotoSans_ExtraBoldItalic45pt7b, 45, "NotoSans_ExtraBoldItalic45pt7b" },
  { &NotoSans_ExtraBoldItalic46pt7b, 46, "NotoSans_ExtraBoldItalic46pt7b" },
  { &NotoSans_ExtraBoldItalic47pt7b, 47, "NotoSans_ExtraBoldItalic47pt7b" },
  { &NotoSans_ExtraBoldItalic48pt7b, 48, "NotoSans_ExtraBoldItalic48pt7b" },
  { &NotoSans_ExtraBoldItalic49pt7b, 49, "NotoSans_ExtraBoldItalic49pt7b" },
  { &NotoSans_ExtraBoldItalic50pt7b, 50, "NotoSans_ExtraBoldItalic50pt7b" },
  { &NotoSans_ExtraBoldItalic51pt7b, 51, "NotoSans_ExtraBoldItalic51pt7b" },
  { &NotoSans_ExtraBoldItalic52pt7b, 52, "NotoSans_ExtraBoldItalic52pt7b" },
  { &NotoSans_ExtraBoldItalic53pt7b, 53, "NotoSans_ExtraBoldItalic53pt7b" },
  { &NotoSans_ExtraBoldItalic54pt7b, 54, "NotoSans_ExtraBoldItalic54pt7b" },
  { &NotoSans_ExtraBoldItalic55pt7b, 55, "NotoSans_ExtraBoldItalic55pt7b" },
  { &NotoSans_ExtraBoldItalic56pt7b, 56, "NotoSans_ExtraBoldItalic56pt7b" },
  { &NotoSans_ExtraBoldItalic57pt7b, 57, "NotoSans_ExtraBoldItalic57pt7b" },
  { &NotoSans_ExtraBoldItalic58pt7b, 58, "NotoSans_ExtraBoldItalic58pt7b" },
  { &NotoSans_ExtraBoldItalic59pt7b, 59, "NotoSans_ExtraBoldItalic59pt7b" },
  { &NotoSans_ExtraBoldItalic60pt7b, 60, "NotoSans_ExtraBoldItalic60pt7b" },
  { &NotoSans_ExtraBoldItalic61pt7b, 61, "NotoSans_ExtraBoldItalic61pt7b" },
  { &NotoSans_ExtraBoldItalic62pt7b, 62, "NotoSans_ExtraBoldItalic62pt7b" },
  { &NotoSans_ExtraBoldItalic63pt7b, 63, "NotoSans_ExtraBoldItalic63pt7b" },
  { &NotoSans_ExtraBoldItalic64pt7b, 64, "NotoSans_ExtraBoldItalic64pt7b" },
  { &NotoSans_ExtraBoldItalic65pt7b, 65, "NotoSans_ExtraBoldItalic65pt7b" },
  { &NotoSans_ExtraBoldItalic66pt7b, 66, "NotoSans_ExtraBoldItalic66pt7b" },
  { &NotoSans_ExtraBoldItalic67pt7b, 67, "NotoSans_ExtraBoldItalic67pt7b" },
  { &NotoSans_ExtraBoldItalic68pt7b, 68, "NotoSans_ExtraBoldItalic68pt7b" },
  { &NotoSans_ExtraBoldItalic69pt7b, 69, "NotoSans_ExtraBoldItalic69pt7b" },
  { &NotoSans_ExtraBoldItalic70pt7b, 70, "NotoSans_ExtraBoldItalic70pt7b" },
  { &NotoSans_ExtraBoldItalic71pt7b, 71, "NotoSans_ExtraBoldItalic71pt7b" },
  { &NotoSans_ExtraBoldItalic72pt7b, 72, "NotoSans_ExtraBoldItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
