#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &IBMPlexMono_MediumItalic6pt7b, 6, "IBMPlexMono_MediumItalic6pt7b" },
  { &IBMPlexMono_MediumItalic7pt7b, 7, "IBMPlexMono_MediumItalic7pt7b" },
  { &IBMPlexMono_MediumItalic8pt7b, 8, "IBMPlexMono_MediumItalic8pt7b" },
  { &IBMPlexMono_MediumItalic9pt7b, 9, "IBMPlexMono_MediumItalic9pt7b" },
  { &IBMPlexMono_MediumItalic10pt7b, 10, "IBMPlexMono_MediumItalic10pt7b" },
  { &IBMPlexMono_MediumItalic11pt7b, 11, "IBMPlexMono_MediumItalic11pt7b" },
  { &IBMPlexMono_MediumItalic12pt7b, 12, "IBMPlexMono_MediumItalic12pt7b" },
  { &IBMPlexMono_MediumItalic13pt7b, 13, "IBMPlexMono_MediumItalic13pt7b" },
  { &IBMPlexMono_MediumItalic14pt7b, 14, "IBMPlexMono_MediumItalic14pt7b" },
  { &IBMPlexMono_MediumItalic15pt7b, 15, "IBMPlexMono_MediumItalic15pt7b" },
  { &IBMPlexMono_MediumItalic16pt7b, 16, "IBMPlexMono_MediumItalic16pt7b" },
  { &IBMPlexMono_MediumItalic17pt7b, 17, "IBMPlexMono_MediumItalic17pt7b" },
  { &IBMPlexMono_MediumItalic18pt7b, 18, "IBMPlexMono_MediumItalic18pt7b" },
  { &IBMPlexMono_MediumItalic19pt7b, 19, "IBMPlexMono_MediumItalic19pt7b" },
  { &IBMPlexMono_MediumItalic20pt7b, 20, "IBMPlexMono_MediumItalic20pt7b" },
  { &IBMPlexMono_MediumItalic21pt7b, 21, "IBMPlexMono_MediumItalic21pt7b" },
  { &IBMPlexMono_MediumItalic22pt7b, 22, "IBMPlexMono_MediumItalic22pt7b" },
  { &IBMPlexMono_MediumItalic23pt7b, 23, "IBMPlexMono_MediumItalic23pt7b" },
  { &IBMPlexMono_MediumItalic24pt7b, 24, "IBMPlexMono_MediumItalic24pt7b" },
  { &IBMPlexMono_MediumItalic25pt7b, 25, "IBMPlexMono_MediumItalic25pt7b" },
  { &IBMPlexMono_MediumItalic26pt7b, 26, "IBMPlexMono_MediumItalic26pt7b" },
  { &IBMPlexMono_MediumItalic27pt7b, 27, "IBMPlexMono_MediumItalic27pt7b" },
  { &IBMPlexMono_MediumItalic28pt7b, 28, "IBMPlexMono_MediumItalic28pt7b" },
  { &IBMPlexMono_MediumItalic29pt7b, 29, "IBMPlexMono_MediumItalic29pt7b" },
  { &IBMPlexMono_MediumItalic30pt7b, 30, "IBMPlexMono_MediumItalic30pt7b" },
  { &IBMPlexMono_MediumItalic31pt7b, 31, "IBMPlexMono_MediumItalic31pt7b" },
  { &IBMPlexMono_MediumItalic32pt7b, 32, "IBMPlexMono_MediumItalic32pt7b" },
  { &IBMPlexMono_MediumItalic33pt7b, 33, "IBMPlexMono_MediumItalic33pt7b" },
  { &IBMPlexMono_MediumItalic34pt7b, 34, "IBMPlexMono_MediumItalic34pt7b" },
  { &IBMPlexMono_MediumItalic35pt7b, 35, "IBMPlexMono_MediumItalic35pt7b" },
  { &IBMPlexMono_MediumItalic36pt7b, 36, "IBMPlexMono_MediumItalic36pt7b" },
  { &IBMPlexMono_MediumItalic37pt7b, 37, "IBMPlexMono_MediumItalic37pt7b" },
  { &IBMPlexMono_MediumItalic38pt7b, 38, "IBMPlexMono_MediumItalic38pt7b" },
  { &IBMPlexMono_MediumItalic39pt7b, 39, "IBMPlexMono_MediumItalic39pt7b" },
  { &IBMPlexMono_MediumItalic40pt7b, 40, "IBMPlexMono_MediumItalic40pt7b" },
  { &IBMPlexMono_MediumItalic41pt7b, 41, "IBMPlexMono_MediumItalic41pt7b" },
  { &IBMPlexMono_MediumItalic42pt7b, 42, "IBMPlexMono_MediumItalic42pt7b" },
  { &IBMPlexMono_MediumItalic43pt7b, 43, "IBMPlexMono_MediumItalic43pt7b" },
  { &IBMPlexMono_MediumItalic44pt7b, 44, "IBMPlexMono_MediumItalic44pt7b" },
  { &IBMPlexMono_MediumItalic45pt7b, 45, "IBMPlexMono_MediumItalic45pt7b" },
  { &IBMPlexMono_MediumItalic46pt7b, 46, "IBMPlexMono_MediumItalic46pt7b" },
  { &IBMPlexMono_MediumItalic47pt7b, 47, "IBMPlexMono_MediumItalic47pt7b" },
  { &IBMPlexMono_MediumItalic48pt7b, 48, "IBMPlexMono_MediumItalic48pt7b" },
  { &IBMPlexMono_MediumItalic49pt7b, 49, "IBMPlexMono_MediumItalic49pt7b" },
  { &IBMPlexMono_MediumItalic50pt7b, 50, "IBMPlexMono_MediumItalic50pt7b" },
  { &IBMPlexMono_MediumItalic51pt7b, 51, "IBMPlexMono_MediumItalic51pt7b" },
  { &IBMPlexMono_MediumItalic52pt7b, 52, "IBMPlexMono_MediumItalic52pt7b" },
  { &IBMPlexMono_MediumItalic53pt7b, 53, "IBMPlexMono_MediumItalic53pt7b" },
  { &IBMPlexMono_MediumItalic54pt7b, 54, "IBMPlexMono_MediumItalic54pt7b" },
  { &IBMPlexMono_MediumItalic55pt7b, 55, "IBMPlexMono_MediumItalic55pt7b" },
  { &IBMPlexMono_MediumItalic56pt7b, 56, "IBMPlexMono_MediumItalic56pt7b" },
  { &IBMPlexMono_MediumItalic57pt7b, 57, "IBMPlexMono_MediumItalic57pt7b" },
  { &IBMPlexMono_MediumItalic58pt7b, 58, "IBMPlexMono_MediumItalic58pt7b" },
  { &IBMPlexMono_MediumItalic59pt7b, 59, "IBMPlexMono_MediumItalic59pt7b" },
  { &IBMPlexMono_MediumItalic60pt7b, 60, "IBMPlexMono_MediumItalic60pt7b" },
  { &IBMPlexMono_MediumItalic61pt7b, 61, "IBMPlexMono_MediumItalic61pt7b" },
  { &IBMPlexMono_MediumItalic62pt7b, 62, "IBMPlexMono_MediumItalic62pt7b" },
  { &IBMPlexMono_MediumItalic63pt7b, 63, "IBMPlexMono_MediumItalic63pt7b" },
  { &IBMPlexMono_MediumItalic64pt7b, 64, "IBMPlexMono_MediumItalic64pt7b" },
  { &IBMPlexMono_MediumItalic65pt7b, 65, "IBMPlexMono_MediumItalic65pt7b" },
  { &IBMPlexMono_MediumItalic66pt7b, 66, "IBMPlexMono_MediumItalic66pt7b" },
  { &IBMPlexMono_MediumItalic67pt7b, 67, "IBMPlexMono_MediumItalic67pt7b" },
  { &IBMPlexMono_MediumItalic68pt7b, 68, "IBMPlexMono_MediumItalic68pt7b" },
  { &IBMPlexMono_MediumItalic69pt7b, 69, "IBMPlexMono_MediumItalic69pt7b" },
  { &IBMPlexMono_MediumItalic70pt7b, 70, "IBMPlexMono_MediumItalic70pt7b" },
  { &IBMPlexMono_MediumItalic71pt7b, 71, "IBMPlexMono_MediumItalic71pt7b" },
  { &IBMPlexMono_MediumItalic72pt7b, 72, "IBMPlexMono_MediumItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
