#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &RobotoCondensed_Regular6pt7b, 6, "RobotoCondensed_Regular6pt7b" },
  { &RobotoCondensed_Regular7pt7b, 7, "RobotoCondensed_Regular7pt7b" },
  { &RobotoCondensed_Regular8pt7b, 8, "RobotoCondensed_Regular8pt7b" },
  { &RobotoCondensed_Regular9pt7b, 9, "RobotoCondensed_Regular9pt7b" },
  { &RobotoCondensed_Regular10pt7b, 10, "RobotoCondensed_Regular10pt7b" },
  { &RobotoCondensed_Regular11pt7b, 11, "RobotoCondensed_Regular11pt7b" },
  { &RobotoCondensed_Regular12pt7b, 12, "RobotoCondensed_Regular12pt7b" },
  { &RobotoCondensed_Regular13pt7b, 13, "RobotoCondensed_Regular13pt7b" },
  { &RobotoCondensed_Regular14pt7b, 14, "RobotoCondensed_Regular14pt7b" },
  { &RobotoCondensed_Regular15pt7b, 15, "RobotoCondensed_Regular15pt7b" },
  { &RobotoCondensed_Regular16pt7b, 16, "RobotoCondensed_Regular16pt7b" },
  { &RobotoCondensed_Regular17pt7b, 17, "RobotoCondensed_Regular17pt7b" },
  { &RobotoCondensed_Regular18pt7b, 18, "RobotoCondensed_Regular18pt7b" },
  { &RobotoCondensed_Regular19pt7b, 19, "RobotoCondensed_Regular19pt7b" },
  { &RobotoCondensed_Regular20pt7b, 20, "RobotoCondensed_Regular20pt7b" },
  { &RobotoCondensed_Regular21pt7b, 21, "RobotoCondensed_Regular21pt7b" },
  { &RobotoCondensed_Regular22pt7b, 22, "RobotoCondensed_Regular22pt7b" },
  { &RobotoCondensed_Regular23pt7b, 23, "RobotoCondensed_Regular23pt7b" },
  { &RobotoCondensed_Regular24pt7b, 24, "RobotoCondensed_Regular24pt7b" },
  { &RobotoCondensed_Regular25pt7b, 25, "RobotoCondensed_Regular25pt7b" },
  { &RobotoCondensed_Regular26pt7b, 26, "RobotoCondensed_Regular26pt7b" },
  { &RobotoCondensed_Regular27pt7b, 27, "RobotoCondensed_Regular27pt7b" },
  { &RobotoCondensed_Regular28pt7b, 28, "RobotoCondensed_Regular28pt7b" },
  { &RobotoCondensed_Regular29pt7b, 29, "RobotoCondensed_Regular29pt7b" },
  { &RobotoCondensed_Regular30pt7b, 30, "RobotoCondensed_Regular30pt7b" },
  { &RobotoCondensed_Regular31pt7b, 31, "RobotoCondensed_Regular31pt7b" },
  { &RobotoCondensed_Regular32pt7b, 32, "RobotoCondensed_Regular32pt7b" },
  { &RobotoCondensed_Regular33pt7b, 33, "RobotoCondensed_Regular33pt7b" },
  { &RobotoCondensed_Regular34pt7b, 34, "RobotoCondensed_Regular34pt7b" },
  { &RobotoCondensed_Regular35pt7b, 35, "RobotoCondensed_Regular35pt7b" },
  { &RobotoCondensed_Regular36pt7b, 36, "RobotoCondensed_Regular36pt7b" },
  { &RobotoCondensed_Regular37pt7b, 37, "RobotoCondensed_Regular37pt7b" },
  { &RobotoCondensed_Regular38pt7b, 38, "RobotoCondensed_Regular38pt7b" },
  { &RobotoCondensed_Regular39pt7b, 39, "RobotoCondensed_Regular39pt7b" },
  { &RobotoCondensed_Regular40pt7b, 40, "RobotoCondensed_Regular40pt7b" },
  { &RobotoCondensed_Regular41pt7b, 41, "RobotoCondensed_Regular41pt7b" },
  { &RobotoCondensed_Regular42pt7b, 42, "RobotoCondensed_Regular42pt7b" },
  { &RobotoCondensed_Regular43pt7b, 43, "RobotoCondensed_Regular43pt7b" },
  { &RobotoCondensed_Regular44pt7b, 44, "RobotoCondensed_Regular44pt7b" },
  { &RobotoCondensed_Regular45pt7b, 45, "RobotoCondensed_Regular45pt7b" },
  { &RobotoCondensed_Regular46pt7b, 46, "RobotoCondensed_Regular46pt7b" },
  { &RobotoCondensed_Regular47pt7b, 47, "RobotoCondensed_Regular47pt7b" },
  { &RobotoCondensed_Regular48pt7b, 48, "RobotoCondensed_Regular48pt7b" },
  { &RobotoCondensed_Regular49pt7b, 49, "RobotoCondensed_Regular49pt7b" },
  { &RobotoCondensed_Regular50pt7b, 50, "RobotoCondensed_Regular50pt7b" },
  { &RobotoCondensed_Regular51pt7b, 51, "RobotoCondensed_Regular51pt7b" },
  { &RobotoCondensed_Regular52pt7b, 52, "RobotoCondensed_Regular52pt7b" },
  { &RobotoCondensed_Regular53pt7b, 53, "RobotoCondensed_Regular53pt7b" },
  { &RobotoCondensed_Regular54pt7b, 54, "RobotoCondensed_Regular54pt7b" },
  { &RobotoCondensed_Regular55pt7b, 55, "RobotoCondensed_Regular55pt7b" },
  { &RobotoCondensed_Regular56pt7b, 56, "RobotoCondensed_Regular56pt7b" },
  { &RobotoCondensed_Regular57pt7b, 57, "RobotoCondensed_Regular57pt7b" },
  { &RobotoCondensed_Regular58pt7b, 58, "RobotoCondensed_Regular58pt7b" },
  { &RobotoCondensed_Regular59pt7b, 59, "RobotoCondensed_Regular59pt7b" },
  { &RobotoCondensed_Regular60pt7b, 60, "RobotoCondensed_Regular60pt7b" },
  { &RobotoCondensed_Regular61pt7b, 61, "RobotoCondensed_Regular61pt7b" },
  { &RobotoCondensed_Regular62pt7b, 62, "RobotoCondensed_Regular62pt7b" },
  { &RobotoCondensed_Regular63pt7b, 63, "RobotoCondensed_Regular63pt7b" },
  { &RobotoCondensed_Regular64pt7b, 64, "RobotoCondensed_Regular64pt7b" },
  { &RobotoCondensed_Regular65pt7b, 65, "RobotoCondensed_Regular65pt7b" },
  { &RobotoCondensed_Regular66pt7b, 66, "RobotoCondensed_Regular66pt7b" },
  { &RobotoCondensed_Regular67pt7b, 67, "RobotoCondensed_Regular67pt7b" },
  { &RobotoCondensed_Regular68pt7b, 68, "RobotoCondensed_Regular68pt7b" },
  { &RobotoCondensed_Regular69pt7b, 69, "RobotoCondensed_Regular69pt7b" },
  { &RobotoCondensed_Regular70pt7b, 70, "RobotoCondensed_Regular70pt7b" },
  { &RobotoCondensed_Regular71pt7b, 71, "RobotoCondensed_Regular71pt7b" },
  { &RobotoCondensed_Regular72pt7b, 72, "RobotoCondensed_Regular72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
