#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_SemiBold6pt7b, 6, "NotoSans_SemiBold6pt7b" },
  { &NotoSans_SemiBold7pt7b, 7, "NotoSans_SemiBold7pt7b" },
  { &NotoSans_SemiBold8pt7b, 8, "NotoSans_SemiBold8pt7b" },
  { &NotoSans_SemiBold9pt7b, 9, "NotoSans_SemiBold9pt7b" },
  { &NotoSans_SemiBold10pt7b, 10, "NotoSans_SemiBold10pt7b" },
  { &NotoSans_SemiBold11pt7b, 11, "NotoSans_SemiBold11pt7b" },
  { &NotoSans_SemiBold12pt7b, 12, "NotoSans_SemiBold12pt7b" },
  { &NotoSans_SemiBold13pt7b, 13, "NotoSans_SemiBold13pt7b" },
  { &NotoSans_SemiBold14pt7b, 14, "NotoSans_SemiBold14pt7b" },
  { &NotoSans_SemiBold15pt7b, 15, "NotoSans_SemiBold15pt7b" },
  { &NotoSans_SemiBold16pt7b, 16, "NotoSans_SemiBold16pt7b" },
  { &NotoSans_SemiBold17pt7b, 17, "NotoSans_SemiBold17pt7b" },
  { &NotoSans_SemiBold18pt7b, 18, "NotoSans_SemiBold18pt7b" },
  { &NotoSans_SemiBold19pt7b, 19, "NotoSans_SemiBold19pt7b" },
  { &NotoSans_SemiBold20pt7b, 20, "NotoSans_SemiBold20pt7b" },
  { &NotoSans_SemiBold21pt7b, 21, "NotoSans_SemiBold21pt7b" },
  { &NotoSans_SemiBold22pt7b, 22, "NotoSans_SemiBold22pt7b" },
  { &NotoSans_SemiBold23pt7b, 23, "NotoSans_SemiBold23pt7b" },
  { &NotoSans_SemiBold24pt7b, 24, "NotoSans_SemiBold24pt7b" },
  { &NotoSans_SemiBold25pt7b, 25, "NotoSans_SemiBold25pt7b" },
  { &NotoSans_SemiBold26pt7b, 26, "NotoSans_SemiBold26pt7b" },
  { &NotoSans_SemiBold27pt7b, 27, "NotoSans_SemiBold27pt7b" },
  { &NotoSans_SemiBold28pt7b, 28, "NotoSans_SemiBold28pt7b" },
  { &NotoSans_SemiBold29pt7b, 29, "NotoSans_SemiBold29pt7b" },
  { &NotoSans_SemiBold30pt7b, 30, "NotoSans_SemiBold30pt7b" },
  { &NotoSans_SemiBold31pt7b, 31, "NotoSans_SemiBold31pt7b" },
  { &NotoSans_SemiBold32pt7b, 32, "NotoSans_SemiBold32pt7b" },
  { &NotoSans_SemiBold33pt7b, 33, "NotoSans_SemiBold33pt7b" },
  { &NotoSans_SemiBold34pt7b, 34, "NotoSans_SemiBold34pt7b" },
  { &NotoSans_SemiBold35pt7b, 35, "NotoSans_SemiBold35pt7b" },
  { &NotoSans_SemiBold36pt7b, 36, "NotoSans_SemiBold36pt7b" },
  { &NotoSans_SemiBold37pt7b, 37, "NotoSans_SemiBold37pt7b" },
  { &NotoSans_SemiBold38pt7b, 38, "NotoSans_SemiBold38pt7b" },
  { &NotoSans_SemiBold39pt7b, 39, "NotoSans_SemiBold39pt7b" },
  { &NotoSans_SemiBold40pt7b, 40, "NotoSans_SemiBold40pt7b" },
  { &NotoSans_SemiBold41pt7b, 41, "NotoSans_SemiBold41pt7b" },
  { &NotoSans_SemiBold42pt7b, 42, "NotoSans_SemiBold42pt7b" },
  { &NotoSans_SemiBold43pt7b, 43, "NotoSans_SemiBold43pt7b" },
  { &NotoSans_SemiBold44pt7b, 44, "NotoSans_SemiBold44pt7b" },
  { &NotoSans_SemiBold45pt7b, 45, "NotoSans_SemiBold45pt7b" },
  { &NotoSans_SemiBold46pt7b, 46, "NotoSans_SemiBold46pt7b" },
  { &NotoSans_SemiBold47pt7b, 47, "NotoSans_SemiBold47pt7b" },
  { &NotoSans_SemiBold48pt7b, 48, "NotoSans_SemiBold48pt7b" },
  { &NotoSans_SemiBold49pt7b, 49, "NotoSans_SemiBold49pt7b" },
  { &NotoSans_SemiBold50pt7b, 50, "NotoSans_SemiBold50pt7b" },
  { &NotoSans_SemiBold51pt7b, 51, "NotoSans_SemiBold51pt7b" },
  { &NotoSans_SemiBold52pt7b, 52, "NotoSans_SemiBold52pt7b" },
  { &NotoSans_SemiBold53pt7b, 53, "NotoSans_SemiBold53pt7b" },
  { &NotoSans_SemiBold54pt7b, 54, "NotoSans_SemiBold54pt7b" },
  { &NotoSans_SemiBold55pt7b, 55, "NotoSans_SemiBold55pt7b" },
  { &NotoSans_SemiBold56pt7b, 56, "NotoSans_SemiBold56pt7b" },
  { &NotoSans_SemiBold57pt7b, 57, "NotoSans_SemiBold57pt7b" },
  { &NotoSans_SemiBold58pt7b, 58, "NotoSans_SemiBold58pt7b" },
  { &NotoSans_SemiBold59pt7b, 59, "NotoSans_SemiBold59pt7b" },
  { &NotoSans_SemiBold60pt7b, 60, "NotoSans_SemiBold60pt7b" },
  { &NotoSans_SemiBold61pt7b, 61, "NotoSans_SemiBold61pt7b" },
  { &NotoSans_SemiBold62pt7b, 62, "NotoSans_SemiBold62pt7b" },
  { &NotoSans_SemiBold63pt7b, 63, "NotoSans_SemiBold63pt7b" },
  { &NotoSans_SemiBold64pt7b, 64, "NotoSans_SemiBold64pt7b" },
  { &NotoSans_SemiBold65pt7b, 65, "NotoSans_SemiBold65pt7b" },
  { &NotoSans_SemiBold66pt7b, 66, "NotoSans_SemiBold66pt7b" },
  { &NotoSans_SemiBold67pt7b, 67, "NotoSans_SemiBold67pt7b" },
  { &NotoSans_SemiBold68pt7b, 68, "NotoSans_SemiBold68pt7b" },
  { &NotoSans_SemiBold69pt7b, 69, "NotoSans_SemiBold69pt7b" },
  { &NotoSans_SemiBold70pt7b, 70, "NotoSans_SemiBold70pt7b" },
  { &NotoSans_SemiBold71pt7b, 71, "NotoSans_SemiBold71pt7b" },
  { &NotoSans_SemiBold72pt7b, 72, "NotoSans_SemiBold72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
