#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &RobotoCondensed_BoldItalic6pt7b, 6, "RobotoCondensed_BoldItalic6pt7b" },
  { &RobotoCondensed_BoldItalic7pt7b, 7, "RobotoCondensed_BoldItalic7pt7b" },
  { &RobotoCondensed_BoldItalic8pt7b, 8, "RobotoCondensed_BoldItalic8pt7b" },
  { &RobotoCondensed_BoldItalic9pt7b, 9, "RobotoCondensed_BoldItalic9pt7b" },
  { &RobotoCondensed_BoldItalic10pt7b, 10, "RobotoCondensed_BoldItalic10pt7b" },
  { &RobotoCondensed_BoldItalic11pt7b, 11, "RobotoCondensed_BoldItalic11pt7b" },
  { &RobotoCondensed_BoldItalic12pt7b, 12, "RobotoCondensed_BoldItalic12pt7b" },
  { &RobotoCondensed_BoldItalic13pt7b, 13, "RobotoCondensed_BoldItalic13pt7b" },
  { &RobotoCondensed_BoldItalic14pt7b, 14, "RobotoCondensed_BoldItalic14pt7b" },
  { &RobotoCondensed_BoldItalic15pt7b, 15, "RobotoCondensed_BoldItalic15pt7b" },
  { &RobotoCondensed_BoldItalic16pt7b, 16, "RobotoCondensed_BoldItalic16pt7b" },
  { &RobotoCondensed_BoldItalic17pt7b, 17, "RobotoCondensed_BoldItalic17pt7b" },
  { &RobotoCondensed_BoldItalic18pt7b, 18, "RobotoCondensed_BoldItalic18pt7b" },
  { &RobotoCondensed_BoldItalic19pt7b, 19, "RobotoCondensed_BoldItalic19pt7b" },
  { &RobotoCondensed_BoldItalic20pt7b, 20, "RobotoCondensed_BoldItalic20pt7b" },
  { &RobotoCondensed_BoldItalic21pt7b, 21, "RobotoCondensed_BoldItalic21pt7b" },
  { &RobotoCondensed_BoldItalic22pt7b, 22, "RobotoCondensed_BoldItalic22pt7b" },
  { &RobotoCondensed_BoldItalic23pt7b, 23, "RobotoCondensed_BoldItalic23pt7b" },
  { &RobotoCondensed_BoldItalic24pt7b, 24, "RobotoCondensed_BoldItalic24pt7b" },
  { &RobotoCondensed_BoldItalic25pt7b, 25, "RobotoCondensed_BoldItalic25pt7b" },
  { &RobotoCondensed_BoldItalic26pt7b, 26, "RobotoCondensed_BoldItalic26pt7b" },
  { &RobotoCondensed_BoldItalic27pt7b, 27, "RobotoCondensed_BoldItalic27pt7b" },
  { &RobotoCondensed_BoldItalic28pt7b, 28, "RobotoCondensed_BoldItalic28pt7b" },
  { &RobotoCondensed_BoldItalic29pt7b, 29, "RobotoCondensed_BoldItalic29pt7b" },
  { &RobotoCondensed_BoldItalic30pt7b, 30, "RobotoCondensed_BoldItalic30pt7b" },
  { &RobotoCondensed_BoldItalic31pt7b, 31, "RobotoCondensed_BoldItalic31pt7b" },
  { &RobotoCondensed_BoldItalic32pt7b, 32, "RobotoCondensed_BoldItalic32pt7b" },
  { &RobotoCondensed_BoldItalic33pt7b, 33, "RobotoCondensed_BoldItalic33pt7b" },
  { &RobotoCondensed_BoldItalic34pt7b, 34, "RobotoCondensed_BoldItalic34pt7b" },
  { &RobotoCondensed_BoldItalic35pt7b, 35, "RobotoCondensed_BoldItalic35pt7b" },
  { &RobotoCondensed_BoldItalic36pt7b, 36, "RobotoCondensed_BoldItalic36pt7b" },
  { &RobotoCondensed_BoldItalic37pt7b, 37, "RobotoCondensed_BoldItalic37pt7b" },
  { &RobotoCondensed_BoldItalic38pt7b, 38, "RobotoCondensed_BoldItalic38pt7b" },
  { &RobotoCondensed_BoldItalic39pt7b, 39, "RobotoCondensed_BoldItalic39pt7b" },
  { &RobotoCondensed_BoldItalic40pt7b, 40, "RobotoCondensed_BoldItalic40pt7b" },
  { &RobotoCondensed_BoldItalic41pt7b, 41, "RobotoCondensed_BoldItalic41pt7b" },
  { &RobotoCondensed_BoldItalic42pt7b, 42, "RobotoCondensed_BoldItalic42pt7b" },
  { &RobotoCondensed_BoldItalic43pt7b, 43, "RobotoCondensed_BoldItalic43pt7b" },
  { &RobotoCondensed_BoldItalic44pt7b, 44, "RobotoCondensed_BoldItalic44pt7b" },
  { &RobotoCondensed_BoldItalic45pt7b, 45, "RobotoCondensed_BoldItalic45pt7b" },
  { &RobotoCondensed_BoldItalic46pt7b, 46, "RobotoCondensed_BoldItalic46pt7b" },
  { &RobotoCondensed_BoldItalic47pt7b, 47, "RobotoCondensed_BoldItalic47pt7b" },
  { &RobotoCondensed_BoldItalic48pt7b, 48, "RobotoCondensed_BoldItalic48pt7b" },
  { &RobotoCondensed_BoldItalic49pt7b, 49, "RobotoCondensed_BoldItalic49pt7b" },
  { &RobotoCondensed_BoldItalic50pt7b, 50, "RobotoCondensed_BoldItalic50pt7b" },
  { &RobotoCondensed_BoldItalic51pt7b, 51, "RobotoCondensed_BoldItalic51pt7b" },
  { &RobotoCondensed_BoldItalic52pt7b, 52, "RobotoCondensed_BoldItalic52pt7b" },
  { &RobotoCondensed_BoldItalic53pt7b, 53, "RobotoCondensed_BoldItalic53pt7b" },
  { &RobotoCondensed_BoldItalic54pt7b, 54, "RobotoCondensed_BoldItalic54pt7b" },
  { &RobotoCondensed_BoldItalic55pt7b, 55, "RobotoCondensed_BoldItalic55pt7b" },
  { &RobotoCondensed_BoldItalic56pt7b, 56, "RobotoCondensed_BoldItalic56pt7b" },
  { &RobotoCondensed_BoldItalic57pt7b, 57, "RobotoCondensed_BoldItalic57pt7b" },
  { &RobotoCondensed_BoldItalic58pt7b, 58, "RobotoCondensed_BoldItalic58pt7b" },
  { &RobotoCondensed_BoldItalic59pt7b, 59, "RobotoCondensed_BoldItalic59pt7b" },
  { &RobotoCondensed_BoldItalic60pt7b, 60, "RobotoCondensed_BoldItalic60pt7b" },
  { &RobotoCondensed_BoldItalic61pt7b, 61, "RobotoCondensed_BoldItalic61pt7b" },
  { &RobotoCondensed_BoldItalic62pt7b, 62, "RobotoCondensed_BoldItalic62pt7b" },
  { &RobotoCondensed_BoldItalic63pt7b, 63, "RobotoCondensed_BoldItalic63pt7b" },
  { &RobotoCondensed_BoldItalic64pt7b, 64, "RobotoCondensed_BoldItalic64pt7b" },
  { &RobotoCondensed_BoldItalic65pt7b, 65, "RobotoCondensed_BoldItalic65pt7b" },
  { &RobotoCondensed_BoldItalic66pt7b, 66, "RobotoCondensed_BoldItalic66pt7b" },
  { &RobotoCondensed_BoldItalic67pt7b, 67, "RobotoCondensed_BoldItalic67pt7b" },
  { &RobotoCondensed_BoldItalic68pt7b, 68, "RobotoCondensed_BoldItalic68pt7b" },
  { &RobotoCondensed_BoldItalic69pt7b, 69, "RobotoCondensed_BoldItalic69pt7b" },
  { &RobotoCondensed_BoldItalic70pt7b, 70, "RobotoCondensed_BoldItalic70pt7b" },
  { &RobotoCondensed_BoldItalic71pt7b, 71, "RobotoCondensed_BoldItalic71pt7b" },
  { &RobotoCondensed_BoldItalic72pt7b, 72, "RobotoCondensed_BoldItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
