#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_ExtraCondensed_ThinItalic6pt7b, 6, "NotoSans_ExtraCondensed_ThinItalic6pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic7pt7b, 7, "NotoSans_ExtraCondensed_ThinItalic7pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic8pt7b, 8, "NotoSans_ExtraCondensed_ThinItalic8pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic9pt7b, 9, "NotoSans_ExtraCondensed_ThinItalic9pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic10pt7b, 10, "NotoSans_ExtraCondensed_ThinItalic10pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic11pt7b, 11, "NotoSans_ExtraCondensed_ThinItalic11pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic12pt7b, 12, "NotoSans_ExtraCondensed_ThinItalic12pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic13pt7b, 13, "NotoSans_ExtraCondensed_ThinItalic13pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic14pt7b, 14, "NotoSans_ExtraCondensed_ThinItalic14pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic15pt7b, 15, "NotoSans_ExtraCondensed_ThinItalic15pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic16pt7b, 16, "NotoSans_ExtraCondensed_ThinItalic16pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic17pt7b, 17, "NotoSans_ExtraCondensed_ThinItalic17pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic18pt7b, 18, "NotoSans_ExtraCondensed_ThinItalic18pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic19pt7b, 19, "NotoSans_ExtraCondensed_ThinItalic19pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic20pt7b, 20, "NotoSans_ExtraCondensed_ThinItalic20pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic21pt7b, 21, "NotoSans_ExtraCondensed_ThinItalic21pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic22pt7b, 22, "NotoSans_ExtraCondensed_ThinItalic22pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic23pt7b, 23, "NotoSans_ExtraCondensed_ThinItalic23pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic24pt7b, 24, "NotoSans_ExtraCondensed_ThinItalic24pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic25pt7b, 25, "NotoSans_ExtraCondensed_ThinItalic25pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic26pt7b, 26, "NotoSans_ExtraCondensed_ThinItalic26pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic27pt7b, 27, "NotoSans_ExtraCondensed_ThinItalic27pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic28pt7b, 28, "NotoSans_ExtraCondensed_ThinItalic28pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic29pt7b, 29, "NotoSans_ExtraCondensed_ThinItalic29pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic30pt7b, 30, "NotoSans_ExtraCondensed_ThinItalic30pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic31pt7b, 31, "NotoSans_ExtraCondensed_ThinItalic31pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic32pt7b, 32, "NotoSans_ExtraCondensed_ThinItalic32pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic33pt7b, 33, "NotoSans_ExtraCondensed_ThinItalic33pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic34pt7b, 34, "NotoSans_ExtraCondensed_ThinItalic34pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic35pt7b, 35, "NotoSans_ExtraCondensed_ThinItalic35pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic36pt7b, 36, "NotoSans_ExtraCondensed_ThinItalic36pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic37pt7b, 37, "NotoSans_ExtraCondensed_ThinItalic37pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic38pt7b, 38, "NotoSans_ExtraCondensed_ThinItalic38pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic39pt7b, 39, "NotoSans_ExtraCondensed_ThinItalic39pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic40pt7b, 40, "NotoSans_ExtraCondensed_ThinItalic40pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic41pt7b, 41, "NotoSans_ExtraCondensed_ThinItalic41pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic42pt7b, 42, "NotoSans_ExtraCondensed_ThinItalic42pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic43pt7b, 43, "NotoSans_ExtraCondensed_ThinItalic43pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic44pt7b, 44, "NotoSans_ExtraCondensed_ThinItalic44pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic45pt7b, 45, "NotoSans_ExtraCondensed_ThinItalic45pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic46pt7b, 46, "NotoSans_ExtraCondensed_ThinItalic46pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic47pt7b, 47, "NotoSans_ExtraCondensed_ThinItalic47pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic48pt7b, 48, "NotoSans_ExtraCondensed_ThinItalic48pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic49pt7b, 49, "NotoSans_ExtraCondensed_ThinItalic49pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic50pt7b, 50, "NotoSans_ExtraCondensed_ThinItalic50pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic51pt7b, 51, "NotoSans_ExtraCondensed_ThinItalic51pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic52pt7b, 52, "NotoSans_ExtraCondensed_ThinItalic52pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic53pt7b, 53, "NotoSans_ExtraCondensed_ThinItalic53pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic54pt7b, 54, "NotoSans_ExtraCondensed_ThinItalic54pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic55pt7b, 55, "NotoSans_ExtraCondensed_ThinItalic55pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic56pt7b, 56, "NotoSans_ExtraCondensed_ThinItalic56pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic57pt7b, 57, "NotoSans_ExtraCondensed_ThinItalic57pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic58pt7b, 58, "NotoSans_ExtraCondensed_ThinItalic58pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic59pt7b, 59, "NotoSans_ExtraCondensed_ThinItalic59pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic60pt7b, 60, "NotoSans_ExtraCondensed_ThinItalic60pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic61pt7b, 61, "NotoSans_ExtraCondensed_ThinItalic61pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic62pt7b, 62, "NotoSans_ExtraCondensed_ThinItalic62pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic63pt7b, 63, "NotoSans_ExtraCondensed_ThinItalic63pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic64pt7b, 64, "NotoSans_ExtraCondensed_ThinItalic64pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic65pt7b, 65, "NotoSans_ExtraCondensed_ThinItalic65pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic66pt7b, 66, "NotoSans_ExtraCondensed_ThinItalic66pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic67pt7b, 67, "NotoSans_ExtraCondensed_ThinItalic67pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic68pt7b, 68, "NotoSans_ExtraCondensed_ThinItalic68pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic69pt7b, 69, "NotoSans_ExtraCondensed_ThinItalic69pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic70pt7b, 70, "NotoSans_ExtraCondensed_ThinItalic70pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic71pt7b, 71, "NotoSans_ExtraCondensed_ThinItalic71pt7b" },
  { &NotoSans_ExtraCondensed_ThinItalic72pt7b, 72, "NotoSans_ExtraCondensed_ThinItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
