#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &JetBrainsMono_Thin6pt7b, 6, "JetBrainsMono_Thin6pt7b" },
  { &JetBrainsMono_Thin7pt7b, 7, "JetBrainsMono_Thin7pt7b" },
  { &JetBrainsMono_Thin8pt7b, 8, "JetBrainsMono_Thin8pt7b" },
  { &JetBrainsMono_Thin9pt7b, 9, "JetBrainsMono_Thin9pt7b" },
  { &JetBrainsMono_Thin10pt7b, 10, "JetBrainsMono_Thin10pt7b" },
  { &JetBrainsMono_Thin11pt7b, 11, "JetBrainsMono_Thin11pt7b" },
  { &JetBrainsMono_Thin12pt7b, 12, "JetBrainsMono_Thin12pt7b" },
  { &JetBrainsMono_Thin13pt7b, 13, "JetBrainsMono_Thin13pt7b" },
  { &JetBrainsMono_Thin14pt7b, 14, "JetBrainsMono_Thin14pt7b" },
  { &JetBrainsMono_Thin15pt7b, 15, "JetBrainsMono_Thin15pt7b" },
  { &JetBrainsMono_Thin16pt7b, 16, "JetBrainsMono_Thin16pt7b" },
  { &JetBrainsMono_Thin17pt7b, 17, "JetBrainsMono_Thin17pt7b" },
  { &JetBrainsMono_Thin18pt7b, 18, "JetBrainsMono_Thin18pt7b" },
  { &JetBrainsMono_Thin19pt7b, 19, "JetBrainsMono_Thin19pt7b" },
  { &JetBrainsMono_Thin20pt7b, 20, "JetBrainsMono_Thin20pt7b" },
  { &JetBrainsMono_Thin21pt7b, 21, "JetBrainsMono_Thin21pt7b" },
  { &JetBrainsMono_Thin22pt7b, 22, "JetBrainsMono_Thin22pt7b" },
  { &JetBrainsMono_Thin23pt7b, 23, "JetBrainsMono_Thin23pt7b" },
  { &JetBrainsMono_Thin24pt7b, 24, "JetBrainsMono_Thin24pt7b" },
  { &JetBrainsMono_Thin25pt7b, 25, "JetBrainsMono_Thin25pt7b" },
  { &JetBrainsMono_Thin26pt7b, 26, "JetBrainsMono_Thin26pt7b" },
  { &JetBrainsMono_Thin27pt7b, 27, "JetBrainsMono_Thin27pt7b" },
  { &JetBrainsMono_Thin28pt7b, 28, "JetBrainsMono_Thin28pt7b" },
  { &JetBrainsMono_Thin29pt7b, 29, "JetBrainsMono_Thin29pt7b" },
  { &JetBrainsMono_Thin30pt7b, 30, "JetBrainsMono_Thin30pt7b" },
  { &JetBrainsMono_Thin31pt7b, 31, "JetBrainsMono_Thin31pt7b" },
  { &JetBrainsMono_Thin32pt7b, 32, "JetBrainsMono_Thin32pt7b" },
  { &JetBrainsMono_Thin33pt7b, 33, "JetBrainsMono_Thin33pt7b" },
  { &JetBrainsMono_Thin34pt7b, 34, "JetBrainsMono_Thin34pt7b" },
  { &JetBrainsMono_Thin35pt7b, 35, "JetBrainsMono_Thin35pt7b" },
  { &JetBrainsMono_Thin36pt7b, 36, "JetBrainsMono_Thin36pt7b" },
  { &JetBrainsMono_Thin37pt7b, 37, "JetBrainsMono_Thin37pt7b" },
  { &JetBrainsMono_Thin38pt7b, 38, "JetBrainsMono_Thin38pt7b" },
  { &JetBrainsMono_Thin39pt7b, 39, "JetBrainsMono_Thin39pt7b" },
  { &JetBrainsMono_Thin40pt7b, 40, "JetBrainsMono_Thin40pt7b" },
  { &JetBrainsMono_Thin41pt7b, 41, "JetBrainsMono_Thin41pt7b" },
  { &JetBrainsMono_Thin42pt7b, 42, "JetBrainsMono_Thin42pt7b" },
  { &JetBrainsMono_Thin43pt7b, 43, "JetBrainsMono_Thin43pt7b" },
  { &JetBrainsMono_Thin44pt7b, 44, "JetBrainsMono_Thin44pt7b" },
  { &JetBrainsMono_Thin45pt7b, 45, "JetBrainsMono_Thin45pt7b" },
  { &JetBrainsMono_Thin46pt7b, 46, "JetBrainsMono_Thin46pt7b" },
  { &JetBrainsMono_Thin47pt7b, 47, "JetBrainsMono_Thin47pt7b" },
  { &JetBrainsMono_Thin48pt7b, 48, "JetBrainsMono_Thin48pt7b" },
  { &JetBrainsMono_Thin49pt7b, 49, "JetBrainsMono_Thin49pt7b" },
  { &JetBrainsMono_Thin50pt7b, 50, "JetBrainsMono_Thin50pt7b" },
  { &JetBrainsMono_Thin51pt7b, 51, "JetBrainsMono_Thin51pt7b" },
  { &JetBrainsMono_Thin52pt7b, 52, "JetBrainsMono_Thin52pt7b" },
  { &JetBrainsMono_Thin53pt7b, 53, "JetBrainsMono_Thin53pt7b" },
  { &JetBrainsMono_Thin54pt7b, 54, "JetBrainsMono_Thin54pt7b" },
  { &JetBrainsMono_Thin55pt7b, 55, "JetBrainsMono_Thin55pt7b" },
  { &JetBrainsMono_Thin56pt7b, 56, "JetBrainsMono_Thin56pt7b" },
  { &JetBrainsMono_Thin57pt7b, 57, "JetBrainsMono_Thin57pt7b" },
  { &JetBrainsMono_Thin58pt7b, 58, "JetBrainsMono_Thin58pt7b" },
  { &JetBrainsMono_Thin59pt7b, 59, "JetBrainsMono_Thin59pt7b" },
  { &JetBrainsMono_Thin60pt7b, 60, "JetBrainsMono_Thin60pt7b" },
  { &JetBrainsMono_Thin61pt7b, 61, "JetBrainsMono_Thin61pt7b" },
  { &JetBrainsMono_Thin62pt7b, 62, "JetBrainsMono_Thin62pt7b" },
  { &JetBrainsMono_Thin63pt7b, 63, "JetBrainsMono_Thin63pt7b" },
  { &JetBrainsMono_Thin64pt7b, 64, "JetBrainsMono_Thin64pt7b" },
  { &JetBrainsMono_Thin65pt7b, 65, "JetBrainsMono_Thin65pt7b" },
  { &JetBrainsMono_Thin66pt7b, 66, "JetBrainsMono_Thin66pt7b" },
  { &JetBrainsMono_Thin67pt7b, 67, "JetBrainsMono_Thin67pt7b" },
  { &JetBrainsMono_Thin68pt7b, 68, "JetBrainsMono_Thin68pt7b" },
  { &JetBrainsMono_Thin69pt7b, 69, "JetBrainsMono_Thin69pt7b" },
  { &JetBrainsMono_Thin70pt7b, 70, "JetBrainsMono_Thin70pt7b" },
  { &JetBrainsMono_Thin71pt7b, 71, "JetBrainsMono_Thin71pt7b" },
  { &JetBrainsMono_Thin72pt7b, 72, "JetBrainsMono_Thin72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
