#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &IBMPlexMono_Light6pt7b, 6, "IBMPlexMono_Light6pt7b" },
  { &IBMPlexMono_Light7pt7b, 7, "IBMPlexMono_Light7pt7b" },
  { &IBMPlexMono_Light8pt7b, 8, "IBMPlexMono_Light8pt7b" },
  { &IBMPlexMono_Light9pt7b, 9, "IBMPlexMono_Light9pt7b" },
  { &IBMPlexMono_Light10pt7b, 10, "IBMPlexMono_Light10pt7b" },
  { &IBMPlexMono_Light11pt7b, 11, "IBMPlexMono_Light11pt7b" },
  { &IBMPlexMono_Light12pt7b, 12, "IBMPlexMono_Light12pt7b" },
  { &IBMPlexMono_Light13pt7b, 13, "IBMPlexMono_Light13pt7b" },
  { &IBMPlexMono_Light14pt7b, 14, "IBMPlexMono_Light14pt7b" },
  { &IBMPlexMono_Light15pt7b, 15, "IBMPlexMono_Light15pt7b" },
  { &IBMPlexMono_Light16pt7b, 16, "IBMPlexMono_Light16pt7b" },
  { &IBMPlexMono_Light17pt7b, 17, "IBMPlexMono_Light17pt7b" },
  { &IBMPlexMono_Light18pt7b, 18, "IBMPlexMono_Light18pt7b" },
  { &IBMPlexMono_Light19pt7b, 19, "IBMPlexMono_Light19pt7b" },
  { &IBMPlexMono_Light20pt7b, 20, "IBMPlexMono_Light20pt7b" },
  { &IBMPlexMono_Light21pt7b, 21, "IBMPlexMono_Light21pt7b" },
  { &IBMPlexMono_Light22pt7b, 22, "IBMPlexMono_Light22pt7b" },
  { &IBMPlexMono_Light23pt7b, 23, "IBMPlexMono_Light23pt7b" },
  { &IBMPlexMono_Light24pt7b, 24, "IBMPlexMono_Light24pt7b" },
  { &IBMPlexMono_Light25pt7b, 25, "IBMPlexMono_Light25pt7b" },
  { &IBMPlexMono_Light26pt7b, 26, "IBMPlexMono_Light26pt7b" },
  { &IBMPlexMono_Light27pt7b, 27, "IBMPlexMono_Light27pt7b" },
  { &IBMPlexMono_Light28pt7b, 28, "IBMPlexMono_Light28pt7b" },
  { &IBMPlexMono_Light29pt7b, 29, "IBMPlexMono_Light29pt7b" },
  { &IBMPlexMono_Light30pt7b, 30, "IBMPlexMono_Light30pt7b" },
  { &IBMPlexMono_Light31pt7b, 31, "IBMPlexMono_Light31pt7b" },
  { &IBMPlexMono_Light32pt7b, 32, "IBMPlexMono_Light32pt7b" },
  { &IBMPlexMono_Light33pt7b, 33, "IBMPlexMono_Light33pt7b" },
  { &IBMPlexMono_Light34pt7b, 34, "IBMPlexMono_Light34pt7b" },
  { &IBMPlexMono_Light35pt7b, 35, "IBMPlexMono_Light35pt7b" },
  { &IBMPlexMono_Light36pt7b, 36, "IBMPlexMono_Light36pt7b" },
  { &IBMPlexMono_Light37pt7b, 37, "IBMPlexMono_Light37pt7b" },
  { &IBMPlexMono_Light38pt7b, 38, "IBMPlexMono_Light38pt7b" },
  { &IBMPlexMono_Light39pt7b, 39, "IBMPlexMono_Light39pt7b" },
  { &IBMPlexMono_Light40pt7b, 40, "IBMPlexMono_Light40pt7b" },
  { &IBMPlexMono_Light41pt7b, 41, "IBMPlexMono_Light41pt7b" },
  { &IBMPlexMono_Light42pt7b, 42, "IBMPlexMono_Light42pt7b" },
  { &IBMPlexMono_Light43pt7b, 43, "IBMPlexMono_Light43pt7b" },
  { &IBMPlexMono_Light44pt7b, 44, "IBMPlexMono_Light44pt7b" },
  { &IBMPlexMono_Light45pt7b, 45, "IBMPlexMono_Light45pt7b" },
  { &IBMPlexMono_Light46pt7b, 46, "IBMPlexMono_Light46pt7b" },
  { &IBMPlexMono_Light47pt7b, 47, "IBMPlexMono_Light47pt7b" },
  { &IBMPlexMono_Light48pt7b, 48, "IBMPlexMono_Light48pt7b" },
  { &IBMPlexMono_Light49pt7b, 49, "IBMPlexMono_Light49pt7b" },
  { &IBMPlexMono_Light50pt7b, 50, "IBMPlexMono_Light50pt7b" },
  { &IBMPlexMono_Light51pt7b, 51, "IBMPlexMono_Light51pt7b" },
  { &IBMPlexMono_Light52pt7b, 52, "IBMPlexMono_Light52pt7b" },
  { &IBMPlexMono_Light53pt7b, 53, "IBMPlexMono_Light53pt7b" },
  { &IBMPlexMono_Light54pt7b, 54, "IBMPlexMono_Light54pt7b" },
  { &IBMPlexMono_Light55pt7b, 55, "IBMPlexMono_Light55pt7b" },
  { &IBMPlexMono_Light56pt7b, 56, "IBMPlexMono_Light56pt7b" },
  { &IBMPlexMono_Light57pt7b, 57, "IBMPlexMono_Light57pt7b" },
  { &IBMPlexMono_Light58pt7b, 58, "IBMPlexMono_Light58pt7b" },
  { &IBMPlexMono_Light59pt7b, 59, "IBMPlexMono_Light59pt7b" },
  { &IBMPlexMono_Light60pt7b, 60, "IBMPlexMono_Light60pt7b" },
  { &IBMPlexMono_Light61pt7b, 61, "IBMPlexMono_Light61pt7b" },
  { &IBMPlexMono_Light62pt7b, 62, "IBMPlexMono_Light62pt7b" },
  { &IBMPlexMono_Light63pt7b, 63, "IBMPlexMono_Light63pt7b" },
  { &IBMPlexMono_Light64pt7b, 64, "IBMPlexMono_Light64pt7b" },
  { &IBMPlexMono_Light65pt7b, 65, "IBMPlexMono_Light65pt7b" },
  { &IBMPlexMono_Light66pt7b, 66, "IBMPlexMono_Light66pt7b" },
  { &IBMPlexMono_Light67pt7b, 67, "IBMPlexMono_Light67pt7b" },
  { &IBMPlexMono_Light68pt7b, 68, "IBMPlexMono_Light68pt7b" },
  { &IBMPlexMono_Light69pt7b, 69, "IBMPlexMono_Light69pt7b" },
  { &IBMPlexMono_Light70pt7b, 70, "IBMPlexMono_Light70pt7b" },
  { &IBMPlexMono_Light71pt7b, 71, "IBMPlexMono_Light71pt7b" },
  { &IBMPlexMono_Light72pt7b, 72, "IBMPlexMono_Light72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
