#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &UbuntuSansMono_SemiBoldItalic6pt7b, 6, "UbuntuSansMono_SemiBoldItalic6pt7b" },
  { &UbuntuSansMono_SemiBoldItalic7pt7b, 7, "UbuntuSansMono_SemiBoldItalic7pt7b" },
  { &UbuntuSansMono_SemiBoldItalic8pt7b, 8, "UbuntuSansMono_SemiBoldItalic8pt7b" },
  { &UbuntuSansMono_SemiBoldItalic9pt7b, 9, "UbuntuSansMono_SemiBoldItalic9pt7b" },
  { &UbuntuSansMono_SemiBoldItalic10pt7b, 10, "UbuntuSansMono_SemiBoldItalic10pt7b" },
  { &UbuntuSansMono_SemiBoldItalic11pt7b, 11, "UbuntuSansMono_SemiBoldItalic11pt7b" },
  { &UbuntuSansMono_SemiBoldItalic12pt7b, 12, "UbuntuSansMono_SemiBoldItalic12pt7b" },
  { &UbuntuSansMono_SemiBoldItalic13pt7b, 13, "UbuntuSansMono_SemiBoldItalic13pt7b" },
  { &UbuntuSansMono_SemiBoldItalic14pt7b, 14, "UbuntuSansMono_SemiBoldItalic14pt7b" },
  { &UbuntuSansMono_SemiBoldItalic15pt7b, 15, "UbuntuSansMono_SemiBoldItalic15pt7b" },
  { &UbuntuSansMono_SemiBoldItalic16pt7b, 16, "UbuntuSansMono_SemiBoldItalic16pt7b" },
  { &UbuntuSansMono_SemiBoldItalic17pt7b, 17, "UbuntuSansMono_SemiBoldItalic17pt7b" },
  { &UbuntuSansMono_SemiBoldItalic18pt7b, 18, "UbuntuSansMono_SemiBoldItalic18pt7b" },
  { &UbuntuSansMono_SemiBoldItalic19pt7b, 19, "UbuntuSansMono_SemiBoldItalic19pt7b" },
  { &UbuntuSansMono_SemiBoldItalic20pt7b, 20, "UbuntuSansMono_SemiBoldItalic20pt7b" },
  { &UbuntuSansMono_SemiBoldItalic21pt7b, 21, "UbuntuSansMono_SemiBoldItalic21pt7b" },
  { &UbuntuSansMono_SemiBoldItalic22pt7b, 22, "UbuntuSansMono_SemiBoldItalic22pt7b" },
  { &UbuntuSansMono_SemiBoldItalic23pt7b, 23, "UbuntuSansMono_SemiBoldItalic23pt7b" },
  { &UbuntuSansMono_SemiBoldItalic24pt7b, 24, "UbuntuSansMono_SemiBoldItalic24pt7b" },
  { &UbuntuSansMono_SemiBoldItalic25pt7b, 25, "UbuntuSansMono_SemiBoldItalic25pt7b" },
  { &UbuntuSansMono_SemiBoldItalic26pt7b, 26, "UbuntuSansMono_SemiBoldItalic26pt7b" },
  { &UbuntuSansMono_SemiBoldItalic27pt7b, 27, "UbuntuSansMono_SemiBoldItalic27pt7b" },
  { &UbuntuSansMono_SemiBoldItalic28pt7b, 28, "UbuntuSansMono_SemiBoldItalic28pt7b" },
  { &UbuntuSansMono_SemiBoldItalic29pt7b, 29, "UbuntuSansMono_SemiBoldItalic29pt7b" },
  { &UbuntuSansMono_SemiBoldItalic30pt7b, 30, "UbuntuSansMono_SemiBoldItalic30pt7b" },
  { &UbuntuSansMono_SemiBoldItalic31pt7b, 31, "UbuntuSansMono_SemiBoldItalic31pt7b" },
  { &UbuntuSansMono_SemiBoldItalic32pt7b, 32, "UbuntuSansMono_SemiBoldItalic32pt7b" },
  { &UbuntuSansMono_SemiBoldItalic33pt7b, 33, "UbuntuSansMono_SemiBoldItalic33pt7b" },
  { &UbuntuSansMono_SemiBoldItalic34pt7b, 34, "UbuntuSansMono_SemiBoldItalic34pt7b" },
  { &UbuntuSansMono_SemiBoldItalic35pt7b, 35, "UbuntuSansMono_SemiBoldItalic35pt7b" },
  { &UbuntuSansMono_SemiBoldItalic36pt7b, 36, "UbuntuSansMono_SemiBoldItalic36pt7b" },
  { &UbuntuSansMono_SemiBoldItalic37pt7b, 37, "UbuntuSansMono_SemiBoldItalic37pt7b" },
  { &UbuntuSansMono_SemiBoldItalic38pt7b, 38, "UbuntuSansMono_SemiBoldItalic38pt7b" },
  { &UbuntuSansMono_SemiBoldItalic39pt7b, 39, "UbuntuSansMono_SemiBoldItalic39pt7b" },
  { &UbuntuSansMono_SemiBoldItalic40pt7b, 40, "UbuntuSansMono_SemiBoldItalic40pt7b" },
  { &UbuntuSansMono_SemiBoldItalic41pt7b, 41, "UbuntuSansMono_SemiBoldItalic41pt7b" },
  { &UbuntuSansMono_SemiBoldItalic42pt7b, 42, "UbuntuSansMono_SemiBoldItalic42pt7b" },
  { &UbuntuSansMono_SemiBoldItalic43pt7b, 43, "UbuntuSansMono_SemiBoldItalic43pt7b" },
  { &UbuntuSansMono_SemiBoldItalic44pt7b, 44, "UbuntuSansMono_SemiBoldItalic44pt7b" },
  { &UbuntuSansMono_SemiBoldItalic45pt7b, 45, "UbuntuSansMono_SemiBoldItalic45pt7b" },
  { &UbuntuSansMono_SemiBoldItalic46pt7b, 46, "UbuntuSansMono_SemiBoldItalic46pt7b" },
  { &UbuntuSansMono_SemiBoldItalic47pt7b, 47, "UbuntuSansMono_SemiBoldItalic47pt7b" },
  { &UbuntuSansMono_SemiBoldItalic48pt7b, 48, "UbuntuSansMono_SemiBoldItalic48pt7b" },
  { &UbuntuSansMono_SemiBoldItalic49pt7b, 49, "UbuntuSansMono_SemiBoldItalic49pt7b" },
  { &UbuntuSansMono_SemiBoldItalic50pt7b, 50, "UbuntuSansMono_SemiBoldItalic50pt7b" },
  { &UbuntuSansMono_SemiBoldItalic51pt7b, 51, "UbuntuSansMono_SemiBoldItalic51pt7b" },
  { &UbuntuSansMono_SemiBoldItalic52pt7b, 52, "UbuntuSansMono_SemiBoldItalic52pt7b" },
  { &UbuntuSansMono_SemiBoldItalic53pt7b, 53, "UbuntuSansMono_SemiBoldItalic53pt7b" },
  { &UbuntuSansMono_SemiBoldItalic54pt7b, 54, "UbuntuSansMono_SemiBoldItalic54pt7b" },
  { &UbuntuSansMono_SemiBoldItalic55pt7b, 55, "UbuntuSansMono_SemiBoldItalic55pt7b" },
  { &UbuntuSansMono_SemiBoldItalic56pt7b, 56, "UbuntuSansMono_SemiBoldItalic56pt7b" },
  { &UbuntuSansMono_SemiBoldItalic57pt7b, 57, "UbuntuSansMono_SemiBoldItalic57pt7b" },
  { &UbuntuSansMono_SemiBoldItalic58pt7b, 58, "UbuntuSansMono_SemiBoldItalic58pt7b" },
  { &UbuntuSansMono_SemiBoldItalic59pt7b, 59, "UbuntuSansMono_SemiBoldItalic59pt7b" },
  { &UbuntuSansMono_SemiBoldItalic60pt7b, 60, "UbuntuSansMono_SemiBoldItalic60pt7b" },
  { &UbuntuSansMono_SemiBoldItalic61pt7b, 61, "UbuntuSansMono_SemiBoldItalic61pt7b" },
  { &UbuntuSansMono_SemiBoldItalic62pt7b, 62, "UbuntuSansMono_SemiBoldItalic62pt7b" },
  { &UbuntuSansMono_SemiBoldItalic63pt7b, 63, "UbuntuSansMono_SemiBoldItalic63pt7b" },
  { &UbuntuSansMono_SemiBoldItalic64pt7b, 64, "UbuntuSansMono_SemiBoldItalic64pt7b" },
  { &UbuntuSansMono_SemiBoldItalic65pt7b, 65, "UbuntuSansMono_SemiBoldItalic65pt7b" },
  { &UbuntuSansMono_SemiBoldItalic66pt7b, 66, "UbuntuSansMono_SemiBoldItalic66pt7b" },
  { &UbuntuSansMono_SemiBoldItalic67pt7b, 67, "UbuntuSansMono_SemiBoldItalic67pt7b" },
  { &UbuntuSansMono_SemiBoldItalic68pt7b, 68, "UbuntuSansMono_SemiBoldItalic68pt7b" },
  { &UbuntuSansMono_SemiBoldItalic69pt7b, 69, "UbuntuSansMono_SemiBoldItalic69pt7b" },
  { &UbuntuSansMono_SemiBoldItalic70pt7b, 70, "UbuntuSansMono_SemiBoldItalic70pt7b" },
  { &UbuntuSansMono_SemiBoldItalic71pt7b, 71, "UbuntuSansMono_SemiBoldItalic71pt7b" },
  { &UbuntuSansMono_SemiBoldItalic72pt7b, 72, "UbuntuSansMono_SemiBoldItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
