#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &RobotoCondensed_MediumItalic6pt7b, 6, "RobotoCondensed_MediumItalic6pt7b" },
  { &RobotoCondensed_MediumItalic7pt7b, 7, "RobotoCondensed_MediumItalic7pt7b" },
  { &RobotoCondensed_MediumItalic8pt7b, 8, "RobotoCondensed_MediumItalic8pt7b" },
  { &RobotoCondensed_MediumItalic9pt7b, 9, "RobotoCondensed_MediumItalic9pt7b" },
  { &RobotoCondensed_MediumItalic10pt7b, 10, "RobotoCondensed_MediumItalic10pt7b" },
  { &RobotoCondensed_MediumItalic11pt7b, 11, "RobotoCondensed_MediumItalic11pt7b" },
  { &RobotoCondensed_MediumItalic12pt7b, 12, "RobotoCondensed_MediumItalic12pt7b" },
  { &RobotoCondensed_MediumItalic13pt7b, 13, "RobotoCondensed_MediumItalic13pt7b" },
  { &RobotoCondensed_MediumItalic14pt7b, 14, "RobotoCondensed_MediumItalic14pt7b" },
  { &RobotoCondensed_MediumItalic15pt7b, 15, "RobotoCondensed_MediumItalic15pt7b" },
  { &RobotoCondensed_MediumItalic16pt7b, 16, "RobotoCondensed_MediumItalic16pt7b" },
  { &RobotoCondensed_MediumItalic17pt7b, 17, "RobotoCondensed_MediumItalic17pt7b" },
  { &RobotoCondensed_MediumItalic18pt7b, 18, "RobotoCondensed_MediumItalic18pt7b" },
  { &RobotoCondensed_MediumItalic19pt7b, 19, "RobotoCondensed_MediumItalic19pt7b" },
  { &RobotoCondensed_MediumItalic20pt7b, 20, "RobotoCondensed_MediumItalic20pt7b" },
  { &RobotoCondensed_MediumItalic21pt7b, 21, "RobotoCondensed_MediumItalic21pt7b" },
  { &RobotoCondensed_MediumItalic22pt7b, 22, "RobotoCondensed_MediumItalic22pt7b" },
  { &RobotoCondensed_MediumItalic23pt7b, 23, "RobotoCondensed_MediumItalic23pt7b" },
  { &RobotoCondensed_MediumItalic24pt7b, 24, "RobotoCondensed_MediumItalic24pt7b" },
  { &RobotoCondensed_MediumItalic25pt7b, 25, "RobotoCondensed_MediumItalic25pt7b" },
  { &RobotoCondensed_MediumItalic26pt7b, 26, "RobotoCondensed_MediumItalic26pt7b" },
  { &RobotoCondensed_MediumItalic27pt7b, 27, "RobotoCondensed_MediumItalic27pt7b" },
  { &RobotoCondensed_MediumItalic28pt7b, 28, "RobotoCondensed_MediumItalic28pt7b" },
  { &RobotoCondensed_MediumItalic29pt7b, 29, "RobotoCondensed_MediumItalic29pt7b" },
  { &RobotoCondensed_MediumItalic30pt7b, 30, "RobotoCondensed_MediumItalic30pt7b" },
  { &RobotoCondensed_MediumItalic31pt7b, 31, "RobotoCondensed_MediumItalic31pt7b" },
  { &RobotoCondensed_MediumItalic32pt7b, 32, "RobotoCondensed_MediumItalic32pt7b" },
  { &RobotoCondensed_MediumItalic33pt7b, 33, "RobotoCondensed_MediumItalic33pt7b" },
  { &RobotoCondensed_MediumItalic34pt7b, 34, "RobotoCondensed_MediumItalic34pt7b" },
  { &RobotoCondensed_MediumItalic35pt7b, 35, "RobotoCondensed_MediumItalic35pt7b" },
  { &RobotoCondensed_MediumItalic36pt7b, 36, "RobotoCondensed_MediumItalic36pt7b" },
  { &RobotoCondensed_MediumItalic37pt7b, 37, "RobotoCondensed_MediumItalic37pt7b" },
  { &RobotoCondensed_MediumItalic38pt7b, 38, "RobotoCondensed_MediumItalic38pt7b" },
  { &RobotoCondensed_MediumItalic39pt7b, 39, "RobotoCondensed_MediumItalic39pt7b" },
  { &RobotoCondensed_MediumItalic40pt7b, 40, "RobotoCondensed_MediumItalic40pt7b" },
  { &RobotoCondensed_MediumItalic41pt7b, 41, "RobotoCondensed_MediumItalic41pt7b" },
  { &RobotoCondensed_MediumItalic42pt7b, 42, "RobotoCondensed_MediumItalic42pt7b" },
  { &RobotoCondensed_MediumItalic43pt7b, 43, "RobotoCondensed_MediumItalic43pt7b" },
  { &RobotoCondensed_MediumItalic44pt7b, 44, "RobotoCondensed_MediumItalic44pt7b" },
  { &RobotoCondensed_MediumItalic45pt7b, 45, "RobotoCondensed_MediumItalic45pt7b" },
  { &RobotoCondensed_MediumItalic46pt7b, 46, "RobotoCondensed_MediumItalic46pt7b" },
  { &RobotoCondensed_MediumItalic47pt7b, 47, "RobotoCondensed_MediumItalic47pt7b" },
  { &RobotoCondensed_MediumItalic48pt7b, 48, "RobotoCondensed_MediumItalic48pt7b" },
  { &RobotoCondensed_MediumItalic49pt7b, 49, "RobotoCondensed_MediumItalic49pt7b" },
  { &RobotoCondensed_MediumItalic50pt7b, 50, "RobotoCondensed_MediumItalic50pt7b" },
  { &RobotoCondensed_MediumItalic51pt7b, 51, "RobotoCondensed_MediumItalic51pt7b" },
  { &RobotoCondensed_MediumItalic52pt7b, 52, "RobotoCondensed_MediumItalic52pt7b" },
  { &RobotoCondensed_MediumItalic53pt7b, 53, "RobotoCondensed_MediumItalic53pt7b" },
  { &RobotoCondensed_MediumItalic54pt7b, 54, "RobotoCondensed_MediumItalic54pt7b" },
  { &RobotoCondensed_MediumItalic55pt7b, 55, "RobotoCondensed_MediumItalic55pt7b" },
  { &RobotoCondensed_MediumItalic56pt7b, 56, "RobotoCondensed_MediumItalic56pt7b" },
  { &RobotoCondensed_MediumItalic57pt7b, 57, "RobotoCondensed_MediumItalic57pt7b" },
  { &RobotoCondensed_MediumItalic58pt7b, 58, "RobotoCondensed_MediumItalic58pt7b" },
  { &RobotoCondensed_MediumItalic59pt7b, 59, "RobotoCondensed_MediumItalic59pt7b" },
  { &RobotoCondensed_MediumItalic60pt7b, 60, "RobotoCondensed_MediumItalic60pt7b" },
  { &RobotoCondensed_MediumItalic61pt7b, 61, "RobotoCondensed_MediumItalic61pt7b" },
  { &RobotoCondensed_MediumItalic62pt7b, 62, "RobotoCondensed_MediumItalic62pt7b" },
  { &RobotoCondensed_MediumItalic63pt7b, 63, "RobotoCondensed_MediumItalic63pt7b" },
  { &RobotoCondensed_MediumItalic64pt7b, 64, "RobotoCondensed_MediumItalic64pt7b" },
  { &RobotoCondensed_MediumItalic65pt7b, 65, "RobotoCondensed_MediumItalic65pt7b" },
  { &RobotoCondensed_MediumItalic66pt7b, 66, "RobotoCondensed_MediumItalic66pt7b" },
  { &RobotoCondensed_MediumItalic67pt7b, 67, "RobotoCondensed_MediumItalic67pt7b" },
  { &RobotoCondensed_MediumItalic68pt7b, 68, "RobotoCondensed_MediumItalic68pt7b" },
  { &RobotoCondensed_MediumItalic69pt7b, 69, "RobotoCondensed_MediumItalic69pt7b" },
  { &RobotoCondensed_MediumItalic70pt7b, 70, "RobotoCondensed_MediumItalic70pt7b" },
  { &RobotoCondensed_MediumItalic71pt7b, 71, "RobotoCondensed_MediumItalic71pt7b" },
  { &RobotoCondensed_MediumItalic72pt7b, 72, "RobotoCondensed_MediumItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
