#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_SemiCondensed_LightItalic6pt7b, 6, "NotoSans_SemiCondensed_LightItalic6pt7b" },
  { &NotoSans_SemiCondensed_LightItalic7pt7b, 7, "NotoSans_SemiCondensed_LightItalic7pt7b" },
  { &NotoSans_SemiCondensed_LightItalic8pt7b, 8, "NotoSans_SemiCondensed_LightItalic8pt7b" },
  { &NotoSans_SemiCondensed_LightItalic9pt7b, 9, "NotoSans_SemiCondensed_LightItalic9pt7b" },
  { &NotoSans_SemiCondensed_LightItalic10pt7b, 10, "NotoSans_SemiCondensed_LightItalic10pt7b" },
  { &NotoSans_SemiCondensed_LightItalic11pt7b, 11, "NotoSans_SemiCondensed_LightItalic11pt7b" },
  { &NotoSans_SemiCondensed_LightItalic12pt7b, 12, "NotoSans_SemiCondensed_LightItalic12pt7b" },
  { &NotoSans_SemiCondensed_LightItalic13pt7b, 13, "NotoSans_SemiCondensed_LightItalic13pt7b" },
  { &NotoSans_SemiCondensed_LightItalic14pt7b, 14, "NotoSans_SemiCondensed_LightItalic14pt7b" },
  { &NotoSans_SemiCondensed_LightItalic15pt7b, 15, "NotoSans_SemiCondensed_LightItalic15pt7b" },
  { &NotoSans_SemiCondensed_LightItalic16pt7b, 16, "NotoSans_SemiCondensed_LightItalic16pt7b" },
  { &NotoSans_SemiCondensed_LightItalic17pt7b, 17, "NotoSans_SemiCondensed_LightItalic17pt7b" },
  { &NotoSans_SemiCondensed_LightItalic18pt7b, 18, "NotoSans_SemiCondensed_LightItalic18pt7b" },
  { &NotoSans_SemiCondensed_LightItalic19pt7b, 19, "NotoSans_SemiCondensed_LightItalic19pt7b" },
  { &NotoSans_SemiCondensed_LightItalic20pt7b, 20, "NotoSans_SemiCondensed_LightItalic20pt7b" },
  { &NotoSans_SemiCondensed_LightItalic21pt7b, 21, "NotoSans_SemiCondensed_LightItalic21pt7b" },
  { &NotoSans_SemiCondensed_LightItalic22pt7b, 22, "NotoSans_SemiCondensed_LightItalic22pt7b" },
  { &NotoSans_SemiCondensed_LightItalic23pt7b, 23, "NotoSans_SemiCondensed_LightItalic23pt7b" },
  { &NotoSans_SemiCondensed_LightItalic24pt7b, 24, "NotoSans_SemiCondensed_LightItalic24pt7b" },
  { &NotoSans_SemiCondensed_LightItalic25pt7b, 25, "NotoSans_SemiCondensed_LightItalic25pt7b" },
  { &NotoSans_SemiCondensed_LightItalic26pt7b, 26, "NotoSans_SemiCondensed_LightItalic26pt7b" },
  { &NotoSans_SemiCondensed_LightItalic27pt7b, 27, "NotoSans_SemiCondensed_LightItalic27pt7b" },
  { &NotoSans_SemiCondensed_LightItalic28pt7b, 28, "NotoSans_SemiCondensed_LightItalic28pt7b" },
  { &NotoSans_SemiCondensed_LightItalic29pt7b, 29, "NotoSans_SemiCondensed_LightItalic29pt7b" },
  { &NotoSans_SemiCondensed_LightItalic30pt7b, 30, "NotoSans_SemiCondensed_LightItalic30pt7b" },
  { &NotoSans_SemiCondensed_LightItalic31pt7b, 31, "NotoSans_SemiCondensed_LightItalic31pt7b" },
  { &NotoSans_SemiCondensed_LightItalic32pt7b, 32, "NotoSans_SemiCondensed_LightItalic32pt7b" },
  { &NotoSans_SemiCondensed_LightItalic33pt7b, 33, "NotoSans_SemiCondensed_LightItalic33pt7b" },
  { &NotoSans_SemiCondensed_LightItalic34pt7b, 34, "NotoSans_SemiCondensed_LightItalic34pt7b" },
  { &NotoSans_SemiCondensed_LightItalic35pt7b, 35, "NotoSans_SemiCondensed_LightItalic35pt7b" },
  { &NotoSans_SemiCondensed_LightItalic36pt7b, 36, "NotoSans_SemiCondensed_LightItalic36pt7b" },
  { &NotoSans_SemiCondensed_LightItalic37pt7b, 37, "NotoSans_SemiCondensed_LightItalic37pt7b" },
  { &NotoSans_SemiCondensed_LightItalic38pt7b, 38, "NotoSans_SemiCondensed_LightItalic38pt7b" },
  { &NotoSans_SemiCondensed_LightItalic39pt7b, 39, "NotoSans_SemiCondensed_LightItalic39pt7b" },
  { &NotoSans_SemiCondensed_LightItalic40pt7b, 40, "NotoSans_SemiCondensed_LightItalic40pt7b" },
  { &NotoSans_SemiCondensed_LightItalic41pt7b, 41, "NotoSans_SemiCondensed_LightItalic41pt7b" },
  { &NotoSans_SemiCondensed_LightItalic42pt7b, 42, "NotoSans_SemiCondensed_LightItalic42pt7b" },
  { &NotoSans_SemiCondensed_LightItalic43pt7b, 43, "NotoSans_SemiCondensed_LightItalic43pt7b" },
  { &NotoSans_SemiCondensed_LightItalic44pt7b, 44, "NotoSans_SemiCondensed_LightItalic44pt7b" },
  { &NotoSans_SemiCondensed_LightItalic45pt7b, 45, "NotoSans_SemiCondensed_LightItalic45pt7b" },
  { &NotoSans_SemiCondensed_LightItalic46pt7b, 46, "NotoSans_SemiCondensed_LightItalic46pt7b" },
  { &NotoSans_SemiCondensed_LightItalic47pt7b, 47, "NotoSans_SemiCondensed_LightItalic47pt7b" },
  { &NotoSans_SemiCondensed_LightItalic48pt7b, 48, "NotoSans_SemiCondensed_LightItalic48pt7b" },
  { &NotoSans_SemiCondensed_LightItalic49pt7b, 49, "NotoSans_SemiCondensed_LightItalic49pt7b" },
  { &NotoSans_SemiCondensed_LightItalic50pt7b, 50, "NotoSans_SemiCondensed_LightItalic50pt7b" },
  { &NotoSans_SemiCondensed_LightItalic51pt7b, 51, "NotoSans_SemiCondensed_LightItalic51pt7b" },
  { &NotoSans_SemiCondensed_LightItalic52pt7b, 52, "NotoSans_SemiCondensed_LightItalic52pt7b" },
  { &NotoSans_SemiCondensed_LightItalic53pt7b, 53, "NotoSans_SemiCondensed_LightItalic53pt7b" },
  { &NotoSans_SemiCondensed_LightItalic54pt7b, 54, "NotoSans_SemiCondensed_LightItalic54pt7b" },
  { &NotoSans_SemiCondensed_LightItalic55pt7b, 55, "NotoSans_SemiCondensed_LightItalic55pt7b" },
  { &NotoSans_SemiCondensed_LightItalic56pt7b, 56, "NotoSans_SemiCondensed_LightItalic56pt7b" },
  { &NotoSans_SemiCondensed_LightItalic57pt7b, 57, "NotoSans_SemiCondensed_LightItalic57pt7b" },
  { &NotoSans_SemiCondensed_LightItalic58pt7b, 58, "NotoSans_SemiCondensed_LightItalic58pt7b" },
  { &NotoSans_SemiCondensed_LightItalic59pt7b, 59, "NotoSans_SemiCondensed_LightItalic59pt7b" },
  { &NotoSans_SemiCondensed_LightItalic60pt7b, 60, "NotoSans_SemiCondensed_LightItalic60pt7b" },
  { &NotoSans_SemiCondensed_LightItalic61pt7b, 61, "NotoSans_SemiCondensed_LightItalic61pt7b" },
  { &NotoSans_SemiCondensed_LightItalic62pt7b, 62, "NotoSans_SemiCondensed_LightItalic62pt7b" },
  { &NotoSans_SemiCondensed_LightItalic63pt7b, 63, "NotoSans_SemiCondensed_LightItalic63pt7b" },
  { &NotoSans_SemiCondensed_LightItalic64pt7b, 64, "NotoSans_SemiCondensed_LightItalic64pt7b" },
  { &NotoSans_SemiCondensed_LightItalic65pt7b, 65, "NotoSans_SemiCondensed_LightItalic65pt7b" },
  { &NotoSans_SemiCondensed_LightItalic66pt7b, 66, "NotoSans_SemiCondensed_LightItalic66pt7b" },
  { &NotoSans_SemiCondensed_LightItalic67pt7b, 67, "NotoSans_SemiCondensed_LightItalic67pt7b" },
  { &NotoSans_SemiCondensed_LightItalic68pt7b, 68, "NotoSans_SemiCondensed_LightItalic68pt7b" },
  { &NotoSans_SemiCondensed_LightItalic69pt7b, 69, "NotoSans_SemiCondensed_LightItalic69pt7b" },
  { &NotoSans_SemiCondensed_LightItalic70pt7b, 70, "NotoSans_SemiCondensed_LightItalic70pt7b" },
  { &NotoSans_SemiCondensed_LightItalic71pt7b, 71, "NotoSans_SemiCondensed_LightItalic71pt7b" },
  { &NotoSans_SemiCondensed_LightItalic72pt7b, 72, "NotoSans_SemiCondensed_LightItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
