#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &RobotoCondensed_ExtraLight6pt7b, 6, "RobotoCondensed_ExtraLight6pt7b" },
  { &RobotoCondensed_ExtraLight7pt7b, 7, "RobotoCondensed_ExtraLight7pt7b" },
  { &RobotoCondensed_ExtraLight8pt7b, 8, "RobotoCondensed_ExtraLight8pt7b" },
  { &RobotoCondensed_ExtraLight9pt7b, 9, "RobotoCondensed_ExtraLight9pt7b" },
  { &RobotoCondensed_ExtraLight10pt7b, 10, "RobotoCondensed_ExtraLight10pt7b" },
  { &RobotoCondensed_ExtraLight11pt7b, 11, "RobotoCondensed_ExtraLight11pt7b" },
  { &RobotoCondensed_ExtraLight12pt7b, 12, "RobotoCondensed_ExtraLight12pt7b" },
  { &RobotoCondensed_ExtraLight13pt7b, 13, "RobotoCondensed_ExtraLight13pt7b" },
  { &RobotoCondensed_ExtraLight14pt7b, 14, "RobotoCondensed_ExtraLight14pt7b" },
  { &RobotoCondensed_ExtraLight15pt7b, 15, "RobotoCondensed_ExtraLight15pt7b" },
  { &RobotoCondensed_ExtraLight16pt7b, 16, "RobotoCondensed_ExtraLight16pt7b" },
  { &RobotoCondensed_ExtraLight17pt7b, 17, "RobotoCondensed_ExtraLight17pt7b" },
  { &RobotoCondensed_ExtraLight18pt7b, 18, "RobotoCondensed_ExtraLight18pt7b" },
  { &RobotoCondensed_ExtraLight19pt7b, 19, "RobotoCondensed_ExtraLight19pt7b" },
  { &RobotoCondensed_ExtraLight20pt7b, 20, "RobotoCondensed_ExtraLight20pt7b" },
  { &RobotoCondensed_ExtraLight21pt7b, 21, "RobotoCondensed_ExtraLight21pt7b" },
  { &RobotoCondensed_ExtraLight22pt7b, 22, "RobotoCondensed_ExtraLight22pt7b" },
  { &RobotoCondensed_ExtraLight23pt7b, 23, "RobotoCondensed_ExtraLight23pt7b" },
  { &RobotoCondensed_ExtraLight24pt7b, 24, "RobotoCondensed_ExtraLight24pt7b" },
  { &RobotoCondensed_ExtraLight25pt7b, 25, "RobotoCondensed_ExtraLight25pt7b" },
  { &RobotoCondensed_ExtraLight26pt7b, 26, "RobotoCondensed_ExtraLight26pt7b" },
  { &RobotoCondensed_ExtraLight27pt7b, 27, "RobotoCondensed_ExtraLight27pt7b" },
  { &RobotoCondensed_ExtraLight28pt7b, 28, "RobotoCondensed_ExtraLight28pt7b" },
  { &RobotoCondensed_ExtraLight29pt7b, 29, "RobotoCondensed_ExtraLight29pt7b" },
  { &RobotoCondensed_ExtraLight30pt7b, 30, "RobotoCondensed_ExtraLight30pt7b" },
  { &RobotoCondensed_ExtraLight31pt7b, 31, "RobotoCondensed_ExtraLight31pt7b" },
  { &RobotoCondensed_ExtraLight32pt7b, 32, "RobotoCondensed_ExtraLight32pt7b" },
  { &RobotoCondensed_ExtraLight33pt7b, 33, "RobotoCondensed_ExtraLight33pt7b" },
  { &RobotoCondensed_ExtraLight34pt7b, 34, "RobotoCondensed_ExtraLight34pt7b" },
  { &RobotoCondensed_ExtraLight35pt7b, 35, "RobotoCondensed_ExtraLight35pt7b" },
  { &RobotoCondensed_ExtraLight36pt7b, 36, "RobotoCondensed_ExtraLight36pt7b" },
  { &RobotoCondensed_ExtraLight37pt7b, 37, "RobotoCondensed_ExtraLight37pt7b" },
  { &RobotoCondensed_ExtraLight38pt7b, 38, "RobotoCondensed_ExtraLight38pt7b" },
  { &RobotoCondensed_ExtraLight39pt7b, 39, "RobotoCondensed_ExtraLight39pt7b" },
  { &RobotoCondensed_ExtraLight40pt7b, 40, "RobotoCondensed_ExtraLight40pt7b" },
  { &RobotoCondensed_ExtraLight41pt7b, 41, "RobotoCondensed_ExtraLight41pt7b" },
  { &RobotoCondensed_ExtraLight42pt7b, 42, "RobotoCondensed_ExtraLight42pt7b" },
  { &RobotoCondensed_ExtraLight43pt7b, 43, "RobotoCondensed_ExtraLight43pt7b" },
  { &RobotoCondensed_ExtraLight44pt7b, 44, "RobotoCondensed_ExtraLight44pt7b" },
  { &RobotoCondensed_ExtraLight45pt7b, 45, "RobotoCondensed_ExtraLight45pt7b" },
  { &RobotoCondensed_ExtraLight46pt7b, 46, "RobotoCondensed_ExtraLight46pt7b" },
  { &RobotoCondensed_ExtraLight47pt7b, 47, "RobotoCondensed_ExtraLight47pt7b" },
  { &RobotoCondensed_ExtraLight48pt7b, 48, "RobotoCondensed_ExtraLight48pt7b" },
  { &RobotoCondensed_ExtraLight49pt7b, 49, "RobotoCondensed_ExtraLight49pt7b" },
  { &RobotoCondensed_ExtraLight50pt7b, 50, "RobotoCondensed_ExtraLight50pt7b" },
  { &RobotoCondensed_ExtraLight51pt7b, 51, "RobotoCondensed_ExtraLight51pt7b" },
  { &RobotoCondensed_ExtraLight52pt7b, 52, "RobotoCondensed_ExtraLight52pt7b" },
  { &RobotoCondensed_ExtraLight53pt7b, 53, "RobotoCondensed_ExtraLight53pt7b" },
  { &RobotoCondensed_ExtraLight54pt7b, 54, "RobotoCondensed_ExtraLight54pt7b" },
  { &RobotoCondensed_ExtraLight55pt7b, 55, "RobotoCondensed_ExtraLight55pt7b" },
  { &RobotoCondensed_ExtraLight56pt7b, 56, "RobotoCondensed_ExtraLight56pt7b" },
  { &RobotoCondensed_ExtraLight57pt7b, 57, "RobotoCondensed_ExtraLight57pt7b" },
  { &RobotoCondensed_ExtraLight58pt7b, 58, "RobotoCondensed_ExtraLight58pt7b" },
  { &RobotoCondensed_ExtraLight59pt7b, 59, "RobotoCondensed_ExtraLight59pt7b" },
  { &RobotoCondensed_ExtraLight60pt7b, 60, "RobotoCondensed_ExtraLight60pt7b" },
  { &RobotoCondensed_ExtraLight61pt7b, 61, "RobotoCondensed_ExtraLight61pt7b" },
  { &RobotoCondensed_ExtraLight62pt7b, 62, "RobotoCondensed_ExtraLight62pt7b" },
  { &RobotoCondensed_ExtraLight63pt7b, 63, "RobotoCondensed_ExtraLight63pt7b" },
  { &RobotoCondensed_ExtraLight64pt7b, 64, "RobotoCondensed_ExtraLight64pt7b" },
  { &RobotoCondensed_ExtraLight65pt7b, 65, "RobotoCondensed_ExtraLight65pt7b" },
  { &RobotoCondensed_ExtraLight66pt7b, 66, "RobotoCondensed_ExtraLight66pt7b" },
  { &RobotoCondensed_ExtraLight67pt7b, 67, "RobotoCondensed_ExtraLight67pt7b" },
  { &RobotoCondensed_ExtraLight68pt7b, 68, "RobotoCondensed_ExtraLight68pt7b" },
  { &RobotoCondensed_ExtraLight69pt7b, 69, "RobotoCondensed_ExtraLight69pt7b" },
  { &RobotoCondensed_ExtraLight70pt7b, 70, "RobotoCondensed_ExtraLight70pt7b" },
  { &RobotoCondensed_ExtraLight71pt7b, 71, "RobotoCondensed_ExtraLight71pt7b" },
  { &RobotoCondensed_ExtraLight72pt7b, 72, "RobotoCondensed_ExtraLight72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
