#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_ExtraCondensed_BlackItalic6pt7b, 6, "NotoSans_ExtraCondensed_BlackItalic6pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic7pt7b, 7, "NotoSans_ExtraCondensed_BlackItalic7pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic8pt7b, 8, "NotoSans_ExtraCondensed_BlackItalic8pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic9pt7b, 9, "NotoSans_ExtraCondensed_BlackItalic9pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic10pt7b, 10, "NotoSans_ExtraCondensed_BlackItalic10pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic11pt7b, 11, "NotoSans_ExtraCondensed_BlackItalic11pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic12pt7b, 12, "NotoSans_ExtraCondensed_BlackItalic12pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic13pt7b, 13, "NotoSans_ExtraCondensed_BlackItalic13pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic14pt7b, 14, "NotoSans_ExtraCondensed_BlackItalic14pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic15pt7b, 15, "NotoSans_ExtraCondensed_BlackItalic15pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic16pt7b, 16, "NotoSans_ExtraCondensed_BlackItalic16pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic17pt7b, 17, "NotoSans_ExtraCondensed_BlackItalic17pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic18pt7b, 18, "NotoSans_ExtraCondensed_BlackItalic18pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic19pt7b, 19, "NotoSans_ExtraCondensed_BlackItalic19pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic20pt7b, 20, "NotoSans_ExtraCondensed_BlackItalic20pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic21pt7b, 21, "NotoSans_ExtraCondensed_BlackItalic21pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic22pt7b, 22, "NotoSans_ExtraCondensed_BlackItalic22pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic23pt7b, 23, "NotoSans_ExtraCondensed_BlackItalic23pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic24pt7b, 24, "NotoSans_ExtraCondensed_BlackItalic24pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic25pt7b, 25, "NotoSans_ExtraCondensed_BlackItalic25pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic26pt7b, 26, "NotoSans_ExtraCondensed_BlackItalic26pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic27pt7b, 27, "NotoSans_ExtraCondensed_BlackItalic27pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic28pt7b, 28, "NotoSans_ExtraCondensed_BlackItalic28pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic29pt7b, 29, "NotoSans_ExtraCondensed_BlackItalic29pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic30pt7b, 30, "NotoSans_ExtraCondensed_BlackItalic30pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic31pt7b, 31, "NotoSans_ExtraCondensed_BlackItalic31pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic32pt7b, 32, "NotoSans_ExtraCondensed_BlackItalic32pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic33pt7b, 33, "NotoSans_ExtraCondensed_BlackItalic33pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic34pt7b, 34, "NotoSans_ExtraCondensed_BlackItalic34pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic35pt7b, 35, "NotoSans_ExtraCondensed_BlackItalic35pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic36pt7b, 36, "NotoSans_ExtraCondensed_BlackItalic36pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic37pt7b, 37, "NotoSans_ExtraCondensed_BlackItalic37pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic38pt7b, 38, "NotoSans_ExtraCondensed_BlackItalic38pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic39pt7b, 39, "NotoSans_ExtraCondensed_BlackItalic39pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic40pt7b, 40, "NotoSans_ExtraCondensed_BlackItalic40pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic41pt7b, 41, "NotoSans_ExtraCondensed_BlackItalic41pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic42pt7b, 42, "NotoSans_ExtraCondensed_BlackItalic42pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic43pt7b, 43, "NotoSans_ExtraCondensed_BlackItalic43pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic44pt7b, 44, "NotoSans_ExtraCondensed_BlackItalic44pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic45pt7b, 45, "NotoSans_ExtraCondensed_BlackItalic45pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic46pt7b, 46, "NotoSans_ExtraCondensed_BlackItalic46pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic47pt7b, 47, "NotoSans_ExtraCondensed_BlackItalic47pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic48pt7b, 48, "NotoSans_ExtraCondensed_BlackItalic48pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic49pt7b, 49, "NotoSans_ExtraCondensed_BlackItalic49pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic50pt7b, 50, "NotoSans_ExtraCondensed_BlackItalic50pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic51pt7b, 51, "NotoSans_ExtraCondensed_BlackItalic51pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic52pt7b, 52, "NotoSans_ExtraCondensed_BlackItalic52pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic53pt7b, 53, "NotoSans_ExtraCondensed_BlackItalic53pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic54pt7b, 54, "NotoSans_ExtraCondensed_BlackItalic54pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic55pt7b, 55, "NotoSans_ExtraCondensed_BlackItalic55pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic56pt7b, 56, "NotoSans_ExtraCondensed_BlackItalic56pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic57pt7b, 57, "NotoSans_ExtraCondensed_BlackItalic57pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic58pt7b, 58, "NotoSans_ExtraCondensed_BlackItalic58pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic59pt7b, 59, "NotoSans_ExtraCondensed_BlackItalic59pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic60pt7b, 60, "NotoSans_ExtraCondensed_BlackItalic60pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic61pt7b, 61, "NotoSans_ExtraCondensed_BlackItalic61pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic62pt7b, 62, "NotoSans_ExtraCondensed_BlackItalic62pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic63pt7b, 63, "NotoSans_ExtraCondensed_BlackItalic63pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic64pt7b, 64, "NotoSans_ExtraCondensed_BlackItalic64pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic65pt7b, 65, "NotoSans_ExtraCondensed_BlackItalic65pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic66pt7b, 66, "NotoSans_ExtraCondensed_BlackItalic66pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic67pt7b, 67, "NotoSans_ExtraCondensed_BlackItalic67pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic68pt7b, 68, "NotoSans_ExtraCondensed_BlackItalic68pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic69pt7b, 69, "NotoSans_ExtraCondensed_BlackItalic69pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic70pt7b, 70, "NotoSans_ExtraCondensed_BlackItalic70pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic71pt7b, 71, "NotoSans_ExtraCondensed_BlackItalic71pt7b" },
  { &NotoSans_ExtraCondensed_BlackItalic72pt7b, 72, "NotoSans_ExtraCondensed_BlackItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
