#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_Regular6pt7b, 6, "NotoSans_Regular6pt7b" },
  { &NotoSans_Regular7pt7b, 7, "NotoSans_Regular7pt7b" },
  { &NotoSans_Regular8pt7b, 8, "NotoSans_Regular8pt7b" },
  { &NotoSans_Regular9pt7b, 9, "NotoSans_Regular9pt7b" },
  { &NotoSans_Regular10pt7b, 10, "NotoSans_Regular10pt7b" },
  { &NotoSans_Regular11pt7b, 11, "NotoSans_Regular11pt7b" },
  { &NotoSans_Regular12pt7b, 12, "NotoSans_Regular12pt7b" },
  { &NotoSans_Regular13pt7b, 13, "NotoSans_Regular13pt7b" },
  { &NotoSans_Regular14pt7b, 14, "NotoSans_Regular14pt7b" },
  { &NotoSans_Regular15pt7b, 15, "NotoSans_Regular15pt7b" },
  { &NotoSans_Regular16pt7b, 16, "NotoSans_Regular16pt7b" },
  { &NotoSans_Regular17pt7b, 17, "NotoSans_Regular17pt7b" },
  { &NotoSans_Regular18pt7b, 18, "NotoSans_Regular18pt7b" },
  { &NotoSans_Regular19pt7b, 19, "NotoSans_Regular19pt7b" },
  { &NotoSans_Regular20pt7b, 20, "NotoSans_Regular20pt7b" },
  { &NotoSans_Regular21pt7b, 21, "NotoSans_Regular21pt7b" },
  { &NotoSans_Regular22pt7b, 22, "NotoSans_Regular22pt7b" },
  { &NotoSans_Regular23pt7b, 23, "NotoSans_Regular23pt7b" },
  { &NotoSans_Regular24pt7b, 24, "NotoSans_Regular24pt7b" },
  { &NotoSans_Regular25pt7b, 25, "NotoSans_Regular25pt7b" },
  { &NotoSans_Regular26pt7b, 26, "NotoSans_Regular26pt7b" },
  { &NotoSans_Regular27pt7b, 27, "NotoSans_Regular27pt7b" },
  { &NotoSans_Regular28pt7b, 28, "NotoSans_Regular28pt7b" },
  { &NotoSans_Regular29pt7b, 29, "NotoSans_Regular29pt7b" },
  { &NotoSans_Regular30pt7b, 30, "NotoSans_Regular30pt7b" },
  { &NotoSans_Regular31pt7b, 31, "NotoSans_Regular31pt7b" },
  { &NotoSans_Regular32pt7b, 32, "NotoSans_Regular32pt7b" },
  { &NotoSans_Regular33pt7b, 33, "NotoSans_Regular33pt7b" },
  { &NotoSans_Regular34pt7b, 34, "NotoSans_Regular34pt7b" },
  { &NotoSans_Regular35pt7b, 35, "NotoSans_Regular35pt7b" },
  { &NotoSans_Regular36pt7b, 36, "NotoSans_Regular36pt7b" },
  { &NotoSans_Regular37pt7b, 37, "NotoSans_Regular37pt7b" },
  { &NotoSans_Regular38pt7b, 38, "NotoSans_Regular38pt7b" },
  { &NotoSans_Regular39pt7b, 39, "NotoSans_Regular39pt7b" },
  { &NotoSans_Regular40pt7b, 40, "NotoSans_Regular40pt7b" },
  { &NotoSans_Regular41pt7b, 41, "NotoSans_Regular41pt7b" },
  { &NotoSans_Regular42pt7b, 42, "NotoSans_Regular42pt7b" },
  { &NotoSans_Regular43pt7b, 43, "NotoSans_Regular43pt7b" },
  { &NotoSans_Regular44pt7b, 44, "NotoSans_Regular44pt7b" },
  { &NotoSans_Regular45pt7b, 45, "NotoSans_Regular45pt7b" },
  { &NotoSans_Regular46pt7b, 46, "NotoSans_Regular46pt7b" },
  { &NotoSans_Regular47pt7b, 47, "NotoSans_Regular47pt7b" },
  { &NotoSans_Regular48pt7b, 48, "NotoSans_Regular48pt7b" },
  { &NotoSans_Regular49pt7b, 49, "NotoSans_Regular49pt7b" },
  { &NotoSans_Regular50pt7b, 50, "NotoSans_Regular50pt7b" },
  { &NotoSans_Regular51pt7b, 51, "NotoSans_Regular51pt7b" },
  { &NotoSans_Regular52pt7b, 52, "NotoSans_Regular52pt7b" },
  { &NotoSans_Regular53pt7b, 53, "NotoSans_Regular53pt7b" },
  { &NotoSans_Regular54pt7b, 54, "NotoSans_Regular54pt7b" },
  { &NotoSans_Regular55pt7b, 55, "NotoSans_Regular55pt7b" },
  { &NotoSans_Regular56pt7b, 56, "NotoSans_Regular56pt7b" },
  { &NotoSans_Regular57pt7b, 57, "NotoSans_Regular57pt7b" },
  { &NotoSans_Regular58pt7b, 58, "NotoSans_Regular58pt7b" },
  { &NotoSans_Regular59pt7b, 59, "NotoSans_Regular59pt7b" },
  { &NotoSans_Regular60pt7b, 60, "NotoSans_Regular60pt7b" },
  { &NotoSans_Regular61pt7b, 61, "NotoSans_Regular61pt7b" },
  { &NotoSans_Regular62pt7b, 62, "NotoSans_Regular62pt7b" },
  { &NotoSans_Regular63pt7b, 63, "NotoSans_Regular63pt7b" },
  { &NotoSans_Regular64pt7b, 64, "NotoSans_Regular64pt7b" },
  { &NotoSans_Regular65pt7b, 65, "NotoSans_Regular65pt7b" },
  { &NotoSans_Regular66pt7b, 66, "NotoSans_Regular66pt7b" },
  { &NotoSans_Regular67pt7b, 67, "NotoSans_Regular67pt7b" },
  { &NotoSans_Regular68pt7b, 68, "NotoSans_Regular68pt7b" },
  { &NotoSans_Regular69pt7b, 69, "NotoSans_Regular69pt7b" },
  { &NotoSans_Regular70pt7b, 70, "NotoSans_Regular70pt7b" },
  { &NotoSans_Regular71pt7b, 71, "NotoSans_Regular71pt7b" },
  { &NotoSans_Regular72pt7b, 72, "NotoSans_Regular72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
