#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_ExtraLightItalic6pt7b, 6, "NotoSans_ExtraLightItalic6pt7b" },
  { &NotoSans_ExtraLightItalic7pt7b, 7, "NotoSans_ExtraLightItalic7pt7b" },
  { &NotoSans_ExtraLightItalic8pt7b, 8, "NotoSans_ExtraLightItalic8pt7b" },
  { &NotoSans_ExtraLightItalic9pt7b, 9, "NotoSans_ExtraLightItalic9pt7b" },
  { &NotoSans_ExtraLightItalic10pt7b, 10, "NotoSans_ExtraLightItalic10pt7b" },
  { &NotoSans_ExtraLightItalic11pt7b, 11, "NotoSans_ExtraLightItalic11pt7b" },
  { &NotoSans_ExtraLightItalic12pt7b, 12, "NotoSans_ExtraLightItalic12pt7b" },
  { &NotoSans_ExtraLightItalic13pt7b, 13, "NotoSans_ExtraLightItalic13pt7b" },
  { &NotoSans_ExtraLightItalic14pt7b, 14, "NotoSans_ExtraLightItalic14pt7b" },
  { &NotoSans_ExtraLightItalic15pt7b, 15, "NotoSans_ExtraLightItalic15pt7b" },
  { &NotoSans_ExtraLightItalic16pt7b, 16, "NotoSans_ExtraLightItalic16pt7b" },
  { &NotoSans_ExtraLightItalic17pt7b, 17, "NotoSans_ExtraLightItalic17pt7b" },
  { &NotoSans_ExtraLightItalic18pt7b, 18, "NotoSans_ExtraLightItalic18pt7b" },
  { &NotoSans_ExtraLightItalic19pt7b, 19, "NotoSans_ExtraLightItalic19pt7b" },
  { &NotoSans_ExtraLightItalic20pt7b, 20, "NotoSans_ExtraLightItalic20pt7b" },
  { &NotoSans_ExtraLightItalic21pt7b, 21, "NotoSans_ExtraLightItalic21pt7b" },
  { &NotoSans_ExtraLightItalic22pt7b, 22, "NotoSans_ExtraLightItalic22pt7b" },
  { &NotoSans_ExtraLightItalic23pt7b, 23, "NotoSans_ExtraLightItalic23pt7b" },
  { &NotoSans_ExtraLightItalic24pt7b, 24, "NotoSans_ExtraLightItalic24pt7b" },
  { &NotoSans_ExtraLightItalic25pt7b, 25, "NotoSans_ExtraLightItalic25pt7b" },
  { &NotoSans_ExtraLightItalic26pt7b, 26, "NotoSans_ExtraLightItalic26pt7b" },
  { &NotoSans_ExtraLightItalic27pt7b, 27, "NotoSans_ExtraLightItalic27pt7b" },
  { &NotoSans_ExtraLightItalic28pt7b, 28, "NotoSans_ExtraLightItalic28pt7b" },
  { &NotoSans_ExtraLightItalic29pt7b, 29, "NotoSans_ExtraLightItalic29pt7b" },
  { &NotoSans_ExtraLightItalic30pt7b, 30, "NotoSans_ExtraLightItalic30pt7b" },
  { &NotoSans_ExtraLightItalic31pt7b, 31, "NotoSans_ExtraLightItalic31pt7b" },
  { &NotoSans_ExtraLightItalic32pt7b, 32, "NotoSans_ExtraLightItalic32pt7b" },
  { &NotoSans_ExtraLightItalic33pt7b, 33, "NotoSans_ExtraLightItalic33pt7b" },
  { &NotoSans_ExtraLightItalic34pt7b, 34, "NotoSans_ExtraLightItalic34pt7b" },
  { &NotoSans_ExtraLightItalic35pt7b, 35, "NotoSans_ExtraLightItalic35pt7b" },
  { &NotoSans_ExtraLightItalic36pt7b, 36, "NotoSans_ExtraLightItalic36pt7b" },
  { &NotoSans_ExtraLightItalic37pt7b, 37, "NotoSans_ExtraLightItalic37pt7b" },
  { &NotoSans_ExtraLightItalic38pt7b, 38, "NotoSans_ExtraLightItalic38pt7b" },
  { &NotoSans_ExtraLightItalic39pt7b, 39, "NotoSans_ExtraLightItalic39pt7b" },
  { &NotoSans_ExtraLightItalic40pt7b, 40, "NotoSans_ExtraLightItalic40pt7b" },
  { &NotoSans_ExtraLightItalic41pt7b, 41, "NotoSans_ExtraLightItalic41pt7b" },
  { &NotoSans_ExtraLightItalic42pt7b, 42, "NotoSans_ExtraLightItalic42pt7b" },
  { &NotoSans_ExtraLightItalic43pt7b, 43, "NotoSans_ExtraLightItalic43pt7b" },
  { &NotoSans_ExtraLightItalic44pt7b, 44, "NotoSans_ExtraLightItalic44pt7b" },
  { &NotoSans_ExtraLightItalic45pt7b, 45, "NotoSans_ExtraLightItalic45pt7b" },
  { &NotoSans_ExtraLightItalic46pt7b, 46, "NotoSans_ExtraLightItalic46pt7b" },
  { &NotoSans_ExtraLightItalic47pt7b, 47, "NotoSans_ExtraLightItalic47pt7b" },
  { &NotoSans_ExtraLightItalic48pt7b, 48, "NotoSans_ExtraLightItalic48pt7b" },
  { &NotoSans_ExtraLightItalic49pt7b, 49, "NotoSans_ExtraLightItalic49pt7b" },
  { &NotoSans_ExtraLightItalic50pt7b, 50, "NotoSans_ExtraLightItalic50pt7b" },
  { &NotoSans_ExtraLightItalic51pt7b, 51, "NotoSans_ExtraLightItalic51pt7b" },
  { &NotoSans_ExtraLightItalic52pt7b, 52, "NotoSans_ExtraLightItalic52pt7b" },
  { &NotoSans_ExtraLightItalic53pt7b, 53, "NotoSans_ExtraLightItalic53pt7b" },
  { &NotoSans_ExtraLightItalic54pt7b, 54, "NotoSans_ExtraLightItalic54pt7b" },
  { &NotoSans_ExtraLightItalic55pt7b, 55, "NotoSans_ExtraLightItalic55pt7b" },
  { &NotoSans_ExtraLightItalic56pt7b, 56, "NotoSans_ExtraLightItalic56pt7b" },
  { &NotoSans_ExtraLightItalic57pt7b, 57, "NotoSans_ExtraLightItalic57pt7b" },
  { &NotoSans_ExtraLightItalic58pt7b, 58, "NotoSans_ExtraLightItalic58pt7b" },
  { &NotoSans_ExtraLightItalic59pt7b, 59, "NotoSans_ExtraLightItalic59pt7b" },
  { &NotoSans_ExtraLightItalic60pt7b, 60, "NotoSans_ExtraLightItalic60pt7b" },
  { &NotoSans_ExtraLightItalic61pt7b, 61, "NotoSans_ExtraLightItalic61pt7b" },
  { &NotoSans_ExtraLightItalic62pt7b, 62, "NotoSans_ExtraLightItalic62pt7b" },
  { &NotoSans_ExtraLightItalic63pt7b, 63, "NotoSans_ExtraLightItalic63pt7b" },
  { &NotoSans_ExtraLightItalic64pt7b, 64, "NotoSans_ExtraLightItalic64pt7b" },
  { &NotoSans_ExtraLightItalic65pt7b, 65, "NotoSans_ExtraLightItalic65pt7b" },
  { &NotoSans_ExtraLightItalic66pt7b, 66, "NotoSans_ExtraLightItalic66pt7b" },
  { &NotoSans_ExtraLightItalic67pt7b, 67, "NotoSans_ExtraLightItalic67pt7b" },
  { &NotoSans_ExtraLightItalic68pt7b, 68, "NotoSans_ExtraLightItalic68pt7b" },
  { &NotoSans_ExtraLightItalic69pt7b, 69, "NotoSans_ExtraLightItalic69pt7b" },
  { &NotoSans_ExtraLightItalic70pt7b, 70, "NotoSans_ExtraLightItalic70pt7b" },
  { &NotoSans_ExtraLightItalic71pt7b, 71, "NotoSans_ExtraLightItalic71pt7b" },
  { &NotoSans_ExtraLightItalic72pt7b, 72, "NotoSans_ExtraLightItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
