#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_Condensed_Light6pt7b, 6, "NotoSans_Condensed_Light6pt7b" },
  { &NotoSans_Condensed_Light7pt7b, 7, "NotoSans_Condensed_Light7pt7b" },
  { &NotoSans_Condensed_Light8pt7b, 8, "NotoSans_Condensed_Light8pt7b" },
  { &NotoSans_Condensed_Light9pt7b, 9, "NotoSans_Condensed_Light9pt7b" },
  { &NotoSans_Condensed_Light10pt7b, 10, "NotoSans_Condensed_Light10pt7b" },
  { &NotoSans_Condensed_Light11pt7b, 11, "NotoSans_Condensed_Light11pt7b" },
  { &NotoSans_Condensed_Light12pt7b, 12, "NotoSans_Condensed_Light12pt7b" },
  { &NotoSans_Condensed_Light13pt7b, 13, "NotoSans_Condensed_Light13pt7b" },
  { &NotoSans_Condensed_Light14pt7b, 14, "NotoSans_Condensed_Light14pt7b" },
  { &NotoSans_Condensed_Light15pt7b, 15, "NotoSans_Condensed_Light15pt7b" },
  { &NotoSans_Condensed_Light16pt7b, 16, "NotoSans_Condensed_Light16pt7b" },
  { &NotoSans_Condensed_Light17pt7b, 17, "NotoSans_Condensed_Light17pt7b" },
  { &NotoSans_Condensed_Light18pt7b, 18, "NotoSans_Condensed_Light18pt7b" },
  { &NotoSans_Condensed_Light19pt7b, 19, "NotoSans_Condensed_Light19pt7b" },
  { &NotoSans_Condensed_Light20pt7b, 20, "NotoSans_Condensed_Light20pt7b" },
  { &NotoSans_Condensed_Light21pt7b, 21, "NotoSans_Condensed_Light21pt7b" },
  { &NotoSans_Condensed_Light22pt7b, 22, "NotoSans_Condensed_Light22pt7b" },
  { &NotoSans_Condensed_Light23pt7b, 23, "NotoSans_Condensed_Light23pt7b" },
  { &NotoSans_Condensed_Light24pt7b, 24, "NotoSans_Condensed_Light24pt7b" },
  { &NotoSans_Condensed_Light25pt7b, 25, "NotoSans_Condensed_Light25pt7b" },
  { &NotoSans_Condensed_Light26pt7b, 26, "NotoSans_Condensed_Light26pt7b" },
  { &NotoSans_Condensed_Light27pt7b, 27, "NotoSans_Condensed_Light27pt7b" },
  { &NotoSans_Condensed_Light28pt7b, 28, "NotoSans_Condensed_Light28pt7b" },
  { &NotoSans_Condensed_Light29pt7b, 29, "NotoSans_Condensed_Light29pt7b" },
  { &NotoSans_Condensed_Light30pt7b, 30, "NotoSans_Condensed_Light30pt7b" },
  { &NotoSans_Condensed_Light31pt7b, 31, "NotoSans_Condensed_Light31pt7b" },
  { &NotoSans_Condensed_Light32pt7b, 32, "NotoSans_Condensed_Light32pt7b" },
  { &NotoSans_Condensed_Light33pt7b, 33, "NotoSans_Condensed_Light33pt7b" },
  { &NotoSans_Condensed_Light34pt7b, 34, "NotoSans_Condensed_Light34pt7b" },
  { &NotoSans_Condensed_Light35pt7b, 35, "NotoSans_Condensed_Light35pt7b" },
  { &NotoSans_Condensed_Light36pt7b, 36, "NotoSans_Condensed_Light36pt7b" },
  { &NotoSans_Condensed_Light37pt7b, 37, "NotoSans_Condensed_Light37pt7b" },
  { &NotoSans_Condensed_Light38pt7b, 38, "NotoSans_Condensed_Light38pt7b" },
  { &NotoSans_Condensed_Light39pt7b, 39, "NotoSans_Condensed_Light39pt7b" },
  { &NotoSans_Condensed_Light40pt7b, 40, "NotoSans_Condensed_Light40pt7b" },
  { &NotoSans_Condensed_Light41pt7b, 41, "NotoSans_Condensed_Light41pt7b" },
  { &NotoSans_Condensed_Light42pt7b, 42, "NotoSans_Condensed_Light42pt7b" },
  { &NotoSans_Condensed_Light43pt7b, 43, "NotoSans_Condensed_Light43pt7b" },
  { &NotoSans_Condensed_Light44pt7b, 44, "NotoSans_Condensed_Light44pt7b" },
  { &NotoSans_Condensed_Light45pt7b, 45, "NotoSans_Condensed_Light45pt7b" },
  { &NotoSans_Condensed_Light46pt7b, 46, "NotoSans_Condensed_Light46pt7b" },
  { &NotoSans_Condensed_Light47pt7b, 47, "NotoSans_Condensed_Light47pt7b" },
  { &NotoSans_Condensed_Light48pt7b, 48, "NotoSans_Condensed_Light48pt7b" },
  { &NotoSans_Condensed_Light49pt7b, 49, "NotoSans_Condensed_Light49pt7b" },
  { &NotoSans_Condensed_Light50pt7b, 50, "NotoSans_Condensed_Light50pt7b" },
  { &NotoSans_Condensed_Light51pt7b, 51, "NotoSans_Condensed_Light51pt7b" },
  { &NotoSans_Condensed_Light52pt7b, 52, "NotoSans_Condensed_Light52pt7b" },
  { &NotoSans_Condensed_Light53pt7b, 53, "NotoSans_Condensed_Light53pt7b" },
  { &NotoSans_Condensed_Light54pt7b, 54, "NotoSans_Condensed_Light54pt7b" },
  { &NotoSans_Condensed_Light55pt7b, 55, "NotoSans_Condensed_Light55pt7b" },
  { &NotoSans_Condensed_Light56pt7b, 56, "NotoSans_Condensed_Light56pt7b" },
  { &NotoSans_Condensed_Light57pt7b, 57, "NotoSans_Condensed_Light57pt7b" },
  { &NotoSans_Condensed_Light58pt7b, 58, "NotoSans_Condensed_Light58pt7b" },
  { &NotoSans_Condensed_Light59pt7b, 59, "NotoSans_Condensed_Light59pt7b" },
  { &NotoSans_Condensed_Light60pt7b, 60, "NotoSans_Condensed_Light60pt7b" },
  { &NotoSans_Condensed_Light61pt7b, 61, "NotoSans_Condensed_Light61pt7b" },
  { &NotoSans_Condensed_Light62pt7b, 62, "NotoSans_Condensed_Light62pt7b" },
  { &NotoSans_Condensed_Light63pt7b, 63, "NotoSans_Condensed_Light63pt7b" },
  { &NotoSans_Condensed_Light64pt7b, 64, "NotoSans_Condensed_Light64pt7b" },
  { &NotoSans_Condensed_Light65pt7b, 65, "NotoSans_Condensed_Light65pt7b" },
  { &NotoSans_Condensed_Light66pt7b, 66, "NotoSans_Condensed_Light66pt7b" },
  { &NotoSans_Condensed_Light67pt7b, 67, "NotoSans_Condensed_Light67pt7b" },
  { &NotoSans_Condensed_Light68pt7b, 68, "NotoSans_Condensed_Light68pt7b" },
  { &NotoSans_Condensed_Light69pt7b, 69, "NotoSans_Condensed_Light69pt7b" },
  { &NotoSans_Condensed_Light70pt7b, 70, "NotoSans_Condensed_Light70pt7b" },
  { &NotoSans_Condensed_Light71pt7b, 71, "NotoSans_Condensed_Light71pt7b" },
  { &NotoSans_Condensed_Light72pt7b, 72, "NotoSans_Condensed_Light72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
