#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_ExtraCondensed_ExtraLightItalic6pt7b, 6, "NotoSans_ExtraCondensed_ExtraLightItalic6pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic7pt7b, 7, "NotoSans_ExtraCondensed_ExtraLightItalic7pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic8pt7b, 8, "NotoSans_ExtraCondensed_ExtraLightItalic8pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic9pt7b, 9, "NotoSans_ExtraCondensed_ExtraLightItalic9pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic10pt7b, 10, "NotoSans_ExtraCondensed_ExtraLightItalic10pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic11pt7b, 11, "NotoSans_ExtraCondensed_ExtraLightItalic11pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic12pt7b, 12, "NotoSans_ExtraCondensed_ExtraLightItalic12pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic13pt7b, 13, "NotoSans_ExtraCondensed_ExtraLightItalic13pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic14pt7b, 14, "NotoSans_ExtraCondensed_ExtraLightItalic14pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic15pt7b, 15, "NotoSans_ExtraCondensed_ExtraLightItalic15pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic16pt7b, 16, "NotoSans_ExtraCondensed_ExtraLightItalic16pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic17pt7b, 17, "NotoSans_ExtraCondensed_ExtraLightItalic17pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic18pt7b, 18, "NotoSans_ExtraCondensed_ExtraLightItalic18pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic19pt7b, 19, "NotoSans_ExtraCondensed_ExtraLightItalic19pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic20pt7b, 20, "NotoSans_ExtraCondensed_ExtraLightItalic20pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic21pt7b, 21, "NotoSans_ExtraCondensed_ExtraLightItalic21pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic22pt7b, 22, "NotoSans_ExtraCondensed_ExtraLightItalic22pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic23pt7b, 23, "NotoSans_ExtraCondensed_ExtraLightItalic23pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic24pt7b, 24, "NotoSans_ExtraCondensed_ExtraLightItalic24pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic25pt7b, 25, "NotoSans_ExtraCondensed_ExtraLightItalic25pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic26pt7b, 26, "NotoSans_ExtraCondensed_ExtraLightItalic26pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic27pt7b, 27, "NotoSans_ExtraCondensed_ExtraLightItalic27pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic28pt7b, 28, "NotoSans_ExtraCondensed_ExtraLightItalic28pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic29pt7b, 29, "NotoSans_ExtraCondensed_ExtraLightItalic29pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic30pt7b, 30, "NotoSans_ExtraCondensed_ExtraLightItalic30pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic31pt7b, 31, "NotoSans_ExtraCondensed_ExtraLightItalic31pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic32pt7b, 32, "NotoSans_ExtraCondensed_ExtraLightItalic32pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic33pt7b, 33, "NotoSans_ExtraCondensed_ExtraLightItalic33pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic34pt7b, 34, "NotoSans_ExtraCondensed_ExtraLightItalic34pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic35pt7b, 35, "NotoSans_ExtraCondensed_ExtraLightItalic35pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic36pt7b, 36, "NotoSans_ExtraCondensed_ExtraLightItalic36pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic37pt7b, 37, "NotoSans_ExtraCondensed_ExtraLightItalic37pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic38pt7b, 38, "NotoSans_ExtraCondensed_ExtraLightItalic38pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic39pt7b, 39, "NotoSans_ExtraCondensed_ExtraLightItalic39pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic40pt7b, 40, "NotoSans_ExtraCondensed_ExtraLightItalic40pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic41pt7b, 41, "NotoSans_ExtraCondensed_ExtraLightItalic41pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic42pt7b, 42, "NotoSans_ExtraCondensed_ExtraLightItalic42pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic43pt7b, 43, "NotoSans_ExtraCondensed_ExtraLightItalic43pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic44pt7b, 44, "NotoSans_ExtraCondensed_ExtraLightItalic44pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic45pt7b, 45, "NotoSans_ExtraCondensed_ExtraLightItalic45pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic46pt7b, 46, "NotoSans_ExtraCondensed_ExtraLightItalic46pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic47pt7b, 47, "NotoSans_ExtraCondensed_ExtraLightItalic47pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic48pt7b, 48, "NotoSans_ExtraCondensed_ExtraLightItalic48pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic49pt7b, 49, "NotoSans_ExtraCondensed_ExtraLightItalic49pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic50pt7b, 50, "NotoSans_ExtraCondensed_ExtraLightItalic50pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic51pt7b, 51, "NotoSans_ExtraCondensed_ExtraLightItalic51pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic52pt7b, 52, "NotoSans_ExtraCondensed_ExtraLightItalic52pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic53pt7b, 53, "NotoSans_ExtraCondensed_ExtraLightItalic53pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic54pt7b, 54, "NotoSans_ExtraCondensed_ExtraLightItalic54pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic55pt7b, 55, "NotoSans_ExtraCondensed_ExtraLightItalic55pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic56pt7b, 56, "NotoSans_ExtraCondensed_ExtraLightItalic56pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic57pt7b, 57, "NotoSans_ExtraCondensed_ExtraLightItalic57pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic58pt7b, 58, "NotoSans_ExtraCondensed_ExtraLightItalic58pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic59pt7b, 59, "NotoSans_ExtraCondensed_ExtraLightItalic59pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic60pt7b, 60, "NotoSans_ExtraCondensed_ExtraLightItalic60pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic61pt7b, 61, "NotoSans_ExtraCondensed_ExtraLightItalic61pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic62pt7b, 62, "NotoSans_ExtraCondensed_ExtraLightItalic62pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic63pt7b, 63, "NotoSans_ExtraCondensed_ExtraLightItalic63pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic64pt7b, 64, "NotoSans_ExtraCondensed_ExtraLightItalic64pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic65pt7b, 65, "NotoSans_ExtraCondensed_ExtraLightItalic65pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic66pt7b, 66, "NotoSans_ExtraCondensed_ExtraLightItalic66pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic67pt7b, 67, "NotoSans_ExtraCondensed_ExtraLightItalic67pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic68pt7b, 68, "NotoSans_ExtraCondensed_ExtraLightItalic68pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic69pt7b, 69, "NotoSans_ExtraCondensed_ExtraLightItalic69pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic70pt7b, 70, "NotoSans_ExtraCondensed_ExtraLightItalic70pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic71pt7b, 71, "NotoSans_ExtraCondensed_ExtraLightItalic71pt7b" },
  { &NotoSans_ExtraCondensed_ExtraLightItalic72pt7b, 72, "NotoSans_ExtraCondensed_ExtraLightItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
