#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &JetBrainsMono_SemiBold6pt7b, 6, "JetBrainsMono_SemiBold6pt7b" },
  { &JetBrainsMono_SemiBold7pt7b, 7, "JetBrainsMono_SemiBold7pt7b" },
  { &JetBrainsMono_SemiBold8pt7b, 8, "JetBrainsMono_SemiBold8pt7b" },
  { &JetBrainsMono_SemiBold9pt7b, 9, "JetBrainsMono_SemiBold9pt7b" },
  { &JetBrainsMono_SemiBold10pt7b, 10, "JetBrainsMono_SemiBold10pt7b" },
  { &JetBrainsMono_SemiBold11pt7b, 11, "JetBrainsMono_SemiBold11pt7b" },
  { &JetBrainsMono_SemiBold12pt7b, 12, "JetBrainsMono_SemiBold12pt7b" },
  { &JetBrainsMono_SemiBold13pt7b, 13, "JetBrainsMono_SemiBold13pt7b" },
  { &JetBrainsMono_SemiBold14pt7b, 14, "JetBrainsMono_SemiBold14pt7b" },
  { &JetBrainsMono_SemiBold15pt7b, 15, "JetBrainsMono_SemiBold15pt7b" },
  { &JetBrainsMono_SemiBold16pt7b, 16, "JetBrainsMono_SemiBold16pt7b" },
  { &JetBrainsMono_SemiBold17pt7b, 17, "JetBrainsMono_SemiBold17pt7b" },
  { &JetBrainsMono_SemiBold18pt7b, 18, "JetBrainsMono_SemiBold18pt7b" },
  { &JetBrainsMono_SemiBold19pt7b, 19, "JetBrainsMono_SemiBold19pt7b" },
  { &JetBrainsMono_SemiBold20pt7b, 20, "JetBrainsMono_SemiBold20pt7b" },
  { &JetBrainsMono_SemiBold21pt7b, 21, "JetBrainsMono_SemiBold21pt7b" },
  { &JetBrainsMono_SemiBold22pt7b, 22, "JetBrainsMono_SemiBold22pt7b" },
  { &JetBrainsMono_SemiBold23pt7b, 23, "JetBrainsMono_SemiBold23pt7b" },
  { &JetBrainsMono_SemiBold24pt7b, 24, "JetBrainsMono_SemiBold24pt7b" },
  { &JetBrainsMono_SemiBold25pt7b, 25, "JetBrainsMono_SemiBold25pt7b" },
  { &JetBrainsMono_SemiBold26pt7b, 26, "JetBrainsMono_SemiBold26pt7b" },
  { &JetBrainsMono_SemiBold27pt7b, 27, "JetBrainsMono_SemiBold27pt7b" },
  { &JetBrainsMono_SemiBold28pt7b, 28, "JetBrainsMono_SemiBold28pt7b" },
  { &JetBrainsMono_SemiBold29pt7b, 29, "JetBrainsMono_SemiBold29pt7b" },
  { &JetBrainsMono_SemiBold30pt7b, 30, "JetBrainsMono_SemiBold30pt7b" },
  { &JetBrainsMono_SemiBold31pt7b, 31, "JetBrainsMono_SemiBold31pt7b" },
  { &JetBrainsMono_SemiBold32pt7b, 32, "JetBrainsMono_SemiBold32pt7b" },
  { &JetBrainsMono_SemiBold33pt7b, 33, "JetBrainsMono_SemiBold33pt7b" },
  { &JetBrainsMono_SemiBold34pt7b, 34, "JetBrainsMono_SemiBold34pt7b" },
  { &JetBrainsMono_SemiBold35pt7b, 35, "JetBrainsMono_SemiBold35pt7b" },
  { &JetBrainsMono_SemiBold36pt7b, 36, "JetBrainsMono_SemiBold36pt7b" },
  { &JetBrainsMono_SemiBold37pt7b, 37, "JetBrainsMono_SemiBold37pt7b" },
  { &JetBrainsMono_SemiBold38pt7b, 38, "JetBrainsMono_SemiBold38pt7b" },
  { &JetBrainsMono_SemiBold39pt7b, 39, "JetBrainsMono_SemiBold39pt7b" },
  { &JetBrainsMono_SemiBold40pt7b, 40, "JetBrainsMono_SemiBold40pt7b" },
  { &JetBrainsMono_SemiBold41pt7b, 41, "JetBrainsMono_SemiBold41pt7b" },
  { &JetBrainsMono_SemiBold42pt7b, 42, "JetBrainsMono_SemiBold42pt7b" },
  { &JetBrainsMono_SemiBold43pt7b, 43, "JetBrainsMono_SemiBold43pt7b" },
  { &JetBrainsMono_SemiBold44pt7b, 44, "JetBrainsMono_SemiBold44pt7b" },
  { &JetBrainsMono_SemiBold45pt7b, 45, "JetBrainsMono_SemiBold45pt7b" },
  { &JetBrainsMono_SemiBold46pt7b, 46, "JetBrainsMono_SemiBold46pt7b" },
  { &JetBrainsMono_SemiBold47pt7b, 47, "JetBrainsMono_SemiBold47pt7b" },
  { &JetBrainsMono_SemiBold48pt7b, 48, "JetBrainsMono_SemiBold48pt7b" },
  { &JetBrainsMono_SemiBold49pt7b, 49, "JetBrainsMono_SemiBold49pt7b" },
  { &JetBrainsMono_SemiBold50pt7b, 50, "JetBrainsMono_SemiBold50pt7b" },
  { &JetBrainsMono_SemiBold51pt7b, 51, "JetBrainsMono_SemiBold51pt7b" },
  { &JetBrainsMono_SemiBold52pt7b, 52, "JetBrainsMono_SemiBold52pt7b" },
  { &JetBrainsMono_SemiBold53pt7b, 53, "JetBrainsMono_SemiBold53pt7b" },
  { &JetBrainsMono_SemiBold54pt7b, 54, "JetBrainsMono_SemiBold54pt7b" },
  { &JetBrainsMono_SemiBold55pt7b, 55, "JetBrainsMono_SemiBold55pt7b" },
  { &JetBrainsMono_SemiBold56pt7b, 56, "JetBrainsMono_SemiBold56pt7b" },
  { &JetBrainsMono_SemiBold57pt7b, 57, "JetBrainsMono_SemiBold57pt7b" },
  { &JetBrainsMono_SemiBold58pt7b, 58, "JetBrainsMono_SemiBold58pt7b" },
  { &JetBrainsMono_SemiBold59pt7b, 59, "JetBrainsMono_SemiBold59pt7b" },
  { &JetBrainsMono_SemiBold60pt7b, 60, "JetBrainsMono_SemiBold60pt7b" },
  { &JetBrainsMono_SemiBold61pt7b, 61, "JetBrainsMono_SemiBold61pt7b" },
  { &JetBrainsMono_SemiBold62pt7b, 62, "JetBrainsMono_SemiBold62pt7b" },
  { &JetBrainsMono_SemiBold63pt7b, 63, "JetBrainsMono_SemiBold63pt7b" },
  { &JetBrainsMono_SemiBold64pt7b, 64, "JetBrainsMono_SemiBold64pt7b" },
  { &JetBrainsMono_SemiBold65pt7b, 65, "JetBrainsMono_SemiBold65pt7b" },
  { &JetBrainsMono_SemiBold66pt7b, 66, "JetBrainsMono_SemiBold66pt7b" },
  { &JetBrainsMono_SemiBold67pt7b, 67, "JetBrainsMono_SemiBold67pt7b" },
  { &JetBrainsMono_SemiBold68pt7b, 68, "JetBrainsMono_SemiBold68pt7b" },
  { &JetBrainsMono_SemiBold69pt7b, 69, "JetBrainsMono_SemiBold69pt7b" },
  { &JetBrainsMono_SemiBold70pt7b, 70, "JetBrainsMono_SemiBold70pt7b" },
  { &JetBrainsMono_SemiBold71pt7b, 71, "JetBrainsMono_SemiBold71pt7b" },
  { &JetBrainsMono_SemiBold72pt7b, 72, "JetBrainsMono_SemiBold72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
