#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &RobotoCondensed_ExtraLightItalic6pt7b, 6, "RobotoCondensed_ExtraLightItalic6pt7b" },
  { &RobotoCondensed_ExtraLightItalic7pt7b, 7, "RobotoCondensed_ExtraLightItalic7pt7b" },
  { &RobotoCondensed_ExtraLightItalic8pt7b, 8, "RobotoCondensed_ExtraLightItalic8pt7b" },
  { &RobotoCondensed_ExtraLightItalic9pt7b, 9, "RobotoCondensed_ExtraLightItalic9pt7b" },
  { &RobotoCondensed_ExtraLightItalic10pt7b, 10, "RobotoCondensed_ExtraLightItalic10pt7b" },
  { &RobotoCondensed_ExtraLightItalic11pt7b, 11, "RobotoCondensed_ExtraLightItalic11pt7b" },
  { &RobotoCondensed_ExtraLightItalic12pt7b, 12, "RobotoCondensed_ExtraLightItalic12pt7b" },
  { &RobotoCondensed_ExtraLightItalic13pt7b, 13, "RobotoCondensed_ExtraLightItalic13pt7b" },
  { &RobotoCondensed_ExtraLightItalic14pt7b, 14, "RobotoCondensed_ExtraLightItalic14pt7b" },
  { &RobotoCondensed_ExtraLightItalic15pt7b, 15, "RobotoCondensed_ExtraLightItalic15pt7b" },
  { &RobotoCondensed_ExtraLightItalic16pt7b, 16, "RobotoCondensed_ExtraLightItalic16pt7b" },
  { &RobotoCondensed_ExtraLightItalic17pt7b, 17, "RobotoCondensed_ExtraLightItalic17pt7b" },
  { &RobotoCondensed_ExtraLightItalic18pt7b, 18, "RobotoCondensed_ExtraLightItalic18pt7b" },
  { &RobotoCondensed_ExtraLightItalic19pt7b, 19, "RobotoCondensed_ExtraLightItalic19pt7b" },
  { &RobotoCondensed_ExtraLightItalic20pt7b, 20, "RobotoCondensed_ExtraLightItalic20pt7b" },
  { &RobotoCondensed_ExtraLightItalic21pt7b, 21, "RobotoCondensed_ExtraLightItalic21pt7b" },
  { &RobotoCondensed_ExtraLightItalic22pt7b, 22, "RobotoCondensed_ExtraLightItalic22pt7b" },
  { &RobotoCondensed_ExtraLightItalic23pt7b, 23, "RobotoCondensed_ExtraLightItalic23pt7b" },
  { &RobotoCondensed_ExtraLightItalic24pt7b, 24, "RobotoCondensed_ExtraLightItalic24pt7b" },
  { &RobotoCondensed_ExtraLightItalic25pt7b, 25, "RobotoCondensed_ExtraLightItalic25pt7b" },
  { &RobotoCondensed_ExtraLightItalic26pt7b, 26, "RobotoCondensed_ExtraLightItalic26pt7b" },
  { &RobotoCondensed_ExtraLightItalic27pt7b, 27, "RobotoCondensed_ExtraLightItalic27pt7b" },
  { &RobotoCondensed_ExtraLightItalic28pt7b, 28, "RobotoCondensed_ExtraLightItalic28pt7b" },
  { &RobotoCondensed_ExtraLightItalic29pt7b, 29, "RobotoCondensed_ExtraLightItalic29pt7b" },
  { &RobotoCondensed_ExtraLightItalic30pt7b, 30, "RobotoCondensed_ExtraLightItalic30pt7b" },
  { &RobotoCondensed_ExtraLightItalic31pt7b, 31, "RobotoCondensed_ExtraLightItalic31pt7b" },
  { &RobotoCondensed_ExtraLightItalic32pt7b, 32, "RobotoCondensed_ExtraLightItalic32pt7b" },
  { &RobotoCondensed_ExtraLightItalic33pt7b, 33, "RobotoCondensed_ExtraLightItalic33pt7b" },
  { &RobotoCondensed_ExtraLightItalic34pt7b, 34, "RobotoCondensed_ExtraLightItalic34pt7b" },
  { &RobotoCondensed_ExtraLightItalic35pt7b, 35, "RobotoCondensed_ExtraLightItalic35pt7b" },
  { &RobotoCondensed_ExtraLightItalic36pt7b, 36, "RobotoCondensed_ExtraLightItalic36pt7b" },
  { &RobotoCondensed_ExtraLightItalic37pt7b, 37, "RobotoCondensed_ExtraLightItalic37pt7b" },
  { &RobotoCondensed_ExtraLightItalic38pt7b, 38, "RobotoCondensed_ExtraLightItalic38pt7b" },
  { &RobotoCondensed_ExtraLightItalic39pt7b, 39, "RobotoCondensed_ExtraLightItalic39pt7b" },
  { &RobotoCondensed_ExtraLightItalic40pt7b, 40, "RobotoCondensed_ExtraLightItalic40pt7b" },
  { &RobotoCondensed_ExtraLightItalic41pt7b, 41, "RobotoCondensed_ExtraLightItalic41pt7b" },
  { &RobotoCondensed_ExtraLightItalic42pt7b, 42, "RobotoCondensed_ExtraLightItalic42pt7b" },
  { &RobotoCondensed_ExtraLightItalic43pt7b, 43, "RobotoCondensed_ExtraLightItalic43pt7b" },
  { &RobotoCondensed_ExtraLightItalic44pt7b, 44, "RobotoCondensed_ExtraLightItalic44pt7b" },
  { &RobotoCondensed_ExtraLightItalic45pt7b, 45, "RobotoCondensed_ExtraLightItalic45pt7b" },
  { &RobotoCondensed_ExtraLightItalic46pt7b, 46, "RobotoCondensed_ExtraLightItalic46pt7b" },
  { &RobotoCondensed_ExtraLightItalic47pt7b, 47, "RobotoCondensed_ExtraLightItalic47pt7b" },
  { &RobotoCondensed_ExtraLightItalic48pt7b, 48, "RobotoCondensed_ExtraLightItalic48pt7b" },
  { &RobotoCondensed_ExtraLightItalic49pt7b, 49, "RobotoCondensed_ExtraLightItalic49pt7b" },
  { &RobotoCondensed_ExtraLightItalic50pt7b, 50, "RobotoCondensed_ExtraLightItalic50pt7b" },
  { &RobotoCondensed_ExtraLightItalic51pt7b, 51, "RobotoCondensed_ExtraLightItalic51pt7b" },
  { &RobotoCondensed_ExtraLightItalic52pt7b, 52, "RobotoCondensed_ExtraLightItalic52pt7b" },
  { &RobotoCondensed_ExtraLightItalic53pt7b, 53, "RobotoCondensed_ExtraLightItalic53pt7b" },
  { &RobotoCondensed_ExtraLightItalic54pt7b, 54, "RobotoCondensed_ExtraLightItalic54pt7b" },
  { &RobotoCondensed_ExtraLightItalic55pt7b, 55, "RobotoCondensed_ExtraLightItalic55pt7b" },
  { &RobotoCondensed_ExtraLightItalic56pt7b, 56, "RobotoCondensed_ExtraLightItalic56pt7b" },
  { &RobotoCondensed_ExtraLightItalic57pt7b, 57, "RobotoCondensed_ExtraLightItalic57pt7b" },
  { &RobotoCondensed_ExtraLightItalic58pt7b, 58, "RobotoCondensed_ExtraLightItalic58pt7b" },
  { &RobotoCondensed_ExtraLightItalic59pt7b, 59, "RobotoCondensed_ExtraLightItalic59pt7b" },
  { &RobotoCondensed_ExtraLightItalic60pt7b, 60, "RobotoCondensed_ExtraLightItalic60pt7b" },
  { &RobotoCondensed_ExtraLightItalic61pt7b, 61, "RobotoCondensed_ExtraLightItalic61pt7b" },
  { &RobotoCondensed_ExtraLightItalic62pt7b, 62, "RobotoCondensed_ExtraLightItalic62pt7b" },
  { &RobotoCondensed_ExtraLightItalic63pt7b, 63, "RobotoCondensed_ExtraLightItalic63pt7b" },
  { &RobotoCondensed_ExtraLightItalic64pt7b, 64, "RobotoCondensed_ExtraLightItalic64pt7b" },
  { &RobotoCondensed_ExtraLightItalic65pt7b, 65, "RobotoCondensed_ExtraLightItalic65pt7b" },
  { &RobotoCondensed_ExtraLightItalic66pt7b, 66, "RobotoCondensed_ExtraLightItalic66pt7b" },
  { &RobotoCondensed_ExtraLightItalic67pt7b, 67, "RobotoCondensed_ExtraLightItalic67pt7b" },
  { &RobotoCondensed_ExtraLightItalic68pt7b, 68, "RobotoCondensed_ExtraLightItalic68pt7b" },
  { &RobotoCondensed_ExtraLightItalic69pt7b, 69, "RobotoCondensed_ExtraLightItalic69pt7b" },
  { &RobotoCondensed_ExtraLightItalic70pt7b, 70, "RobotoCondensed_ExtraLightItalic70pt7b" },
  { &RobotoCondensed_ExtraLightItalic71pt7b, 71, "RobotoCondensed_ExtraLightItalic71pt7b" },
  { &RobotoCondensed_ExtraLightItalic72pt7b, 72, "RobotoCondensed_ExtraLightItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
