#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &LiberationMono_Regular6pt7b, 6, "LiberationMono_Regular6pt7b" },
  { &LiberationMono_Regular7pt7b, 7, "LiberationMono_Regular7pt7b" },
  { &LiberationMono_Regular8pt7b, 8, "LiberationMono_Regular8pt7b" },
  { &LiberationMono_Regular9pt7b, 9, "LiberationMono_Regular9pt7b" },
  { &LiberationMono_Regular10pt7b, 10, "LiberationMono_Regular10pt7b" },
  { &LiberationMono_Regular11pt7b, 11, "LiberationMono_Regular11pt7b" },
  { &LiberationMono_Regular12pt7b, 12, "LiberationMono_Regular12pt7b" },
  { &LiberationMono_Regular13pt7b, 13, "LiberationMono_Regular13pt7b" },
  { &LiberationMono_Regular14pt7b, 14, "LiberationMono_Regular14pt7b" },
  { &LiberationMono_Regular15pt7b, 15, "LiberationMono_Regular15pt7b" },
  { &LiberationMono_Regular16pt7b, 16, "LiberationMono_Regular16pt7b" },
  { &LiberationMono_Regular17pt7b, 17, "LiberationMono_Regular17pt7b" },
  { &LiberationMono_Regular18pt7b, 18, "LiberationMono_Regular18pt7b" },
  { &LiberationMono_Regular19pt7b, 19, "LiberationMono_Regular19pt7b" },
  { &LiberationMono_Regular20pt7b, 20, "LiberationMono_Regular20pt7b" },
  { &LiberationMono_Regular21pt7b, 21, "LiberationMono_Regular21pt7b" },
  { &LiberationMono_Regular22pt7b, 22, "LiberationMono_Regular22pt7b" },
  { &LiberationMono_Regular23pt7b, 23, "LiberationMono_Regular23pt7b" },
  { &LiberationMono_Regular24pt7b, 24, "LiberationMono_Regular24pt7b" },
  { &LiberationMono_Regular25pt7b, 25, "LiberationMono_Regular25pt7b" },
  { &LiberationMono_Regular26pt7b, 26, "LiberationMono_Regular26pt7b" },
  { &LiberationMono_Regular27pt7b, 27, "LiberationMono_Regular27pt7b" },
  { &LiberationMono_Regular28pt7b, 28, "LiberationMono_Regular28pt7b" },
  { &LiberationMono_Regular29pt7b, 29, "LiberationMono_Regular29pt7b" },
  { &LiberationMono_Regular30pt7b, 30, "LiberationMono_Regular30pt7b" },
  { &LiberationMono_Regular31pt7b, 31, "LiberationMono_Regular31pt7b" },
  { &LiberationMono_Regular32pt7b, 32, "LiberationMono_Regular32pt7b" },
  { &LiberationMono_Regular33pt7b, 33, "LiberationMono_Regular33pt7b" },
  { &LiberationMono_Regular34pt7b, 34, "LiberationMono_Regular34pt7b" },
  { &LiberationMono_Regular35pt7b, 35, "LiberationMono_Regular35pt7b" },
  { &LiberationMono_Regular36pt7b, 36, "LiberationMono_Regular36pt7b" },
  { &LiberationMono_Regular37pt7b, 37, "LiberationMono_Regular37pt7b" },
  { &LiberationMono_Regular38pt7b, 38, "LiberationMono_Regular38pt7b" },
  { &LiberationMono_Regular39pt7b, 39, "LiberationMono_Regular39pt7b" },
  { &LiberationMono_Regular40pt7b, 40, "LiberationMono_Regular40pt7b" },
  { &LiberationMono_Regular41pt7b, 41, "LiberationMono_Regular41pt7b" },
  { &LiberationMono_Regular42pt7b, 42, "LiberationMono_Regular42pt7b" },
  { &LiberationMono_Regular43pt7b, 43, "LiberationMono_Regular43pt7b" },
  { &LiberationMono_Regular44pt7b, 44, "LiberationMono_Regular44pt7b" },
  { &LiberationMono_Regular45pt7b, 45, "LiberationMono_Regular45pt7b" },
  { &LiberationMono_Regular46pt7b, 46, "LiberationMono_Regular46pt7b" },
  { &LiberationMono_Regular47pt7b, 47, "LiberationMono_Regular47pt7b" },
  { &LiberationMono_Regular48pt7b, 48, "LiberationMono_Regular48pt7b" },
  { &LiberationMono_Regular49pt7b, 49, "LiberationMono_Regular49pt7b" },
  { &LiberationMono_Regular50pt7b, 50, "LiberationMono_Regular50pt7b" },
  { &LiberationMono_Regular51pt7b, 51, "LiberationMono_Regular51pt7b" },
  { &LiberationMono_Regular52pt7b, 52, "LiberationMono_Regular52pt7b" },
  { &LiberationMono_Regular53pt7b, 53, "LiberationMono_Regular53pt7b" },
  { &LiberationMono_Regular54pt7b, 54, "LiberationMono_Regular54pt7b" },
  { &LiberationMono_Regular55pt7b, 55, "LiberationMono_Regular55pt7b" },
  { &LiberationMono_Regular56pt7b, 56, "LiberationMono_Regular56pt7b" },
  { &LiberationMono_Regular57pt7b, 57, "LiberationMono_Regular57pt7b" },
  { &LiberationMono_Regular58pt7b, 58, "LiberationMono_Regular58pt7b" },
  { &LiberationMono_Regular59pt7b, 59, "LiberationMono_Regular59pt7b" },
  { &LiberationMono_Regular60pt7b, 60, "LiberationMono_Regular60pt7b" },
  { &LiberationMono_Regular61pt7b, 61, "LiberationMono_Regular61pt7b" },
  { &LiberationMono_Regular62pt7b, 62, "LiberationMono_Regular62pt7b" },
  { &LiberationMono_Regular63pt7b, 63, "LiberationMono_Regular63pt7b" },
  { &LiberationMono_Regular64pt7b, 64, "LiberationMono_Regular64pt7b" },
  { &LiberationMono_Regular65pt7b, 65, "LiberationMono_Regular65pt7b" },
  { &LiberationMono_Regular66pt7b, 66, "LiberationMono_Regular66pt7b" },
  { &LiberationMono_Regular67pt7b, 67, "LiberationMono_Regular67pt7b" },
  { &LiberationMono_Regular68pt7b, 68, "LiberationMono_Regular68pt7b" },
  { &LiberationMono_Regular69pt7b, 69, "LiberationMono_Regular69pt7b" },
  { &LiberationMono_Regular70pt7b, 70, "LiberationMono_Regular70pt7b" },
  { &LiberationMono_Regular71pt7b, 71, "LiberationMono_Regular71pt7b" },
  { &LiberationMono_Regular72pt7b, 72, "LiberationMono_Regular72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
