#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &IBMPlexMono_ThinItalic6pt7b, 6, "IBMPlexMono_ThinItalic6pt7b" },
  { &IBMPlexMono_ThinItalic7pt7b, 7, "IBMPlexMono_ThinItalic7pt7b" },
  { &IBMPlexMono_ThinItalic8pt7b, 8, "IBMPlexMono_ThinItalic8pt7b" },
  { &IBMPlexMono_ThinItalic9pt7b, 9, "IBMPlexMono_ThinItalic9pt7b" },
  { &IBMPlexMono_ThinItalic10pt7b, 10, "IBMPlexMono_ThinItalic10pt7b" },
  { &IBMPlexMono_ThinItalic11pt7b, 11, "IBMPlexMono_ThinItalic11pt7b" },
  { &IBMPlexMono_ThinItalic12pt7b, 12, "IBMPlexMono_ThinItalic12pt7b" },
  { &IBMPlexMono_ThinItalic13pt7b, 13, "IBMPlexMono_ThinItalic13pt7b" },
  { &IBMPlexMono_ThinItalic14pt7b, 14, "IBMPlexMono_ThinItalic14pt7b" },
  { &IBMPlexMono_ThinItalic15pt7b, 15, "IBMPlexMono_ThinItalic15pt7b" },
  { &IBMPlexMono_ThinItalic16pt7b, 16, "IBMPlexMono_ThinItalic16pt7b" },
  { &IBMPlexMono_ThinItalic17pt7b, 17, "IBMPlexMono_ThinItalic17pt7b" },
  { &IBMPlexMono_ThinItalic18pt7b, 18, "IBMPlexMono_ThinItalic18pt7b" },
  { &IBMPlexMono_ThinItalic19pt7b, 19, "IBMPlexMono_ThinItalic19pt7b" },
  { &IBMPlexMono_ThinItalic20pt7b, 20, "IBMPlexMono_ThinItalic20pt7b" },
  { &IBMPlexMono_ThinItalic21pt7b, 21, "IBMPlexMono_ThinItalic21pt7b" },
  { &IBMPlexMono_ThinItalic22pt7b, 22, "IBMPlexMono_ThinItalic22pt7b" },
  { &IBMPlexMono_ThinItalic23pt7b, 23, "IBMPlexMono_ThinItalic23pt7b" },
  { &IBMPlexMono_ThinItalic24pt7b, 24, "IBMPlexMono_ThinItalic24pt7b" },
  { &IBMPlexMono_ThinItalic25pt7b, 25, "IBMPlexMono_ThinItalic25pt7b" },
  { &IBMPlexMono_ThinItalic26pt7b, 26, "IBMPlexMono_ThinItalic26pt7b" },
  { &IBMPlexMono_ThinItalic27pt7b, 27, "IBMPlexMono_ThinItalic27pt7b" },
  { &IBMPlexMono_ThinItalic28pt7b, 28, "IBMPlexMono_ThinItalic28pt7b" },
  { &IBMPlexMono_ThinItalic29pt7b, 29, "IBMPlexMono_ThinItalic29pt7b" },
  { &IBMPlexMono_ThinItalic30pt7b, 30, "IBMPlexMono_ThinItalic30pt7b" },
  { &IBMPlexMono_ThinItalic31pt7b, 31, "IBMPlexMono_ThinItalic31pt7b" },
  { &IBMPlexMono_ThinItalic32pt7b, 32, "IBMPlexMono_ThinItalic32pt7b" },
  { &IBMPlexMono_ThinItalic33pt7b, 33, "IBMPlexMono_ThinItalic33pt7b" },
  { &IBMPlexMono_ThinItalic34pt7b, 34, "IBMPlexMono_ThinItalic34pt7b" },
  { &IBMPlexMono_ThinItalic35pt7b, 35, "IBMPlexMono_ThinItalic35pt7b" },
  { &IBMPlexMono_ThinItalic36pt7b, 36, "IBMPlexMono_ThinItalic36pt7b" },
  { &IBMPlexMono_ThinItalic37pt7b, 37, "IBMPlexMono_ThinItalic37pt7b" },
  { &IBMPlexMono_ThinItalic38pt7b, 38, "IBMPlexMono_ThinItalic38pt7b" },
  { &IBMPlexMono_ThinItalic39pt7b, 39, "IBMPlexMono_ThinItalic39pt7b" },
  { &IBMPlexMono_ThinItalic40pt7b, 40, "IBMPlexMono_ThinItalic40pt7b" },
  { &IBMPlexMono_ThinItalic41pt7b, 41, "IBMPlexMono_ThinItalic41pt7b" },
  { &IBMPlexMono_ThinItalic42pt7b, 42, "IBMPlexMono_ThinItalic42pt7b" },
  { &IBMPlexMono_ThinItalic43pt7b, 43, "IBMPlexMono_ThinItalic43pt7b" },
  { &IBMPlexMono_ThinItalic44pt7b, 44, "IBMPlexMono_ThinItalic44pt7b" },
  { &IBMPlexMono_ThinItalic45pt7b, 45, "IBMPlexMono_ThinItalic45pt7b" },
  { &IBMPlexMono_ThinItalic46pt7b, 46, "IBMPlexMono_ThinItalic46pt7b" },
  { &IBMPlexMono_ThinItalic47pt7b, 47, "IBMPlexMono_ThinItalic47pt7b" },
  { &IBMPlexMono_ThinItalic48pt7b, 48, "IBMPlexMono_ThinItalic48pt7b" },
  { &IBMPlexMono_ThinItalic49pt7b, 49, "IBMPlexMono_ThinItalic49pt7b" },
  { &IBMPlexMono_ThinItalic50pt7b, 50, "IBMPlexMono_ThinItalic50pt7b" },
  { &IBMPlexMono_ThinItalic51pt7b, 51, "IBMPlexMono_ThinItalic51pt7b" },
  { &IBMPlexMono_ThinItalic52pt7b, 52, "IBMPlexMono_ThinItalic52pt7b" },
  { &IBMPlexMono_ThinItalic53pt7b, 53, "IBMPlexMono_ThinItalic53pt7b" },
  { &IBMPlexMono_ThinItalic54pt7b, 54, "IBMPlexMono_ThinItalic54pt7b" },
  { &IBMPlexMono_ThinItalic55pt7b, 55, "IBMPlexMono_ThinItalic55pt7b" },
  { &IBMPlexMono_ThinItalic56pt7b, 56, "IBMPlexMono_ThinItalic56pt7b" },
  { &IBMPlexMono_ThinItalic57pt7b, 57, "IBMPlexMono_ThinItalic57pt7b" },
  { &IBMPlexMono_ThinItalic58pt7b, 58, "IBMPlexMono_ThinItalic58pt7b" },
  { &IBMPlexMono_ThinItalic59pt7b, 59, "IBMPlexMono_ThinItalic59pt7b" },
  { &IBMPlexMono_ThinItalic60pt7b, 60, "IBMPlexMono_ThinItalic60pt7b" },
  { &IBMPlexMono_ThinItalic61pt7b, 61, "IBMPlexMono_ThinItalic61pt7b" },
  { &IBMPlexMono_ThinItalic62pt7b, 62, "IBMPlexMono_ThinItalic62pt7b" },
  { &IBMPlexMono_ThinItalic63pt7b, 63, "IBMPlexMono_ThinItalic63pt7b" },
  { &IBMPlexMono_ThinItalic64pt7b, 64, "IBMPlexMono_ThinItalic64pt7b" },
  { &IBMPlexMono_ThinItalic65pt7b, 65, "IBMPlexMono_ThinItalic65pt7b" },
  { &IBMPlexMono_ThinItalic66pt7b, 66, "IBMPlexMono_ThinItalic66pt7b" },
  { &IBMPlexMono_ThinItalic67pt7b, 67, "IBMPlexMono_ThinItalic67pt7b" },
  { &IBMPlexMono_ThinItalic68pt7b, 68, "IBMPlexMono_ThinItalic68pt7b" },
  { &IBMPlexMono_ThinItalic69pt7b, 69, "IBMPlexMono_ThinItalic69pt7b" },
  { &IBMPlexMono_ThinItalic70pt7b, 70, "IBMPlexMono_ThinItalic70pt7b" },
  { &IBMPlexMono_ThinItalic71pt7b, 71, "IBMPlexMono_ThinItalic71pt7b" },
  { &IBMPlexMono_ThinItalic72pt7b, 72, "IBMPlexMono_ThinItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
