#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &RobotoCondensed_Bold6pt7b, 6, "RobotoCondensed_Bold6pt7b" },
  { &RobotoCondensed_Bold7pt7b, 7, "RobotoCondensed_Bold7pt7b" },
  { &RobotoCondensed_Bold8pt7b, 8, "RobotoCondensed_Bold8pt7b" },
  { &RobotoCondensed_Bold9pt7b, 9, "RobotoCondensed_Bold9pt7b" },
  { &RobotoCondensed_Bold10pt7b, 10, "RobotoCondensed_Bold10pt7b" },
  { &RobotoCondensed_Bold11pt7b, 11, "RobotoCondensed_Bold11pt7b" },
  { &RobotoCondensed_Bold12pt7b, 12, "RobotoCondensed_Bold12pt7b" },
  { &RobotoCondensed_Bold13pt7b, 13, "RobotoCondensed_Bold13pt7b" },
  { &RobotoCondensed_Bold14pt7b, 14, "RobotoCondensed_Bold14pt7b" },
  { &RobotoCondensed_Bold15pt7b, 15, "RobotoCondensed_Bold15pt7b" },
  { &RobotoCondensed_Bold16pt7b, 16, "RobotoCondensed_Bold16pt7b" },
  { &RobotoCondensed_Bold17pt7b, 17, "RobotoCondensed_Bold17pt7b" },
  { &RobotoCondensed_Bold18pt7b, 18, "RobotoCondensed_Bold18pt7b" },
  { &RobotoCondensed_Bold19pt7b, 19, "RobotoCondensed_Bold19pt7b" },
  { &RobotoCondensed_Bold20pt7b, 20, "RobotoCondensed_Bold20pt7b" },
  { &RobotoCondensed_Bold21pt7b, 21, "RobotoCondensed_Bold21pt7b" },
  { &RobotoCondensed_Bold22pt7b, 22, "RobotoCondensed_Bold22pt7b" },
  { &RobotoCondensed_Bold23pt7b, 23, "RobotoCondensed_Bold23pt7b" },
  { &RobotoCondensed_Bold24pt7b, 24, "RobotoCondensed_Bold24pt7b" },
  { &RobotoCondensed_Bold25pt7b, 25, "RobotoCondensed_Bold25pt7b" },
  { &RobotoCondensed_Bold26pt7b, 26, "RobotoCondensed_Bold26pt7b" },
  { &RobotoCondensed_Bold27pt7b, 27, "RobotoCondensed_Bold27pt7b" },
  { &RobotoCondensed_Bold28pt7b, 28, "RobotoCondensed_Bold28pt7b" },
  { &RobotoCondensed_Bold29pt7b, 29, "RobotoCondensed_Bold29pt7b" },
  { &RobotoCondensed_Bold30pt7b, 30, "RobotoCondensed_Bold30pt7b" },
  { &RobotoCondensed_Bold31pt7b, 31, "RobotoCondensed_Bold31pt7b" },
  { &RobotoCondensed_Bold32pt7b, 32, "RobotoCondensed_Bold32pt7b" },
  { &RobotoCondensed_Bold33pt7b, 33, "RobotoCondensed_Bold33pt7b" },
  { &RobotoCondensed_Bold34pt7b, 34, "RobotoCondensed_Bold34pt7b" },
  { &RobotoCondensed_Bold35pt7b, 35, "RobotoCondensed_Bold35pt7b" },
  { &RobotoCondensed_Bold36pt7b, 36, "RobotoCondensed_Bold36pt7b" },
  { &RobotoCondensed_Bold37pt7b, 37, "RobotoCondensed_Bold37pt7b" },
  { &RobotoCondensed_Bold38pt7b, 38, "RobotoCondensed_Bold38pt7b" },
  { &RobotoCondensed_Bold39pt7b, 39, "RobotoCondensed_Bold39pt7b" },
  { &RobotoCondensed_Bold40pt7b, 40, "RobotoCondensed_Bold40pt7b" },
  { &RobotoCondensed_Bold41pt7b, 41, "RobotoCondensed_Bold41pt7b" },
  { &RobotoCondensed_Bold42pt7b, 42, "RobotoCondensed_Bold42pt7b" },
  { &RobotoCondensed_Bold43pt7b, 43, "RobotoCondensed_Bold43pt7b" },
  { &RobotoCondensed_Bold44pt7b, 44, "RobotoCondensed_Bold44pt7b" },
  { &RobotoCondensed_Bold45pt7b, 45, "RobotoCondensed_Bold45pt7b" },
  { &RobotoCondensed_Bold46pt7b, 46, "RobotoCondensed_Bold46pt7b" },
  { &RobotoCondensed_Bold47pt7b, 47, "RobotoCondensed_Bold47pt7b" },
  { &RobotoCondensed_Bold48pt7b, 48, "RobotoCondensed_Bold48pt7b" },
  { &RobotoCondensed_Bold49pt7b, 49, "RobotoCondensed_Bold49pt7b" },
  { &RobotoCondensed_Bold50pt7b, 50, "RobotoCondensed_Bold50pt7b" },
  { &RobotoCondensed_Bold51pt7b, 51, "RobotoCondensed_Bold51pt7b" },
  { &RobotoCondensed_Bold52pt7b, 52, "RobotoCondensed_Bold52pt7b" },
  { &RobotoCondensed_Bold53pt7b, 53, "RobotoCondensed_Bold53pt7b" },
  { &RobotoCondensed_Bold54pt7b, 54, "RobotoCondensed_Bold54pt7b" },
  { &RobotoCondensed_Bold55pt7b, 55, "RobotoCondensed_Bold55pt7b" },
  { &RobotoCondensed_Bold56pt7b, 56, "RobotoCondensed_Bold56pt7b" },
  { &RobotoCondensed_Bold57pt7b, 57, "RobotoCondensed_Bold57pt7b" },
  { &RobotoCondensed_Bold58pt7b, 58, "RobotoCondensed_Bold58pt7b" },
  { &RobotoCondensed_Bold59pt7b, 59, "RobotoCondensed_Bold59pt7b" },
  { &RobotoCondensed_Bold60pt7b, 60, "RobotoCondensed_Bold60pt7b" },
  { &RobotoCondensed_Bold61pt7b, 61, "RobotoCondensed_Bold61pt7b" },
  { &RobotoCondensed_Bold62pt7b, 62, "RobotoCondensed_Bold62pt7b" },
  { &RobotoCondensed_Bold63pt7b, 63, "RobotoCondensed_Bold63pt7b" },
  { &RobotoCondensed_Bold64pt7b, 64, "RobotoCondensed_Bold64pt7b" },
  { &RobotoCondensed_Bold65pt7b, 65, "RobotoCondensed_Bold65pt7b" },
  { &RobotoCondensed_Bold66pt7b, 66, "RobotoCondensed_Bold66pt7b" },
  { &RobotoCondensed_Bold67pt7b, 67, "RobotoCondensed_Bold67pt7b" },
  { &RobotoCondensed_Bold68pt7b, 68, "RobotoCondensed_Bold68pt7b" },
  { &RobotoCondensed_Bold69pt7b, 69, "RobotoCondensed_Bold69pt7b" },
  { &RobotoCondensed_Bold70pt7b, 70, "RobotoCondensed_Bold70pt7b" },
  { &RobotoCondensed_Bold71pt7b, 71, "RobotoCondensed_Bold71pt7b" },
  { &RobotoCondensed_Bold72pt7b, 72, "RobotoCondensed_Bold72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
