#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &RobotoMono_Light6pt7b, 6, "RobotoMono_Light6pt7b" },
  { &RobotoMono_Light7pt7b, 7, "RobotoMono_Light7pt7b" },
  { &RobotoMono_Light8pt7b, 8, "RobotoMono_Light8pt7b" },
  { &RobotoMono_Light9pt7b, 9, "RobotoMono_Light9pt7b" },
  { &RobotoMono_Light10pt7b, 10, "RobotoMono_Light10pt7b" },
  { &RobotoMono_Light11pt7b, 11, "RobotoMono_Light11pt7b" },
  { &RobotoMono_Light12pt7b, 12, "RobotoMono_Light12pt7b" },
  { &RobotoMono_Light13pt7b, 13, "RobotoMono_Light13pt7b" },
  { &RobotoMono_Light14pt7b, 14, "RobotoMono_Light14pt7b" },
  { &RobotoMono_Light15pt7b, 15, "RobotoMono_Light15pt7b" },
  { &RobotoMono_Light16pt7b, 16, "RobotoMono_Light16pt7b" },
  { &RobotoMono_Light17pt7b, 17, "RobotoMono_Light17pt7b" },
  { &RobotoMono_Light18pt7b, 18, "RobotoMono_Light18pt7b" },
  { &RobotoMono_Light19pt7b, 19, "RobotoMono_Light19pt7b" },
  { &RobotoMono_Light20pt7b, 20, "RobotoMono_Light20pt7b" },
  { &RobotoMono_Light21pt7b, 21, "RobotoMono_Light21pt7b" },
  { &RobotoMono_Light22pt7b, 22, "RobotoMono_Light22pt7b" },
  { &RobotoMono_Light23pt7b, 23, "RobotoMono_Light23pt7b" },
  { &RobotoMono_Light24pt7b, 24, "RobotoMono_Light24pt7b" },
  { &RobotoMono_Light25pt7b, 25, "RobotoMono_Light25pt7b" },
  { &RobotoMono_Light26pt7b, 26, "RobotoMono_Light26pt7b" },
  { &RobotoMono_Light27pt7b, 27, "RobotoMono_Light27pt7b" },
  { &RobotoMono_Light28pt7b, 28, "RobotoMono_Light28pt7b" },
  { &RobotoMono_Light29pt7b, 29, "RobotoMono_Light29pt7b" },
  { &RobotoMono_Light30pt7b, 30, "RobotoMono_Light30pt7b" },
  { &RobotoMono_Light31pt7b, 31, "RobotoMono_Light31pt7b" },
  { &RobotoMono_Light32pt7b, 32, "RobotoMono_Light32pt7b" },
  { &RobotoMono_Light33pt7b, 33, "RobotoMono_Light33pt7b" },
  { &RobotoMono_Light34pt7b, 34, "RobotoMono_Light34pt7b" },
  { &RobotoMono_Light35pt7b, 35, "RobotoMono_Light35pt7b" },
  { &RobotoMono_Light36pt7b, 36, "RobotoMono_Light36pt7b" },
  { &RobotoMono_Light37pt7b, 37, "RobotoMono_Light37pt7b" },
  { &RobotoMono_Light38pt7b, 38, "RobotoMono_Light38pt7b" },
  { &RobotoMono_Light39pt7b, 39, "RobotoMono_Light39pt7b" },
  { &RobotoMono_Light40pt7b, 40, "RobotoMono_Light40pt7b" },
  { &RobotoMono_Light41pt7b, 41, "RobotoMono_Light41pt7b" },
  { &RobotoMono_Light42pt7b, 42, "RobotoMono_Light42pt7b" },
  { &RobotoMono_Light43pt7b, 43, "RobotoMono_Light43pt7b" },
  { &RobotoMono_Light44pt7b, 44, "RobotoMono_Light44pt7b" },
  { &RobotoMono_Light45pt7b, 45, "RobotoMono_Light45pt7b" },
  { &RobotoMono_Light46pt7b, 46, "RobotoMono_Light46pt7b" },
  { &RobotoMono_Light47pt7b, 47, "RobotoMono_Light47pt7b" },
  { &RobotoMono_Light48pt7b, 48, "RobotoMono_Light48pt7b" },
  { &RobotoMono_Light49pt7b, 49, "RobotoMono_Light49pt7b" },
  { &RobotoMono_Light50pt7b, 50, "RobotoMono_Light50pt7b" },
  { &RobotoMono_Light51pt7b, 51, "RobotoMono_Light51pt7b" },
  { &RobotoMono_Light52pt7b, 52, "RobotoMono_Light52pt7b" },
  { &RobotoMono_Light53pt7b, 53, "RobotoMono_Light53pt7b" },
  { &RobotoMono_Light54pt7b, 54, "RobotoMono_Light54pt7b" },
  { &RobotoMono_Light55pt7b, 55, "RobotoMono_Light55pt7b" },
  { &RobotoMono_Light56pt7b, 56, "RobotoMono_Light56pt7b" },
  { &RobotoMono_Light57pt7b, 57, "RobotoMono_Light57pt7b" },
  { &RobotoMono_Light58pt7b, 58, "RobotoMono_Light58pt7b" },
  { &RobotoMono_Light59pt7b, 59, "RobotoMono_Light59pt7b" },
  { &RobotoMono_Light60pt7b, 60, "RobotoMono_Light60pt7b" },
  { &RobotoMono_Light61pt7b, 61, "RobotoMono_Light61pt7b" },
  { &RobotoMono_Light62pt7b, 62, "RobotoMono_Light62pt7b" },
  { &RobotoMono_Light63pt7b, 63, "RobotoMono_Light63pt7b" },
  { &RobotoMono_Light64pt7b, 64, "RobotoMono_Light64pt7b" },
  { &RobotoMono_Light65pt7b, 65, "RobotoMono_Light65pt7b" },
  { &RobotoMono_Light66pt7b, 66, "RobotoMono_Light66pt7b" },
  { &RobotoMono_Light67pt7b, 67, "RobotoMono_Light67pt7b" },
  { &RobotoMono_Light68pt7b, 68, "RobotoMono_Light68pt7b" },
  { &RobotoMono_Light69pt7b, 69, "RobotoMono_Light69pt7b" },
  { &RobotoMono_Light70pt7b, 70, "RobotoMono_Light70pt7b" },
  { &RobotoMono_Light71pt7b, 71, "RobotoMono_Light71pt7b" },
  { &RobotoMono_Light72pt7b, 72, "RobotoMono_Light72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
