#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_Condensed_Black6pt7b, 6, "NotoSans_Condensed_Black6pt7b" },
  { &NotoSans_Condensed_Black7pt7b, 7, "NotoSans_Condensed_Black7pt7b" },
  { &NotoSans_Condensed_Black8pt7b, 8, "NotoSans_Condensed_Black8pt7b" },
  { &NotoSans_Condensed_Black9pt7b, 9, "NotoSans_Condensed_Black9pt7b" },
  { &NotoSans_Condensed_Black10pt7b, 10, "NotoSans_Condensed_Black10pt7b" },
  { &NotoSans_Condensed_Black11pt7b, 11, "NotoSans_Condensed_Black11pt7b" },
  { &NotoSans_Condensed_Black12pt7b, 12, "NotoSans_Condensed_Black12pt7b" },
  { &NotoSans_Condensed_Black13pt7b, 13, "NotoSans_Condensed_Black13pt7b" },
  { &NotoSans_Condensed_Black14pt7b, 14, "NotoSans_Condensed_Black14pt7b" },
  { &NotoSans_Condensed_Black15pt7b, 15, "NotoSans_Condensed_Black15pt7b" },
  { &NotoSans_Condensed_Black16pt7b, 16, "NotoSans_Condensed_Black16pt7b" },
  { &NotoSans_Condensed_Black17pt7b, 17, "NotoSans_Condensed_Black17pt7b" },
  { &NotoSans_Condensed_Black18pt7b, 18, "NotoSans_Condensed_Black18pt7b" },
  { &NotoSans_Condensed_Black19pt7b, 19, "NotoSans_Condensed_Black19pt7b" },
  { &NotoSans_Condensed_Black20pt7b, 20, "NotoSans_Condensed_Black20pt7b" },
  { &NotoSans_Condensed_Black21pt7b, 21, "NotoSans_Condensed_Black21pt7b" },
  { &NotoSans_Condensed_Black22pt7b, 22, "NotoSans_Condensed_Black22pt7b" },
  { &NotoSans_Condensed_Black23pt7b, 23, "NotoSans_Condensed_Black23pt7b" },
  { &NotoSans_Condensed_Black24pt7b, 24, "NotoSans_Condensed_Black24pt7b" },
  { &NotoSans_Condensed_Black25pt7b, 25, "NotoSans_Condensed_Black25pt7b" },
  { &NotoSans_Condensed_Black26pt7b, 26, "NotoSans_Condensed_Black26pt7b" },
  { &NotoSans_Condensed_Black27pt7b, 27, "NotoSans_Condensed_Black27pt7b" },
  { &NotoSans_Condensed_Black28pt7b, 28, "NotoSans_Condensed_Black28pt7b" },
  { &NotoSans_Condensed_Black29pt7b, 29, "NotoSans_Condensed_Black29pt7b" },
  { &NotoSans_Condensed_Black30pt7b, 30, "NotoSans_Condensed_Black30pt7b" },
  { &NotoSans_Condensed_Black31pt7b, 31, "NotoSans_Condensed_Black31pt7b" },
  { &NotoSans_Condensed_Black32pt7b, 32, "NotoSans_Condensed_Black32pt7b" },
  { &NotoSans_Condensed_Black33pt7b, 33, "NotoSans_Condensed_Black33pt7b" },
  { &NotoSans_Condensed_Black34pt7b, 34, "NotoSans_Condensed_Black34pt7b" },
  { &NotoSans_Condensed_Black35pt7b, 35, "NotoSans_Condensed_Black35pt7b" },
  { &NotoSans_Condensed_Black36pt7b, 36, "NotoSans_Condensed_Black36pt7b" },
  { &NotoSans_Condensed_Black37pt7b, 37, "NotoSans_Condensed_Black37pt7b" },
  { &NotoSans_Condensed_Black38pt7b, 38, "NotoSans_Condensed_Black38pt7b" },
  { &NotoSans_Condensed_Black39pt7b, 39, "NotoSans_Condensed_Black39pt7b" },
  { &NotoSans_Condensed_Black40pt7b, 40, "NotoSans_Condensed_Black40pt7b" },
  { &NotoSans_Condensed_Black41pt7b, 41, "NotoSans_Condensed_Black41pt7b" },
  { &NotoSans_Condensed_Black42pt7b, 42, "NotoSans_Condensed_Black42pt7b" },
  { &NotoSans_Condensed_Black43pt7b, 43, "NotoSans_Condensed_Black43pt7b" },
  { &NotoSans_Condensed_Black44pt7b, 44, "NotoSans_Condensed_Black44pt7b" },
  { &NotoSans_Condensed_Black45pt7b, 45, "NotoSans_Condensed_Black45pt7b" },
  { &NotoSans_Condensed_Black46pt7b, 46, "NotoSans_Condensed_Black46pt7b" },
  { &NotoSans_Condensed_Black47pt7b, 47, "NotoSans_Condensed_Black47pt7b" },
  { &NotoSans_Condensed_Black48pt7b, 48, "NotoSans_Condensed_Black48pt7b" },
  { &NotoSans_Condensed_Black49pt7b, 49, "NotoSans_Condensed_Black49pt7b" },
  { &NotoSans_Condensed_Black50pt7b, 50, "NotoSans_Condensed_Black50pt7b" },
  { &NotoSans_Condensed_Black51pt7b, 51, "NotoSans_Condensed_Black51pt7b" },
  { &NotoSans_Condensed_Black52pt7b, 52, "NotoSans_Condensed_Black52pt7b" },
  { &NotoSans_Condensed_Black53pt7b, 53, "NotoSans_Condensed_Black53pt7b" },
  { &NotoSans_Condensed_Black54pt7b, 54, "NotoSans_Condensed_Black54pt7b" },
  { &NotoSans_Condensed_Black55pt7b, 55, "NotoSans_Condensed_Black55pt7b" },
  { &NotoSans_Condensed_Black56pt7b, 56, "NotoSans_Condensed_Black56pt7b" },
  { &NotoSans_Condensed_Black57pt7b, 57, "NotoSans_Condensed_Black57pt7b" },
  { &NotoSans_Condensed_Black58pt7b, 58, "NotoSans_Condensed_Black58pt7b" },
  { &NotoSans_Condensed_Black59pt7b, 59, "NotoSans_Condensed_Black59pt7b" },
  { &NotoSans_Condensed_Black60pt7b, 60, "NotoSans_Condensed_Black60pt7b" },
  { &NotoSans_Condensed_Black61pt7b, 61, "NotoSans_Condensed_Black61pt7b" },
  { &NotoSans_Condensed_Black62pt7b, 62, "NotoSans_Condensed_Black62pt7b" },
  { &NotoSans_Condensed_Black63pt7b, 63, "NotoSans_Condensed_Black63pt7b" },
  { &NotoSans_Condensed_Black64pt7b, 64, "NotoSans_Condensed_Black64pt7b" },
  { &NotoSans_Condensed_Black65pt7b, 65, "NotoSans_Condensed_Black65pt7b" },
  { &NotoSans_Condensed_Black66pt7b, 66, "NotoSans_Condensed_Black66pt7b" },
  { &NotoSans_Condensed_Black67pt7b, 67, "NotoSans_Condensed_Black67pt7b" },
  { &NotoSans_Condensed_Black68pt7b, 68, "NotoSans_Condensed_Black68pt7b" },
  { &NotoSans_Condensed_Black69pt7b, 69, "NotoSans_Condensed_Black69pt7b" },
  { &NotoSans_Condensed_Black70pt7b, 70, "NotoSans_Condensed_Black70pt7b" },
  { &NotoSans_Condensed_Black71pt7b, 71, "NotoSans_Condensed_Black71pt7b" },
  { &NotoSans_Condensed_Black72pt7b, 72, "NotoSans_Condensed_Black72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
