#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &UbuntuSansMono_Bold6pt7b, 6, "UbuntuSansMono_Bold6pt7b" },
  { &UbuntuSansMono_Bold7pt7b, 7, "UbuntuSansMono_Bold7pt7b" },
  { &UbuntuSansMono_Bold8pt7b, 8, "UbuntuSansMono_Bold8pt7b" },
  { &UbuntuSansMono_Bold9pt7b, 9, "UbuntuSansMono_Bold9pt7b" },
  { &UbuntuSansMono_Bold10pt7b, 10, "UbuntuSansMono_Bold10pt7b" },
  { &UbuntuSansMono_Bold11pt7b, 11, "UbuntuSansMono_Bold11pt7b" },
  { &UbuntuSansMono_Bold12pt7b, 12, "UbuntuSansMono_Bold12pt7b" },
  { &UbuntuSansMono_Bold13pt7b, 13, "UbuntuSansMono_Bold13pt7b" },
  { &UbuntuSansMono_Bold14pt7b, 14, "UbuntuSansMono_Bold14pt7b" },
  { &UbuntuSansMono_Bold15pt7b, 15, "UbuntuSansMono_Bold15pt7b" },
  { &UbuntuSansMono_Bold16pt7b, 16, "UbuntuSansMono_Bold16pt7b" },
  { &UbuntuSansMono_Bold17pt7b, 17, "UbuntuSansMono_Bold17pt7b" },
  { &UbuntuSansMono_Bold18pt7b, 18, "UbuntuSansMono_Bold18pt7b" },
  { &UbuntuSansMono_Bold19pt7b, 19, "UbuntuSansMono_Bold19pt7b" },
  { &UbuntuSansMono_Bold20pt7b, 20, "UbuntuSansMono_Bold20pt7b" },
  { &UbuntuSansMono_Bold21pt7b, 21, "UbuntuSansMono_Bold21pt7b" },
  { &UbuntuSansMono_Bold22pt7b, 22, "UbuntuSansMono_Bold22pt7b" },
  { &UbuntuSansMono_Bold23pt7b, 23, "UbuntuSansMono_Bold23pt7b" },
  { &UbuntuSansMono_Bold24pt7b, 24, "UbuntuSansMono_Bold24pt7b" },
  { &UbuntuSansMono_Bold25pt7b, 25, "UbuntuSansMono_Bold25pt7b" },
  { &UbuntuSansMono_Bold26pt7b, 26, "UbuntuSansMono_Bold26pt7b" },
  { &UbuntuSansMono_Bold27pt7b, 27, "UbuntuSansMono_Bold27pt7b" },
  { &UbuntuSansMono_Bold28pt7b, 28, "UbuntuSansMono_Bold28pt7b" },
  { &UbuntuSansMono_Bold29pt7b, 29, "UbuntuSansMono_Bold29pt7b" },
  { &UbuntuSansMono_Bold30pt7b, 30, "UbuntuSansMono_Bold30pt7b" },
  { &UbuntuSansMono_Bold31pt7b, 31, "UbuntuSansMono_Bold31pt7b" },
  { &UbuntuSansMono_Bold32pt7b, 32, "UbuntuSansMono_Bold32pt7b" },
  { &UbuntuSansMono_Bold33pt7b, 33, "UbuntuSansMono_Bold33pt7b" },
  { &UbuntuSansMono_Bold34pt7b, 34, "UbuntuSansMono_Bold34pt7b" },
  { &UbuntuSansMono_Bold35pt7b, 35, "UbuntuSansMono_Bold35pt7b" },
  { &UbuntuSansMono_Bold36pt7b, 36, "UbuntuSansMono_Bold36pt7b" },
  { &UbuntuSansMono_Bold37pt7b, 37, "UbuntuSansMono_Bold37pt7b" },
  { &UbuntuSansMono_Bold38pt7b, 38, "UbuntuSansMono_Bold38pt7b" },
  { &UbuntuSansMono_Bold39pt7b, 39, "UbuntuSansMono_Bold39pt7b" },
  { &UbuntuSansMono_Bold40pt7b, 40, "UbuntuSansMono_Bold40pt7b" },
  { &UbuntuSansMono_Bold41pt7b, 41, "UbuntuSansMono_Bold41pt7b" },
  { &UbuntuSansMono_Bold42pt7b, 42, "UbuntuSansMono_Bold42pt7b" },
  { &UbuntuSansMono_Bold43pt7b, 43, "UbuntuSansMono_Bold43pt7b" },
  { &UbuntuSansMono_Bold44pt7b, 44, "UbuntuSansMono_Bold44pt7b" },
  { &UbuntuSansMono_Bold45pt7b, 45, "UbuntuSansMono_Bold45pt7b" },
  { &UbuntuSansMono_Bold46pt7b, 46, "UbuntuSansMono_Bold46pt7b" },
  { &UbuntuSansMono_Bold47pt7b, 47, "UbuntuSansMono_Bold47pt7b" },
  { &UbuntuSansMono_Bold48pt7b, 48, "UbuntuSansMono_Bold48pt7b" },
  { &UbuntuSansMono_Bold49pt7b, 49, "UbuntuSansMono_Bold49pt7b" },
  { &UbuntuSansMono_Bold50pt7b, 50, "UbuntuSansMono_Bold50pt7b" },
  { &UbuntuSansMono_Bold51pt7b, 51, "UbuntuSansMono_Bold51pt7b" },
  { &UbuntuSansMono_Bold52pt7b, 52, "UbuntuSansMono_Bold52pt7b" },
  { &UbuntuSansMono_Bold53pt7b, 53, "UbuntuSansMono_Bold53pt7b" },
  { &UbuntuSansMono_Bold54pt7b, 54, "UbuntuSansMono_Bold54pt7b" },
  { &UbuntuSansMono_Bold55pt7b, 55, "UbuntuSansMono_Bold55pt7b" },
  { &UbuntuSansMono_Bold56pt7b, 56, "UbuntuSansMono_Bold56pt7b" },
  { &UbuntuSansMono_Bold57pt7b, 57, "UbuntuSansMono_Bold57pt7b" },
  { &UbuntuSansMono_Bold58pt7b, 58, "UbuntuSansMono_Bold58pt7b" },
  { &UbuntuSansMono_Bold59pt7b, 59, "UbuntuSansMono_Bold59pt7b" },
  { &UbuntuSansMono_Bold60pt7b, 60, "UbuntuSansMono_Bold60pt7b" },
  { &UbuntuSansMono_Bold61pt7b, 61, "UbuntuSansMono_Bold61pt7b" },
  { &UbuntuSansMono_Bold62pt7b, 62, "UbuntuSansMono_Bold62pt7b" },
  { &UbuntuSansMono_Bold63pt7b, 63, "UbuntuSansMono_Bold63pt7b" },
  { &UbuntuSansMono_Bold64pt7b, 64, "UbuntuSansMono_Bold64pt7b" },
  { &UbuntuSansMono_Bold65pt7b, 65, "UbuntuSansMono_Bold65pt7b" },
  { &UbuntuSansMono_Bold66pt7b, 66, "UbuntuSansMono_Bold66pt7b" },
  { &UbuntuSansMono_Bold67pt7b, 67, "UbuntuSansMono_Bold67pt7b" },
  { &UbuntuSansMono_Bold68pt7b, 68, "UbuntuSansMono_Bold68pt7b" },
  { &UbuntuSansMono_Bold69pt7b, 69, "UbuntuSansMono_Bold69pt7b" },
  { &UbuntuSansMono_Bold70pt7b, 70, "UbuntuSansMono_Bold70pt7b" },
  { &UbuntuSansMono_Bold71pt7b, 71, "UbuntuSansMono_Bold71pt7b" },
  { &UbuntuSansMono_Bold72pt7b, 72, "UbuntuSansMono_Bold72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
