#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &LiberationMono_BoldItalic6pt7b, 6, "LiberationMono_BoldItalic6pt7b" },
  { &LiberationMono_BoldItalic7pt7b, 7, "LiberationMono_BoldItalic7pt7b" },
  { &LiberationMono_BoldItalic8pt7b, 8, "LiberationMono_BoldItalic8pt7b" },
  { &LiberationMono_BoldItalic9pt7b, 9, "LiberationMono_BoldItalic9pt7b" },
  { &LiberationMono_BoldItalic10pt7b, 10, "LiberationMono_BoldItalic10pt7b" },
  { &LiberationMono_BoldItalic11pt7b, 11, "LiberationMono_BoldItalic11pt7b" },
  { &LiberationMono_BoldItalic12pt7b, 12, "LiberationMono_BoldItalic12pt7b" },
  { &LiberationMono_BoldItalic13pt7b, 13, "LiberationMono_BoldItalic13pt7b" },
  { &LiberationMono_BoldItalic14pt7b, 14, "LiberationMono_BoldItalic14pt7b" },
  { &LiberationMono_BoldItalic15pt7b, 15, "LiberationMono_BoldItalic15pt7b" },
  { &LiberationMono_BoldItalic16pt7b, 16, "LiberationMono_BoldItalic16pt7b" },
  { &LiberationMono_BoldItalic17pt7b, 17, "LiberationMono_BoldItalic17pt7b" },
  { &LiberationMono_BoldItalic18pt7b, 18, "LiberationMono_BoldItalic18pt7b" },
  { &LiberationMono_BoldItalic19pt7b, 19, "LiberationMono_BoldItalic19pt7b" },
  { &LiberationMono_BoldItalic20pt7b, 20, "LiberationMono_BoldItalic20pt7b" },
  { &LiberationMono_BoldItalic21pt7b, 21, "LiberationMono_BoldItalic21pt7b" },
  { &LiberationMono_BoldItalic22pt7b, 22, "LiberationMono_BoldItalic22pt7b" },
  { &LiberationMono_BoldItalic23pt7b, 23, "LiberationMono_BoldItalic23pt7b" },
  { &LiberationMono_BoldItalic24pt7b, 24, "LiberationMono_BoldItalic24pt7b" },
  { &LiberationMono_BoldItalic25pt7b, 25, "LiberationMono_BoldItalic25pt7b" },
  { &LiberationMono_BoldItalic26pt7b, 26, "LiberationMono_BoldItalic26pt7b" },
  { &LiberationMono_BoldItalic27pt7b, 27, "LiberationMono_BoldItalic27pt7b" },
  { &LiberationMono_BoldItalic28pt7b, 28, "LiberationMono_BoldItalic28pt7b" },
  { &LiberationMono_BoldItalic29pt7b, 29, "LiberationMono_BoldItalic29pt7b" },
  { &LiberationMono_BoldItalic30pt7b, 30, "LiberationMono_BoldItalic30pt7b" },
  { &LiberationMono_BoldItalic31pt7b, 31, "LiberationMono_BoldItalic31pt7b" },
  { &LiberationMono_BoldItalic32pt7b, 32, "LiberationMono_BoldItalic32pt7b" },
  { &LiberationMono_BoldItalic33pt7b, 33, "LiberationMono_BoldItalic33pt7b" },
  { &LiberationMono_BoldItalic34pt7b, 34, "LiberationMono_BoldItalic34pt7b" },
  { &LiberationMono_BoldItalic35pt7b, 35, "LiberationMono_BoldItalic35pt7b" },
  { &LiberationMono_BoldItalic36pt7b, 36, "LiberationMono_BoldItalic36pt7b" },
  { &LiberationMono_BoldItalic37pt7b, 37, "LiberationMono_BoldItalic37pt7b" },
  { &LiberationMono_BoldItalic38pt7b, 38, "LiberationMono_BoldItalic38pt7b" },
  { &LiberationMono_BoldItalic39pt7b, 39, "LiberationMono_BoldItalic39pt7b" },
  { &LiberationMono_BoldItalic40pt7b, 40, "LiberationMono_BoldItalic40pt7b" },
  { &LiberationMono_BoldItalic41pt7b, 41, "LiberationMono_BoldItalic41pt7b" },
  { &LiberationMono_BoldItalic42pt7b, 42, "LiberationMono_BoldItalic42pt7b" },
  { &LiberationMono_BoldItalic43pt7b, 43, "LiberationMono_BoldItalic43pt7b" },
  { &LiberationMono_BoldItalic44pt7b, 44, "LiberationMono_BoldItalic44pt7b" },
  { &LiberationMono_BoldItalic45pt7b, 45, "LiberationMono_BoldItalic45pt7b" },
  { &LiberationMono_BoldItalic46pt7b, 46, "LiberationMono_BoldItalic46pt7b" },
  { &LiberationMono_BoldItalic47pt7b, 47, "LiberationMono_BoldItalic47pt7b" },
  { &LiberationMono_BoldItalic48pt7b, 48, "LiberationMono_BoldItalic48pt7b" },
  { &LiberationMono_BoldItalic49pt7b, 49, "LiberationMono_BoldItalic49pt7b" },
  { &LiberationMono_BoldItalic50pt7b, 50, "LiberationMono_BoldItalic50pt7b" },
  { &LiberationMono_BoldItalic51pt7b, 51, "LiberationMono_BoldItalic51pt7b" },
  { &LiberationMono_BoldItalic52pt7b, 52, "LiberationMono_BoldItalic52pt7b" },
  { &LiberationMono_BoldItalic53pt7b, 53, "LiberationMono_BoldItalic53pt7b" },
  { &LiberationMono_BoldItalic54pt7b, 54, "LiberationMono_BoldItalic54pt7b" },
  { &LiberationMono_BoldItalic55pt7b, 55, "LiberationMono_BoldItalic55pt7b" },
  { &LiberationMono_BoldItalic56pt7b, 56, "LiberationMono_BoldItalic56pt7b" },
  { &LiberationMono_BoldItalic57pt7b, 57, "LiberationMono_BoldItalic57pt7b" },
  { &LiberationMono_BoldItalic58pt7b, 58, "LiberationMono_BoldItalic58pt7b" },
  { &LiberationMono_BoldItalic59pt7b, 59, "LiberationMono_BoldItalic59pt7b" },
  { &LiberationMono_BoldItalic60pt7b, 60, "LiberationMono_BoldItalic60pt7b" },
  { &LiberationMono_BoldItalic61pt7b, 61, "LiberationMono_BoldItalic61pt7b" },
  { &LiberationMono_BoldItalic62pt7b, 62, "LiberationMono_BoldItalic62pt7b" },
  { &LiberationMono_BoldItalic63pt7b, 63, "LiberationMono_BoldItalic63pt7b" },
  { &LiberationMono_BoldItalic64pt7b, 64, "LiberationMono_BoldItalic64pt7b" },
  { &LiberationMono_BoldItalic65pt7b, 65, "LiberationMono_BoldItalic65pt7b" },
  { &LiberationMono_BoldItalic66pt7b, 66, "LiberationMono_BoldItalic66pt7b" },
  { &LiberationMono_BoldItalic67pt7b, 67, "LiberationMono_BoldItalic67pt7b" },
  { &LiberationMono_BoldItalic68pt7b, 68, "LiberationMono_BoldItalic68pt7b" },
  { &LiberationMono_BoldItalic69pt7b, 69, "LiberationMono_BoldItalic69pt7b" },
  { &LiberationMono_BoldItalic70pt7b, 70, "LiberationMono_BoldItalic70pt7b" },
  { &LiberationMono_BoldItalic71pt7b, 71, "LiberationMono_BoldItalic71pt7b" },
  { &LiberationMono_BoldItalic72pt7b, 72, "LiberationMono_BoldItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
