#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_Condensed_ExtraBold6pt7b, 6, "NotoSans_Condensed_ExtraBold6pt7b" },
  { &NotoSans_Condensed_ExtraBold7pt7b, 7, "NotoSans_Condensed_ExtraBold7pt7b" },
  { &NotoSans_Condensed_ExtraBold8pt7b, 8, "NotoSans_Condensed_ExtraBold8pt7b" },
  { &NotoSans_Condensed_ExtraBold9pt7b, 9, "NotoSans_Condensed_ExtraBold9pt7b" },
  { &NotoSans_Condensed_ExtraBold10pt7b, 10, "NotoSans_Condensed_ExtraBold10pt7b" },
  { &NotoSans_Condensed_ExtraBold11pt7b, 11, "NotoSans_Condensed_ExtraBold11pt7b" },
  { &NotoSans_Condensed_ExtraBold12pt7b, 12, "NotoSans_Condensed_ExtraBold12pt7b" },
  { &NotoSans_Condensed_ExtraBold13pt7b, 13, "NotoSans_Condensed_ExtraBold13pt7b" },
  { &NotoSans_Condensed_ExtraBold14pt7b, 14, "NotoSans_Condensed_ExtraBold14pt7b" },
  { &NotoSans_Condensed_ExtraBold15pt7b, 15, "NotoSans_Condensed_ExtraBold15pt7b" },
  { &NotoSans_Condensed_ExtraBold16pt7b, 16, "NotoSans_Condensed_ExtraBold16pt7b" },
  { &NotoSans_Condensed_ExtraBold17pt7b, 17, "NotoSans_Condensed_ExtraBold17pt7b" },
  { &NotoSans_Condensed_ExtraBold18pt7b, 18, "NotoSans_Condensed_ExtraBold18pt7b" },
  { &NotoSans_Condensed_ExtraBold19pt7b, 19, "NotoSans_Condensed_ExtraBold19pt7b" },
  { &NotoSans_Condensed_ExtraBold20pt7b, 20, "NotoSans_Condensed_ExtraBold20pt7b" },
  { &NotoSans_Condensed_ExtraBold21pt7b, 21, "NotoSans_Condensed_ExtraBold21pt7b" },
  { &NotoSans_Condensed_ExtraBold22pt7b, 22, "NotoSans_Condensed_ExtraBold22pt7b" },
  { &NotoSans_Condensed_ExtraBold23pt7b, 23, "NotoSans_Condensed_ExtraBold23pt7b" },
  { &NotoSans_Condensed_ExtraBold24pt7b, 24, "NotoSans_Condensed_ExtraBold24pt7b" },
  { &NotoSans_Condensed_ExtraBold25pt7b, 25, "NotoSans_Condensed_ExtraBold25pt7b" },
  { &NotoSans_Condensed_ExtraBold26pt7b, 26, "NotoSans_Condensed_ExtraBold26pt7b" },
  { &NotoSans_Condensed_ExtraBold27pt7b, 27, "NotoSans_Condensed_ExtraBold27pt7b" },
  { &NotoSans_Condensed_ExtraBold28pt7b, 28, "NotoSans_Condensed_ExtraBold28pt7b" },
  { &NotoSans_Condensed_ExtraBold29pt7b, 29, "NotoSans_Condensed_ExtraBold29pt7b" },
  { &NotoSans_Condensed_ExtraBold30pt7b, 30, "NotoSans_Condensed_ExtraBold30pt7b" },
  { &NotoSans_Condensed_ExtraBold31pt7b, 31, "NotoSans_Condensed_ExtraBold31pt7b" },
  { &NotoSans_Condensed_ExtraBold32pt7b, 32, "NotoSans_Condensed_ExtraBold32pt7b" },
  { &NotoSans_Condensed_ExtraBold33pt7b, 33, "NotoSans_Condensed_ExtraBold33pt7b" },
  { &NotoSans_Condensed_ExtraBold34pt7b, 34, "NotoSans_Condensed_ExtraBold34pt7b" },
  { &NotoSans_Condensed_ExtraBold35pt7b, 35, "NotoSans_Condensed_ExtraBold35pt7b" },
  { &NotoSans_Condensed_ExtraBold36pt7b, 36, "NotoSans_Condensed_ExtraBold36pt7b" },
  { &NotoSans_Condensed_ExtraBold37pt7b, 37, "NotoSans_Condensed_ExtraBold37pt7b" },
  { &NotoSans_Condensed_ExtraBold38pt7b, 38, "NotoSans_Condensed_ExtraBold38pt7b" },
  { &NotoSans_Condensed_ExtraBold39pt7b, 39, "NotoSans_Condensed_ExtraBold39pt7b" },
  { &NotoSans_Condensed_ExtraBold40pt7b, 40, "NotoSans_Condensed_ExtraBold40pt7b" },
  { &NotoSans_Condensed_ExtraBold41pt7b, 41, "NotoSans_Condensed_ExtraBold41pt7b" },
  { &NotoSans_Condensed_ExtraBold42pt7b, 42, "NotoSans_Condensed_ExtraBold42pt7b" },
  { &NotoSans_Condensed_ExtraBold43pt7b, 43, "NotoSans_Condensed_ExtraBold43pt7b" },
  { &NotoSans_Condensed_ExtraBold44pt7b, 44, "NotoSans_Condensed_ExtraBold44pt7b" },
  { &NotoSans_Condensed_ExtraBold45pt7b, 45, "NotoSans_Condensed_ExtraBold45pt7b" },
  { &NotoSans_Condensed_ExtraBold46pt7b, 46, "NotoSans_Condensed_ExtraBold46pt7b" },
  { &NotoSans_Condensed_ExtraBold47pt7b, 47, "NotoSans_Condensed_ExtraBold47pt7b" },
  { &NotoSans_Condensed_ExtraBold48pt7b, 48, "NotoSans_Condensed_ExtraBold48pt7b" },
  { &NotoSans_Condensed_ExtraBold49pt7b, 49, "NotoSans_Condensed_ExtraBold49pt7b" },
  { &NotoSans_Condensed_ExtraBold50pt7b, 50, "NotoSans_Condensed_ExtraBold50pt7b" },
  { &NotoSans_Condensed_ExtraBold51pt7b, 51, "NotoSans_Condensed_ExtraBold51pt7b" },
  { &NotoSans_Condensed_ExtraBold52pt7b, 52, "NotoSans_Condensed_ExtraBold52pt7b" },
  { &NotoSans_Condensed_ExtraBold53pt7b, 53, "NotoSans_Condensed_ExtraBold53pt7b" },
  { &NotoSans_Condensed_ExtraBold54pt7b, 54, "NotoSans_Condensed_ExtraBold54pt7b" },
  { &NotoSans_Condensed_ExtraBold55pt7b, 55, "NotoSans_Condensed_ExtraBold55pt7b" },
  { &NotoSans_Condensed_ExtraBold56pt7b, 56, "NotoSans_Condensed_ExtraBold56pt7b" },
  { &NotoSans_Condensed_ExtraBold57pt7b, 57, "NotoSans_Condensed_ExtraBold57pt7b" },
  { &NotoSans_Condensed_ExtraBold58pt7b, 58, "NotoSans_Condensed_ExtraBold58pt7b" },
  { &NotoSans_Condensed_ExtraBold59pt7b, 59, "NotoSans_Condensed_ExtraBold59pt7b" },
  { &NotoSans_Condensed_ExtraBold60pt7b, 60, "NotoSans_Condensed_ExtraBold60pt7b" },
  { &NotoSans_Condensed_ExtraBold61pt7b, 61, "NotoSans_Condensed_ExtraBold61pt7b" },
  { &NotoSans_Condensed_ExtraBold62pt7b, 62, "NotoSans_Condensed_ExtraBold62pt7b" },
  { &NotoSans_Condensed_ExtraBold63pt7b, 63, "NotoSans_Condensed_ExtraBold63pt7b" },
  { &NotoSans_Condensed_ExtraBold64pt7b, 64, "NotoSans_Condensed_ExtraBold64pt7b" },
  { &NotoSans_Condensed_ExtraBold65pt7b, 65, "NotoSans_Condensed_ExtraBold65pt7b" },
  { &NotoSans_Condensed_ExtraBold66pt7b, 66, "NotoSans_Condensed_ExtraBold66pt7b" },
  { &NotoSans_Condensed_ExtraBold67pt7b, 67, "NotoSans_Condensed_ExtraBold67pt7b" },
  { &NotoSans_Condensed_ExtraBold68pt7b, 68, "NotoSans_Condensed_ExtraBold68pt7b" },
  { &NotoSans_Condensed_ExtraBold69pt7b, 69, "NotoSans_Condensed_ExtraBold69pt7b" },
  { &NotoSans_Condensed_ExtraBold70pt7b, 70, "NotoSans_Condensed_ExtraBold70pt7b" },
  { &NotoSans_Condensed_ExtraBold71pt7b, 71, "NotoSans_Condensed_ExtraBold71pt7b" },
  { &NotoSans_Condensed_ExtraBold72pt7b, 72, "NotoSans_Condensed_ExtraBold72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
