#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &RobotoCondensed_Thin6pt7b, 6, "RobotoCondensed_Thin6pt7b" },
  { &RobotoCondensed_Thin7pt7b, 7, "RobotoCondensed_Thin7pt7b" },
  { &RobotoCondensed_Thin8pt7b, 8, "RobotoCondensed_Thin8pt7b" },
  { &RobotoCondensed_Thin9pt7b, 9, "RobotoCondensed_Thin9pt7b" },
  { &RobotoCondensed_Thin10pt7b, 10, "RobotoCondensed_Thin10pt7b" },
  { &RobotoCondensed_Thin11pt7b, 11, "RobotoCondensed_Thin11pt7b" },
  { &RobotoCondensed_Thin12pt7b, 12, "RobotoCondensed_Thin12pt7b" },
  { &RobotoCondensed_Thin13pt7b, 13, "RobotoCondensed_Thin13pt7b" },
  { &RobotoCondensed_Thin14pt7b, 14, "RobotoCondensed_Thin14pt7b" },
  { &RobotoCondensed_Thin15pt7b, 15, "RobotoCondensed_Thin15pt7b" },
  { &RobotoCondensed_Thin16pt7b, 16, "RobotoCondensed_Thin16pt7b" },
  { &RobotoCondensed_Thin17pt7b, 17, "RobotoCondensed_Thin17pt7b" },
  { &RobotoCondensed_Thin18pt7b, 18, "RobotoCondensed_Thin18pt7b" },
  { &RobotoCondensed_Thin19pt7b, 19, "RobotoCondensed_Thin19pt7b" },
  { &RobotoCondensed_Thin20pt7b, 20, "RobotoCondensed_Thin20pt7b" },
  { &RobotoCondensed_Thin21pt7b, 21, "RobotoCondensed_Thin21pt7b" },
  { &RobotoCondensed_Thin22pt7b, 22, "RobotoCondensed_Thin22pt7b" },
  { &RobotoCondensed_Thin23pt7b, 23, "RobotoCondensed_Thin23pt7b" },
  { &RobotoCondensed_Thin24pt7b, 24, "RobotoCondensed_Thin24pt7b" },
  { &RobotoCondensed_Thin25pt7b, 25, "RobotoCondensed_Thin25pt7b" },
  { &RobotoCondensed_Thin26pt7b, 26, "RobotoCondensed_Thin26pt7b" },
  { &RobotoCondensed_Thin27pt7b, 27, "RobotoCondensed_Thin27pt7b" },
  { &RobotoCondensed_Thin28pt7b, 28, "RobotoCondensed_Thin28pt7b" },
  { &RobotoCondensed_Thin29pt7b, 29, "RobotoCondensed_Thin29pt7b" },
  { &RobotoCondensed_Thin30pt7b, 30, "RobotoCondensed_Thin30pt7b" },
  { &RobotoCondensed_Thin31pt7b, 31, "RobotoCondensed_Thin31pt7b" },
  { &RobotoCondensed_Thin32pt7b, 32, "RobotoCondensed_Thin32pt7b" },
  { &RobotoCondensed_Thin33pt7b, 33, "RobotoCondensed_Thin33pt7b" },
  { &RobotoCondensed_Thin34pt7b, 34, "RobotoCondensed_Thin34pt7b" },
  { &RobotoCondensed_Thin35pt7b, 35, "RobotoCondensed_Thin35pt7b" },
  { &RobotoCondensed_Thin36pt7b, 36, "RobotoCondensed_Thin36pt7b" },
  { &RobotoCondensed_Thin37pt7b, 37, "RobotoCondensed_Thin37pt7b" },
  { &RobotoCondensed_Thin38pt7b, 38, "RobotoCondensed_Thin38pt7b" },
  { &RobotoCondensed_Thin39pt7b, 39, "RobotoCondensed_Thin39pt7b" },
  { &RobotoCondensed_Thin40pt7b, 40, "RobotoCondensed_Thin40pt7b" },
  { &RobotoCondensed_Thin41pt7b, 41, "RobotoCondensed_Thin41pt7b" },
  { &RobotoCondensed_Thin42pt7b, 42, "RobotoCondensed_Thin42pt7b" },
  { &RobotoCondensed_Thin43pt7b, 43, "RobotoCondensed_Thin43pt7b" },
  { &RobotoCondensed_Thin44pt7b, 44, "RobotoCondensed_Thin44pt7b" },
  { &RobotoCondensed_Thin45pt7b, 45, "RobotoCondensed_Thin45pt7b" },
  { &RobotoCondensed_Thin46pt7b, 46, "RobotoCondensed_Thin46pt7b" },
  { &RobotoCondensed_Thin47pt7b, 47, "RobotoCondensed_Thin47pt7b" },
  { &RobotoCondensed_Thin48pt7b, 48, "RobotoCondensed_Thin48pt7b" },
  { &RobotoCondensed_Thin49pt7b, 49, "RobotoCondensed_Thin49pt7b" },
  { &RobotoCondensed_Thin50pt7b, 50, "RobotoCondensed_Thin50pt7b" },
  { &RobotoCondensed_Thin51pt7b, 51, "RobotoCondensed_Thin51pt7b" },
  { &RobotoCondensed_Thin52pt7b, 52, "RobotoCondensed_Thin52pt7b" },
  { &RobotoCondensed_Thin53pt7b, 53, "RobotoCondensed_Thin53pt7b" },
  { &RobotoCondensed_Thin54pt7b, 54, "RobotoCondensed_Thin54pt7b" },
  { &RobotoCondensed_Thin55pt7b, 55, "RobotoCondensed_Thin55pt7b" },
  { &RobotoCondensed_Thin56pt7b, 56, "RobotoCondensed_Thin56pt7b" },
  { &RobotoCondensed_Thin57pt7b, 57, "RobotoCondensed_Thin57pt7b" },
  { &RobotoCondensed_Thin58pt7b, 58, "RobotoCondensed_Thin58pt7b" },
  { &RobotoCondensed_Thin59pt7b, 59, "RobotoCondensed_Thin59pt7b" },
  { &RobotoCondensed_Thin60pt7b, 60, "RobotoCondensed_Thin60pt7b" },
  { &RobotoCondensed_Thin61pt7b, 61, "RobotoCondensed_Thin61pt7b" },
  { &RobotoCondensed_Thin62pt7b, 62, "RobotoCondensed_Thin62pt7b" },
  { &RobotoCondensed_Thin63pt7b, 63, "RobotoCondensed_Thin63pt7b" },
  { &RobotoCondensed_Thin64pt7b, 64, "RobotoCondensed_Thin64pt7b" },
  { &RobotoCondensed_Thin65pt7b, 65, "RobotoCondensed_Thin65pt7b" },
  { &RobotoCondensed_Thin66pt7b, 66, "RobotoCondensed_Thin66pt7b" },
  { &RobotoCondensed_Thin67pt7b, 67, "RobotoCondensed_Thin67pt7b" },
  { &RobotoCondensed_Thin68pt7b, 68, "RobotoCondensed_Thin68pt7b" },
  { &RobotoCondensed_Thin69pt7b, 69, "RobotoCondensed_Thin69pt7b" },
  { &RobotoCondensed_Thin70pt7b, 70, "RobotoCondensed_Thin70pt7b" },
  { &RobotoCondensed_Thin71pt7b, 71, "RobotoCondensed_Thin71pt7b" },
  { &RobotoCondensed_Thin72pt7b, 72, "RobotoCondensed_Thin72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
