#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_SemiCondensed_Italic6pt7b, 6, "NotoSans_SemiCondensed_Italic6pt7b" },
  { &NotoSans_SemiCondensed_Italic7pt7b, 7, "NotoSans_SemiCondensed_Italic7pt7b" },
  { &NotoSans_SemiCondensed_Italic8pt7b, 8, "NotoSans_SemiCondensed_Italic8pt7b" },
  { &NotoSans_SemiCondensed_Italic9pt7b, 9, "NotoSans_SemiCondensed_Italic9pt7b" },
  { &NotoSans_SemiCondensed_Italic10pt7b, 10, "NotoSans_SemiCondensed_Italic10pt7b" },
  { &NotoSans_SemiCondensed_Italic11pt7b, 11, "NotoSans_SemiCondensed_Italic11pt7b" },
  { &NotoSans_SemiCondensed_Italic12pt7b, 12, "NotoSans_SemiCondensed_Italic12pt7b" },
  { &NotoSans_SemiCondensed_Italic13pt7b, 13, "NotoSans_SemiCondensed_Italic13pt7b" },
  { &NotoSans_SemiCondensed_Italic14pt7b, 14, "NotoSans_SemiCondensed_Italic14pt7b" },
  { &NotoSans_SemiCondensed_Italic15pt7b, 15, "NotoSans_SemiCondensed_Italic15pt7b" },
  { &NotoSans_SemiCondensed_Italic16pt7b, 16, "NotoSans_SemiCondensed_Italic16pt7b" },
  { &NotoSans_SemiCondensed_Italic17pt7b, 17, "NotoSans_SemiCondensed_Italic17pt7b" },
  { &NotoSans_SemiCondensed_Italic18pt7b, 18, "NotoSans_SemiCondensed_Italic18pt7b" },
  { &NotoSans_SemiCondensed_Italic19pt7b, 19, "NotoSans_SemiCondensed_Italic19pt7b" },
  { &NotoSans_SemiCondensed_Italic20pt7b, 20, "NotoSans_SemiCondensed_Italic20pt7b" },
  { &NotoSans_SemiCondensed_Italic21pt7b, 21, "NotoSans_SemiCondensed_Italic21pt7b" },
  { &NotoSans_SemiCondensed_Italic22pt7b, 22, "NotoSans_SemiCondensed_Italic22pt7b" },
  { &NotoSans_SemiCondensed_Italic23pt7b, 23, "NotoSans_SemiCondensed_Italic23pt7b" },
  { &NotoSans_SemiCondensed_Italic24pt7b, 24, "NotoSans_SemiCondensed_Italic24pt7b" },
  { &NotoSans_SemiCondensed_Italic25pt7b, 25, "NotoSans_SemiCondensed_Italic25pt7b" },
  { &NotoSans_SemiCondensed_Italic26pt7b, 26, "NotoSans_SemiCondensed_Italic26pt7b" },
  { &NotoSans_SemiCondensed_Italic27pt7b, 27, "NotoSans_SemiCondensed_Italic27pt7b" },
  { &NotoSans_SemiCondensed_Italic28pt7b, 28, "NotoSans_SemiCondensed_Italic28pt7b" },
  { &NotoSans_SemiCondensed_Italic29pt7b, 29, "NotoSans_SemiCondensed_Italic29pt7b" },
  { &NotoSans_SemiCondensed_Italic30pt7b, 30, "NotoSans_SemiCondensed_Italic30pt7b" },
  { &NotoSans_SemiCondensed_Italic31pt7b, 31, "NotoSans_SemiCondensed_Italic31pt7b" },
  { &NotoSans_SemiCondensed_Italic32pt7b, 32, "NotoSans_SemiCondensed_Italic32pt7b" },
  { &NotoSans_SemiCondensed_Italic33pt7b, 33, "NotoSans_SemiCondensed_Italic33pt7b" },
  { &NotoSans_SemiCondensed_Italic34pt7b, 34, "NotoSans_SemiCondensed_Italic34pt7b" },
  { &NotoSans_SemiCondensed_Italic35pt7b, 35, "NotoSans_SemiCondensed_Italic35pt7b" },
  { &NotoSans_SemiCondensed_Italic36pt7b, 36, "NotoSans_SemiCondensed_Italic36pt7b" },
  { &NotoSans_SemiCondensed_Italic37pt7b, 37, "NotoSans_SemiCondensed_Italic37pt7b" },
  { &NotoSans_SemiCondensed_Italic38pt7b, 38, "NotoSans_SemiCondensed_Italic38pt7b" },
  { &NotoSans_SemiCondensed_Italic39pt7b, 39, "NotoSans_SemiCondensed_Italic39pt7b" },
  { &NotoSans_SemiCondensed_Italic40pt7b, 40, "NotoSans_SemiCondensed_Italic40pt7b" },
  { &NotoSans_SemiCondensed_Italic41pt7b, 41, "NotoSans_SemiCondensed_Italic41pt7b" },
  { &NotoSans_SemiCondensed_Italic42pt7b, 42, "NotoSans_SemiCondensed_Italic42pt7b" },
  { &NotoSans_SemiCondensed_Italic43pt7b, 43, "NotoSans_SemiCondensed_Italic43pt7b" },
  { &NotoSans_SemiCondensed_Italic44pt7b, 44, "NotoSans_SemiCondensed_Italic44pt7b" },
  { &NotoSans_SemiCondensed_Italic45pt7b, 45, "NotoSans_SemiCondensed_Italic45pt7b" },
  { &NotoSans_SemiCondensed_Italic46pt7b, 46, "NotoSans_SemiCondensed_Italic46pt7b" },
  { &NotoSans_SemiCondensed_Italic47pt7b, 47, "NotoSans_SemiCondensed_Italic47pt7b" },
  { &NotoSans_SemiCondensed_Italic48pt7b, 48, "NotoSans_SemiCondensed_Italic48pt7b" },
  { &NotoSans_SemiCondensed_Italic49pt7b, 49, "NotoSans_SemiCondensed_Italic49pt7b" },
  { &NotoSans_SemiCondensed_Italic50pt7b, 50, "NotoSans_SemiCondensed_Italic50pt7b" },
  { &NotoSans_SemiCondensed_Italic51pt7b, 51, "NotoSans_SemiCondensed_Italic51pt7b" },
  { &NotoSans_SemiCondensed_Italic52pt7b, 52, "NotoSans_SemiCondensed_Italic52pt7b" },
  { &NotoSans_SemiCondensed_Italic53pt7b, 53, "NotoSans_SemiCondensed_Italic53pt7b" },
  { &NotoSans_SemiCondensed_Italic54pt7b, 54, "NotoSans_SemiCondensed_Italic54pt7b" },
  { &NotoSans_SemiCondensed_Italic55pt7b, 55, "NotoSans_SemiCondensed_Italic55pt7b" },
  { &NotoSans_SemiCondensed_Italic56pt7b, 56, "NotoSans_SemiCondensed_Italic56pt7b" },
  { &NotoSans_SemiCondensed_Italic57pt7b, 57, "NotoSans_SemiCondensed_Italic57pt7b" },
  { &NotoSans_SemiCondensed_Italic58pt7b, 58, "NotoSans_SemiCondensed_Italic58pt7b" },
  { &NotoSans_SemiCondensed_Italic59pt7b, 59, "NotoSans_SemiCondensed_Italic59pt7b" },
  { &NotoSans_SemiCondensed_Italic60pt7b, 60, "NotoSans_SemiCondensed_Italic60pt7b" },
  { &NotoSans_SemiCondensed_Italic61pt7b, 61, "NotoSans_SemiCondensed_Italic61pt7b" },
  { &NotoSans_SemiCondensed_Italic62pt7b, 62, "NotoSans_SemiCondensed_Italic62pt7b" },
  { &NotoSans_SemiCondensed_Italic63pt7b, 63, "NotoSans_SemiCondensed_Italic63pt7b" },
  { &NotoSans_SemiCondensed_Italic64pt7b, 64, "NotoSans_SemiCondensed_Italic64pt7b" },
  { &NotoSans_SemiCondensed_Italic65pt7b, 65, "NotoSans_SemiCondensed_Italic65pt7b" },
  { &NotoSans_SemiCondensed_Italic66pt7b, 66, "NotoSans_SemiCondensed_Italic66pt7b" },
  { &NotoSans_SemiCondensed_Italic67pt7b, 67, "NotoSans_SemiCondensed_Italic67pt7b" },
  { &NotoSans_SemiCondensed_Italic68pt7b, 68, "NotoSans_SemiCondensed_Italic68pt7b" },
  { &NotoSans_SemiCondensed_Italic69pt7b, 69, "NotoSans_SemiCondensed_Italic69pt7b" },
  { &NotoSans_SemiCondensed_Italic70pt7b, 70, "NotoSans_SemiCondensed_Italic70pt7b" },
  { &NotoSans_SemiCondensed_Italic71pt7b, 71, "NotoSans_SemiCondensed_Italic71pt7b" },
  { &NotoSans_SemiCondensed_Italic72pt7b, 72, "NotoSans_SemiCondensed_Italic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
