#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_Bold6pt7b, 6, "NotoSans_Bold6pt7b" },
  { &NotoSans_Bold7pt7b, 7, "NotoSans_Bold7pt7b" },
  { &NotoSans_Bold8pt7b, 8, "NotoSans_Bold8pt7b" },
  { &NotoSans_Bold9pt7b, 9, "NotoSans_Bold9pt7b" },
  { &NotoSans_Bold10pt7b, 10, "NotoSans_Bold10pt7b" },
  { &NotoSans_Bold11pt7b, 11, "NotoSans_Bold11pt7b" },
  { &NotoSans_Bold12pt7b, 12, "NotoSans_Bold12pt7b" },
  { &NotoSans_Bold13pt7b, 13, "NotoSans_Bold13pt7b" },
  { &NotoSans_Bold14pt7b, 14, "NotoSans_Bold14pt7b" },
  { &NotoSans_Bold15pt7b, 15, "NotoSans_Bold15pt7b" },
  { &NotoSans_Bold16pt7b, 16, "NotoSans_Bold16pt7b" },
  { &NotoSans_Bold17pt7b, 17, "NotoSans_Bold17pt7b" },
  { &NotoSans_Bold18pt7b, 18, "NotoSans_Bold18pt7b" },
  { &NotoSans_Bold19pt7b, 19, "NotoSans_Bold19pt7b" },
  { &NotoSans_Bold20pt7b, 20, "NotoSans_Bold20pt7b" },
  { &NotoSans_Bold21pt7b, 21, "NotoSans_Bold21pt7b" },
  { &NotoSans_Bold22pt7b, 22, "NotoSans_Bold22pt7b" },
  { &NotoSans_Bold23pt7b, 23, "NotoSans_Bold23pt7b" },
  { &NotoSans_Bold24pt7b, 24, "NotoSans_Bold24pt7b" },
  { &NotoSans_Bold25pt7b, 25, "NotoSans_Bold25pt7b" },
  { &NotoSans_Bold26pt7b, 26, "NotoSans_Bold26pt7b" },
  { &NotoSans_Bold27pt7b, 27, "NotoSans_Bold27pt7b" },
  { &NotoSans_Bold28pt7b, 28, "NotoSans_Bold28pt7b" },
  { &NotoSans_Bold29pt7b, 29, "NotoSans_Bold29pt7b" },
  { &NotoSans_Bold30pt7b, 30, "NotoSans_Bold30pt7b" },
  { &NotoSans_Bold31pt7b, 31, "NotoSans_Bold31pt7b" },
  { &NotoSans_Bold32pt7b, 32, "NotoSans_Bold32pt7b" },
  { &NotoSans_Bold33pt7b, 33, "NotoSans_Bold33pt7b" },
  { &NotoSans_Bold34pt7b, 34, "NotoSans_Bold34pt7b" },
  { &NotoSans_Bold35pt7b, 35, "NotoSans_Bold35pt7b" },
  { &NotoSans_Bold36pt7b, 36, "NotoSans_Bold36pt7b" },
  { &NotoSans_Bold37pt7b, 37, "NotoSans_Bold37pt7b" },
  { &NotoSans_Bold38pt7b, 38, "NotoSans_Bold38pt7b" },
  { &NotoSans_Bold39pt7b, 39, "NotoSans_Bold39pt7b" },
  { &NotoSans_Bold40pt7b, 40, "NotoSans_Bold40pt7b" },
  { &NotoSans_Bold41pt7b, 41, "NotoSans_Bold41pt7b" },
  { &NotoSans_Bold42pt7b, 42, "NotoSans_Bold42pt7b" },
  { &NotoSans_Bold43pt7b, 43, "NotoSans_Bold43pt7b" },
  { &NotoSans_Bold44pt7b, 44, "NotoSans_Bold44pt7b" },
  { &NotoSans_Bold45pt7b, 45, "NotoSans_Bold45pt7b" },
  { &NotoSans_Bold46pt7b, 46, "NotoSans_Bold46pt7b" },
  { &NotoSans_Bold47pt7b, 47, "NotoSans_Bold47pt7b" },
  { &NotoSans_Bold48pt7b, 48, "NotoSans_Bold48pt7b" },
  { &NotoSans_Bold49pt7b, 49, "NotoSans_Bold49pt7b" },
  { &NotoSans_Bold50pt7b, 50, "NotoSans_Bold50pt7b" },
  { &NotoSans_Bold51pt7b, 51, "NotoSans_Bold51pt7b" },
  { &NotoSans_Bold52pt7b, 52, "NotoSans_Bold52pt7b" },
  { &NotoSans_Bold53pt7b, 53, "NotoSans_Bold53pt7b" },
  { &NotoSans_Bold54pt7b, 54, "NotoSans_Bold54pt7b" },
  { &NotoSans_Bold55pt7b, 55, "NotoSans_Bold55pt7b" },
  { &NotoSans_Bold56pt7b, 56, "NotoSans_Bold56pt7b" },
  { &NotoSans_Bold57pt7b, 57, "NotoSans_Bold57pt7b" },
  { &NotoSans_Bold58pt7b, 58, "NotoSans_Bold58pt7b" },
  { &NotoSans_Bold59pt7b, 59, "NotoSans_Bold59pt7b" },
  { &NotoSans_Bold60pt7b, 60, "NotoSans_Bold60pt7b" },
  { &NotoSans_Bold61pt7b, 61, "NotoSans_Bold61pt7b" },
  { &NotoSans_Bold62pt7b, 62, "NotoSans_Bold62pt7b" },
  { &NotoSans_Bold63pt7b, 63, "NotoSans_Bold63pt7b" },
  { &NotoSans_Bold64pt7b, 64, "NotoSans_Bold64pt7b" },
  { &NotoSans_Bold65pt7b, 65, "NotoSans_Bold65pt7b" },
  { &NotoSans_Bold66pt7b, 66, "NotoSans_Bold66pt7b" },
  { &NotoSans_Bold67pt7b, 67, "NotoSans_Bold67pt7b" },
  { &NotoSans_Bold68pt7b, 68, "NotoSans_Bold68pt7b" },
  { &NotoSans_Bold69pt7b, 69, "NotoSans_Bold69pt7b" },
  { &NotoSans_Bold70pt7b, 70, "NotoSans_Bold70pt7b" },
  { &NotoSans_Bold71pt7b, 71, "NotoSans_Bold71pt7b" },
  { &NotoSans_Bold72pt7b, 72, "NotoSans_Bold72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
