#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &JetBrainsMono_Italic6pt7b, 6, "JetBrainsMono_Italic6pt7b" },
  { &JetBrainsMono_Italic7pt7b, 7, "JetBrainsMono_Italic7pt7b" },
  { &JetBrainsMono_Italic8pt7b, 8, "JetBrainsMono_Italic8pt7b" },
  { &JetBrainsMono_Italic9pt7b, 9, "JetBrainsMono_Italic9pt7b" },
  { &JetBrainsMono_Italic10pt7b, 10, "JetBrainsMono_Italic10pt7b" },
  { &JetBrainsMono_Italic11pt7b, 11, "JetBrainsMono_Italic11pt7b" },
  { &JetBrainsMono_Italic12pt7b, 12, "JetBrainsMono_Italic12pt7b" },
  { &JetBrainsMono_Italic13pt7b, 13, "JetBrainsMono_Italic13pt7b" },
  { &JetBrainsMono_Italic14pt7b, 14, "JetBrainsMono_Italic14pt7b" },
  { &JetBrainsMono_Italic15pt7b, 15, "JetBrainsMono_Italic15pt7b" },
  { &JetBrainsMono_Italic16pt7b, 16, "JetBrainsMono_Italic16pt7b" },
  { &JetBrainsMono_Italic17pt7b, 17, "JetBrainsMono_Italic17pt7b" },
  { &JetBrainsMono_Italic18pt7b, 18, "JetBrainsMono_Italic18pt7b" },
  { &JetBrainsMono_Italic19pt7b, 19, "JetBrainsMono_Italic19pt7b" },
  { &JetBrainsMono_Italic20pt7b, 20, "JetBrainsMono_Italic20pt7b" },
  { &JetBrainsMono_Italic21pt7b, 21, "JetBrainsMono_Italic21pt7b" },
  { &JetBrainsMono_Italic22pt7b, 22, "JetBrainsMono_Italic22pt7b" },
  { &JetBrainsMono_Italic23pt7b, 23, "JetBrainsMono_Italic23pt7b" },
  { &JetBrainsMono_Italic24pt7b, 24, "JetBrainsMono_Italic24pt7b" },
  { &JetBrainsMono_Italic25pt7b, 25, "JetBrainsMono_Italic25pt7b" },
  { &JetBrainsMono_Italic26pt7b, 26, "JetBrainsMono_Italic26pt7b" },
  { &JetBrainsMono_Italic27pt7b, 27, "JetBrainsMono_Italic27pt7b" },
  { &JetBrainsMono_Italic28pt7b, 28, "JetBrainsMono_Italic28pt7b" },
  { &JetBrainsMono_Italic29pt7b, 29, "JetBrainsMono_Italic29pt7b" },
  { &JetBrainsMono_Italic30pt7b, 30, "JetBrainsMono_Italic30pt7b" },
  { &JetBrainsMono_Italic31pt7b, 31, "JetBrainsMono_Italic31pt7b" },
  { &JetBrainsMono_Italic32pt7b, 32, "JetBrainsMono_Italic32pt7b" },
  { &JetBrainsMono_Italic33pt7b, 33, "JetBrainsMono_Italic33pt7b" },
  { &JetBrainsMono_Italic34pt7b, 34, "JetBrainsMono_Italic34pt7b" },
  { &JetBrainsMono_Italic35pt7b, 35, "JetBrainsMono_Italic35pt7b" },
  { &JetBrainsMono_Italic36pt7b, 36, "JetBrainsMono_Italic36pt7b" },
  { &JetBrainsMono_Italic37pt7b, 37, "JetBrainsMono_Italic37pt7b" },
  { &JetBrainsMono_Italic38pt7b, 38, "JetBrainsMono_Italic38pt7b" },
  { &JetBrainsMono_Italic39pt7b, 39, "JetBrainsMono_Italic39pt7b" },
  { &JetBrainsMono_Italic40pt7b, 40, "JetBrainsMono_Italic40pt7b" },
  { &JetBrainsMono_Italic41pt7b, 41, "JetBrainsMono_Italic41pt7b" },
  { &JetBrainsMono_Italic42pt7b, 42, "JetBrainsMono_Italic42pt7b" },
  { &JetBrainsMono_Italic43pt7b, 43, "JetBrainsMono_Italic43pt7b" },
  { &JetBrainsMono_Italic44pt7b, 44, "JetBrainsMono_Italic44pt7b" },
  { &JetBrainsMono_Italic45pt7b, 45, "JetBrainsMono_Italic45pt7b" },
  { &JetBrainsMono_Italic46pt7b, 46, "JetBrainsMono_Italic46pt7b" },
  { &JetBrainsMono_Italic47pt7b, 47, "JetBrainsMono_Italic47pt7b" },
  { &JetBrainsMono_Italic48pt7b, 48, "JetBrainsMono_Italic48pt7b" },
  { &JetBrainsMono_Italic49pt7b, 49, "JetBrainsMono_Italic49pt7b" },
  { &JetBrainsMono_Italic50pt7b, 50, "JetBrainsMono_Italic50pt7b" },
  { &JetBrainsMono_Italic51pt7b, 51, "JetBrainsMono_Italic51pt7b" },
  { &JetBrainsMono_Italic52pt7b, 52, "JetBrainsMono_Italic52pt7b" },
  { &JetBrainsMono_Italic53pt7b, 53, "JetBrainsMono_Italic53pt7b" },
  { &JetBrainsMono_Italic54pt7b, 54, "JetBrainsMono_Italic54pt7b" },
  { &JetBrainsMono_Italic55pt7b, 55, "JetBrainsMono_Italic55pt7b" },
  { &JetBrainsMono_Italic56pt7b, 56, "JetBrainsMono_Italic56pt7b" },
  { &JetBrainsMono_Italic57pt7b, 57, "JetBrainsMono_Italic57pt7b" },
  { &JetBrainsMono_Italic58pt7b, 58, "JetBrainsMono_Italic58pt7b" },
  { &JetBrainsMono_Italic59pt7b, 59, "JetBrainsMono_Italic59pt7b" },
  { &JetBrainsMono_Italic60pt7b, 60, "JetBrainsMono_Italic60pt7b" },
  { &JetBrainsMono_Italic61pt7b, 61, "JetBrainsMono_Italic61pt7b" },
  { &JetBrainsMono_Italic62pt7b, 62, "JetBrainsMono_Italic62pt7b" },
  { &JetBrainsMono_Italic63pt7b, 63, "JetBrainsMono_Italic63pt7b" },
  { &JetBrainsMono_Italic64pt7b, 64, "JetBrainsMono_Italic64pt7b" },
  { &JetBrainsMono_Italic65pt7b, 65, "JetBrainsMono_Italic65pt7b" },
  { &JetBrainsMono_Italic66pt7b, 66, "JetBrainsMono_Italic66pt7b" },
  { &JetBrainsMono_Italic67pt7b, 67, "JetBrainsMono_Italic67pt7b" },
  { &JetBrainsMono_Italic68pt7b, 68, "JetBrainsMono_Italic68pt7b" },
  { &JetBrainsMono_Italic69pt7b, 69, "JetBrainsMono_Italic69pt7b" },
  { &JetBrainsMono_Italic70pt7b, 70, "JetBrainsMono_Italic70pt7b" },
  { &JetBrainsMono_Italic71pt7b, 71, "JetBrainsMono_Italic71pt7b" },
  { &JetBrainsMono_Italic72pt7b, 72, "JetBrainsMono_Italic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
