#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &RobotoCondensed_Black6pt7b, 6, "RobotoCondensed_Black6pt7b" },
  { &RobotoCondensed_Black7pt7b, 7, "RobotoCondensed_Black7pt7b" },
  { &RobotoCondensed_Black8pt7b, 8, "RobotoCondensed_Black8pt7b" },
  { &RobotoCondensed_Black9pt7b, 9, "RobotoCondensed_Black9pt7b" },
  { &RobotoCondensed_Black10pt7b, 10, "RobotoCondensed_Black10pt7b" },
  { &RobotoCondensed_Black11pt7b, 11, "RobotoCondensed_Black11pt7b" },
  { &RobotoCondensed_Black12pt7b, 12, "RobotoCondensed_Black12pt7b" },
  { &RobotoCondensed_Black13pt7b, 13, "RobotoCondensed_Black13pt7b" },
  { &RobotoCondensed_Black14pt7b, 14, "RobotoCondensed_Black14pt7b" },
  { &RobotoCondensed_Black15pt7b, 15, "RobotoCondensed_Black15pt7b" },
  { &RobotoCondensed_Black16pt7b, 16, "RobotoCondensed_Black16pt7b" },
  { &RobotoCondensed_Black17pt7b, 17, "RobotoCondensed_Black17pt7b" },
  { &RobotoCondensed_Black18pt7b, 18, "RobotoCondensed_Black18pt7b" },
  { &RobotoCondensed_Black19pt7b, 19, "RobotoCondensed_Black19pt7b" },
  { &RobotoCondensed_Black20pt7b, 20, "RobotoCondensed_Black20pt7b" },
  { &RobotoCondensed_Black21pt7b, 21, "RobotoCondensed_Black21pt7b" },
  { &RobotoCondensed_Black22pt7b, 22, "RobotoCondensed_Black22pt7b" },
  { &RobotoCondensed_Black23pt7b, 23, "RobotoCondensed_Black23pt7b" },
  { &RobotoCondensed_Black24pt7b, 24, "RobotoCondensed_Black24pt7b" },
  { &RobotoCondensed_Black25pt7b, 25, "RobotoCondensed_Black25pt7b" },
  { &RobotoCondensed_Black26pt7b, 26, "RobotoCondensed_Black26pt7b" },
  { &RobotoCondensed_Black27pt7b, 27, "RobotoCondensed_Black27pt7b" },
  { &RobotoCondensed_Black28pt7b, 28, "RobotoCondensed_Black28pt7b" },
  { &RobotoCondensed_Black29pt7b, 29, "RobotoCondensed_Black29pt7b" },
  { &RobotoCondensed_Black30pt7b, 30, "RobotoCondensed_Black30pt7b" },
  { &RobotoCondensed_Black31pt7b, 31, "RobotoCondensed_Black31pt7b" },
  { &RobotoCondensed_Black32pt7b, 32, "RobotoCondensed_Black32pt7b" },
  { &RobotoCondensed_Black33pt7b, 33, "RobotoCondensed_Black33pt7b" },
  { &RobotoCondensed_Black34pt7b, 34, "RobotoCondensed_Black34pt7b" },
  { &RobotoCondensed_Black35pt7b, 35, "RobotoCondensed_Black35pt7b" },
  { &RobotoCondensed_Black36pt7b, 36, "RobotoCondensed_Black36pt7b" },
  { &RobotoCondensed_Black37pt7b, 37, "RobotoCondensed_Black37pt7b" },
  { &RobotoCondensed_Black38pt7b, 38, "RobotoCondensed_Black38pt7b" },
  { &RobotoCondensed_Black39pt7b, 39, "RobotoCondensed_Black39pt7b" },
  { &RobotoCondensed_Black40pt7b, 40, "RobotoCondensed_Black40pt7b" },
  { &RobotoCondensed_Black41pt7b, 41, "RobotoCondensed_Black41pt7b" },
  { &RobotoCondensed_Black42pt7b, 42, "RobotoCondensed_Black42pt7b" },
  { &RobotoCondensed_Black43pt7b, 43, "RobotoCondensed_Black43pt7b" },
  { &RobotoCondensed_Black44pt7b, 44, "RobotoCondensed_Black44pt7b" },
  { &RobotoCondensed_Black45pt7b, 45, "RobotoCondensed_Black45pt7b" },
  { &RobotoCondensed_Black46pt7b, 46, "RobotoCondensed_Black46pt7b" },
  { &RobotoCondensed_Black47pt7b, 47, "RobotoCondensed_Black47pt7b" },
  { &RobotoCondensed_Black48pt7b, 48, "RobotoCondensed_Black48pt7b" },
  { &RobotoCondensed_Black49pt7b, 49, "RobotoCondensed_Black49pt7b" },
  { &RobotoCondensed_Black50pt7b, 50, "RobotoCondensed_Black50pt7b" },
  { &RobotoCondensed_Black51pt7b, 51, "RobotoCondensed_Black51pt7b" },
  { &RobotoCondensed_Black52pt7b, 52, "RobotoCondensed_Black52pt7b" },
  { &RobotoCondensed_Black53pt7b, 53, "RobotoCondensed_Black53pt7b" },
  { &RobotoCondensed_Black54pt7b, 54, "RobotoCondensed_Black54pt7b" },
  { &RobotoCondensed_Black55pt7b, 55, "RobotoCondensed_Black55pt7b" },
  { &RobotoCondensed_Black56pt7b, 56, "RobotoCondensed_Black56pt7b" },
  { &RobotoCondensed_Black57pt7b, 57, "RobotoCondensed_Black57pt7b" },
  { &RobotoCondensed_Black58pt7b, 58, "RobotoCondensed_Black58pt7b" },
  { &RobotoCondensed_Black59pt7b, 59, "RobotoCondensed_Black59pt7b" },
  { &RobotoCondensed_Black60pt7b, 60, "RobotoCondensed_Black60pt7b" },
  { &RobotoCondensed_Black61pt7b, 61, "RobotoCondensed_Black61pt7b" },
  { &RobotoCondensed_Black62pt7b, 62, "RobotoCondensed_Black62pt7b" },
  { &RobotoCondensed_Black63pt7b, 63, "RobotoCondensed_Black63pt7b" },
  { &RobotoCondensed_Black64pt7b, 64, "RobotoCondensed_Black64pt7b" },
  { &RobotoCondensed_Black65pt7b, 65, "RobotoCondensed_Black65pt7b" },
  { &RobotoCondensed_Black66pt7b, 66, "RobotoCondensed_Black66pt7b" },
  { &RobotoCondensed_Black67pt7b, 67, "RobotoCondensed_Black67pt7b" },
  { &RobotoCondensed_Black68pt7b, 68, "RobotoCondensed_Black68pt7b" },
  { &RobotoCondensed_Black69pt7b, 69, "RobotoCondensed_Black69pt7b" },
  { &RobotoCondensed_Black70pt7b, 70, "RobotoCondensed_Black70pt7b" },
  { &RobotoCondensed_Black71pt7b, 71, "RobotoCondensed_Black71pt7b" },
  { &RobotoCondensed_Black72pt7b, 72, "RobotoCondensed_Black72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
