#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &UbuntuMono_Italic6pt7b, 6, "UbuntuMono_Italic6pt7b" },
  { &UbuntuMono_Italic7pt7b, 7, "UbuntuMono_Italic7pt7b" },
  { &UbuntuMono_Italic8pt7b, 8, "UbuntuMono_Italic8pt7b" },
  { &UbuntuMono_Italic9pt7b, 9, "UbuntuMono_Italic9pt7b" },
  { &UbuntuMono_Italic10pt7b, 10, "UbuntuMono_Italic10pt7b" },
  { &UbuntuMono_Italic11pt7b, 11, "UbuntuMono_Italic11pt7b" },
  { &UbuntuMono_Italic12pt7b, 12, "UbuntuMono_Italic12pt7b" },
  { &UbuntuMono_Italic13pt7b, 13, "UbuntuMono_Italic13pt7b" },
  { &UbuntuMono_Italic14pt7b, 14, "UbuntuMono_Italic14pt7b" },
  { &UbuntuMono_Italic15pt7b, 15, "UbuntuMono_Italic15pt7b" },
  { &UbuntuMono_Italic16pt7b, 16, "UbuntuMono_Italic16pt7b" },
  { &UbuntuMono_Italic17pt7b, 17, "UbuntuMono_Italic17pt7b" },
  { &UbuntuMono_Italic18pt7b, 18, "UbuntuMono_Italic18pt7b" },
  { &UbuntuMono_Italic19pt7b, 19, "UbuntuMono_Italic19pt7b" },
  { &UbuntuMono_Italic20pt7b, 20, "UbuntuMono_Italic20pt7b" },
  { &UbuntuMono_Italic21pt7b, 21, "UbuntuMono_Italic21pt7b" },
  { &UbuntuMono_Italic22pt7b, 22, "UbuntuMono_Italic22pt7b" },
  { &UbuntuMono_Italic23pt7b, 23, "UbuntuMono_Italic23pt7b" },
  { &UbuntuMono_Italic24pt7b, 24, "UbuntuMono_Italic24pt7b" },
  { &UbuntuMono_Italic25pt7b, 25, "UbuntuMono_Italic25pt7b" },
  { &UbuntuMono_Italic26pt7b, 26, "UbuntuMono_Italic26pt7b" },
  { &UbuntuMono_Italic27pt7b, 27, "UbuntuMono_Italic27pt7b" },
  { &UbuntuMono_Italic28pt7b, 28, "UbuntuMono_Italic28pt7b" },
  { &UbuntuMono_Italic29pt7b, 29, "UbuntuMono_Italic29pt7b" },
  { &UbuntuMono_Italic30pt7b, 30, "UbuntuMono_Italic30pt7b" },
  { &UbuntuMono_Italic31pt7b, 31, "UbuntuMono_Italic31pt7b" },
  { &UbuntuMono_Italic32pt7b, 32, "UbuntuMono_Italic32pt7b" },
  { &UbuntuMono_Italic33pt7b, 33, "UbuntuMono_Italic33pt7b" },
  { &UbuntuMono_Italic34pt7b, 34, "UbuntuMono_Italic34pt7b" },
  { &UbuntuMono_Italic35pt7b, 35, "UbuntuMono_Italic35pt7b" },
  { &UbuntuMono_Italic36pt7b, 36, "UbuntuMono_Italic36pt7b" },
  { &UbuntuMono_Italic37pt7b, 37, "UbuntuMono_Italic37pt7b" },
  { &UbuntuMono_Italic38pt7b, 38, "UbuntuMono_Italic38pt7b" },
  { &UbuntuMono_Italic39pt7b, 39, "UbuntuMono_Italic39pt7b" },
  { &UbuntuMono_Italic40pt7b, 40, "UbuntuMono_Italic40pt7b" },
  { &UbuntuMono_Italic41pt7b, 41, "UbuntuMono_Italic41pt7b" },
  { &UbuntuMono_Italic42pt7b, 42, "UbuntuMono_Italic42pt7b" },
  { &UbuntuMono_Italic43pt7b, 43, "UbuntuMono_Italic43pt7b" },
  { &UbuntuMono_Italic44pt7b, 44, "UbuntuMono_Italic44pt7b" },
  { &UbuntuMono_Italic45pt7b, 45, "UbuntuMono_Italic45pt7b" },
  { &UbuntuMono_Italic46pt7b, 46, "UbuntuMono_Italic46pt7b" },
  { &UbuntuMono_Italic47pt7b, 47, "UbuntuMono_Italic47pt7b" },
  { &UbuntuMono_Italic48pt7b, 48, "UbuntuMono_Italic48pt7b" },
  { &UbuntuMono_Italic49pt7b, 49, "UbuntuMono_Italic49pt7b" },
  { &UbuntuMono_Italic50pt7b, 50, "UbuntuMono_Italic50pt7b" },
  { &UbuntuMono_Italic51pt7b, 51, "UbuntuMono_Italic51pt7b" },
  { &UbuntuMono_Italic52pt7b, 52, "UbuntuMono_Italic52pt7b" },
  { &UbuntuMono_Italic53pt7b, 53, "UbuntuMono_Italic53pt7b" },
  { &UbuntuMono_Italic54pt7b, 54, "UbuntuMono_Italic54pt7b" },
  { &UbuntuMono_Italic55pt7b, 55, "UbuntuMono_Italic55pt7b" },
  { &UbuntuMono_Italic56pt7b, 56, "UbuntuMono_Italic56pt7b" },
  { &UbuntuMono_Italic57pt7b, 57, "UbuntuMono_Italic57pt7b" },
  { &UbuntuMono_Italic58pt7b, 58, "UbuntuMono_Italic58pt7b" },
  { &UbuntuMono_Italic59pt7b, 59, "UbuntuMono_Italic59pt7b" },
  { &UbuntuMono_Italic60pt7b, 60, "UbuntuMono_Italic60pt7b" },
  { &UbuntuMono_Italic61pt7b, 61, "UbuntuMono_Italic61pt7b" },
  { &UbuntuMono_Italic62pt7b, 62, "UbuntuMono_Italic62pt7b" },
  { &UbuntuMono_Italic63pt7b, 63, "UbuntuMono_Italic63pt7b" },
  { &UbuntuMono_Italic64pt7b, 64, "UbuntuMono_Italic64pt7b" },
  { &UbuntuMono_Italic65pt7b, 65, "UbuntuMono_Italic65pt7b" },
  { &UbuntuMono_Italic66pt7b, 66, "UbuntuMono_Italic66pt7b" },
  { &UbuntuMono_Italic67pt7b, 67, "UbuntuMono_Italic67pt7b" },
  { &UbuntuMono_Italic68pt7b, 68, "UbuntuMono_Italic68pt7b" },
  { &UbuntuMono_Italic69pt7b, 69, "UbuntuMono_Italic69pt7b" },
  { &UbuntuMono_Italic70pt7b, 70, "UbuntuMono_Italic70pt7b" },
  { &UbuntuMono_Italic71pt7b, 71, "UbuntuMono_Italic71pt7b" },
  { &UbuntuMono_Italic72pt7b, 72, "UbuntuMono_Italic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
