#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &RobotoMono_Bold6pt7b, 6, "RobotoMono_Bold6pt7b" },
  { &RobotoMono_Bold7pt7b, 7, "RobotoMono_Bold7pt7b" },
  { &RobotoMono_Bold8pt7b, 8, "RobotoMono_Bold8pt7b" },
  { &RobotoMono_Bold9pt7b, 9, "RobotoMono_Bold9pt7b" },
  { &RobotoMono_Bold10pt7b, 10, "RobotoMono_Bold10pt7b" },
  { &RobotoMono_Bold11pt7b, 11, "RobotoMono_Bold11pt7b" },
  { &RobotoMono_Bold12pt7b, 12, "RobotoMono_Bold12pt7b" },
  { &RobotoMono_Bold13pt7b, 13, "RobotoMono_Bold13pt7b" },
  { &RobotoMono_Bold14pt7b, 14, "RobotoMono_Bold14pt7b" },
  { &RobotoMono_Bold15pt7b, 15, "RobotoMono_Bold15pt7b" },
  { &RobotoMono_Bold16pt7b, 16, "RobotoMono_Bold16pt7b" },
  { &RobotoMono_Bold17pt7b, 17, "RobotoMono_Bold17pt7b" },
  { &RobotoMono_Bold18pt7b, 18, "RobotoMono_Bold18pt7b" },
  { &RobotoMono_Bold19pt7b, 19, "RobotoMono_Bold19pt7b" },
  { &RobotoMono_Bold20pt7b, 20, "RobotoMono_Bold20pt7b" },
  { &RobotoMono_Bold21pt7b, 21, "RobotoMono_Bold21pt7b" },
  { &RobotoMono_Bold22pt7b, 22, "RobotoMono_Bold22pt7b" },
  { &RobotoMono_Bold23pt7b, 23, "RobotoMono_Bold23pt7b" },
  { &RobotoMono_Bold24pt7b, 24, "RobotoMono_Bold24pt7b" },
  { &RobotoMono_Bold25pt7b, 25, "RobotoMono_Bold25pt7b" },
  { &RobotoMono_Bold26pt7b, 26, "RobotoMono_Bold26pt7b" },
  { &RobotoMono_Bold27pt7b, 27, "RobotoMono_Bold27pt7b" },
  { &RobotoMono_Bold28pt7b, 28, "RobotoMono_Bold28pt7b" },
  { &RobotoMono_Bold29pt7b, 29, "RobotoMono_Bold29pt7b" },
  { &RobotoMono_Bold30pt7b, 30, "RobotoMono_Bold30pt7b" },
  { &RobotoMono_Bold31pt7b, 31, "RobotoMono_Bold31pt7b" },
  { &RobotoMono_Bold32pt7b, 32, "RobotoMono_Bold32pt7b" },
  { &RobotoMono_Bold33pt7b, 33, "RobotoMono_Bold33pt7b" },
  { &RobotoMono_Bold34pt7b, 34, "RobotoMono_Bold34pt7b" },
  { &RobotoMono_Bold35pt7b, 35, "RobotoMono_Bold35pt7b" },
  { &RobotoMono_Bold36pt7b, 36, "RobotoMono_Bold36pt7b" },
  { &RobotoMono_Bold37pt7b, 37, "RobotoMono_Bold37pt7b" },
  { &RobotoMono_Bold38pt7b, 38, "RobotoMono_Bold38pt7b" },
  { &RobotoMono_Bold39pt7b, 39, "RobotoMono_Bold39pt7b" },
  { &RobotoMono_Bold40pt7b, 40, "RobotoMono_Bold40pt7b" },
  { &RobotoMono_Bold41pt7b, 41, "RobotoMono_Bold41pt7b" },
  { &RobotoMono_Bold42pt7b, 42, "RobotoMono_Bold42pt7b" },
  { &RobotoMono_Bold43pt7b, 43, "RobotoMono_Bold43pt7b" },
  { &RobotoMono_Bold44pt7b, 44, "RobotoMono_Bold44pt7b" },
  { &RobotoMono_Bold45pt7b, 45, "RobotoMono_Bold45pt7b" },
  { &RobotoMono_Bold46pt7b, 46, "RobotoMono_Bold46pt7b" },
  { &RobotoMono_Bold47pt7b, 47, "RobotoMono_Bold47pt7b" },
  { &RobotoMono_Bold48pt7b, 48, "RobotoMono_Bold48pt7b" },
  { &RobotoMono_Bold49pt7b, 49, "RobotoMono_Bold49pt7b" },
  { &RobotoMono_Bold50pt7b, 50, "RobotoMono_Bold50pt7b" },
  { &RobotoMono_Bold51pt7b, 51, "RobotoMono_Bold51pt7b" },
  { &RobotoMono_Bold52pt7b, 52, "RobotoMono_Bold52pt7b" },
  { &RobotoMono_Bold53pt7b, 53, "RobotoMono_Bold53pt7b" },
  { &RobotoMono_Bold54pt7b, 54, "RobotoMono_Bold54pt7b" },
  { &RobotoMono_Bold55pt7b, 55, "RobotoMono_Bold55pt7b" },
  { &RobotoMono_Bold56pt7b, 56, "RobotoMono_Bold56pt7b" },
  { &RobotoMono_Bold57pt7b, 57, "RobotoMono_Bold57pt7b" },
  { &RobotoMono_Bold58pt7b, 58, "RobotoMono_Bold58pt7b" },
  { &RobotoMono_Bold59pt7b, 59, "RobotoMono_Bold59pt7b" },
  { &RobotoMono_Bold60pt7b, 60, "RobotoMono_Bold60pt7b" },
  { &RobotoMono_Bold61pt7b, 61, "RobotoMono_Bold61pt7b" },
  { &RobotoMono_Bold62pt7b, 62, "RobotoMono_Bold62pt7b" },
  { &RobotoMono_Bold63pt7b, 63, "RobotoMono_Bold63pt7b" },
  { &RobotoMono_Bold64pt7b, 64, "RobotoMono_Bold64pt7b" },
  { &RobotoMono_Bold65pt7b, 65, "RobotoMono_Bold65pt7b" },
  { &RobotoMono_Bold66pt7b, 66, "RobotoMono_Bold66pt7b" },
  { &RobotoMono_Bold67pt7b, 67, "RobotoMono_Bold67pt7b" },
  { &RobotoMono_Bold68pt7b, 68, "RobotoMono_Bold68pt7b" },
  { &RobotoMono_Bold69pt7b, 69, "RobotoMono_Bold69pt7b" },
  { &RobotoMono_Bold70pt7b, 70, "RobotoMono_Bold70pt7b" },
  { &RobotoMono_Bold71pt7b, 71, "RobotoMono_Bold71pt7b" },
  { &RobotoMono_Bold72pt7b, 72, "RobotoMono_Bold72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
