#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_Condensed_Regular6pt7b, 6, "NotoSans_Condensed_Regular6pt7b" },
  { &NotoSans_Condensed_Regular7pt7b, 7, "NotoSans_Condensed_Regular7pt7b" },
  { &NotoSans_Condensed_Regular8pt7b, 8, "NotoSans_Condensed_Regular8pt7b" },
  { &NotoSans_Condensed_Regular9pt7b, 9, "NotoSans_Condensed_Regular9pt7b" },
  { &NotoSans_Condensed_Regular10pt7b, 10, "NotoSans_Condensed_Regular10pt7b" },
  { &NotoSans_Condensed_Regular11pt7b, 11, "NotoSans_Condensed_Regular11pt7b" },
  { &NotoSans_Condensed_Regular12pt7b, 12, "NotoSans_Condensed_Regular12pt7b" },
  { &NotoSans_Condensed_Regular13pt7b, 13, "NotoSans_Condensed_Regular13pt7b" },
  { &NotoSans_Condensed_Regular14pt7b, 14, "NotoSans_Condensed_Regular14pt7b" },
  { &NotoSans_Condensed_Regular15pt7b, 15, "NotoSans_Condensed_Regular15pt7b" },
  { &NotoSans_Condensed_Regular16pt7b, 16, "NotoSans_Condensed_Regular16pt7b" },
  { &NotoSans_Condensed_Regular17pt7b, 17, "NotoSans_Condensed_Regular17pt7b" },
  { &NotoSans_Condensed_Regular18pt7b, 18, "NotoSans_Condensed_Regular18pt7b" },
  { &NotoSans_Condensed_Regular19pt7b, 19, "NotoSans_Condensed_Regular19pt7b" },
  { &NotoSans_Condensed_Regular20pt7b, 20, "NotoSans_Condensed_Regular20pt7b" },
  { &NotoSans_Condensed_Regular21pt7b, 21, "NotoSans_Condensed_Regular21pt7b" },
  { &NotoSans_Condensed_Regular22pt7b, 22, "NotoSans_Condensed_Regular22pt7b" },
  { &NotoSans_Condensed_Regular23pt7b, 23, "NotoSans_Condensed_Regular23pt7b" },
  { &NotoSans_Condensed_Regular24pt7b, 24, "NotoSans_Condensed_Regular24pt7b" },
  { &NotoSans_Condensed_Regular25pt7b, 25, "NotoSans_Condensed_Regular25pt7b" },
  { &NotoSans_Condensed_Regular26pt7b, 26, "NotoSans_Condensed_Regular26pt7b" },
  { &NotoSans_Condensed_Regular27pt7b, 27, "NotoSans_Condensed_Regular27pt7b" },
  { &NotoSans_Condensed_Regular28pt7b, 28, "NotoSans_Condensed_Regular28pt7b" },
  { &NotoSans_Condensed_Regular29pt7b, 29, "NotoSans_Condensed_Regular29pt7b" },
  { &NotoSans_Condensed_Regular30pt7b, 30, "NotoSans_Condensed_Regular30pt7b" },
  { &NotoSans_Condensed_Regular31pt7b, 31, "NotoSans_Condensed_Regular31pt7b" },
  { &NotoSans_Condensed_Regular32pt7b, 32, "NotoSans_Condensed_Regular32pt7b" },
  { &NotoSans_Condensed_Regular33pt7b, 33, "NotoSans_Condensed_Regular33pt7b" },
  { &NotoSans_Condensed_Regular34pt7b, 34, "NotoSans_Condensed_Regular34pt7b" },
  { &NotoSans_Condensed_Regular35pt7b, 35, "NotoSans_Condensed_Regular35pt7b" },
  { &NotoSans_Condensed_Regular36pt7b, 36, "NotoSans_Condensed_Regular36pt7b" },
  { &NotoSans_Condensed_Regular37pt7b, 37, "NotoSans_Condensed_Regular37pt7b" },
  { &NotoSans_Condensed_Regular38pt7b, 38, "NotoSans_Condensed_Regular38pt7b" },
  { &NotoSans_Condensed_Regular39pt7b, 39, "NotoSans_Condensed_Regular39pt7b" },
  { &NotoSans_Condensed_Regular40pt7b, 40, "NotoSans_Condensed_Regular40pt7b" },
  { &NotoSans_Condensed_Regular41pt7b, 41, "NotoSans_Condensed_Regular41pt7b" },
  { &NotoSans_Condensed_Regular42pt7b, 42, "NotoSans_Condensed_Regular42pt7b" },
  { &NotoSans_Condensed_Regular43pt7b, 43, "NotoSans_Condensed_Regular43pt7b" },
  { &NotoSans_Condensed_Regular44pt7b, 44, "NotoSans_Condensed_Regular44pt7b" },
  { &NotoSans_Condensed_Regular45pt7b, 45, "NotoSans_Condensed_Regular45pt7b" },
  { &NotoSans_Condensed_Regular46pt7b, 46, "NotoSans_Condensed_Regular46pt7b" },
  { &NotoSans_Condensed_Regular47pt7b, 47, "NotoSans_Condensed_Regular47pt7b" },
  { &NotoSans_Condensed_Regular48pt7b, 48, "NotoSans_Condensed_Regular48pt7b" },
  { &NotoSans_Condensed_Regular49pt7b, 49, "NotoSans_Condensed_Regular49pt7b" },
  { &NotoSans_Condensed_Regular50pt7b, 50, "NotoSans_Condensed_Regular50pt7b" },
  { &NotoSans_Condensed_Regular51pt7b, 51, "NotoSans_Condensed_Regular51pt7b" },
  { &NotoSans_Condensed_Regular52pt7b, 52, "NotoSans_Condensed_Regular52pt7b" },
  { &NotoSans_Condensed_Regular53pt7b, 53, "NotoSans_Condensed_Regular53pt7b" },
  { &NotoSans_Condensed_Regular54pt7b, 54, "NotoSans_Condensed_Regular54pt7b" },
  { &NotoSans_Condensed_Regular55pt7b, 55, "NotoSans_Condensed_Regular55pt7b" },
  { &NotoSans_Condensed_Regular56pt7b, 56, "NotoSans_Condensed_Regular56pt7b" },
  { &NotoSans_Condensed_Regular57pt7b, 57, "NotoSans_Condensed_Regular57pt7b" },
  { &NotoSans_Condensed_Regular58pt7b, 58, "NotoSans_Condensed_Regular58pt7b" },
  { &NotoSans_Condensed_Regular59pt7b, 59, "NotoSans_Condensed_Regular59pt7b" },
  { &NotoSans_Condensed_Regular60pt7b, 60, "NotoSans_Condensed_Regular60pt7b" },
  { &NotoSans_Condensed_Regular61pt7b, 61, "NotoSans_Condensed_Regular61pt7b" },
  { &NotoSans_Condensed_Regular62pt7b, 62, "NotoSans_Condensed_Regular62pt7b" },
  { &NotoSans_Condensed_Regular63pt7b, 63, "NotoSans_Condensed_Regular63pt7b" },
  { &NotoSans_Condensed_Regular64pt7b, 64, "NotoSans_Condensed_Regular64pt7b" },
  { &NotoSans_Condensed_Regular65pt7b, 65, "NotoSans_Condensed_Regular65pt7b" },
  { &NotoSans_Condensed_Regular66pt7b, 66, "NotoSans_Condensed_Regular66pt7b" },
  { &NotoSans_Condensed_Regular67pt7b, 67, "NotoSans_Condensed_Regular67pt7b" },
  { &NotoSans_Condensed_Regular68pt7b, 68, "NotoSans_Condensed_Regular68pt7b" },
  { &NotoSans_Condensed_Regular69pt7b, 69, "NotoSans_Condensed_Regular69pt7b" },
  { &NotoSans_Condensed_Regular70pt7b, 70, "NotoSans_Condensed_Regular70pt7b" },
  { &NotoSans_Condensed_Regular71pt7b, 71, "NotoSans_Condensed_Regular71pt7b" },
  { &NotoSans_Condensed_Regular72pt7b, 72, "NotoSans_Condensed_Regular72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
