#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &UbuntuSansMono_MediumItalic6pt7b, 6, "UbuntuSansMono_MediumItalic6pt7b" },
  { &UbuntuSansMono_MediumItalic7pt7b, 7, "UbuntuSansMono_MediumItalic7pt7b" },
  { &UbuntuSansMono_MediumItalic8pt7b, 8, "UbuntuSansMono_MediumItalic8pt7b" },
  { &UbuntuSansMono_MediumItalic9pt7b, 9, "UbuntuSansMono_MediumItalic9pt7b" },
  { &UbuntuSansMono_MediumItalic10pt7b, 10, "UbuntuSansMono_MediumItalic10pt7b" },
  { &UbuntuSansMono_MediumItalic11pt7b, 11, "UbuntuSansMono_MediumItalic11pt7b" },
  { &UbuntuSansMono_MediumItalic12pt7b, 12, "UbuntuSansMono_MediumItalic12pt7b" },
  { &UbuntuSansMono_MediumItalic13pt7b, 13, "UbuntuSansMono_MediumItalic13pt7b" },
  { &UbuntuSansMono_MediumItalic14pt7b, 14, "UbuntuSansMono_MediumItalic14pt7b" },
  { &UbuntuSansMono_MediumItalic15pt7b, 15, "UbuntuSansMono_MediumItalic15pt7b" },
  { &UbuntuSansMono_MediumItalic16pt7b, 16, "UbuntuSansMono_MediumItalic16pt7b" },
  { &UbuntuSansMono_MediumItalic17pt7b, 17, "UbuntuSansMono_MediumItalic17pt7b" },
  { &UbuntuSansMono_MediumItalic18pt7b, 18, "UbuntuSansMono_MediumItalic18pt7b" },
  { &UbuntuSansMono_MediumItalic19pt7b, 19, "UbuntuSansMono_MediumItalic19pt7b" },
  { &UbuntuSansMono_MediumItalic20pt7b, 20, "UbuntuSansMono_MediumItalic20pt7b" },
  { &UbuntuSansMono_MediumItalic21pt7b, 21, "UbuntuSansMono_MediumItalic21pt7b" },
  { &UbuntuSansMono_MediumItalic22pt7b, 22, "UbuntuSansMono_MediumItalic22pt7b" },
  { &UbuntuSansMono_MediumItalic23pt7b, 23, "UbuntuSansMono_MediumItalic23pt7b" },
  { &UbuntuSansMono_MediumItalic24pt7b, 24, "UbuntuSansMono_MediumItalic24pt7b" },
  { &UbuntuSansMono_MediumItalic25pt7b, 25, "UbuntuSansMono_MediumItalic25pt7b" },
  { &UbuntuSansMono_MediumItalic26pt7b, 26, "UbuntuSansMono_MediumItalic26pt7b" },
  { &UbuntuSansMono_MediumItalic27pt7b, 27, "UbuntuSansMono_MediumItalic27pt7b" },
  { &UbuntuSansMono_MediumItalic28pt7b, 28, "UbuntuSansMono_MediumItalic28pt7b" },
  { &UbuntuSansMono_MediumItalic29pt7b, 29, "UbuntuSansMono_MediumItalic29pt7b" },
  { &UbuntuSansMono_MediumItalic30pt7b, 30, "UbuntuSansMono_MediumItalic30pt7b" },
  { &UbuntuSansMono_MediumItalic31pt7b, 31, "UbuntuSansMono_MediumItalic31pt7b" },
  { &UbuntuSansMono_MediumItalic32pt7b, 32, "UbuntuSansMono_MediumItalic32pt7b" },
  { &UbuntuSansMono_MediumItalic33pt7b, 33, "UbuntuSansMono_MediumItalic33pt7b" },
  { &UbuntuSansMono_MediumItalic34pt7b, 34, "UbuntuSansMono_MediumItalic34pt7b" },
  { &UbuntuSansMono_MediumItalic35pt7b, 35, "UbuntuSansMono_MediumItalic35pt7b" },
  { &UbuntuSansMono_MediumItalic36pt7b, 36, "UbuntuSansMono_MediumItalic36pt7b" },
  { &UbuntuSansMono_MediumItalic37pt7b, 37, "UbuntuSansMono_MediumItalic37pt7b" },
  { &UbuntuSansMono_MediumItalic38pt7b, 38, "UbuntuSansMono_MediumItalic38pt7b" },
  { &UbuntuSansMono_MediumItalic39pt7b, 39, "UbuntuSansMono_MediumItalic39pt7b" },
  { &UbuntuSansMono_MediumItalic40pt7b, 40, "UbuntuSansMono_MediumItalic40pt7b" },
  { &UbuntuSansMono_MediumItalic41pt7b, 41, "UbuntuSansMono_MediumItalic41pt7b" },
  { &UbuntuSansMono_MediumItalic42pt7b, 42, "UbuntuSansMono_MediumItalic42pt7b" },
  { &UbuntuSansMono_MediumItalic43pt7b, 43, "UbuntuSansMono_MediumItalic43pt7b" },
  { &UbuntuSansMono_MediumItalic44pt7b, 44, "UbuntuSansMono_MediumItalic44pt7b" },
  { &UbuntuSansMono_MediumItalic45pt7b, 45, "UbuntuSansMono_MediumItalic45pt7b" },
  { &UbuntuSansMono_MediumItalic46pt7b, 46, "UbuntuSansMono_MediumItalic46pt7b" },
  { &UbuntuSansMono_MediumItalic47pt7b, 47, "UbuntuSansMono_MediumItalic47pt7b" },
  { &UbuntuSansMono_MediumItalic48pt7b, 48, "UbuntuSansMono_MediumItalic48pt7b" },
  { &UbuntuSansMono_MediumItalic49pt7b, 49, "UbuntuSansMono_MediumItalic49pt7b" },
  { &UbuntuSansMono_MediumItalic50pt7b, 50, "UbuntuSansMono_MediumItalic50pt7b" },
  { &UbuntuSansMono_MediumItalic51pt7b, 51, "UbuntuSansMono_MediumItalic51pt7b" },
  { &UbuntuSansMono_MediumItalic52pt7b, 52, "UbuntuSansMono_MediumItalic52pt7b" },
  { &UbuntuSansMono_MediumItalic53pt7b, 53, "UbuntuSansMono_MediumItalic53pt7b" },
  { &UbuntuSansMono_MediumItalic54pt7b, 54, "UbuntuSansMono_MediumItalic54pt7b" },
  { &UbuntuSansMono_MediumItalic55pt7b, 55, "UbuntuSansMono_MediumItalic55pt7b" },
  { &UbuntuSansMono_MediumItalic56pt7b, 56, "UbuntuSansMono_MediumItalic56pt7b" },
  { &UbuntuSansMono_MediumItalic57pt7b, 57, "UbuntuSansMono_MediumItalic57pt7b" },
  { &UbuntuSansMono_MediumItalic58pt7b, 58, "UbuntuSansMono_MediumItalic58pt7b" },
  { &UbuntuSansMono_MediumItalic59pt7b, 59, "UbuntuSansMono_MediumItalic59pt7b" },
  { &UbuntuSansMono_MediumItalic60pt7b, 60, "UbuntuSansMono_MediumItalic60pt7b" },
  { &UbuntuSansMono_MediumItalic61pt7b, 61, "UbuntuSansMono_MediumItalic61pt7b" },
  { &UbuntuSansMono_MediumItalic62pt7b, 62, "UbuntuSansMono_MediumItalic62pt7b" },
  { &UbuntuSansMono_MediumItalic63pt7b, 63, "UbuntuSansMono_MediumItalic63pt7b" },
  { &UbuntuSansMono_MediumItalic64pt7b, 64, "UbuntuSansMono_MediumItalic64pt7b" },
  { &UbuntuSansMono_MediumItalic65pt7b, 65, "UbuntuSansMono_MediumItalic65pt7b" },
  { &UbuntuSansMono_MediumItalic66pt7b, 66, "UbuntuSansMono_MediumItalic66pt7b" },
  { &UbuntuSansMono_MediumItalic67pt7b, 67, "UbuntuSansMono_MediumItalic67pt7b" },
  { &UbuntuSansMono_MediumItalic68pt7b, 68, "UbuntuSansMono_MediumItalic68pt7b" },
  { &UbuntuSansMono_MediumItalic69pt7b, 69, "UbuntuSansMono_MediumItalic69pt7b" },
  { &UbuntuSansMono_MediumItalic70pt7b, 70, "UbuntuSansMono_MediumItalic70pt7b" },
  { &UbuntuSansMono_MediumItalic71pt7b, 71, "UbuntuSansMono_MediumItalic71pt7b" },
  { &UbuntuSansMono_MediumItalic72pt7b, 72, "UbuntuSansMono_MediumItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
