#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &UnifrakturMaguntia_Regular6pt7b, 6, "UnifrakturMaguntia_Regular6pt7b" },
  { &UnifrakturMaguntia_Regular7pt7b, 7, "UnifrakturMaguntia_Regular7pt7b" },
  { &UnifrakturMaguntia_Regular8pt7b, 8, "UnifrakturMaguntia_Regular8pt7b" },
  { &UnifrakturMaguntia_Regular9pt7b, 9, "UnifrakturMaguntia_Regular9pt7b" },
  { &UnifrakturMaguntia_Regular10pt7b, 10, "UnifrakturMaguntia_Regular10pt7b" },
  { &UnifrakturMaguntia_Regular11pt7b, 11, "UnifrakturMaguntia_Regular11pt7b" },
  { &UnifrakturMaguntia_Regular12pt7b, 12, "UnifrakturMaguntia_Regular12pt7b" },
  { &UnifrakturMaguntia_Regular13pt7b, 13, "UnifrakturMaguntia_Regular13pt7b" },
  { &UnifrakturMaguntia_Regular14pt7b, 14, "UnifrakturMaguntia_Regular14pt7b" },
  { &UnifrakturMaguntia_Regular15pt7b, 15, "UnifrakturMaguntia_Regular15pt7b" },
  { &UnifrakturMaguntia_Regular16pt7b, 16, "UnifrakturMaguntia_Regular16pt7b" },
  { &UnifrakturMaguntia_Regular17pt7b, 17, "UnifrakturMaguntia_Regular17pt7b" },
  { &UnifrakturMaguntia_Regular18pt7b, 18, "UnifrakturMaguntia_Regular18pt7b" },
  { &UnifrakturMaguntia_Regular19pt7b, 19, "UnifrakturMaguntia_Regular19pt7b" },
  { &UnifrakturMaguntia_Regular20pt7b, 20, "UnifrakturMaguntia_Regular20pt7b" },
  { &UnifrakturMaguntia_Regular21pt7b, 21, "UnifrakturMaguntia_Regular21pt7b" },
  { &UnifrakturMaguntia_Regular22pt7b, 22, "UnifrakturMaguntia_Regular22pt7b" },
  { &UnifrakturMaguntia_Regular23pt7b, 23, "UnifrakturMaguntia_Regular23pt7b" },
  { &UnifrakturMaguntia_Regular24pt7b, 24, "UnifrakturMaguntia_Regular24pt7b" },
  { &UnifrakturMaguntia_Regular25pt7b, 25, "UnifrakturMaguntia_Regular25pt7b" },
  { &UnifrakturMaguntia_Regular26pt7b, 26, "UnifrakturMaguntia_Regular26pt7b" },
  { &UnifrakturMaguntia_Regular27pt7b, 27, "UnifrakturMaguntia_Regular27pt7b" },
  { &UnifrakturMaguntia_Regular28pt7b, 28, "UnifrakturMaguntia_Regular28pt7b" },
  { &UnifrakturMaguntia_Regular29pt7b, 29, "UnifrakturMaguntia_Regular29pt7b" },
  { &UnifrakturMaguntia_Regular30pt7b, 30, "UnifrakturMaguntia_Regular30pt7b" },
  { &UnifrakturMaguntia_Regular31pt7b, 31, "UnifrakturMaguntia_Regular31pt7b" },
  { &UnifrakturMaguntia_Regular32pt7b, 32, "UnifrakturMaguntia_Regular32pt7b" },
  { &UnifrakturMaguntia_Regular33pt7b, 33, "UnifrakturMaguntia_Regular33pt7b" },
  { &UnifrakturMaguntia_Regular34pt7b, 34, "UnifrakturMaguntia_Regular34pt7b" },
  { &UnifrakturMaguntia_Regular35pt7b, 35, "UnifrakturMaguntia_Regular35pt7b" },
  { &UnifrakturMaguntia_Regular36pt7b, 36, "UnifrakturMaguntia_Regular36pt7b" },
  { &UnifrakturMaguntia_Regular37pt7b, 37, "UnifrakturMaguntia_Regular37pt7b" },
  { &UnifrakturMaguntia_Regular38pt7b, 38, "UnifrakturMaguntia_Regular38pt7b" },
  { &UnifrakturMaguntia_Regular39pt7b, 39, "UnifrakturMaguntia_Regular39pt7b" },
  { &UnifrakturMaguntia_Regular40pt7b, 40, "UnifrakturMaguntia_Regular40pt7b" },
  { &UnifrakturMaguntia_Regular41pt7b, 41, "UnifrakturMaguntia_Regular41pt7b" },
  { &UnifrakturMaguntia_Regular42pt7b, 42, "UnifrakturMaguntia_Regular42pt7b" },
  { &UnifrakturMaguntia_Regular43pt7b, 43, "UnifrakturMaguntia_Regular43pt7b" },
  { &UnifrakturMaguntia_Regular44pt7b, 44, "UnifrakturMaguntia_Regular44pt7b" },
  { &UnifrakturMaguntia_Regular45pt7b, 45, "UnifrakturMaguntia_Regular45pt7b" },
  { &UnifrakturMaguntia_Regular46pt7b, 46, "UnifrakturMaguntia_Regular46pt7b" },
  { &UnifrakturMaguntia_Regular47pt7b, 47, "UnifrakturMaguntia_Regular47pt7b" },
  { &UnifrakturMaguntia_Regular48pt7b, 48, "UnifrakturMaguntia_Regular48pt7b" },
  { &UnifrakturMaguntia_Regular49pt7b, 49, "UnifrakturMaguntia_Regular49pt7b" },
  { &UnifrakturMaguntia_Regular50pt7b, 50, "UnifrakturMaguntia_Regular50pt7b" },
  { &UnifrakturMaguntia_Regular51pt7b, 51, "UnifrakturMaguntia_Regular51pt7b" },
  { &UnifrakturMaguntia_Regular52pt7b, 52, "UnifrakturMaguntia_Regular52pt7b" },
  { &UnifrakturMaguntia_Regular53pt7b, 53, "UnifrakturMaguntia_Regular53pt7b" },
  { &UnifrakturMaguntia_Regular54pt7b, 54, "UnifrakturMaguntia_Regular54pt7b" },
  { &UnifrakturMaguntia_Regular55pt7b, 55, "UnifrakturMaguntia_Regular55pt7b" },
  { &UnifrakturMaguntia_Regular56pt7b, 56, "UnifrakturMaguntia_Regular56pt7b" },
  { &UnifrakturMaguntia_Regular57pt7b, 57, "UnifrakturMaguntia_Regular57pt7b" },
  { &UnifrakturMaguntia_Regular58pt7b, 58, "UnifrakturMaguntia_Regular58pt7b" },
  { &UnifrakturMaguntia_Regular59pt7b, 59, "UnifrakturMaguntia_Regular59pt7b" },
  { &UnifrakturMaguntia_Regular60pt7b, 60, "UnifrakturMaguntia_Regular60pt7b" },
  { &UnifrakturMaguntia_Regular61pt7b, 61, "UnifrakturMaguntia_Regular61pt7b" },
  { &UnifrakturMaguntia_Regular62pt7b, 62, "UnifrakturMaguntia_Regular62pt7b" },
  { &UnifrakturMaguntia_Regular63pt7b, 63, "UnifrakturMaguntia_Regular63pt7b" },
  { &UnifrakturMaguntia_Regular64pt7b, 64, "UnifrakturMaguntia_Regular64pt7b" },
  { &UnifrakturMaguntia_Regular65pt7b, 65, "UnifrakturMaguntia_Regular65pt7b" },
  { &UnifrakturMaguntia_Regular66pt7b, 66, "UnifrakturMaguntia_Regular66pt7b" },
  { &UnifrakturMaguntia_Regular67pt7b, 67, "UnifrakturMaguntia_Regular67pt7b" },
  { &UnifrakturMaguntia_Regular68pt7b, 68, "UnifrakturMaguntia_Regular68pt7b" },
  { &UnifrakturMaguntia_Regular69pt7b, 69, "UnifrakturMaguntia_Regular69pt7b" },
  { &UnifrakturMaguntia_Regular70pt7b, 70, "UnifrakturMaguntia_Regular70pt7b" },
  { &UnifrakturMaguntia_Regular71pt7b, 71, "UnifrakturMaguntia_Regular71pt7b" },
  { &UnifrakturMaguntia_Regular72pt7b, 72, "UnifrakturMaguntia_Regular72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
