#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &JetBrainsMono_BoldItalic6pt7b, 6, "JetBrainsMono_BoldItalic6pt7b" },
  { &JetBrainsMono_BoldItalic7pt7b, 7, "JetBrainsMono_BoldItalic7pt7b" },
  { &JetBrainsMono_BoldItalic8pt7b, 8, "JetBrainsMono_BoldItalic8pt7b" },
  { &JetBrainsMono_BoldItalic9pt7b, 9, "JetBrainsMono_BoldItalic9pt7b" },
  { &JetBrainsMono_BoldItalic10pt7b, 10, "JetBrainsMono_BoldItalic10pt7b" },
  { &JetBrainsMono_BoldItalic11pt7b, 11, "JetBrainsMono_BoldItalic11pt7b" },
  { &JetBrainsMono_BoldItalic12pt7b, 12, "JetBrainsMono_BoldItalic12pt7b" },
  { &JetBrainsMono_BoldItalic13pt7b, 13, "JetBrainsMono_BoldItalic13pt7b" },
  { &JetBrainsMono_BoldItalic14pt7b, 14, "JetBrainsMono_BoldItalic14pt7b" },
  { &JetBrainsMono_BoldItalic15pt7b, 15, "JetBrainsMono_BoldItalic15pt7b" },
  { &JetBrainsMono_BoldItalic16pt7b, 16, "JetBrainsMono_BoldItalic16pt7b" },
  { &JetBrainsMono_BoldItalic17pt7b, 17, "JetBrainsMono_BoldItalic17pt7b" },
  { &JetBrainsMono_BoldItalic18pt7b, 18, "JetBrainsMono_BoldItalic18pt7b" },
  { &JetBrainsMono_BoldItalic19pt7b, 19, "JetBrainsMono_BoldItalic19pt7b" },
  { &JetBrainsMono_BoldItalic20pt7b, 20, "JetBrainsMono_BoldItalic20pt7b" },
  { &JetBrainsMono_BoldItalic21pt7b, 21, "JetBrainsMono_BoldItalic21pt7b" },
  { &JetBrainsMono_BoldItalic22pt7b, 22, "JetBrainsMono_BoldItalic22pt7b" },
  { &JetBrainsMono_BoldItalic23pt7b, 23, "JetBrainsMono_BoldItalic23pt7b" },
  { &JetBrainsMono_BoldItalic24pt7b, 24, "JetBrainsMono_BoldItalic24pt7b" },
  { &JetBrainsMono_BoldItalic25pt7b, 25, "JetBrainsMono_BoldItalic25pt7b" },
  { &JetBrainsMono_BoldItalic26pt7b, 26, "JetBrainsMono_BoldItalic26pt7b" },
  { &JetBrainsMono_BoldItalic27pt7b, 27, "JetBrainsMono_BoldItalic27pt7b" },
  { &JetBrainsMono_BoldItalic28pt7b, 28, "JetBrainsMono_BoldItalic28pt7b" },
  { &JetBrainsMono_BoldItalic29pt7b, 29, "JetBrainsMono_BoldItalic29pt7b" },
  { &JetBrainsMono_BoldItalic30pt7b, 30, "JetBrainsMono_BoldItalic30pt7b" },
  { &JetBrainsMono_BoldItalic31pt7b, 31, "JetBrainsMono_BoldItalic31pt7b" },
  { &JetBrainsMono_BoldItalic32pt7b, 32, "JetBrainsMono_BoldItalic32pt7b" },
  { &JetBrainsMono_BoldItalic33pt7b, 33, "JetBrainsMono_BoldItalic33pt7b" },
  { &JetBrainsMono_BoldItalic34pt7b, 34, "JetBrainsMono_BoldItalic34pt7b" },
  { &JetBrainsMono_BoldItalic35pt7b, 35, "JetBrainsMono_BoldItalic35pt7b" },
  { &JetBrainsMono_BoldItalic36pt7b, 36, "JetBrainsMono_BoldItalic36pt7b" },
  { &JetBrainsMono_BoldItalic37pt7b, 37, "JetBrainsMono_BoldItalic37pt7b" },
  { &JetBrainsMono_BoldItalic38pt7b, 38, "JetBrainsMono_BoldItalic38pt7b" },
  { &JetBrainsMono_BoldItalic39pt7b, 39, "JetBrainsMono_BoldItalic39pt7b" },
  { &JetBrainsMono_BoldItalic40pt7b, 40, "JetBrainsMono_BoldItalic40pt7b" },
  { &JetBrainsMono_BoldItalic41pt7b, 41, "JetBrainsMono_BoldItalic41pt7b" },
  { &JetBrainsMono_BoldItalic42pt7b, 42, "JetBrainsMono_BoldItalic42pt7b" },
  { &JetBrainsMono_BoldItalic43pt7b, 43, "JetBrainsMono_BoldItalic43pt7b" },
  { &JetBrainsMono_BoldItalic44pt7b, 44, "JetBrainsMono_BoldItalic44pt7b" },
  { &JetBrainsMono_BoldItalic45pt7b, 45, "JetBrainsMono_BoldItalic45pt7b" },
  { &JetBrainsMono_BoldItalic46pt7b, 46, "JetBrainsMono_BoldItalic46pt7b" },
  { &JetBrainsMono_BoldItalic47pt7b, 47, "JetBrainsMono_BoldItalic47pt7b" },
  { &JetBrainsMono_BoldItalic48pt7b, 48, "JetBrainsMono_BoldItalic48pt7b" },
  { &JetBrainsMono_BoldItalic49pt7b, 49, "JetBrainsMono_BoldItalic49pt7b" },
  { &JetBrainsMono_BoldItalic50pt7b, 50, "JetBrainsMono_BoldItalic50pt7b" },
  { &JetBrainsMono_BoldItalic51pt7b, 51, "JetBrainsMono_BoldItalic51pt7b" },
  { &JetBrainsMono_BoldItalic52pt7b, 52, "JetBrainsMono_BoldItalic52pt7b" },
  { &JetBrainsMono_BoldItalic53pt7b, 53, "JetBrainsMono_BoldItalic53pt7b" },
  { &JetBrainsMono_BoldItalic54pt7b, 54, "JetBrainsMono_BoldItalic54pt7b" },
  { &JetBrainsMono_BoldItalic55pt7b, 55, "JetBrainsMono_BoldItalic55pt7b" },
  { &JetBrainsMono_BoldItalic56pt7b, 56, "JetBrainsMono_BoldItalic56pt7b" },
  { &JetBrainsMono_BoldItalic57pt7b, 57, "JetBrainsMono_BoldItalic57pt7b" },
  { &JetBrainsMono_BoldItalic58pt7b, 58, "JetBrainsMono_BoldItalic58pt7b" },
  { &JetBrainsMono_BoldItalic59pt7b, 59, "JetBrainsMono_BoldItalic59pt7b" },
  { &JetBrainsMono_BoldItalic60pt7b, 60, "JetBrainsMono_BoldItalic60pt7b" },
  { &JetBrainsMono_BoldItalic61pt7b, 61, "JetBrainsMono_BoldItalic61pt7b" },
  { &JetBrainsMono_BoldItalic62pt7b, 62, "JetBrainsMono_BoldItalic62pt7b" },
  { &JetBrainsMono_BoldItalic63pt7b, 63, "JetBrainsMono_BoldItalic63pt7b" },
  { &JetBrainsMono_BoldItalic64pt7b, 64, "JetBrainsMono_BoldItalic64pt7b" },
  { &JetBrainsMono_BoldItalic65pt7b, 65, "JetBrainsMono_BoldItalic65pt7b" },
  { &JetBrainsMono_BoldItalic66pt7b, 66, "JetBrainsMono_BoldItalic66pt7b" },
  { &JetBrainsMono_BoldItalic67pt7b, 67, "JetBrainsMono_BoldItalic67pt7b" },
  { &JetBrainsMono_BoldItalic68pt7b, 68, "JetBrainsMono_BoldItalic68pt7b" },
  { &JetBrainsMono_BoldItalic69pt7b, 69, "JetBrainsMono_BoldItalic69pt7b" },
  { &JetBrainsMono_BoldItalic70pt7b, 70, "JetBrainsMono_BoldItalic70pt7b" },
  { &JetBrainsMono_BoldItalic71pt7b, 71, "JetBrainsMono_BoldItalic71pt7b" },
  { &JetBrainsMono_BoldItalic72pt7b, 72, "JetBrainsMono_BoldItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
