#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &RobotoMono_BoldItalic6pt7b, 6, "RobotoMono_BoldItalic6pt7b" },
  { &RobotoMono_BoldItalic7pt7b, 7, "RobotoMono_BoldItalic7pt7b" },
  { &RobotoMono_BoldItalic8pt7b, 8, "RobotoMono_BoldItalic8pt7b" },
  { &RobotoMono_BoldItalic9pt7b, 9, "RobotoMono_BoldItalic9pt7b" },
  { &RobotoMono_BoldItalic10pt7b, 10, "RobotoMono_BoldItalic10pt7b" },
  { &RobotoMono_BoldItalic11pt7b, 11, "RobotoMono_BoldItalic11pt7b" },
  { &RobotoMono_BoldItalic12pt7b, 12, "RobotoMono_BoldItalic12pt7b" },
  { &RobotoMono_BoldItalic13pt7b, 13, "RobotoMono_BoldItalic13pt7b" },
  { &RobotoMono_BoldItalic14pt7b, 14, "RobotoMono_BoldItalic14pt7b" },
  { &RobotoMono_BoldItalic15pt7b, 15, "RobotoMono_BoldItalic15pt7b" },
  { &RobotoMono_BoldItalic16pt7b, 16, "RobotoMono_BoldItalic16pt7b" },
  { &RobotoMono_BoldItalic17pt7b, 17, "RobotoMono_BoldItalic17pt7b" },
  { &RobotoMono_BoldItalic18pt7b, 18, "RobotoMono_BoldItalic18pt7b" },
  { &RobotoMono_BoldItalic19pt7b, 19, "RobotoMono_BoldItalic19pt7b" },
  { &RobotoMono_BoldItalic20pt7b, 20, "RobotoMono_BoldItalic20pt7b" },
  { &RobotoMono_BoldItalic21pt7b, 21, "RobotoMono_BoldItalic21pt7b" },
  { &RobotoMono_BoldItalic22pt7b, 22, "RobotoMono_BoldItalic22pt7b" },
  { &RobotoMono_BoldItalic23pt7b, 23, "RobotoMono_BoldItalic23pt7b" },
  { &RobotoMono_BoldItalic24pt7b, 24, "RobotoMono_BoldItalic24pt7b" },
  { &RobotoMono_BoldItalic25pt7b, 25, "RobotoMono_BoldItalic25pt7b" },
  { &RobotoMono_BoldItalic26pt7b, 26, "RobotoMono_BoldItalic26pt7b" },
  { &RobotoMono_BoldItalic27pt7b, 27, "RobotoMono_BoldItalic27pt7b" },
  { &RobotoMono_BoldItalic28pt7b, 28, "RobotoMono_BoldItalic28pt7b" },
  { &RobotoMono_BoldItalic29pt7b, 29, "RobotoMono_BoldItalic29pt7b" },
  { &RobotoMono_BoldItalic30pt7b, 30, "RobotoMono_BoldItalic30pt7b" },
  { &RobotoMono_BoldItalic31pt7b, 31, "RobotoMono_BoldItalic31pt7b" },
  { &RobotoMono_BoldItalic32pt7b, 32, "RobotoMono_BoldItalic32pt7b" },
  { &RobotoMono_BoldItalic33pt7b, 33, "RobotoMono_BoldItalic33pt7b" },
  { &RobotoMono_BoldItalic34pt7b, 34, "RobotoMono_BoldItalic34pt7b" },
  { &RobotoMono_BoldItalic35pt7b, 35, "RobotoMono_BoldItalic35pt7b" },
  { &RobotoMono_BoldItalic36pt7b, 36, "RobotoMono_BoldItalic36pt7b" },
  { &RobotoMono_BoldItalic37pt7b, 37, "RobotoMono_BoldItalic37pt7b" },
  { &RobotoMono_BoldItalic38pt7b, 38, "RobotoMono_BoldItalic38pt7b" },
  { &RobotoMono_BoldItalic39pt7b, 39, "RobotoMono_BoldItalic39pt7b" },
  { &RobotoMono_BoldItalic40pt7b, 40, "RobotoMono_BoldItalic40pt7b" },
  { &RobotoMono_BoldItalic41pt7b, 41, "RobotoMono_BoldItalic41pt7b" },
  { &RobotoMono_BoldItalic42pt7b, 42, "RobotoMono_BoldItalic42pt7b" },
  { &RobotoMono_BoldItalic43pt7b, 43, "RobotoMono_BoldItalic43pt7b" },
  { &RobotoMono_BoldItalic44pt7b, 44, "RobotoMono_BoldItalic44pt7b" },
  { &RobotoMono_BoldItalic45pt7b, 45, "RobotoMono_BoldItalic45pt7b" },
  { &RobotoMono_BoldItalic46pt7b, 46, "RobotoMono_BoldItalic46pt7b" },
  { &RobotoMono_BoldItalic47pt7b, 47, "RobotoMono_BoldItalic47pt7b" },
  { &RobotoMono_BoldItalic48pt7b, 48, "RobotoMono_BoldItalic48pt7b" },
  { &RobotoMono_BoldItalic49pt7b, 49, "RobotoMono_BoldItalic49pt7b" },
  { &RobotoMono_BoldItalic50pt7b, 50, "RobotoMono_BoldItalic50pt7b" },
  { &RobotoMono_BoldItalic51pt7b, 51, "RobotoMono_BoldItalic51pt7b" },
  { &RobotoMono_BoldItalic52pt7b, 52, "RobotoMono_BoldItalic52pt7b" },
  { &RobotoMono_BoldItalic53pt7b, 53, "RobotoMono_BoldItalic53pt7b" },
  { &RobotoMono_BoldItalic54pt7b, 54, "RobotoMono_BoldItalic54pt7b" },
  { &RobotoMono_BoldItalic55pt7b, 55, "RobotoMono_BoldItalic55pt7b" },
  { &RobotoMono_BoldItalic56pt7b, 56, "RobotoMono_BoldItalic56pt7b" },
  { &RobotoMono_BoldItalic57pt7b, 57, "RobotoMono_BoldItalic57pt7b" },
  { &RobotoMono_BoldItalic58pt7b, 58, "RobotoMono_BoldItalic58pt7b" },
  { &RobotoMono_BoldItalic59pt7b, 59, "RobotoMono_BoldItalic59pt7b" },
  { &RobotoMono_BoldItalic60pt7b, 60, "RobotoMono_BoldItalic60pt7b" },
  { &RobotoMono_BoldItalic61pt7b, 61, "RobotoMono_BoldItalic61pt7b" },
  { &RobotoMono_BoldItalic62pt7b, 62, "RobotoMono_BoldItalic62pt7b" },
  { &RobotoMono_BoldItalic63pt7b, 63, "RobotoMono_BoldItalic63pt7b" },
  { &RobotoMono_BoldItalic64pt7b, 64, "RobotoMono_BoldItalic64pt7b" },
  { &RobotoMono_BoldItalic65pt7b, 65, "RobotoMono_BoldItalic65pt7b" },
  { &RobotoMono_BoldItalic66pt7b, 66, "RobotoMono_BoldItalic66pt7b" },
  { &RobotoMono_BoldItalic67pt7b, 67, "RobotoMono_BoldItalic67pt7b" },
  { &RobotoMono_BoldItalic68pt7b, 68, "RobotoMono_BoldItalic68pt7b" },
  { &RobotoMono_BoldItalic69pt7b, 69, "RobotoMono_BoldItalic69pt7b" },
  { &RobotoMono_BoldItalic70pt7b, 70, "RobotoMono_BoldItalic70pt7b" },
  { &RobotoMono_BoldItalic71pt7b, 71, "RobotoMono_BoldItalic71pt7b" },
  { &RobotoMono_BoldItalic72pt7b, 72, "RobotoMono_BoldItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
