#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &RobotoCondensed_Italic6pt7b, 6, "RobotoCondensed_Italic6pt7b" },
  { &RobotoCondensed_Italic7pt7b, 7, "RobotoCondensed_Italic7pt7b" },
  { &RobotoCondensed_Italic8pt7b, 8, "RobotoCondensed_Italic8pt7b" },
  { &RobotoCondensed_Italic9pt7b, 9, "RobotoCondensed_Italic9pt7b" },
  { &RobotoCondensed_Italic10pt7b, 10, "RobotoCondensed_Italic10pt7b" },
  { &RobotoCondensed_Italic11pt7b, 11, "RobotoCondensed_Italic11pt7b" },
  { &RobotoCondensed_Italic12pt7b, 12, "RobotoCondensed_Italic12pt7b" },
  { &RobotoCondensed_Italic13pt7b, 13, "RobotoCondensed_Italic13pt7b" },
  { &RobotoCondensed_Italic14pt7b, 14, "RobotoCondensed_Italic14pt7b" },
  { &RobotoCondensed_Italic15pt7b, 15, "RobotoCondensed_Italic15pt7b" },
  { &RobotoCondensed_Italic16pt7b, 16, "RobotoCondensed_Italic16pt7b" },
  { &RobotoCondensed_Italic17pt7b, 17, "RobotoCondensed_Italic17pt7b" },
  { &RobotoCondensed_Italic18pt7b, 18, "RobotoCondensed_Italic18pt7b" },
  { &RobotoCondensed_Italic19pt7b, 19, "RobotoCondensed_Italic19pt7b" },
  { &RobotoCondensed_Italic20pt7b, 20, "RobotoCondensed_Italic20pt7b" },
  { &RobotoCondensed_Italic21pt7b, 21, "RobotoCondensed_Italic21pt7b" },
  { &RobotoCondensed_Italic22pt7b, 22, "RobotoCondensed_Italic22pt7b" },
  { &RobotoCondensed_Italic23pt7b, 23, "RobotoCondensed_Italic23pt7b" },
  { &RobotoCondensed_Italic24pt7b, 24, "RobotoCondensed_Italic24pt7b" },
  { &RobotoCondensed_Italic25pt7b, 25, "RobotoCondensed_Italic25pt7b" },
  { &RobotoCondensed_Italic26pt7b, 26, "RobotoCondensed_Italic26pt7b" },
  { &RobotoCondensed_Italic27pt7b, 27, "RobotoCondensed_Italic27pt7b" },
  { &RobotoCondensed_Italic28pt7b, 28, "RobotoCondensed_Italic28pt7b" },
  { &RobotoCondensed_Italic29pt7b, 29, "RobotoCondensed_Italic29pt7b" },
  { &RobotoCondensed_Italic30pt7b, 30, "RobotoCondensed_Italic30pt7b" },
  { &RobotoCondensed_Italic31pt7b, 31, "RobotoCondensed_Italic31pt7b" },
  { &RobotoCondensed_Italic32pt7b, 32, "RobotoCondensed_Italic32pt7b" },
  { &RobotoCondensed_Italic33pt7b, 33, "RobotoCondensed_Italic33pt7b" },
  { &RobotoCondensed_Italic34pt7b, 34, "RobotoCondensed_Italic34pt7b" },
  { &RobotoCondensed_Italic35pt7b, 35, "RobotoCondensed_Italic35pt7b" },
  { &RobotoCondensed_Italic36pt7b, 36, "RobotoCondensed_Italic36pt7b" },
  { &RobotoCondensed_Italic37pt7b, 37, "RobotoCondensed_Italic37pt7b" },
  { &RobotoCondensed_Italic38pt7b, 38, "RobotoCondensed_Italic38pt7b" },
  { &RobotoCondensed_Italic39pt7b, 39, "RobotoCondensed_Italic39pt7b" },
  { &RobotoCondensed_Italic40pt7b, 40, "RobotoCondensed_Italic40pt7b" },
  { &RobotoCondensed_Italic41pt7b, 41, "RobotoCondensed_Italic41pt7b" },
  { &RobotoCondensed_Italic42pt7b, 42, "RobotoCondensed_Italic42pt7b" },
  { &RobotoCondensed_Italic43pt7b, 43, "RobotoCondensed_Italic43pt7b" },
  { &RobotoCondensed_Italic44pt7b, 44, "RobotoCondensed_Italic44pt7b" },
  { &RobotoCondensed_Italic45pt7b, 45, "RobotoCondensed_Italic45pt7b" },
  { &RobotoCondensed_Italic46pt7b, 46, "RobotoCondensed_Italic46pt7b" },
  { &RobotoCondensed_Italic47pt7b, 47, "RobotoCondensed_Italic47pt7b" },
  { &RobotoCondensed_Italic48pt7b, 48, "RobotoCondensed_Italic48pt7b" },
  { &RobotoCondensed_Italic49pt7b, 49, "RobotoCondensed_Italic49pt7b" },
  { &RobotoCondensed_Italic50pt7b, 50, "RobotoCondensed_Italic50pt7b" },
  { &RobotoCondensed_Italic51pt7b, 51, "RobotoCondensed_Italic51pt7b" },
  { &RobotoCondensed_Italic52pt7b, 52, "RobotoCondensed_Italic52pt7b" },
  { &RobotoCondensed_Italic53pt7b, 53, "RobotoCondensed_Italic53pt7b" },
  { &RobotoCondensed_Italic54pt7b, 54, "RobotoCondensed_Italic54pt7b" },
  { &RobotoCondensed_Italic55pt7b, 55, "RobotoCondensed_Italic55pt7b" },
  { &RobotoCondensed_Italic56pt7b, 56, "RobotoCondensed_Italic56pt7b" },
  { &RobotoCondensed_Italic57pt7b, 57, "RobotoCondensed_Italic57pt7b" },
  { &RobotoCondensed_Italic58pt7b, 58, "RobotoCondensed_Italic58pt7b" },
  { &RobotoCondensed_Italic59pt7b, 59, "RobotoCondensed_Italic59pt7b" },
  { &RobotoCondensed_Italic60pt7b, 60, "RobotoCondensed_Italic60pt7b" },
  { &RobotoCondensed_Italic61pt7b, 61, "RobotoCondensed_Italic61pt7b" },
  { &RobotoCondensed_Italic62pt7b, 62, "RobotoCondensed_Italic62pt7b" },
  { &RobotoCondensed_Italic63pt7b, 63, "RobotoCondensed_Italic63pt7b" },
  { &RobotoCondensed_Italic64pt7b, 64, "RobotoCondensed_Italic64pt7b" },
  { &RobotoCondensed_Italic65pt7b, 65, "RobotoCondensed_Italic65pt7b" },
  { &RobotoCondensed_Italic66pt7b, 66, "RobotoCondensed_Italic66pt7b" },
  { &RobotoCondensed_Italic67pt7b, 67, "RobotoCondensed_Italic67pt7b" },
  { &RobotoCondensed_Italic68pt7b, 68, "RobotoCondensed_Italic68pt7b" },
  { &RobotoCondensed_Italic69pt7b, 69, "RobotoCondensed_Italic69pt7b" },
  { &RobotoCondensed_Italic70pt7b, 70, "RobotoCondensed_Italic70pt7b" },
  { &RobotoCondensed_Italic71pt7b, 71, "RobotoCondensed_Italic71pt7b" },
  { &RobotoCondensed_Italic72pt7b, 72, "RobotoCondensed_Italic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
