#pragma once

// Auto-generated by fontMaker.py
#include <TFT_eSPI.h>

struct FontEntry
{
  const GFXfont *font;
  uint16_t sizePt;
  const char *name;
};

// Includes are in all_fonts.h (include that before this file)
static const FontEntry kFonts[] = {
  { &NotoSans_BoldItalic6pt7b, 6, "NotoSans_BoldItalic6pt7b" },
  { &NotoSans_BoldItalic7pt7b, 7, "NotoSans_BoldItalic7pt7b" },
  { &NotoSans_BoldItalic8pt7b, 8, "NotoSans_BoldItalic8pt7b" },
  { &NotoSans_BoldItalic9pt7b, 9, "NotoSans_BoldItalic9pt7b" },
  { &NotoSans_BoldItalic10pt7b, 10, "NotoSans_BoldItalic10pt7b" },
  { &NotoSans_BoldItalic11pt7b, 11, "NotoSans_BoldItalic11pt7b" },
  { &NotoSans_BoldItalic12pt7b, 12, "NotoSans_BoldItalic12pt7b" },
  { &NotoSans_BoldItalic13pt7b, 13, "NotoSans_BoldItalic13pt7b" },
  { &NotoSans_BoldItalic14pt7b, 14, "NotoSans_BoldItalic14pt7b" },
  { &NotoSans_BoldItalic15pt7b, 15, "NotoSans_BoldItalic15pt7b" },
  { &NotoSans_BoldItalic16pt7b, 16, "NotoSans_BoldItalic16pt7b" },
  { &NotoSans_BoldItalic17pt7b, 17, "NotoSans_BoldItalic17pt7b" },
  { &NotoSans_BoldItalic18pt7b, 18, "NotoSans_BoldItalic18pt7b" },
  { &NotoSans_BoldItalic19pt7b, 19, "NotoSans_BoldItalic19pt7b" },
  { &NotoSans_BoldItalic20pt7b, 20, "NotoSans_BoldItalic20pt7b" },
  { &NotoSans_BoldItalic21pt7b, 21, "NotoSans_BoldItalic21pt7b" },
  { &NotoSans_BoldItalic22pt7b, 22, "NotoSans_BoldItalic22pt7b" },
  { &NotoSans_BoldItalic23pt7b, 23, "NotoSans_BoldItalic23pt7b" },
  { &NotoSans_BoldItalic24pt7b, 24, "NotoSans_BoldItalic24pt7b" },
  { &NotoSans_BoldItalic25pt7b, 25, "NotoSans_BoldItalic25pt7b" },
  { &NotoSans_BoldItalic26pt7b, 26, "NotoSans_BoldItalic26pt7b" },
  { &NotoSans_BoldItalic27pt7b, 27, "NotoSans_BoldItalic27pt7b" },
  { &NotoSans_BoldItalic28pt7b, 28, "NotoSans_BoldItalic28pt7b" },
  { &NotoSans_BoldItalic29pt7b, 29, "NotoSans_BoldItalic29pt7b" },
  { &NotoSans_BoldItalic30pt7b, 30, "NotoSans_BoldItalic30pt7b" },
  { &NotoSans_BoldItalic31pt7b, 31, "NotoSans_BoldItalic31pt7b" },
  { &NotoSans_BoldItalic32pt7b, 32, "NotoSans_BoldItalic32pt7b" },
  { &NotoSans_BoldItalic33pt7b, 33, "NotoSans_BoldItalic33pt7b" },
  { &NotoSans_BoldItalic34pt7b, 34, "NotoSans_BoldItalic34pt7b" },
  { &NotoSans_BoldItalic35pt7b, 35, "NotoSans_BoldItalic35pt7b" },
  { &NotoSans_BoldItalic36pt7b, 36, "NotoSans_BoldItalic36pt7b" },
  { &NotoSans_BoldItalic37pt7b, 37, "NotoSans_BoldItalic37pt7b" },
  { &NotoSans_BoldItalic38pt7b, 38, "NotoSans_BoldItalic38pt7b" },
  { &NotoSans_BoldItalic39pt7b, 39, "NotoSans_BoldItalic39pt7b" },
  { &NotoSans_BoldItalic40pt7b, 40, "NotoSans_BoldItalic40pt7b" },
  { &NotoSans_BoldItalic41pt7b, 41, "NotoSans_BoldItalic41pt7b" },
  { &NotoSans_BoldItalic42pt7b, 42, "NotoSans_BoldItalic42pt7b" },
  { &NotoSans_BoldItalic43pt7b, 43, "NotoSans_BoldItalic43pt7b" },
  { &NotoSans_BoldItalic44pt7b, 44, "NotoSans_BoldItalic44pt7b" },
  { &NotoSans_BoldItalic45pt7b, 45, "NotoSans_BoldItalic45pt7b" },
  { &NotoSans_BoldItalic46pt7b, 46, "NotoSans_BoldItalic46pt7b" },
  { &NotoSans_BoldItalic47pt7b, 47, "NotoSans_BoldItalic47pt7b" },
  { &NotoSans_BoldItalic48pt7b, 48, "NotoSans_BoldItalic48pt7b" },
  { &NotoSans_BoldItalic49pt7b, 49, "NotoSans_BoldItalic49pt7b" },
  { &NotoSans_BoldItalic50pt7b, 50, "NotoSans_BoldItalic50pt7b" },
  { &NotoSans_BoldItalic51pt7b, 51, "NotoSans_BoldItalic51pt7b" },
  { &NotoSans_BoldItalic52pt7b, 52, "NotoSans_BoldItalic52pt7b" },
  { &NotoSans_BoldItalic53pt7b, 53, "NotoSans_BoldItalic53pt7b" },
  { &NotoSans_BoldItalic54pt7b, 54, "NotoSans_BoldItalic54pt7b" },
  { &NotoSans_BoldItalic55pt7b, 55, "NotoSans_BoldItalic55pt7b" },
  { &NotoSans_BoldItalic56pt7b, 56, "NotoSans_BoldItalic56pt7b" },
  { &NotoSans_BoldItalic57pt7b, 57, "NotoSans_BoldItalic57pt7b" },
  { &NotoSans_BoldItalic58pt7b, 58, "NotoSans_BoldItalic58pt7b" },
  { &NotoSans_BoldItalic59pt7b, 59, "NotoSans_BoldItalic59pt7b" },
  { &NotoSans_BoldItalic60pt7b, 60, "NotoSans_BoldItalic60pt7b" },
  { &NotoSans_BoldItalic61pt7b, 61, "NotoSans_BoldItalic61pt7b" },
  { &NotoSans_BoldItalic62pt7b, 62, "NotoSans_BoldItalic62pt7b" },
  { &NotoSans_BoldItalic63pt7b, 63, "NotoSans_BoldItalic63pt7b" },
  { &NotoSans_BoldItalic64pt7b, 64, "NotoSans_BoldItalic64pt7b" },
  { &NotoSans_BoldItalic65pt7b, 65, "NotoSans_BoldItalic65pt7b" },
  { &NotoSans_BoldItalic66pt7b, 66, "NotoSans_BoldItalic66pt7b" },
  { &NotoSans_BoldItalic67pt7b, 67, "NotoSans_BoldItalic67pt7b" },
  { &NotoSans_BoldItalic68pt7b, 68, "NotoSans_BoldItalic68pt7b" },
  { &NotoSans_BoldItalic69pt7b, 69, "NotoSans_BoldItalic69pt7b" },
  { &NotoSans_BoldItalic70pt7b, 70, "NotoSans_BoldItalic70pt7b" },
  { &NotoSans_BoldItalic71pt7b, 71, "NotoSans_BoldItalic71pt7b" },
  { &NotoSans_BoldItalic72pt7b, 72, "NotoSans_BoldItalic72pt7b" },
};
static constexpr size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);
